finos/waltz

waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Multi-select upstream/downstream flows

waltz-ng/client/physical-specifications/physical-specification-view.html
=> Fixing breadcrumbs

waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.scss, waltz-ng/client/physical-flows/components/spec-definition/physical-spec-definition-panel.html, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/style/_variables.scss, waltz-ng/style/_waltz.scss
- auto select first active defn
#1992
=> Highlight selected definition

waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramIdSelectorFactory.java
=> FlowDiagramIdSelectorFactory

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Annotations can be linked to logical flows (buckets)

waltz-ng/client/survey/components/survey-run-create-general.js
=> Cannot create survey runs directly for a change initiative

waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-physical-flow-popup.html
=> Better handling of large lists of feeds/specs

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/playpen/3/playpen3.html
=> Pan and zoom only enabled if ctrl or meta key held down.

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/search/PhysicalSpecificationSearchDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/PhysicalSpecificationHarness.java, waltz-ng/client/navbar/components/nav-search-results.html, waltz-ng/client/navbar/components/navbar-search-form.js, waltz-ng/client/physical-specifications/services/physical-specification-store.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification/PhysicalSpecificationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecificationEndpoint.java
=> Search for specs

waltz-ng/client/data-types/components/rated-flow-boingy-graph.html
=> Fixing data flow view for widescreens

waltz-ng/client/physical-specifications/components/specification-definition/physical-spec-definition-create-panel.html, waltz-ng/client/physical-specifications/components/specification-definition/physical-spec-definition-create-panel.js
- also improved help text
#1993 
#1981
=> Nicer error reporting on spec defn's

waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/data-types/data-type-list.js
=> Call to old lineage endpoint causing errors

waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification_definition/PhysicalSpecDefinitionService.java
=> Added changelog to spec view page

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-specifications/components/create/physical-spec-definition-create-panel.html
=> Integrating diagrams with phys flow page

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.scss, waltz-ng/client/physical-flows/physical-flow-view.js
=> Minor diagram fixes

waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.html, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js
=> Save title etc

waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramDao.java
=> Fix bug preventing upated on MSSQL

waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/search/PhysicalSpecificationSearchDao.java, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.html, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js
- bonus fixing problem with Phys Spec Search on MSSQL
#2026
=> Allow editing of flow diagrams

waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-physical-flow-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-physical-flow-popup.js, waltz-ng/client/physical-flows/physical-flow-registration.html, waltz-ng/client/physical-flows/physical-flow-registration.js, waltz-ng/client/physical-flows/routes.js
=> Flow Diagram: links on popups to create new phys/logical flows

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.scss, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js
=> Show graph details when selecting nodes.

waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.js, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.html
=> Allow creation of first flow diagram.

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> Phys Spec Definitions: version numbers must NOT be globally unique

waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinitionFieldType.java, waltz-ng/client/common/services/display-names.js, waltz-ng/client/physical-specifications/components/create/physical-spec-definition-create-panel.html, waltz-ng/client/physical-specifications/components/create/physical-spec-definition-create-panel.js
=> Allow field type of ENUM in spec definitions

waltz-ng/client/physical-specifications/components/create/physical-spec-definition-create-panel.js, waltz-ng/client/physical-specifications/components/spec-definition/physical-spec-definition-panel.html
=> Fix: Status field was reseting when validating input

waltz-ng/client/physical-specifications/components/spec-definition/physical-spec-definition-panel.html
=> Phys Spec Defn: discourage linking to obsolete versions

waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationDao.java, waltz-ng/client/attestation/services/attestation-store.js, waltz-ng/client/system/recalculate-view.html, waltz-ng/client/system/recalculate-view.js, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttestationEndpoint.java
=> Fix batch attestation calculation for lineage

waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorRatingsCalculator.java
=> Logical flow decorator rating call fails

waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramDao.java, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/services/flow-diagram-store.js, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FlowDiagramEndpoint.java
=> Allow deletion of flow diagrams

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-ng/client/person/person-view.js
=> Lineage Reports - 404 not found on aggregate pages

waltz-ng/client/logical-flow/logical-flow-edit.js
=> Logical flow edit view error when adding decorator

waltz-ng/client/common/services/icon-names.js, waltz-ng/client/physical-specifications/physical-specification-view.html
=> Physical flow and specification not distinguishable in `Recent` list

waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinitionSampleFileCreateCommand.java, waltz-ng/client/physical-specifications/components/create/physical-spec-definition-create-panel.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/physical-specifications/services/physical-spec-definition-sample-file-store.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecDefinitionSampleFileEndpoint.java
=> Spec Defn Files: allow upload/paste of sample

waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationSelectorFactory.java, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/flow-diagram/routes.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> 'permalink' view for flow-diagrams

waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js
=> tooltips for file icons in slope graph

waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.js
=> Survey bugs

waltz-model/src/main/java/com/khartec/waltz/model/entity_relationship/RelationshipKind.java, waltz-ng/client/change-initiative/change-initiative-app-relationship-edit.js, waltz-ng/client/common/services/display-names.js
=> Update CI - App relationship types

waltz-ng/client/common/d3-utils.js, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js
=> Flow Diagram - not drawing new diagrams correctly on IE

waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html
=> Clarified 'back to list' link

waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js
=> Warn users that flow diagrams are not automatically saved

waltz-ng/client/navbar/directives/navbar-profile.html
=> Nav Profile - Survey before System Admin

waltz-ng/client/applications/data-load.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-utilities.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js, waltz-ng/client/logical-flow/logical-flow-edit.js
=> Improve logical flow editor for deletion with physical flows

waltz-ng/client/survey/survey-run-view.html
=> Survey: Allow editing recipients for In Progress surveys

waltz-ng/package.json
=> Webpack Dev Server should be in package.json

waltz-schema/pom.xml
=> Upgrading to jOOQ 3.9.2

waltz-ng/client/technology/components/technology-summary-section.html, waltz-ng/client/technology/components/technology-summary-section.js
=> Use <waltz-no-data> in Technology section

waltz-ng/client/applications/directives/app-overview.html
=> Complexity Popup: should mention that it's calculated periodically

waltz-ng/client/common/services/index.js, waltz-ng/client/common/services/prevent-navigation-service.js, waltz-ng/client/physical-flows/physical-flow-registration.html, waltz-ng/client/physical-flows/physical-flow-registration.js
=> Register Phys Flows - warn if canceling / moving away

waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-view.html, waltz-ng/client/widgets/editable-field.html, waltz-ng/client/widgets/editable-field.js
=> Survey: Suggest adding recipients to surveys

waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.js
=> Flow diagram perma view table shows logical-only flows

pom.xml, waltz-web/src/test/java/com/khartec/waltz/web/WebUtilities_attemptRender.java
=> Upgrade spark to 2.5.5

waltz-ng/client/survey/components/survey-section.html
=> Survey: Description on survey section should support markdown

waltz-model/src/main/java/com/khartec/waltz/model/change_initiative/ChangeInitiative.java
=> Entity search: Display external id for change initiatives in search list

.travis.yml, waltz-ng/package.json, waltz-ng/webpack.config.js
=> Upgrade Webpack to 2.x

waltz-ng/client/survey/services/survey-template-store.js, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey: Allow cloning of templates

waltz-data/src/main/ddl/liquibase/db.changelog-1.4.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-model/src/main/java/com/khartec/waltz/model/entity_named_note/EntityNamedNodeType.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_named_note/EntityNamedNote.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteTypeEndpoint.java
=> Entity Notes: DDL and endpoint

waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNodeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNoteTypeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_named_note/EntityNamedNoteTypeChangeCommand.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_named_note/EntityNamedNoteService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_named_note/EntityNamedNoteTypeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteTypeEndpoint.java
=> DAO/Service/Endpoints for EntityNamedNoteType management

waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNoteTypeDao.java, waltz-ng/client/entity-named-note/index.js, waltz-ng/client/entity-named-note/services/entity-named-note-type-service.js, waltz-ng/client/entity-named-note/services/entity-named-note-type-store.js, waltz-ng/client/modules.js, waltz-ng/client/system/entity-named-node-types-view.html, waltz-ng/client/system/entity-named-node-types-view.js, waltz-ng/client/system/routes.js, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/widgets/_styles.scss, waltz-ng/client/widgets/editable-field.html, waltz-ng/client/widgets/markdown.scss
=> Entity Notes: UI changes - admin

waltz-ng/client/applications/app-registration.js
=> Fix: unable to register new applications

waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNoteDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNoteTypeDao.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_named_note/EntityNamedNoteService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteEndpoint.java
=> DAO/Service/Endpoints for EntityNamedNote

waltz-model/src/main/java/com/khartec/waltz/model/StringChangeCommand.java, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/common/services/index.js, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.html, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.js, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.scss, waltz-ng/client/entity-named-note/index.js, waltz-ng/client/entity-named-note/services/entity-named-note-store.js, waltz-ng/style/_waltz.scss, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteEndpoint.java
=> Entity Notes: UI changes - end user

waltz-data/src/main/ddl/liquibase/db.changelog-1.4.xml, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_data_type/PhysicalSpecificationDataType.java
=> Phys spec data type decoration

waltz-data/src/main/ddl/liquibase/db.changelog-1.4.xml, waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNoteTypeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_named_note/EntityNamedNodeType.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_named_note/EntityNamedNoteTypeChangeCommand.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_named_note/EntityNamedNoteService.java
=> Add readOnly flag to Entity Named Notes Types

waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNoteTypeDao.java, waltz-ng/client/system/entity-named-node-types-view.html, waltz-ng/client/system/entity-named-node-types-view.js, waltz-ng/client/widgets/editable-field.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteTypeEndpoint.java
=> Add readOnly flag to admin ui

pom.xml
=> Add security vulnerability checks to maven build

waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Warn if moving away from edited flow diagram

docs/releases/1.4.md, pom.xml, waltz-schema/pom.xml
=> Updating java libs

waltz-ng/client/thirdparty-setup.js
=> Markdown: Allow tables

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/widgets/toggle.html
=> Waltz 2156

waltz-ng/client/entity-named-note/components/entity-named-notes-panel.html, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.js
=> Entity Notes: Move edit note button to the first column

waltz-service/src/main/java/com/khartec/waltz/service/physical_specification_definition/PhysicalSpecDefinitionService.java
=> spec defn service enforce state

waltz-ng/client/entity/components/entity-selector/entity-selector.html, waltz-ng/client/entity/components/entity-selector/entity-selector.scss, waltz-ng/style/_waltz.scss
=> Entity selector broken - Doesn't render selected entity properly

waltz-data/src/main/ddl/liquibase/db.changelog-1.4.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstance.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceCreateCommand.java, waltz-ng/client/survey/components/survey-run-overview.html, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/survey-instance-view.html, waltz-ng/client/survey/survey-instance-view.js, waltz-ng/client/survey/survey-run-view.html, waltz-ng/client/survey/survey-run-view.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyInstanceEndpoint.java
=> Survey: Due date at instance level

waltz-ng/client/survey/survey-run-create.js
=> Survey: Email generation link doesn't work on Chrome 58

waltz-data/src/main/ddl/liquibase/db.changelog-1.4.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceRecipientDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyRunDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstance.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRun.java, waltz-ng/client/common/components/date-picker/date-picker-form-input.html, waltz-ng/client/common/components/date-picker/date-picker-form-input.js, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/survey-instance-view.js, waltz-ng/client/survey/survey-run-view.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java
=> Survey: Make due date mandatory

waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-model/src/main/java/com/khartec/waltz/model/involvement/EntityInvolvementChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/involvement/Involvement.java, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/common/checks.js, waltz-ng/client/entity/components/entity-involvement-editor/entity-involvement-editor.html, waltz-ng/client/entity/components/entity-involvement-editor/entity-involvement-editor.js, waltz-ng/client/entity/index.js, waltz-ng/client/involvement/components/involved-people-section.html, waltz-ng/client/involvement/components/involved-people-section.js, waltz-ng/client/involvement/index.js, waltz-ng/client/involvement/involvement-utils.js, waltz-ng/client/involvement/services/involved-section-service.js, waltz-ng/client/involvement/services/involvement-store.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/networking.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-service/src/main/java/com/khartec/waltz/service/involvement/InvolvementService.java, waltz-service/src/main/java/com/khartec/waltz/service/user/RoleUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/user/UserRoleService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementEndpoint.java
=> Allow people to be associated with entities via GUI

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> Exclude full text changesets in liquibase via context flags

waltz-common/src/main/java/com/khartec/waltz/common/hierarchy/HierarchyUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/hierarchies/HierarchyUtils_toForest.java, waltz-common/src/test/java/com/khartec/waltz/common/hierarchies/SampleData.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntityHierarchyHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/LevelProvider.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java
=> Entity Hierarchy - defend against self loops on root node.

waltz-data/src/main/java/com/khartec/waltz/data/EntityNameUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationDao.java, waltz-ng/client/attestation/components/attestation-table.html, waltz-ng/client/attestation/components/attestation-table.js, waltz-ng/client/common/link-utils.js, waltz-ng/client/common/services/icon-names.js
=> Attestation: Show attesting entity on physical flow attestations section

waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramIdSelectorFactory.java, waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js
=> Add flow diagrams to actor page

waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Flow Diagrams: allow cloning of diagram

waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/common/services/index.js, waltz-ng/client/common/services/service-broker.js, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.js, waltz-ng/client/entity-named-note/index.js, waltz-ng/client/entity-named-note/services/entity-named-note-store.js, waltz-ng/client/entity-named-note/services/entity-named-note-type-store.js, waltz-ng/client/playpen/5/playpen5.html, waltz-ng/client/playpen/5/playpen5.js, waltz-ng/package.json
=> Create Generic Data Service and integrate with Entity Notes

waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.html, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.js, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/measurable/components/summary/measurable-summary.js
=> Entity Notes: Add entity notes on measurables view

waltz-ng/test/common/services/test_core-api-utils.js
=> Unit Tests: api_utils

waltz-ng/client/entity/components/entity-involvement-editor/entity-involvement-editor.html
=> Involvment Editor: ensure role list is sorted

waltz-ng/client/applications/components/app-overview.html, waltz-ng/client/applications/components/app-overview.js, waltz-ng/client/applications/index.js, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/data-types/components/data-type-overview.html, waltz-ng/client/data-types/components/data-type-overview.js, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/measurable/components/summary/measurable-summary.js, waltz-ng/client/org-units/components/overview/org-unit-overview.html, waltz-ng/client/org-units/components/overview/org-unit-overview.js
=> Entity Notes: add to applications, orgunits and datatype

waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html
=> Count of physical feeds at app level

waltz-ng/client/common/services/service-broker.js, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.js, waltz-ng/client/system/entity-named-node-types-view.js, waltz-ng/webpack.config.js
=> ServiceBroker: anonymous fn detect not working in IE

waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-node-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-node-popup.js, waltz-ng/client/flow-diagram/index.js
=> Flow Diagram: allow disjointed nodes

waltz-data/src/main/java/com/khartec/waltz/data/physical_specification_data_type/PhysicalSpecDataTypeDao.java, waltz-ng/client/common/checks.js, waltz-ng/client/common/module-utils.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/data-types/index.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-list.html, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-list.js, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-section.html, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-section.js, waltz-ng/client/physical-specifications/index.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/physical-specifications/services/physical-spec-data-type-store.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification_data_type/PhysicalSpecDataTypeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecDataTypeEndpoint.java
=> Physical Specs: tag with datatype - interim

waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification_data_type/PhysicalSpecDataTypeDao.java, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-list.js, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-section.html, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-section.js, waltz-ng/client/physical-specifications/services/physical-spec-data-type-store.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification_data_type/PhysicalSpecDataTypeService.java, waltz-web/src/main/java/com/khartec/waltz/web/action/UpdatePhysicalSpecDataTypesAction.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecDataTypeEndpoint.java
=> Physical specification data type: Editor

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/applications/components/apps-section/apps-section.js, waltz-ng/client/applications/services/application-store.js, waltz-ng/client/applications/services/index.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/end-user-apps/index.js, waltz-ng/client/end-user-apps/services/end-user-app-store.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/source-data-rating/index.js, waltz-ng/client/source-data-rating/services/source-data-rating-store.js
Added to flow-diagram page
#2237
=> Apps section converted to service broker

waltz-ng/client/common/checks.js, waltz-ng/client/common/services/service-broker.js
=> API checks for service-broker functions

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/common/checks.js, waltz-ng/client/common/module-utils.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-ng/client/technology/components/group-technology-summary.js, waltz-ng/client/technology/components/technology-summary-pies.js, waltz-ng/client/technology/components/technology-summary-section.js, waltz-ng/client/technology/index.js, waltz-ng/client/technology/services/technology-statistics-service.js
Added to flow-diagram page
#2239
=> Tech summary section converted to service broker

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/common/module-utils.js, waltz-ng/client/common/selector-utils.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.html, waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.js, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/index.js, waltz-ng/client/entity-statistics/services/entity-statistic-store.js, waltz-ng/client/entity-statistics/services/entity-statistics-utilities.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html
=> Flow Diagram View: Indicators section

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/applications/data-load.js, waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/change-log/components/change-log-section.js, waltz-ng/client/change-log/index.js, waltz-ng/client/change-log/services/change-log-store.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/profile/view.html, waltz-ng/client/profile/view.js
=> Flow Diagram View: Changes section

waltz-data/src/main/ddl/liquibase/db.changelog-1.4.xml
=> Entity Relationship now includes description and last updated

waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/change-log/components/change-log-section.js, waltz-ng/client/change-log/services/change-log-store.js, waltz-ng/client/change-log/view.js, waltz-ng/client/user/user-log.js
=> ChangeLogSection: Load lazily

waltz-ng/style/_waltz-tabs.scss
=> Measurable tabs - make it clearer which is the selected tab

waltz-ng/client/physical-specifications/physical-specification-view.html
=> Physical Spec Data Types: spec page - reorder sections

waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-list.html
=> Physical spec data types: UI cleanup

waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html
=> Flow Diagram: Add "Back to list" when creating a new diagram

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.js, waltz-ng/client/bookmarks/index.js, waltz-ng/client/bookmarks/services/bookmark-store.js, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/data-type-view.js, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js
-and service broker the section and other usages
#2236
=> Flow Diagram View: bookmarks section

waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/physical-specifications/components/data-type/physical-spec-data-type-list.html
=> Update physical spec data type label style

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/actor/components/actor-overview.html, waltz-ng/client/actor/components/actor-overview.js, waltz-ng/client/actor/index.js, waltz-ng/client/common/selector-utils.js, waltz-ng/client/entity-named-note/components/entity-named-notes-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html
=> Actor Page: make more like a group page

waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.js, waltz-ng/client/measurable-rating/index.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js
=> Flow Diagram View: viewpoint rating section

waltz-ng/client/common/entity-utils.js, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/measurable/components/summary/measurable-summary.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js
=> Measurable overview simplification

waltz-ng/client/actor/actor-view.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.js
=> Actor page: Fix diagram initialisation

waltz-service/src/main/java/com/khartec/waltz/service/change_initiative/ChangeInitiativeService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_relationship/EntityRelationshipUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeInitiativeEndpoint.java
=> Entity Relationship being updated with by/at.

waltz-ng/client/ratings/components/rating-picker/rating-picker.html
=> Show description/names on rating picker options

waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/ratings/rating-utils.js, waltz-ng/client/system/perspectives-view.html
=> Perspective Definition - cannot save new definitions

waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js
- and cancel reloads original state
#2271
=> Flow Diagram: Cancel should not return to list

waltz-ng/client/bookmarks/bookmark-editor.js
=> Edit Bookmark: Entity stat view done and breadcrumb doesn't work

waltz-data/src/main/java/com/khartec/waltz/data/EntityNameUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/EntityReferenceNameResolver.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntityRefHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityReference.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityReferenceUtilities.java, waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/change-log/components/change-log-section.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_relationship/MeasurableRelationshipService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRelationshipEndpoint.java
=> Detailed logging on measurable relationship changes

waltz-ng/client/perspective/components/overrides/perspective-overrides.html
=> Application Ratings: overrides say [Object Object] not the name

waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js, waltz-ng/client/physical-flows/physical-flow-registration.js
=> Flows: Allow physical flows to be created from logical flow pop up

waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js
=> Waltz 2307

waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js, waltz-ng/client/measurable-relationship/components/viz/related-measurables-viz.js, waltz-ng/client/measurable-relationship/measurable-relationship-utils.js, waltz-ng/client/measurable-relationship/services/measurable-relationship-store.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_relationship/MeasurableRelationshipService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRelationshipEndpoint.java
=> Related measurables genericized

waltz-ng/client/thirdparty-setup.js, waltz-ng/client/widgets/markdown.scss
=> Modifying markdown params for more natural line breaks

waltz-ng/client/measurable-relationship/components/viz/related-measurables-viz.js
=> Depluralizing Change Initiatives bubble

waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/person/person-view-data.js
=> Group pages: Server stat is not being displayed in overview

waltz-ng/client/measurable-relationship/components/viz/related-measurables-viz.js, waltz-ng/client/measurable-relationship/services/measurable-relationship-store.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_relationship/MeasurableRelationshipService.java
=> Spindle graph updates counts on segments correctly.

waltz-ng/client/measurable/components/summary/measurable-summary.html
=> Measurable Summary - hide info panels if app count == 0

waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/perspective/components/panel/perspective-rating-panel.html, waltz-ng/client/perspective/components/panel/perspective-rating-panel.js, waltz-ng/client/perspective/perspective-rating-edit.html
=> App ratings section

waltz-service/src/main/java/com/khartec/waltz/service/measurable_relationship/MeasurableRelationshipService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRelationshipEndpoint.java
=> Measurable relationships should use EntityRelationshipUtilities

waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/viz/related-measurables-viz.js, waltz-ng/client/measurable-relationship/components/viz/related-measurables-viz.scss
Highlighting selected bucket
#2326
#2327
=> Making table a bit larger

waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthSourceRatingCalculator.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_named_note/EntityNamedNoteService.java, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ActorEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementKindEndpoint.java
=> Fixing aggressive rename of update -> save

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/MeasurableRelationshipsGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_relationship/RelationshipKind.java, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.html, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js, waltz-ng/client/measurable-relationship/components/editor/related-measurable-editor-utils.js, waltz-ng/client/measurable-relationship/components/editor/update-related-measurable-editor.html, waltz-ng/client/measurable-relationship/components/editor/update-related-measurable-editor.js, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html
- Measurable to CI relationship kinds (support DEPRECATES)
- Disable relationship kind updated
- Remove LOOSELY_RELATES_TO
#2333
=> Measurable relationship kinds

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/flow-diagram-utils.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Colour diagrams by app type

waltz-common/src/main/java/com/khartec/waltz/common/ArrayUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/CollectionUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/ArrayUtilities_all.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_find.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_head.java, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.scss, waltz-ng/style/_waltz.scss
- added a few unit tests
#2341
=> Improving look of rel-measures panel

waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js
=> Fixing usage of selection.merge().selectAll()

waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js
=> Export logical flows (app level)

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/perspective/components/panel/perspective-rating-panel.js
=> App Rating Section: Perspectives should co-ordinate with Measurable tabs

waltz-ng/client/data-types/components/data-type-overview.html, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/org-units/components/overview/org-unit-overview.html
=> Show description label on page overviews, also remove excess spacing

waltz-data/src/main/ddl/liquibase/db.changelog-1.4.xml, waltz-data/src/main/java/com/khartec/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java
=> Ensure app group relationships are cleaned up when group is deleted.

waltz-ng/client/person/person-view.html, waltz-ng/client/person/person-view.js
=> Allow export of person apps

waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java
=> Re-adding CAPABILITY kind for backwards compat.

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/logical-flow/index.js, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-ng/client/system/orphans-view.html, waltz-ng/client/system/orphans-view.js, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
=> Adding support for cleaning up orphan logical flows

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/directives/app-group-summary.html, waltz-ng/client/app-groups/directives/app-group-summary.js
=> Show owners of groups on app-group-view page

waltz-ng/client/entity-named-note/components/panel/entity-named-notes-panel.html, waltz-ng/client/entity-named-note/components/section/entity-named-notes-section.html, waltz-ng/client/entity-named-note/components/section/entity-named-notes-section.js
=> Improving look and feel of entity named notes.

waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
=> Switching logical flow orphan cleanup method to GET (from POST)

waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-ng/client/auth-sources/index.js, waltz-ng/client/auth-sources/services/auth-sources-store.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/system/orphans-view.html, waltz-ng/client/system/orphans-view.js, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AuthoritativeSourceEndpoint.java
=> Allow auth source to be cleaned up

waltz-ng/client/perspective/components/panel/perspective-rating-panel.html
=> Perpective Ratings: replace green background selection with tabs

waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-specifications/components/create/physical-spec-definition-create-panel.html, waltz-ng/client/physical-specifications/components/spec-definition/physical-spec-definition-panel.html, waltz-ng/client/physical-specifications/components/spec-definition/physical-spec-definition-panel.js, waltz-ng/client/physical-specifications/physical-specification-view.html
=> Physical flow view: reword spec defn no-data msg

waltz-ng/client/ratings/components/rating-picker/rating-picker.html
=> Ensure rating picker descriptions are on new line

waltz-ng/client/entity/components/entity-involvement-editor/entity-involvement-editor.html
=> Remove link to self in person editor

waltz-ng/client/change-initiative/directives/change-initiative-selector.html, waltz-ng/client/change-initiative/directives/change-initiative-selector.scss, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java
=> Cannot add change initiatives to app group

waltz-data/src/main/ddl/liquibase/db.changelog-1.5.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> Drop application_tag table from db

waltz-ng/client/survey/components/survey-run-create-recipient.js
=> Survey: Run creation - excluded recipients are not actually excluded

waltz-data/src/main/ddl/liquibase/db.changelog-1.5.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/asset_cost/AssetCostStatsDao.java, waltz-model/src/main/java/com/khartec/waltz/model/cost/CostKind.java, waltz-ng/client/common/services/display-names.js
=> Typo in CostKind enum

waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js
=> Edit Logical Flow: label tweakers don't get attached

waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/static-panel/index.js, waltz-ng/client/static-panel/services/static-panel-store.js
=> Static Panel Store added to Core API

waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Link measurables to flow diagrams.

waltz-ng/client/flow-diagram/components/associations/flow-diagram-associations.html, waltz-ng/client/flow-diagram/components/associations/flow-diagram-associations.js
=> Flow diagram: fixes

waltz-data/src/main/ddl/liquibase/db.changelog-1.5.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java
=> Add 'concrete' flag to data types

waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java, waltz-ng/client/common/components/multi-select-tree-control/multi-select-treecontrol.js, waltz-ng/client/data-types/components/data-type-overview.html, waltz-ng/client/data-types/components/data-type-tree.html
=> GUI stuff for non selectable data types

waltz-ng/client/common/components/multi-select-tree-control/multi-select-treecontrol.html, waltz-ng/client/data-types/components/data-type-tree.html, waltz-ng/client/data-types/data-type-list.html
=> Fixing multitree control

waltz-ng/client/data-types/components/data-type-overview.html, waltz-ng/client/data-types/components/data-type-tree.html
=> Data Types: make non-concrete types linkable

waltz-ng/client/actor/actor-view.html
=> Actor View: Flow diagrams not showing

waltz-ng/client/static-panel/components/static-panel.html
=> Fixing static panel

docs/releases/release-lifecycle.md
=> Document release lifecycle

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PersonDataGenerator.java
=> Update java library versions

pom.xml, waltz-schema/pom.xml
=> Update java library versions in response to security scan

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> Remove old perspective (1_1) tables

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.html, waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/measurable/measurable-list.html, waltz-ng/client/perspective/components/panel/perspective-rating-panel.html
=> Fixing tab names

docs/features/README.md, docs/features/configuration/svg_diagrams.md
=> Documenting Nav Aids

waltz-ng/client/source-data-rating/components/overlay/source-data-overlay.js
=> Source Data Overlay: remove extra console log 'loaded SDR'

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml, waltz-web/src/main/java/com/khartec/waltz/web/action/UpdateAppCapabilitiesAction.java
=> Measurables: remove app_capability table

waltz-ng/client/entity-statistics/directives/entity-statistic-numeric-renderer.js, waltz-ng/client/entity-statistics/directives/entity-statistic-percentage-renderer.js
=> Entity stat renders: isNumber check should use _.isNumber()

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml
=> Remove capability tables

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html
=> Measurable rating description: support markdown

waltz-model/src/main/java/com/khartec/waltz/model/user/Role.java, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/navbar/directives/navbar-profile.html, waltz-ng/client/navbar/directives/navbar-profile.js, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/user/index.js, waltz-ng/client/user/services/user-store.js, waltz-ng/client/user/user-management.html, waltz-ng/client/user/user-management.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/UserEndpoint.java
=> Create USER_ADMIN role

waltz-ng/client/measurable/routes.js
=> Measurable: route by external_id

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml, waltz-data/src/main/java/com/khartec/waltz/data/end_user_app/EndUserAppDao.java, waltz-model/src/main/java/com/khartec/waltz/model/enduserapp/EndUserApplication.java
=> End User App: add external id column

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupEntryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/asset_cost/AssetCostStatsDao.java, waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java, waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityLifecycleStatus.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityLifecycleStatusProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java
=> Add `EntityLifecycleStatus` on apps

waltz-data/src/main/java/com/khartec/waltz/data/user/UserRoleDao.java, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/system/system-admin-list.js, waltz-service/src/main/java/com/khartec/waltz/service/user/UserRoleService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/UserEndpoint.java
=> Allow ADMIN role to manage users

waltz-ng/client/auth-sources/edit.js
=> Authoritative Sources: Confirmation dialog on delete

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml
=> Attestation_1_6: rename primary key to attestation_1_6_pkey

pom.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/FlowLineageHarness.java, waltz-ng/client/common/d3-utils.js, waltz-ng/client/logical-flow-decorator/services/logical-flow-decorator-store.js, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-ng/client/playpen/4/entity-data-sourcing-panel/entity-data-sourcing-panel.html, waltz-ng/client/playpen/4/entity-data-sourcing-panel/entity-data-sourcing-panel.js, waltz-ng/client/playpen/4/flow-explorer/flow-explorer-utils.js, waltz-ng/client/playpen/4/flow-explorer/flow-explorer.html, waltz-ng/client/playpen/4/flow-explorer/flow-explorer.js, waltz-ng/client/playpen/4/flow-explorer/flow-explorer.scss, waltz-ng/client/playpen/4/foo-widget/foo-widget.html, waltz-ng/client/playpen/4/foo-widget/foo-widget.js, waltz-ng/client/playpen/4/playpen4.html, waltz-ng/client/playpen/4/playpen4.js, waltz-ng/client/playpen/4/playpen4.scss, waltz-ng/client/playpen/index.js, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowDecoratorEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
=> DataSourcing wip 

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml, waltz-data/src/main/java/com/khartec/waltz/data/enum_value/EnumValueDao.java, waltz-model/src/main/java/com/khartec/waltz/model/EnumValue.java, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/common/services/index.js, waltz-ng/client/data-types/services/data-type-service.js, waltz-ng/client/enum-value/index.js, waltz-ng/client/enum-value/services/enum-value-store.js, waltz-ng/client/modules.js, waltz-ng/client/playpen/1/playpen1.html, waltz-service/src/main/java/com/khartec/waltz/service/enum_value/EnumValueService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EnumValueEndpoint.java
=> Entity Enum Service, DAO, Table etc

waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html
=> Allow admin defined bookmark kinds (via enum-value table)

waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/involvement-kind/index.js, waltz-ng/client/involvement-kind/services/involvement-kind-store.js, waltz-ng/client/person/components/summary/person-summary.html, waltz-ng/client/person/components/summary/person-summary.js, waltz-ng/client/person/person-view-data.js
- bonus: converted involvement kind store to service broker
#2507
=> Adding org unit to person page

waltz-ng/client/navbar/components/nav-search-results.html, waltz-ng/client/navbar/components/nav-search-results.scss, waltz-ng/client/navbar/components/navbar-search-form.html, waltz-ng/client/widgets/toggle.js
- bonus: made it look like bookmark filter
#2509
=> FIX: click anywhere on search results category filter

waltz-ng/client/widgets/currency-amount.js
=> FIX: prevent 'undefined' showing whilst currency amount loading

waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/applications/components/app-costs-section/app-costs-section.js, waltz-ng/client/applications/data-load.js, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/common/role-utils.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-annotation-popup.js, waltz-ng/client/involvement/components/involved-people-section.html, waltz-ng/client/involvement/components/involved-people-section.js, waltz-ng/client/involvement/involvement-utils.js, waltz-ng/client/involvement/services/involvement-store.js, waltz-ng/client/logical-flow/components/edit/logical-flow-counterpart-selector.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/system/involvement-kinds-view.js
=> Allowing people to be assoc with DT's

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-ng/client/data-types/components/data-type-tree.html, waltz-ng/client/data-types/components/data-type-tree.js, waltz-ng/client/data-types/index.js, waltz-ng/client/logical-flow-decorator/services/logical-flow-decorator-store.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowDecoratorEndpoint.java
=> Summarize data type usage on dt index page

waltz-ng/client/data-types/components/data-type-tree.html, waltz-ng/client/data-types/components/data-type-tree.js, waltz-ng/client/involvement/components/involved-people-section.html
=> Simple fixes

waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/widgets/icon.js
=> Fixing wording on source/target graph

waltz-ng/client/common/services/service-broker.js
=> Better error reporting

docs/features/README.md, docs/features/asset_costs/asset_costs.md, docs/features/configuration/settings.md
=> Documenting asset codes

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.html, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.js, waltz-ng/client/flow-diagram/flow-diagram-utils.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/flow-diagram/services/flow-diagram-starter-service.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/playpen/1/playpen1.js
=> Flow Diagram - service for creating initial commands

waltz-ng/client/applications/resolvers.js, waltz-ng/client/applications/services/application-store.js, waltz-ng/client/server-info/services/server-info-store.js
=> Fixing up incorrect declaration in server-info-store

waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataExtractHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/MeasurableExporterHarness.java, waltz-ng/client/common/file-utils.js, waltz-ng/client/flow-diagram/flow-diagram-view.js, waltz-ng/client/logical-flow/components/logical-flows-tabgroup-section/logical-flows-tabgroup-section.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup-section/logical-flows-tabgroup-section.js, waltz-ng/client/measurable/measurable-list.html, waltz-ng/client/org-units/list-view.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/widgets/data-extract-link.html, waltz-ng/client/widgets/data-extract-link.js, waltz-ng/dev-server.sh, waltz-web/src/main/java/com/khartec/waltz/web/Main.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/BaseDataExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/CSVSerializer.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/LogicalFlowExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/MeasurableCategoryExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/OrgUnitExtractor.java
=> Export Viewpoints

waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml
=> Survey_Instance_Recipient: Add index on person_id

waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/widgets/inline-edit-area.html
=> Ratings Editor: Can't save comments in IE

waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type/search/DataTypeSearchDao.java, waltz-ng/client/data-types/services/data-type-store.js, waltz-ng/client/navbar/components/nav-search-overlay.js, waltz-service/src/main/java/com/khartec/waltz/service/data_type/DataTypeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataTypesEndpoint.java
=> Search: support for datatype

waltz-ng/client/logical-flow/components/logical-flow-edit-panel/logical-flow-edit-panel.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-utilities.js
=> Logical Flow Editor: Physical flow icons incorrect

waltz-ng/client/applications/directives/app-selector.js, waltz-ng/client/auth-sources/components/editor/auth-source-editor-panel.html, waltz-ng/client/auth-sources/components/editor/auth-source-editor-panel.js, waltz-ng/client/auth-sources/components/section/auth-sources-section.html, waltz-ng/client/auth-sources/components/summary-panel/auth-sources-summary-panel.html, waltz-ng/client/auth-sources/components/tree-picker/tree-picker.html, waltz-ng/client/auth-sources/components/tree-picker/tree-picker.js, waltz-ng/client/auth-sources/index.js, waltz-ng/client/common/hierarchy-utils.js, waltz-ng/client/data-types/components/data-type-tree.js, waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/data-types/data-type-list.js
=> Auth Sources editor

waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java
=> Fixing non-auth query for mssql server

waltz-ng/client/auth-sources/components/summary-panel/auth-sources-summary-panel.js
=> Making split pie look ok for zero flows

waltz-ng/client/svg-diagram/component/svg-diagrams.js
=> Tabbed SVG diagrams cause issues on IE

waltz-ng/client/auth-sources/components/summary-panel/auth-sources-summary-panel.js
=> Improving the auth source summary panel

waltz-ng/client/common/services/index.js, waltz-ng/client/routes.js
=> Ensure enums loaded before view rendering

waltz-ng/client/navbar/components/nav-search-overlay.html, waltz-ng/client/navbar/components/nav-search-overlay.js, waltz-ng/client/navbar/components/nav-search-overlay.scss
=> Search: Esc key whilst input not focussed should dismiss search overlay

docs/features/configuration/settings.md, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.js
=> Summary stats for known/unknown data types

waltz-model/src/main/java/com/khartec/waltz/model/entity_relationship/RelationshipKind.java, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/components/related-data-type-section/change-initiative-related-data-type-section.html, waltz-ng/client/change-initiative/components/related-data-type-section/change-initiative-related-data-type-section.js, waltz-ng/client/change-initiative/index.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-service/src/main/java/com/khartec/waltz/service/change_initiative/ChangeInitiativeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeInitiativeEndpoint.java
=> Allow Change Initiatives to be related with Data Types

waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/client/navbar/components/nav-search-overlay.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java
=> App Group search: doesn't work with uppercase and where - are in query

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> asset_cost: remove currency column

waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/survey/components/survey-section.js, waltz-ng/client/survey/index.js, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/services/survey-run-store.js
=> Componentise Surveys Section

waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/change-log/components/change-log-section.js
=> Changelog section: support turning lazy load off

waltz-ng/client/logical-flow/components/logical-flow-edit-panel/logical-flow-edit-panel.html
=> Logical flow editor: remove back to app link

waltz-ng/client/actor/actor-view.html, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/applications/components/apps-section/apps-section.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/org-units/unit-view.html
=> Apps section should derive scope

waltz-ng/client/actor/actor-view.html, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-view.html, waltz-ng/client/technology/components/technology-summary-section.js
=> Tech section should derive scope

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.js, waltz-ng/client/org-units/unit-view.html
=> Ratings Browser section should derive scope

waltz-ng/client/applications/pages/view/app-view.html, waltz-ng/client/common/components/dynamic-section-wrapper/dynamic-section-wrapper.js, waltz-ng/client/common/components/index.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/index.js
=> DynaWidget: Rename to DynamicSectionWrapper and move out of playpen

waltz-ng/client/actor/actor-view.html, waltz-ng/client/applications/app-view.html, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-specifications/physical-specification-view.html
=> Remove can-create param from flow diagrams

waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js
#2641 
@kamransaleem - could you do the honours pls ?
=> Componentize related-measurables-section

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/asset-cost/components/asset-costs-section.js
#2644 
@rovats - another gruelling review for you!
=> Remove scope param from asset-costs-section

waltz-ng/client/applications/pages/view/app-view.html, waltz-ng/client/common/components/dynamic-section-navigation/dynamic-section-navigation.html, waltz-ng/client/common/components/dynamic-section-navigation/dynamic-section-navigation.js, waltz-ng/client/common/components/dynamic-section-navigation/dynamic-section-navigation.scss, waltz-ng/client/common/components/index.js, waltz-ng/client/common/index.js, waltz-ng/style/_waltz.scss
=>  Navigation: Fade in navigation for DynamicSection when scrolling down

waltz-ng/client/common/components/dynamic-section-navigation/dynamic-section-navigation.js, waltz-ng/client/common/index.js, waltz-ng/client/widgets/page-header/page-header.js
=> Remove scroll to top animation

waltz-ng/client/navbar/components/nav-search-overlay.js
=> Clearing search resets selected category

waltz-ng/client/logical-flow/components/index.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js, waltz-ng/client/system/services/settings-service.js
=> Adding app name to source and target graph

waltz-ng/client/applications/pages/registration/app-registration.js
=> App Registration page broken

waltz-ng/client/common/checks.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/dynamic-section/dynamic-section-utils.js, waltz-ng/client/dynamic-section/services/dynamic-section-manager.js
=> Persisting dynamic sections (org unit / application)

waltz-ng/client/applications/formly/fields.js, waltz-ng/client/applications/pages/edit/app-edit.js, waltz-ng/client/applications/pages/registration/app-registration.js, waltz-ng/client/formly/index.js, waltz-ng/client/formly/org-unit-input-template.html
=> Register app page: org unit drop down hangs if too many nodes

waltz-ng/client/dynamic-section/dynamic-section-utils.js, waltz-ng/client/playpen/dyna-test-view/dyna-test-view.html, waltz-ng/client/playpen/dyna-test-view/dyna-test-view.js, waltz-ng/client/playpen/index.js
=> Allow hosting of a single dyna-section in a playpen page

waltz-data/src/main/java/com/khartec/waltz/data/asset_cost/AssetCostStatsDao.java
=> asset_cost: change total cost kind

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js, waltz-ng/client/measurable-relationship/components/viz/related-measurables-viz.js, waltz-ng/client/measurable/pages/list-view/measurable-list.js
=> Measurables and categories should be loaded at app level, not view level

waltz-ng/client/dynamic-section/components/dynamic-section-wrapper/dynamic-section-wrapper.js, waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.html, waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js
- bonus: sections without on remove no longer render 'close' icon
#2686
=> Phys Flow page now uses dyna-sections

waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js
=> Phys Spec page now uses dyna-sections

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-model/src/main/java/com/khartec/waltz/model/bookmark/Bookmark.java, waltz-ng/client/bookmarks/components/bookmark-kind-select/bookmark-kind-select.html, waltz-ng/client/bookmarks/components/bookmark-kind-select/bookmark-kind-select.js, waltz-ng/client/bookmarks/components/bookmarks-edit-panel/bookmarks-edit-panel.html, waltz-ng/client/bookmarks/directives/bookmark-form.html
=> Bookmarks: Ability to have "required" bookmarks

waltz-ng/client/system/recalculate-view.html, waltz-ng/client/system/recalculate-view.js
=> Remove attestations from Hierarchy Recalc page

waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-view.html
=> Survey: display instance id

waltz-ng/client/physical-flows/physical-flow-view.html
=> Show last updated by detail on physical flow detail page

waltz-ng/client/actor/pages/actor-view/actor-view.html, waltz-ng/client/app-groups/pages/view/app-group-view.html, waltz-ng/client/applications/pages/view/app-view.html, waltz-ng/client/change-initiative/pages/view/change-initiative-view.html, waltz-ng/client/data-types/pages/view/data-type-view.html, waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.html, waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.js, waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.scss, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/measurable/pages/measurable-view/measurable-view.html, waltz-ng/client/org-units/pages/unit-view/unit-view.html, waltz-ng/client/person/pages/view/person-view.html, waltz-ng/style/_variables.scss
=> Improving LnF of section nav bar

waltz-ng/client/person/components/person-apps-section/person-apps-section.js
=> Person apps section: Add 'Roles' column in exports

waltz-ng/client/extensions/extensions.js, waltz-ng/client/extensions/extensions.scss, waltz-ng/client/extensions/index.js, waltz-ng/client/modules.js, waltz-ng/style/_waltz.scss
=> UI extensions framework

pom.xml, waltz-schema/pom.xml
=> Upgrading mariadb drivers

waltz-ng/client/person/components/summary/person-summary.js
=> Waltz 2709

waltz-ng/client/entity-named-note/components/section/entity-named-notes-section.html
=> Entity Named Notes - removed nesting sections

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupEntryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-ng/client/app-groups/pages/edit/app-group-edit.html, waltz-ng/client/app-groups/pages/edit/app-group-edit.js, waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.html, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.js, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.scss, waltz-ng/client/applications/index.js, waltz-ng/client/applications/services/application-store.js, waltz-ng/client/entity/index.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-service/src/main/java/com/khartec/waltz/service/changelog/ChangeLogService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java
=> App Group: Bulk adding of applications into an App Group

waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.html, waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.js, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.js, waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.html, waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.js, waltz-ng/client/person/components/summary/person-summary.js
=> Showing bookmark category selector for all entity kinds

waltz-ng/client/dynamic-section/services/dynamic-section-manager.js
=> Prevent null dynamic section ids from entering local storage

waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java
=> BookmarkDao: Fix null URL mapping

waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js
=> Adding changelog section to phys flow view page

waltz-ng/client/auth-sources/components/section/auth-sources-section.js, waltz-ng/client/auth-sources/components/summary-panel/auth-sources-summary-panel.html, waltz-ng/client/auth-sources/components/summary-panel/auth-sources-summary-panel.js, waltz-ng/client/logical-flow/components/index.js, waltz-ng/client/logical-flow/components/rated-flow-summary/rated-flow-summary-panel.html, waltz-ng/client/logical-flow/components/rated-flow-summary/rated-flow-summary-panel.js
=> Better handling of no-data in auth sources section

waltz-service/src/main/java/com/khartec/waltz/service/involvement/InvolvementService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementEndpoint.java
=> Adding / Removing person involvement doesn't update change log

waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.scss, waltz-ng/client/widgets/page-header/page-header.scss
=> Sticky headers no longer capture events when hidden

waltz-ng/client/common/d3-utils.js, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.scss
=> Flow diagrams - curve lines

waltz-ng/client/asset-cost/components/asset-cost-table.js
=> Cost table: Cost kind filter doesn't work

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/LogicalFlowExtractor.java
=> LogicalFlowExtractor: Performance issue

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/FlowAttributes.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlow.java, waltz-ng/client/physical-flows/components/attribute-editor/physical-flow-attribute-editor.js, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.html, waltz-ng/client/physical-flows/components/register/physical-flow-edit-overview.html, waltz-ng/client/physical-flows/formly/physical-flow-fields.js, waltz-ng/client/physical-flows/physical-flow-registration.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
=> Adding criticality to phys flows

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/ChangeInitiativeGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/OrganisationalUnitIdProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/change_initiative/ChangeInitiative.java
Adding Org Unit Id to change initiative
#2742
=> Adding Org Unit Id to change initiative

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml
=>  Unique key on auth source table

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java, waltz-ng/client/data-flow/components/application-flow-summary-pane/application-flow-summary-pane.js, waltz-ng/client/data-types/data-type-utils.js, waltz-ng/client/data-types/services/data-type-store.js, waltz-ng/client/logical-flow/components/logical-flows-data-type-summary-pane/logical-flows-data-type-summary-pane.js
- re-purposed to add built-in support for the unknown data type
#2623
=> Ensure unknown data type is present and registered in settings table

waltz-ng/client/auth-sources/components/summary-panel/auth-sources-summary-panel.html, waltz-ng/client/auth-sources/components/summary-panel/auth-sources-summary-panel.js
=> Auth Source donuts missing

waltz-model/src/main/java/com/khartec/waltz/model/user/Role.java, waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-list-user-view.js, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-list.html, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js, waltz-ng/client/user/user-management.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyQuestionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey: New role SURVEY_TEMPLATE_ADMIN

waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.html, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.html
=> Entity Stats: show related even if parent has no data

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml
=> Remove unique constraint on Application.Name

waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-ng/client/change-log/components/change-log-section.js, waltz-ng/client/change-log/view.js, waltz-ng/client/profile/view.html, waltz-ng/client/profile/view.js, waltz-service/src/main/java/com/khartec/waltz/service/changelog/ChangeLogService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeLogEndpoint.java
=> Profile page not rendering properly

waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.js
=> Flow Diagram view broken

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-ng/client/orphan/services/orphan-store.js, waltz-ng/client/physical-flows/service/physical-flow-store.js, waltz-ng/client/system/orphans-view.html, waltz-ng/client/system/orphans-view.js, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/orphan/OrphanService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/OrphanEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Maintenance task: remove self flows

waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.js
=> Bulk App Selector: trim whitespaces for app identifiers

waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml
=> Fix for MSSQL

waltz-ng/client/dynamic-section/services/dynamic-section-manager.js
=> Sort dynamic sections based on name (but change log will come last)

waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html
=> Survey instance shows incorrect due date

waltz-ng/client/change-initiative/components/change-initiative-navigator-section/change-initiative-navigator-section.html, waltz-ng/client/change-initiative/components/change-initiative-navigator-section/change-initiative-navigator-section.js, waltz-ng/client/change-initiative/index.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> Change Initiative View: Show parent and child CI's

waltz-ng/client/flow-diagram/components/associations/flow-diagram-associations.html, waltz-ng/client/flow-diagram/components/associations/flow-diagram-associations.js, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/diagrams-panel/browse/flow-diagrams-panel-browse.html, waltz-ng/client/flow-diagram/components/diagrams-panel/browse/flow-diagrams-panel-browse.js, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.html, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.js, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.scss, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.scss, waltz-ng/client/flow-diagram/components/editor/flow-diagram-node-popup.html, waltz-ng/client/flow-diagram/components/section/flow-diagrams-section.html, waltz-ng/client/flow-diagram/flow-diagram.scss, waltz-ng/client/flow-diagram/index.js, waltz-ng/style/_waltz-popups.scss
This is a pre-cursor to doing the CI integration work
#2761
=> Flow diagram improvements

waltz-ng/client/flow-diagram/components/associations/flow-diagram-associations.js, waltz-ng/client/flow-diagram/components/diagrams-panel/browse/flow-diagrams-panel-browse.html, waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-annotation-popup.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-info-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-info-popup.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/flow-diagram/services/flow-diagram-entity-store.js, waltz-ng/client/widgets/editable-field.html, waltz-ng/client/widgets/editable-field.js, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramEntityService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FlowDiagramEntityEndpoint.java
=> More Flow diagram changes

waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/flow-diagram/components/change-initiative-associations/flow-diagram-change-initiative-associations.html, waltz-ng/client/flow-diagram/components/change-initiative-associations/flow-diagram-change-initiative-associations.js, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-info-popup.html, waltz-ng/client/flow-diagram/components/measurable-associations/flow-diagram-measurable-associations.html, waltz-ng/client/flow-diagram/components/measurable-associations/flow-diagram-measurable-associations.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js
=> Finally, flow diagrams can be linked to change initiatives

waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.html, waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.js, waltz-ng/client/common/components/grid/grid-with-search.html, waltz-ng/client/common/components/grid/grid-with-search.js, waltz-ng/client/common/components/grid/grid.js
=> Change Initiatives: slow to load

waltz-ng/client/bookmarks/directives/bookmark-form.html, waltz-ng/client/common/colors.js, waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.html, waltz-ng/client/examples/demo-endpoint-app-capability.html, waltz-ng/client/examples/demo-endpoint-application.html, waltz-ng/client/examples/demo-endpoint-person.html, waltz-ng/client/examples/demo-endpoint-perspective.html, waltz-ng/client/examples/waltz-roadmap.html, waltz-ng/client/logical-flow/components/logical-flow-edit-panel/logical-flow-edit-panel.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.html, waltz-ng/client/physical-specifications/components/specification-consumers/physical-specification-consumers.html
=> Fixing typos and rag colors

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/SetAttributeCommand.java, waltz-ng/client/physical-flows/components/flow-editor/physical-flow-editor.html, waltz-ng/client/physical-flows/components/flow-editor/physical-flow-editor.js, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.html, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.js, waltz-ng/client/physical-flows/index.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-flows/service/physical-flow-store.js, waltz-ng/client/widgets/editable-enum/editable-enum.html, waltz-ng/client/widgets/editable-enum/editable-enum.js, waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/sub-section.scss, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Allow editing of non crucial physical flow attributes

waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.js, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.scss
=> Flow Diagram: popup placement on IE incorrect

waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java
=> Revert CI status filter

docs/features/complexity/complexity.md
=> Document Complexity

waltz-ng/client/widgets/pie.js
=> Popping pie charts

waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> Adding bookmarks to person view

waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.html, waltz-ng/client/physical-flows/components/flow-editor/physical-flow-editor.html, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.html, waltz-ng/style/_waltz-field-table.scss
- bonus: render descriptions in markdown
#2802
=> Align popup fields to top

waltz-ng/client/applications/components/app-costs-section/app-costs-section.html, waltz-ng/client/asset-cost/components/asset-cost-table.html, waltz-ng/client/asset-cost/components/asset-cost-table.js, waltz-ng/client/asset-cost/components/asset-costs-section.html
=> Convert costs grid to new style (unified search)

waltz-ng/client/app-groups/components/subscription-buttons/subscription-buttons.html, waltz-ng/client/app-groups/components/subscription-buttons/subscription-buttons.js, waltz-ng/client/app-groups/components/summary/app-group-summary.html, waltz-ng/client/app-groups/components/summary/app-group-summary.js, waltz-ng/client/app-groups/index.js, waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/style/_waltz.scss
=> Add Subscribe/Unsubscribe buttons to app groups

docs/features/configuration/static-panels.md, waltz-ng/client/complexity/components/section/complexity-section.html, waltz-ng/client/complexity/components/section/complexity-section.js
=> Add info panel to complexity section

waltz-service/src/main/java/com/khartec/waltz/service/scheduled_job/ScheduledJobService.java
=> Scheduled jobs - change schedule

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/end_user_app/EndUserAppDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/AppGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/application/AppRegistrationRequest.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/enduserapp/EndUserApplication.java, waltz-ng/client/applications/application-utils.js, waltz-ng/client/applications/components/app-summary.js, waltz-ng/client/applications/components/apps-section/apps-section.js, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/applications/formly/fields.js, waltz-ng/client/applications/pages/registration/app-registration.js
=> Change Application.kind() to applicationKind()

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroup.java, waltz-ng/client/app-groups/pages/edit/app-group-edit.html, waltz-ng/client/app-groups/pages/view/app-group-view.html, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java
=> Change AppGroup.kind() to appGroupKind()

waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-model/src/main/java/com/khartec/waltz/model/bookmark/Bookmark.java, waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.js, waltz-ng/client/bookmarks/components/bookmarks-edit-panel/bookmarks-edit-panel.html, waltz-ng/client/bookmarks/components/bookmarks-edit-panel/bookmarks-edit-panel.js, waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.html, waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.js, waltz-ng/client/bookmarks/directives/bookmark-form.html, waltz-ng/client/bookmarks/directives/bookmark-form.js, waltz-service/src/main/java/com/khartec/waltz/service/bookmark/BookmarkService.java
=> Change Bookmark.kind() to bookmarkKind()

waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/change_initiative/ChangeInitiative.java, waltz-ng/client/change-initiative/components/change-initiative-navigator-section/change-initiative-navigator-section.js, waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.js, waltz-ng/client/change-initiative/pages/view/change-initiative-view.html
=> Change ChangeInitiative.kind() to changeInitiativeKind()

waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PersonDataGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/person/Person.java
=> Change Person.kind() to personKind()

waltz-model/src/main/java/com/khartec/waltz/model/EntityKindProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/actor/Actor.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroup.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/bookmark/Bookmark.java, waltz-model/src/main/java/com/khartec/waltz/model/change_initiative/ChangeInitiative.java, waltz-model/src/main/java/com/khartec/waltz/model/cost/Cost.java, waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java, waltz-model/src/main/java/com/khartec/waltz/model/enduserapp/EndUserApplication.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable/Measurable.java, waltz-model/src/main/java/com/khartec/waltz/model/orgunit/OrganisationalUnit.java, waltz-model/src/main/java/com/khartec/waltz/model/person/Person.java
=> All Entities derive from an KindProvider interface

waltz-ng/client/flow-diagram/components/diagrams-panel/flow-diagrams-panel.js, waltz-ng/client/flow-diagram/services/flow-diagram-starter-service.js
=> Flow Diagram: Creating new diagram for a measurable throws error

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/BaseDataExtractor.java
=> CSV Mulitline exports breaking when region/format is set to 'German'

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupEntryDao.java, waltz-ng/client/app-groups/pages/edit/app-group-edit.html, waltz-ng/client/app-groups/pages/edit/app-group-edit.js, waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.html, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.js, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java
=> App groups: delete all apps or bulk replace

waltz-ng/client/auth-sources/components/section/auth-sources-section.html, waltz-ng/client/auth-sources/components/section/auth-sources-section.js, waltz-ng/client/logical-flow/components/rated-flow-summary/rated-flow-summary-info-cell.html, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java
=> Auth sources view fixes

waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/entity-statistics/services/entity-statistics-utilities.js
=> Add Entity Stats to CI's

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/BusinessRegionProductHierarchyGenerator.java
=> Auth Source Measurable Hierarchy generator

waltz-ng/client/common/services/enums.js
=> Updating enums

waltz-data/src/main/java/com/khartec/waltz/data/measurable_category/MeasurableCategoryDao.java, waltz-ng/client/auth-sources/components/navigator-chart/auth-sources-navigator-chart.js, waltz-ng/client/auth-sources/components/navigator-chart/auth-sources-navigator-chart.scss, waltz-ng/client/auth-sources/components/navigator/auth-sources-navigator.html, waltz-ng/client/auth-sources/components/navigator/auth-sources-navigator.js, waltz-ng/client/common/d3-utils.js
- bonus: truncate long text
- bonus: ordering of measurable categories
#2861
=> Allow switching between measurable types

waltz-ng/client/auth-sources/services/auth-source-navigator-utils.js, waltz-ng/client/system/services/settings-names.js
=> Filter rowgroups where zero entries

waltz-ng/client/auth-sources/components/navigator-chart/auth-sources-navigator-chart.js, waltz-ng/client/auth-sources/components/navigator/auth-sources-navigator.html, waltz-ng/client/auth-sources/components/navigator/auth-sources-navigator.js, waltz-ng/client/auth-sources/services/auth-source-navigator-utils.js, waltz-ng/client/common/d3-utils.js
- bonus, truncating is on timeout to ensure it happens
- bonus, fixed description category names
#2862
=> Fixing view when no data

README.md
=> Fix whitespace in readme.md

waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js
=> Related Viewpoints, error on export

waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.html, waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.js, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.js
=> Fixing ordering of data type selector dropdown

waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-physical-flow-popup.js
=> Sort physical / logical flows in diagram popups

waltz-ng/client/auth-sources/components/section/auth-sources-section.html, waltz-ng/client/drill-grid/components/definition-selector/drill-grid-definition-selector.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.js, waltz-ng/client/measurable-rating/components/browser-tree-panel/measurable-ratings-browser-tree-panel.html, waltz-ng/client/measurable-rating/components/browser-tree-panel/measurable-ratings-browser-tree-panel.js, waltz-ng/client/measurable-rating/index.js
Also tidied up the drill grid definition selector 
#2896
=> Moved drill grid explorer into the ratings section

waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/spreadsheet-loader/spreadsheet-loader.html, waltz-ng/client/widgets/spreadsheet-loader/spreadsheet-loader.js, waltz-ng/package.json
=>  Bulk Loader: Excel spreadsheet reader and parser

waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.html, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.js, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.scss, waltz-ng/client/drill-grid/utils/row-group.js
=> Adding tooltips

waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/client/widgets/column-mapper/column-mapper.html, waltz-ng/client/widgets/column-mapper/column-mapper.js, waltz-ng/client/widgets/index.js
=> Bulk Loader: Column Mapper

waltz-ng/client/common/string-utils.js, waltz-ng/client/drill-grid/components/definition-selector/drill-grid-definition-selector.html, waltz-ng/client/drill-grid/components/definition-selector/drill-grid-definition-selector.js, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.html, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.js, waltz-ng/client/drill-grid/components/drill-grid-panel/drill-grid-panel.js, waltz-ng/client/playpen/4/playpen4.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java, waltz-service/src/main/java/com/khartec/waltz/service/scheduled_job/ScheduledJobService.java
=> Drill grid improvements

waltz-ng/client/dynamic-section/services/dynamic-section-manager.js
=> Toggle dynamic sections (if it's at the top)

waltz-ng/client/data-types/components/usage-panel/data-type-usage-panel.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/widgets/editable-enum/editable-enum.html, waltz-ng/client/widgets/editable-enum/editable-enum.js, waltz-ng/style/_animations.scss
Bonus:
- 'focus flash' when switching to edit mode
#2913
=> Fixed editor dropdowns

waltz-data/src/main/ddl/liquibase/db.changelog-1.8.xml, waltz-data/src/main/java/com/khartec/waltz/data/entity_event/EntityEventDao.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_event/EntityEvent.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_event/EntityEventService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityEventEndpoint.java
- DDL
- DAO/Service/Endpoint
#2924
=> Entity timeline

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/data_flow_decorator/UpdateDataFlowDecoratorsAction.java, waltz-ng/client/logical-flow-decorator/services/logical-flow-decorator-store.js, waltz-ng/client/logical-flow/components/bulk-logical-flow-loader-wizard/bulk-logical-flow-loader-wizard.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-loader-wizard/bulk-logical-flow-loader-wizard.js, waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.js, waltz-ng/client/logical-flow/components/bulk-logical-flow-uploader/bulk-logical-flow-uploader.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-uploader/bulk-logical-flow-uploader.js, waltz-ng/client/logical-flow/components/index.js, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/client/widgets/column-mapper/column-mapper.html, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowDecoratorEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
=> Logical Flow Wizard + Upload functionality

waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.js
=> Bulk Loader: Improve summary on logical flow parser component

waltz-ng/client/logical-flow/components/bulk-logical-flow-loader-wizard/bulk-logical-flow-loader-wizard.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-loader-wizard/bulk-logical-flow-loader-wizard.js, waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.js, waltz-ng/client/logical-flow/components/bulk-logical-flow-uploader/bulk-logical-flow-uploader.js
=> Bulk Loader: Prevent Next when current step is in invalid state

waltz-data/src/main/ddl/liquibase/db.changelog-1.8.xml, waltz-data/src/main/java/com/khartec/waltz/data/entity_workflow/EntityWorkflowStateDao.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_workflow/EntityWorkflowState.java
=> EntityWorkflowState: Add description column

waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.js, waltz-ng/client/widgets/column-mapper/column-mapper.js
=> Bulk Loader: incorporate wizard into dataflows section

waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.js, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.scss, waltz-ng/client/playpen/4/playpen4.js, waltz-ng/style/_waltz-scroll-region.scss
=> Drill Grid Improvements to popups - Db contrib/waltz 2942

waltz-data/src/main/ddl/liquibase/db.changelog-1.8.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-ng/client/applications/components/overview/app-overview.html
=> Store and display app retirement dates

waltz-ng/client/widgets/spreadsheet-loader/spreadsheet-loader.html, waltz-ng/client/widgets/spreadsheet-loader/spreadsheet-loader.js
=> Bulk Loader: Spreadsheet loader errors in prod mode

waltz-ng/client/widgets/spreadsheet-loader/spreadsheet-loader.js
=> Db contrib/IE filereader bug

waltz-data/src/main/ddl/liquibase/db.changelog-1.8.xml, waltz-ng/client/change-initiative/components/change-initiative-navigator-section/change-initiative-navigator-section.js, waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.js, waltz-ng/client/change-initiative/pages/view/change-initiative-view.html, waltz-ng/client/extensions/components/change-initiative/change-initiative-section/db-change-initiative-section.html
=> Soft code changeInitiativeLifecyclePhase

waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java
=> Logical Bulk Uploader: Change log entry incorrect

waltz-service/src/main/java/com/khartec/waltz/service/changelog/ChangeLogService.java
=> Db contrib/waltz 2966 change log phs flows

waltz-data/src/main/ddl/liquibase/db.changelog-1.8.xml
=> EntityStatisticValue: Create index on statistic_id + outcome

waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.js
=> Logical Bulk Loader: Ability to export parse errors

waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.js
=> Logical Bulk Loader: Report circular flows as errors

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java
=> Indicator history: Improve performance

waltz-ng/client/logical-flow/components/bulk-logical-flow-uploader/bulk-logical-flow-uploader.js
=> Logical Bulk Loader: do a distinct on new logical flow uploads

waltz-ng/client/survey/survey-instance-response-edit.js
=> Survey: Remind users to save survey comments before submitting

waltz-model/src/main/java/com/khartec/waltz/model/EntityReference.java, waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/common/services/enums.js, waltz-ng/client/navbar/components/nav-search-overlay.html, waltz-ng/client/navbar/components/nav-search-overlay.js, waltz-ng/client/widgets/toggle.html
=> Db contrib/waltz 2986 search removed filer

waltz-ng/client/applications/components/related-apps-section/related-apps-section.js, waltz-ng/client/common/selector-utils.js
=> Db contrib/waltz 2990 view retired apps programme page

waltz-service/src/main/java/com/khartec/waltz/service/change_initiative/ChangeInitiativeService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_relationship/EntityRelationshipUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable_relationship/MeasurableRelationshipService.java
=> Db contrib/waltz 2992 remove related app validation

waltz-ng/client/common/filters/index.js, waltz-ng/client/involvement/components/involved-people-section.js
=> Involvements: Show provenance of involvements in Waltz

waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.js
=>  Flow Diagram: Click here to add new node doesn't work 

waltz-data/src/main/ddl/liquibase/db.changelog-1.8.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstance.java, waltz-ng/client/survey/components/survey-section.html, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyInstanceEndpoint.java
=> Allow completed surveys to be approved

waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FlowDiagramEndpoint.java
=> Flow Diagram: Change log entry when diagram changed

waltz-data/src/main/java/com/khartec/waltz/data/entity_svg_diagram/EntitySvgDiagramDao.java
=> Db contrib/waltz 2883 entity svg diagram optional external

waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js
=> Db contrib/waltz 2880 survey show coordinator

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/applications/components/overview/app-overview.js, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java
=> Db contrib/waltz 2890 app view group membership

waltz-ng/client/person/components/person-apps-section/person-apps-section.js
=> Db contrib/waltz 3007 person app section involvement bug

waltz-data/src/main/ddl/liquibase/db.changelog-1.9.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/enum_value/EnumValueDao.java, waltz-model/src/main/java/com/khartec/waltz/model/EnumValue.java, waltz-model/src/main/java/com/khartec/waltz/model/PositionProvider.java, waltz-ng/client/applications/formly/fields.js, waltz-ng/client/common/services/enums.js, waltz-ng/client/enum-value/services/enum-value-service.js, waltz-ng/client/widgets/editable-enum/editable-enum.html, waltz-ng/client/widgets/editable-enum/editable-enum.js
=> Add explicit ordering to enum values

waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceStatusChangeCommand.java, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java
=> Add a comment field when marking a survey back in progress

waltz-ng/client/common/d3-context-menu.js
=> Missing copyright/license terms from 3rd party authors

waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js, waltz-ng/client/entity-statistics/services/entity-statistics-utilities.js
=> EntityStatisticView: convert to service broker

waltz-data/pom.xml, waltz-data/src/main/java/com/khartec/waltz/data/SearchUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/application/search/MariaAppSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/application/search/SqlServerAppSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/search/PhysicalSpecificationSearchDao.java, waltz-data/src/test/java/com/khartec/waltz/data/SearchUtilities_RelevancyComparatorTest.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/MsSqlSearchHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/PhysicalSpecificationHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_search/EntitySearchOptions.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification/PhysicalSpecification.java, waltz-ng/client/navbar/components/nav-search-overlay.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_search/EntitySearchService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification/PhysicalSpecificationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecificationEndpoint.java
Also improves the entity search facility and reroutes the main search functionality through that.
#3034
=> Improve search ordering

waltz-ng/client/survey/survey-instance-response-edit.js
=> Survey response authorisation is case sensitive

waltz-ng/package.json
=> Updating moment js

waltz-ng/index.template.html
=> Db contrib/waltz 3024 anim colour

waltz-ng/client/logical-data-element/logical-data-element-view.html, waltz-ng/client/logical-data-element/logical-data-element-view.js, waltz-ng/client/logical-data-element/routes.js
=> Db contrib/waltz 3053 lde page

waltz-ng/client/entity-enum/components/entity-enum/entity-enum.js, waltz-ng/client/enum-value/components/enum-value/enum-value.js
=> Db contrib/waltz 3030 entity enum fix

waltz-ng/client/survey/survey-instance-response-view.js, waltz-ng/client/survey/survey-instance-view.js
=> Db contrib/waltz 3045 prompt ie fix

waltz-ng/client/survey/components/survey-section.html, waltz-ng/client/survey/components/survey-section.js
=> Db contrib/waltz 3062 survey section

waltz-data/src/main/java/com/khartec/waltz/data/physical_specification_definition/PhysicalSpecDefinitionFieldDao.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_data_element/LogicalDataElementChangeCommand.java, waltz-ng/client/entity/components/entity-selector/entity-selector.html, waltz-ng/client/entity/components/entity-selector/entity-selector.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-specifications/components/spec-definition/physical-spec-definition-panel.js, waltz-ng/client/widgets/editable-field.html, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification_definition/PhysicalSpecDefinitionFieldService.java
=> Db contrib/waltz 3069 entity selector clearable

waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_data_element/LogicalDataElement.java, waltz-ng/client/common/common.scss, waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/common/components/entity-link/entity-icon-label.scss, waltz-ng/client/entity/components/entity-selector/entity-selector.html, waltz-ng/client/entity/components/entity-selector/entity-selector.js, waltz-ng/client/entity/components/entity-selector/entity-selector.scss, waltz-ng/client/navbar/components/nav-search-overlay.js
=> Db contrib/waltz 3074 entity selector status

waltz-common/src/main/java/com/khartec/waltz/common/DigestUtilities.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.9.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/com/khartec/waltz/data/shared_preference/SharedPreferenceDao.java, waltz-model/src/main/java/com/khartec/waltz/model/shared_preference/SharedPreference.java, waltz-model/src/main/java/com/khartec/waltz/model/shared_preference/SharedPreferenceSaveCommand.java, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/logical-flow/components/bulk-logical-flow-loader-wizard/bulk-logical-flow-loader-wizard.html, waltz-ng/client/logical-flow/components/bulk-logical-flow-loader-wizard/bulk-logical-flow-loader-wizard.js, waltz-ng/client/modules.js, waltz-ng/client/physical-flows/components/bulk-physical-flow-loader-wizard/bulk-physical-flow-loader-wizard.html, waltz-ng/client/physical-flows/components/bulk-physical-flow-loader-wizard/bulk-physical-flow-loader-wizard.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/client/shared-preference/index.js, waltz-ng/client/shared-preference/services/shared-preference-store.js, waltz-ng/client/widgets/column-mapper/column-mapper.js, waltz-service/src/main/java/com/khartec/waltz/service/shared_preference/SharedPreferenceService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SharedPreferenceEndpoint.java
=> Db contrib/waltz 3077 column mapping persist

waltz-ng/client/shared-preference/services/shared-preference-store.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SharedPreferenceEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/json/SharedPreferenceKeyAndCategory.java
=> Db contrib/waltz 3082 shared preference post

waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/TransportKind.java, waltz-ng/client/common/services/enums.js
=> Add 'manual' to physical file transport types

docs/features/configuration/static-panels.md, waltz-ng/client/data-types/pages/home/data-type-list.html, waltz-ng/client/data-types/pages/home/data-type-list.js, waltz-ng/client/static-panel/components/static-panel.js
=> Adding auth source static panel to data type home page

waltz-ng/client/drill-grid/components/definition-selector/drill-grid-definition-selector.js, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.html, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.js, waltz-ng/client/drill-grid/components/drill-grid-chart/drill-grid-chart.scss, waltz-ng/client/drill-grid/components/drill-grid-panel/drill-grid-panel.html, waltz-ng/client/drill-grid/components/drill-grid-panel/drill-grid-panel.js, waltz-ng/client/drill-grid/utils/hierarchical-axis.js, waltz-ng/client/widgets/loading-notification.js
=> Db contrib/waltz 3088 drill grid

waltz-ng/client/auth-sources/components/section/auth-sources-section.js, waltz-ng/client/auth-sources/components/table/auth-sources-table.html, waltz-ng/client/auth-sources/components/table/auth-sources-table.js, waltz-ng/client/common/grid-utils.js
=> Auth source table move to grid w/ search

waltz-model/src/main/java/com/khartec/waltz/model/user/PasswordResetRequest.java, waltz-ng/client/entity-named-note/components/panel/entity-named-notes-panel.js, waltz-ng/client/profile/view.html, waltz-ng/client/profile/view.js, waltz-ng/client/user/services/user-store.js, waltz-service/src/main/java/com/khartec/waltz/service/user/UserService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/UserEndpoint.java
=> Allow user password resets

waltz-data/src/main/ddl/liquibase/db.changelog-1.9.xml, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlow.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowUploadService.java
=> Db contrib/waltz 3022 physical flow external

waltz-data/src/main/ddl/liquibase/db.changelog-1.9.xml
=> Db contrib/waltz 3104 custom rating

waltz-ng/client/logical-flow/components/bulk-logical-flow-loader-wizard/bulk-logical-flow-loader-wizard.js, waltz-ng/client/logical-flow/components/bulk-logical-flow-parser/bulk-logical-flow-parser.js, waltz-ng/client/physical-flows/components/bulk-physical-flow-loader-wizard/bulk-physical-flow-loader-wizard.js, waltz-ng/client/physical-flows/components/bulk-physical-flow-parser/bulk-physical-flow-parser.js, waltz-ng/client/widgets/_styles.scss, waltz-ng/client/widgets/column-mapper/column-mapper.html, waltz-ng/client/widgets/column-mapper/column-mapper.js, waltz-ng/client/widgets/column-mapper/column-mapper.scss, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowUploadService.java
=> Db contrib/waltz 3108 column mapper look feel

waltz-ng/client/common/services/service-broker.js, waltz-ng/client/physical-flows/components/bulk-physical-flow-parser/bulk-physical-flow-parser.html, waltz-ng/client/physical-flows/components/bulk-physical-flow-parser/bulk-physical-flow-parser.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Db contrib/waltz 3111 uploader parse exceptions

waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-list-user-view.js, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js
=> Db contrib/waltz 3116 survey grid search

docs/features/configuration/static_panels.md, waltz-ng/client/applications/components/app-costs-section/app-costs-section.html, waltz-ng/client/applications/components/app-costs-section/app-costs-section.js, waltz-ng/client/asset-cost/components/asset-costs-section.html, waltz-ng/client/asset-cost/components/asset-costs-section.js, waltz-ng/client/auth-sources/components/section/auth-sources-section.html, waltz-ng/client/auth-sources/components/section/auth-sources-section.js, waltz-ng/client/complexity/components/section/complexity-section.html, waltz-ng/client/complexity/components/section/complexity-section.js, waltz-ng/client/data-types/pages/home/data-type-list.html, waltz-ng/client/data-types/pages/home/data-type-list.js, waltz-ng/client/measurable/pages/list-view/measurable-list.html, waltz-ng/client/measurable/pages/list-view/measurable-list.js, waltz-ng/client/org-units/pages/list-view/list-view.html, waltz-ng/client/org-units/pages/list-view/list-view.js, waltz-ng/client/person/pages/home/person-home.html, waltz-ng/client/person/pages/home/person-home.js, waltz-ng/client/perspective/perspective-rating-edit.html, waltz-ng/client/perspective/perspective-rating-edit.js, waltz-ng/client/static-panel/components/static-panels.js, waltz-ng/client/welcome/welcome.html, waltz-ng/client/welcome/welcome.js
=> Static panels use service broker to load their own data

waltz-jobs/src/main/java/com/khartec/waltz/jobs/MsSqlSearchHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_search/EntitySearchOptions.java
=> Increasing search results

waltz-ng/client/applications/formly/fields.js, waltz-ng/client/attestation/attestation-run-create.js, waltz-ng/client/auth-sources/components/editor/auth-source-editor-panel.html, waltz-ng/client/auth-sources/components/editor/auth-source-editor-panel.js, waltz-ng/client/entity/components/entity-involvement-editor/entity-involvement-editor.js, waltz-ng/client/entity/components/entity-selector/entity-selector.js, waltz-ng/client/entity/components/related-entity-editor/related-entity-editor.js, waltz-ng/client/flow-diagram/components/change-initiative-associations/flow-diagram-change-initiative-associations.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-node-popup.js, waltz-ng/client/formly/index.js, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js, waltz-ng/client/person/pages/home/person-home.html, waltz-ng/client/person/pages/home/person-home.js, waltz-ng/client/physical-specifications/components/create/physical-spec-definition-create-panel.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-ng/client/survey/components/survey-run-create-general.js, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-view.js, waltz-ng/client/widgets/editable-field.js
=> Swap args and then remove redundant arg

docs/task_notes/919-legend.txt, waltz-common/src/main/java/com/khartec/waltz/common/ArrayUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/DebugUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/IOUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/StreamUtilities.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.10.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable_category/MeasurableCategoryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/perspective_definition/PerspectiveDefinitionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/InvolvementImporter.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/SurveyBuilder.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionDropdownEntry.java, waltz-ng/client/common/colors.js, waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/common/components/entity-link/entity-icon-label.js, waltz-ng/client/perspective/components/editor/perspective-editor.html, waltz-ng/client/perspective/components/editor/perspective-editor.js, waltz-ng/client/perspective/components/grid/perspective-grid.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.js, waltz-service/src/main/java/com/khartec/waltz/service/rating_scheme/RatingSchemeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/RatingSchemeEndpoint.java
=> Db contrib/waltz 3144 rating dao

waltz-ng/client/common/services/enums/field-data-type.js, waltz-ng/client/common/services/enums/index.js
=> Ensuring js enum has same name as java counterpart

waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/StringUtilities_firstChar.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.10.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-data/src/main/java/com/khartec/waltz/data/perspective_rating/PerspectiveRatingDao.java, waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/SurveyBuilder.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/MeasurableRating.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/SaveMeasurableRatingCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/perspective/PerspectiveRatingValue.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RagName.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RagRating.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RatingScheme.java, waltz-model/src/main/java/com/khartec/waltz/model/tally/MeasurableRatingTally.java, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/common/filters/index.js, waltz-ng/client/common/filters/use-default-rating-scheme-filter.js, waltz-ng/client/logical-flow/components/logical-flow-table/logical-flow-table.js, waltz-ng/client/measurable-rating/components/browser-tree-panel/measurable-ratings-browser-tree-panel.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.js, waltz-ng/client/ratings/rating-utils.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Db contrib/waltz 3151 rag enum

waltz-common/src/main/java/com/khartec/waltz/common/DateTimeUtilities.java, waltz-data/src/main/ddl/liquibase/README.md, waltz-data/src/main/ddl/liquibase/db.changelog-1.10.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/MeasurableRating.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/SaveMeasurableRatingCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RagName.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RatingScheme.java, waltz-ng/client/common/components/date-picker/date-picker-form-input.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/services/measurable-rating-store.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Db contrib/waltz 3169 ratings set planned date

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java
=> Db contrib/waltz 3171

waltz-ng/client/survey/survey-instance-response-view.html
=> Db contrib/waltz 3180 survey approved response

waltz-ng/client/attestation/attestation-instance-list-user-view.html, waltz-ng/client/attestation/attestation-run-list.html, waltz-ng/client/attestation/components/section/attestation-section.html, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-ng/client/survey/components/instance-list/survey-instance-list.html, waltz-ng/client/survey/survey-instance-list-user-view.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-view.html, waltz-ng/client/survey/survey-run-view.html, waltz-ng/client/survey/survey-template-view.js, waltz-ng/client/widgets/from-now.js
=> Db contrib/waltz 3174 from now nearest day

waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/ChangeReporter.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/FlowSummaryExport.java, waltz-service/src/main/java/com/khartec/waltz/service/DIConfiguration.java, waltz-web/README.md
=> Db contrib/waltz 2907 scheduler and reports

waltz-data/src/main/ddl/liquibase/db.changelog-1.11.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java
=> Db contrib/waltz 3166 measurable planned date type

waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/AuthSourceHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/FlowSummaryExport.java, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceResolver.java, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorRatingsCalculator.java
=> Db contrib/waltz 3196 auth rating calc

waltz-data/src/main/java/com/khartec/waltz/data/ExternalIdUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstance.java, waltz-ng/client/survey/survey-instance-list-user-view.js
=> Db contrib/waltz 3118 survey show external

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowSearchDao.java, waltz-schema/pom.xml
=> Updating jOOQ

waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_relationship/RelationshipKind.java
=> Db contrib/waltz 3194

pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 3156 update libs

waltz-ng/client/physical-flows/components/flow-editor/physical-flow-editor.html, waltz-ng/client/physical-flows/components/flow-editor/physical-flow-editor.js
=> Db contrib/waltz 3094 basis offset editable

waltz-ng/client/attestation/attestation-run-view.js
=> Db contrib/waltz 3218 att indicator cell blank

waltz-ng/client/attestation/attestation-run-view.js, waltz-ng/client/widgets/from-now.js
=> Db contrib/waltz 3219 from now not updating null

waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.html, waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.js, waltz-ng/client/logical-flow/components/index.js, waltz-ng/client/logical-flow/components/logical-flows-boingy-graph/logical-flows-boingy-graph.html, waltz-ng/client/logical-flow/components/logical-flows-boingy-graph/logical-flows-boingy-graph.js, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.js, waltz-ng/client/logical-flow/services/logical-flow-utility.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js
=> Boingy graph uses hierarchical data type selector

waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/widgets/from-now.js
=> Db contrib/waltz 3228 group notes

waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html
=> Db contrib/waltz 3234 logical flows add here link

waltz-common/src/main/java/com/khartec/waltz/common/StreamUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/AppGroupHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_relationship/Directionality.java, waltz-ng/client/app-groups/app-group-utils.js, waltz-ng/client/app-groups/components/related-app-groups-section/related-app-groups-section.html, waltz-ng/client/app-groups/components/related-app-groups-section/related-app-groups-section.js, waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/client/applications/components/overview/app-overview.js, waltz-ng/client/common/promise-utils.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/common/services/enums/app-group-kind.js, waltz-ng/client/common/services/enums/index.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/entity-relationship/index.js, waltz-ng/client/entity-relationship/services/entity-relationship-store.js, waltz-ng/client/modules.js, waltz-ng/client/user/services/user-store.js, waltz-ng/style/_waltz-visibility.scss, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_relationship/EntityRelationshipService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityRelationshipEndpoint.java
=> Related app groups

waltz-ng/client/change-initiative/index.js, waltz-ng/client/data-types/components/related-data-types-section/related-data-types-section.html, waltz-ng/client/data-types/components/related-data-types-section/related-data-types-section.js, waltz-ng/client/data-types/components/usage-tree/data-type-usage-tree.js, waltz-ng/client/data-types/index.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> Relating groups to data types

waltz-ng/client/app-groups/pages/view/app-group-view.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js, waltz-ng/client/measurable-relationship/components/viz/related-measurables-viz.js, waltz-ng/client/measurable-relationship/measurable-relationship-utils.js
=> Db contrib/waltz 3245 spindle app group

waltz-ng/client/applications/components/related-apps-section/related-apps-section.js, waltz-ng/client/entity/components/related-entity-editor/related-entity-editor.html, waltz-ng/client/entity/components/related-entity-editor/related-entity-editor.js, waltz-ng/client/widgets/editable-dropdown/editable-dropdown.html, waltz-ng/client/widgets/editable-dropdown/editable-dropdown.js, waltz-ng/client/widgets/index.js
=> Db contrib/waltz 3249 ci app reln edit

waltz-ng/client/measurable/pages/list-view/measurable-list.js
=> Db contrib/waltz 3251 lazy svg diagrams

waltz-ng/client/auth-sources/components/table/auth-sources-table.js, waltz-ng/client/measurable/pages/list-view/measurable-list.js
=> Fixing auth source filter and minor measurable index bug

waltz-ng/client/measurable-relationship/components/item-view/related-measurable-item-view.html, waltz-ng/client/measurable-relationship/components/item-view/related-measurable-item-view.js, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.html, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.js, waltz-ng/client/measurable-relationship/index.js
Waltz #3256 spindle improvements
=> Spindle improvements

waltz-ng/client/measurable-relationship/components/table/related-measurables-table.html
=> Adding filtering to measurable relationships

waltz-ng/package.json, waltz-ng/webpack.config.js
=> webpack 4.x perf tweaks

waltz-ng/client/attestation/attestation-run-view.html, waltz-ng/client/widgets/data-extract-link.js, waltz-web/src/main/java/com/khartec/waltz/web/Main.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AttestationExtractor.java
=> Db contrib/waltz 3276 export attestations

pom.xml, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-jobs/pom.xml, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/ShortestPath.java
=> Graph demo

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/MeasurableRatingHarness.java, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/measurable-rating/services/measurable-rating-store.js, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.html, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/tree/related-measurables-tree.html, waltz-ng/client/measurable-relationship/components/tree/related-measurables-tree.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Db contrib/waltz 3315 spindle bug

waltz-data/src/main/ddl/liquibase/db.changelog-1.12.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/com/khartec/waltz/data/assessment_definition/AssessmentDefinitionDao.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_definition/AssessmentDefinition.java, waltz-ng/client/assessment_definition/index.js, waltz-ng/client/assessment_definition/services/assessment-definition-store.js, waltz-ng/client/assessment_definition/services/index.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/modules.js, waltz-service/src/main/java/com/khartec/waltz/service/assessment_definition/AssessmentDefinitionService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssessmentDefinitionEndpoint.java
=> Assessments: Immutable, DAO, Service, Endpoint, Store

waltz-data/src/main/ddl/liquibase/db.changelog-1.12.xml, waltz-data/src/main/java/com/khartec/waltz/data/assessment_definition/AssessmentDefinitionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/assessment_rating/AssessmentRatingDao.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_rating/AssessmentRating.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_rating/AssessmentRatingCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_rating/RemoveAssessmentRatingCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_rating/SaveAssessmentRatingCommand.java, waltz-ng/client/assessments/components/editor/assessment-rating-editor.html, waltz-ng/client/assessments/components/editor/assessment-rating-editor.js, waltz-ng/client/assessments/components/panel/assessment-rating-panel.html, waltz-ng/client/assessments/components/panel/assessment-rating-panel.js, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.html, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.js, waltz-ng/client/assessments/index.js, waltz-ng/client/assessments/services/assessment-definition-store.js, waltz-ng/client/assessments/services/assessment-rating-store.js, waltz-ng/client/assessments/services/index.js, waltz-ng/client/change-initiative/pages/view/change-initiative-view.html, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/entity/components/related-entity-editor/related-entity-editor.js, waltz-ng/client/modules.js, waltz-ng/client/playpen/5/playpen5.html, waltz-ng/client/ratings/rating-utils.js, waltz-ng/client/widgets/editable-dropdown/editable-dropdown.html, waltz-ng/client/widgets/editable-dropdown/editable-dropdown.js, waltz-service/src/main/java/com/khartec/waltz/service/assessment_definition/AssessmentDefinitionService.java, waltz-service/src/main/java/com/khartec/waltz/service/assessment_rating/AssessmentRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssessmentDefinitionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssessmentRatingEndpoint.java
=> assessments display panel

waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/ShortestPath.java
=> Db contrib/waltz 3327 shortest path

waltz-ng/client/assessments/components/panel/assessment-rating-panel.html
=> Assessments: description tooltip

waltz-data/src/main/ddl/liquibase/db.changelog-1.12.xml, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroup.java, waltz-ng/client/app-groups/pages/edit/app-group-edit.html, waltz-ng/client/app-groups/pages/edit/app-group-edit.js
=> App Groups: Ability to delete app groups

waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/PersonHarness.java, waltz-ng/client/person/components/person-hierarchy-section/person-hierarchy-section.html, waltz-ng/client/person/components/person-hierarchy-section/person-hierarchy-section.js, waltz-ng/client/person/services/person-store.js, waltz-ng/client/roadmap/components/roadmap-diagram/roadmap-diagram-layout.js, waltz-ng/client/roadmap/components/roadmap-diagram/roadmap-diagram-options.js, waltz-ng/client/roadmap/components/roadmap-diagram/roadmap-diagram-render.js, waltz-ng/client/roadmap/components/roadmap-diagram/roadmap-diagram-utils.js, waltz-ng/client/roadmap/components/roadmap-diagram/roadmap-diagram.html, waltz-ng/client/roadmap/components/roadmap-diagram/roadmap-diagram.js, waltz-service/src/main/java/com/khartec/waltz/service/person/PersonService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PersonEndpoint.java
=> Waltz 3329 emp count

waltz-ng/client/person/components/person-apps-section/person-apps-section.html
=> Db contrib/waltz 3342 zero apps

waltz-ng/client/survey/components/instance-list/survey-instance-list.html, waltz-ng/client/survey/components/instance-list/survey-instance-list.js
=> Db contrib/waltz 3340 categorise surveys

waltz-data/src/main/ddl/liquibase/db.changelog-1.12.xml, waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramDao.java, waltz-model/src/main/java/com/khartec/waltz/model/flow_diagram/FlowDiagram.java, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramService.java
=> Db contrib/waltz 3336 fd soft delete

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-ng/client/app-groups/components/related-app-groups-section/related-app-groups-section.js
=> Db contrib/waltz 3348 related app groups bug

docs/README.md, waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-service/src/main/java/com/khartec/waltz/service/user/UserRoleService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/UserEndpoint.java
=> Db contrib/waltz 3274 change log user role

waltz-ng/client/widgets/editable-dropdown/editable-dropdown.html, waltz-ng/client/widgets/editable-dropdown/editable-dropdown.js, waltz-ng/client/widgets/editable-enum/editable-enum.html, waltz-ng/client/widgets/editable-enum/editable-enum.js
=> Db contrib/waltz 3359 editable dropdown improvements

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/LogicalFlowHarness.java
=> Db contrib/waltz 3362 person logical find by selector slow

waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.js, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.js, waltz-ng/client/widgets/page-header/page-header.js
=> Db contrib/waltz 3372 fd popup off screen

waltz-ng/client/navbar/components/nav-search-overlay.html
=> Db contrib/waltz 3371 search icon display

waltz-common/src/main/java/com/khartec/waltz/common/MapUtilities.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.13.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/PersonHarness.java, waltz-ng/client/person/components/person-hierarchy-section/person-hierarchy-section.html, waltz-ng/client/person/components/person-hierarchy-section/person-hierarchy-section.js, waltz-ng/client/person/components/summary/person-summary.html, waltz-ng/client/person/directives/person-directs-list.html, waltz-ng/client/person/services/person-store.js, waltz-service/src/main/java/com/khartec/waltz/service/person/PersonService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PersonEndpoint.java
=> Db contrib/waltz 3370 emp kind

waltz-data/src/main/ddl/liquibase/db.changelog-1.13.xml, waltz-data/src/main/java/com/khartec/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntityRelationshipHarness.java, waltz-ng/client/measurable-relationship/services/measurable-relationship-store.js, waltz-ng/client/measurable/components/summary/measurable-summary.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_relationship/MeasurableRelationshipService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRelationshipEndpoint.java
- added dedicated endpoint for retrieving entity stats
#3389
=> Measurable Perf

waltz-ng/client/common/d3-context-menu.js, waltz-ng/client/common/d3-context-menu.scss, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/roadmap/components/list/roadmaps-list.html, waltz-ng/client/roadmap/components/list/roadmaps-list.js, waltz-ng/client/roadmap/components/panel/roadmaps-panel.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-grid-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js
=> Roadmap views (WIP)

waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioRatingItemDao.java, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-data-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-node-grid-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-row-utils.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioRatingItemService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
=> Roadmap list/create/edit section

waltz-ng/client/common/components/last-updated/last-updated.js, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/data-types/components/overview/data-type-overview.js, waltz-ng/client/data-types/components/usage-count-tree/data-type-usage-count-tree.js, waltz-ng/client/data-types/components/usage-tree/data-type-usage-tree.js, waltz-ng/client/entity-statistics/components/entity-statistic-tree.js, waltz-ng/client/entity/components/entity-hierarchy-navigator/entity-hierarchy-navigator.js, waltz-ng/client/extensions/components/change-initiative/change-initiative-browser/db-change-initiative-browser.js, waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.js, waltz-ng/client/logical-flow/pages/view/logical-flow-view.js, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js, waltz-ng/client/measurable-category/routes.js, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js, waltz-ng/client/measurable-relationship/components/tree/related-measurables-tree.js, waltz-ng/client/measurable/components/tree/measurable-tree.js, waltz-ng/client/ratings/components/rag-line/rag-line.js, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.js, waltz-ng/client/ratings/index.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/roadmap/services/roadmap-store.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-static-node-utils.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-ng/client/user/services/user-preference-service.js, waltz-ng/client/widgets/loading-notification.js, waltz-ng/webpack.config.js
=> Waltz 3403 roadmap c

waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioRatingItemDao.java, waltz-ng/client/common/d3-utils.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-static-node-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioRatingItemService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
=> Scenario - edit rating / show comment

waltz-data/src/main/java/com/khartec/waltz/data/roadmap/RoadmapDao.java, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-ng/client/roadmap/components/list/roadmaps-list.html, waltz-ng/client/roadmap/components/list/roadmaps-list.js, waltz-ng/client/roadmap/components/panel/roadmaps-panel.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.js, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.html, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html, waltz-ng/client/roadmap/index.js, waltz-ng/client/roadmap/services/roadmap-store.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-ng/client/widgets/editable-field.js, waltz-service/src/main/java/com/khartec/waltz/service/roadmap/RoadmapService.java, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/RoadmapEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
=> Waltz 3415 roadmap rename

waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-model/src/main/java/com/khartec/waltz/model/DateChangeCommand.java, waltz-ng/client/roadmap/components/panel/roadmaps-panel.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.js, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.html, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
- target date can be edited
- WIP
#3404
=> Roadmaps: update scenario details

waltz-data/src/main/ddl/liquibase/db.changelog-1.13.xml, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioAxisItemDao.java, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/ScenarioHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/AxisOrientation.java, waltz-model/src/main/java/com/khartec/waltz/model/scenario/Scenario.java, waltz-model/src/main/java/com/khartec/waltz/model/scenario/ScenarioAxisItem.java, waltz-ng/client/common/components/index.js, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/common/list-utils.js, waltz-ng/client/roadmap/components/list/roadmaps-list.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.js, waltz-ng/client/roadmap/components/roadmap-scenario-axis-config/roadmap-scenario-axis-config.html, waltz-ng/client/roadmap/components/roadmap-scenario-axis-config/roadmap-scenario-axis-config.js, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.html, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/roadmap/index.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-data-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-row-utils.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-ng/client/widgets/no-data.js, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
=> Waltz 3404 scenario edit

waltz-data/src/main/ddl/liquibase/db.changelog-1.13.xml, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioAxisItemDao.java, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioRatingItemDao.java, waltz-ng/client/roadmap/components/list/roadmaps-list.html, waltz-ng/client/roadmap/components/roadmap-scenario-axis-config/roadmap-scenario-axis-config.js
=> Roadmaps: update column names to more accurately reflect problem domain

waltz-data/src/main/ddl/liquibase/db.changelog-1.13.xml, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-model/src/main/java/com/khartec/waltz/model/scenario/Scenario.java, waltz-model/src/main/java/com/khartec/waltz/model/scenario/ScenarioStatus.java, waltz-ng/client/roadmap/components/list/roadmaps-list.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.js, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.html, waltz-ng/client/roadmap/components/roadmap-scenario-config/roadmap-scenario-config.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-ng/client/widgets/editable-enum/editable-enum.js, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
- one of: Target,Interim,Current
#3417
=> Roadmaps: add scenario status

waltz-common/src/main/java/com/khartec/waltz/common/DateTimeUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/roadmap/components/panel/roadmaps-panel.html, waltz-ng/client/roadmap/components/panel/roadmaps-panel.js, waltz-ng/client/roadmap/components/roadmap-add-scenario/roadmap-add-scenario.html, waltz-ng/client/roadmap/components/roadmap-add-scenario/roadmap-add-scenario.js, waltz-ng/client/roadmap/index.js, waltz-ng/client/roadmap/services/roadmap-store.js, waltz-service/src/main/java/com/khartec/waltz/service/roadmap/RoadmapService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/RoadmapEndpoint.java
=> Roadmaps: add scenario

waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-axis-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-dimensions.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-node-grid-utils.js
=> Roadmaps: improve look of empty cols/rows

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioRatingItemDao.java, waltz-ng/client/logical-flow/components/logical-flows-boingy-graph/logical-flows-boingy-graph.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/header/scenario-header.html, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.html, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioRatingItemService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
- bonus: fixing logical flows for scenarios
- updating timestamps on edits
#3434
=> Roadmaps: adding read-only support

waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.html, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js
=> Waltz 3447 roadmap pan & zoom controls

waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/roadmap/components/roadmap-scenario-axis-config/roadmap-scenario-axis-config.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
=> Roadmaps: tree no longer re-expands on selection

waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-ng/client/common/components/index.js, waltz-ng/client/common/components/mini-actions/mini-actions.html, waltz-ng/client/common/components/mini-actions/mini-actions.js, waltz-ng/client/common/dialog-utils.js, waltz-ng/client/scenario/components/list-section/scenario-list-section.html, waltz-ng/client/scenario/components/list-section/scenario-list-section.js, waltz-ng/client/scenario/components/list/scenario-list.html, waltz-ng/client/scenario/components/list/scenario-list.js, waltz-ng/client/scenario/services/scenario-store.js, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
=> Waltz 3436 roadmap workflow

waltz-ng/client/roadmap/pages/view/roadmap-view.html, waltz-ng/client/roadmap/pages/view/roadmap-view.js, waltz-ng/client/scenario/components/header/scenario-header.js, waltz-service/src/main/java/com/khartec/waltz/service/roadmap/RoadmapService.java, waltz-service/src/main/java/com/khartec/waltz/service/roadmap/RoadmapUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioAxisItemService.java, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioRatingItemService.java, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioService.java, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ScenarioEndpoint.java
=> Waltz 3448 roadmap logs

waltz-ng/client/scenario/components/list-section/scenario-list-section.js
- imported `confirmWithUser` to prevent runtime error
#3460
=> Roadmaps: bug

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-ng/client/assessments/components/panel/assessment-rating-panel.html
=> Db contrib/waltz 3462 app rating null exception when app miss

waltz-web/src/main/java/com/khartec/waltz/web/Main.java
=> CORS: cache OPT requests

waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioAxisItemDao.java, waltz-ng/client/roadmap/components/roadmap-references/roadmap-references.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.html, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js
- also clarified search text
- fixed offset in diagram
#3476
=> Roadmap: sorting columns on mssql

waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java
=> Roadmap: fixed day offset problem

waltz-ng/client/roadmap/components/roadmap-references/roadmap-references.html, waltz-ng/client/scenario/components/list/scenario-list.html
=> Roadmap: add release status to table

waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html
- was appearing under some gui elements
#3483
=> Roadmap: fixing z-index of popup

waltz-ng/client/common/services/enums/entity.js, waltz-ng/client/roadmap/components/header/roadmap-header.html, waltz-ng/client/roadmap/components/header/roadmap-header.js, waltz-ng/client/roadmap/pages/view/roadmap-view.js, waltz-ng/client/scenario/components/header/scenario-header.html, waltz-ng/client/scenario/components/header/scenario-header.js
=> Roadmap: add roadmaps and scenarios to history

waltz-ng/client/system/hierarchies-view.html
=> Roadmaps: scenario extract

waltz-data/src/main/java/com/khartec/waltz/data/roadmap/RoadmapDao.java, waltz-data/src/main/java/com/khartec/waltz/data/roadmap/RoadmapSearchDao.java, waltz-model/src/main/java/com/khartec/waltz/model/roadmap/Roadmap.java, waltz-ng/client/common/link-utils.js, waltz-ng/client/navbar/components/nav-search-overlay.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_search/EntitySearchService.java, waltz-service/src/main/java/com/khartec/waltz/service/roadmap/RoadmapService.java, waltz-web/src/main/resources/logback.example.xml
=> Db contrib/waltz 3491 roadmap search

waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagam.scss, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js, waltz-ng/style/_waltz.scss
=> Roadmaps: popup

waltz-ng/client/attestation/components/inline-measurable-rating-panel/inline-measurable-rating-panel.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-data-utils.js
=> Db contrib/waltz 3503 att measurable rating bug

waltz-ng/package-lock.json, waltz-ng/package.json, waltz-ng/webpack.config.js, waltz-ng/webpack.dev.js, waltz-ng/webpack.prod.js
=> Build: optimise prod asset sizes

waltz-ng/package.json
- ensuring webpack dev server uses dev settings (not prod)
#3506
=> Build perf -

docs/faq.md
=> Documentation: add FAQ

waltz-ng/client/app-groups/components/related-app-groups-section/related-app-groups-section.js, waltz-ng/client/applications/components/related-apps-section/related-apps-section.js, waltz-ng/client/common/relationship-utils.js, waltz-ng/client/common/role-utils.js, waltz-ng/client/data-types/components/related-data-types-section/related-data-types-section.js, waltz-ng/client/entity-relationship/services/entity-relationship-store.js, waltz-ng/client/org-units/components/related-org-unit-section/related-org-unit-section.html, waltz-ng/client/org-units/components/related-org-unit-section/related-org-unit-section.js
=> Roadmaps: linking to Org Units

waltz-model/src/main/java/com/khartec/waltz/model/roadmap/Roadmap.java, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/roadmap/components/roadmap-references/roadmap-references.html, waltz-ng/client/roadmap/components/roadmap-references/roadmap-references.js
- fixing typo in directive name
#3511
=> Roadmap references, typo in directive name

waltz-jobs/src/main/java/com/khartec/waltz/jobs/SoftwareCatalogHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/change_initiative/ChangeInitiativeService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_statistic/EntityStatisticService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_workflow/EntityWorkflowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowUploadService.java, waltz-service/src/main/java/com/khartec/waltz/service/software_catalog/SoftwareCatalogService.java, waltz-service/src/main/java/com/khartec/waltz/service/user/UserRoleService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityStatisticEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityWorkflowEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SoftwareCatalogEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/UserEndpoint.java, waltz-web/src/test/java/com/khartec/waltz/web/ArchitectureCompliance.java, waltz-web/src/test/java/com/khartec/waltz/web/BaseArchitectureComplianceCheck.java, waltz-web/src/test/java/com/khartec/waltz/web/DaoArchitectureCompliance.java, waltz-web/src/test/java/com/khartec/waltz/web/EndpointArchitectureCompliance.java, waltz-web/src/test/java/com/khartec/waltz/web/ServicesArchitectureCompliance.java
- also enforcing find* rules against service layer
#3521
=> Quality: enabled no-generic exceptions check

waltz-ng/client/svg-diagram/component/svg-diagram.js, waltz-ng/webpack.config.js
- also split dist files into smaller chunks
#3526
=> Navaid: timing issue prevents links from rendering

waltz-ng/client/ratings/components/rating-scheme-legend/rating-scheme-legend.html, waltz-ng/client/ratings/components/rating-scheme-legend/rating-scheme-legend.js, waltz-ng/client/ratings/index.js, waltz-ng/client/roadmap/components/add-roadmap/add-roadmap.html, waltz-ng/client/roadmap/components/header/roadmap-header.html, waltz-ng/client/roadmap/components/header/roadmap-header.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.html, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js
=> Roadmap: show applied rating scheme

waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-axis-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-data-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-grid-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.html, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js
=> Roadmap: hide columns

waltz-ng/client/roadmap/components/add-roadmap/add-roadmap.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js
=> Roadmap: remember last rating

waltz-model/src/main/java/com/khartec/waltz/model/ReleaseLifecycleStatusChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/StringChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/actor/ActorCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_rating/AssessmentRatingCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/attestation/AttestationRunCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/authoritativesource/AuthoritativeSourceCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/authoritativesource/AuthoritativeSourceUpdateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_named_note/EntityNamedNoteTypeChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_relationship/EntityRelationshipChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/involvement/EntityInvolvementChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/involvement_kind/InvolvementKindCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/MeasurableRatingCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlowSpecDefinitionChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinitionChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinitionFieldChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinitionSampleFileCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/roadmap/RoadmapCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceRecipientCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceRecipientUpdateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceStatusChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunStatusChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyTemplateChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-web/src/test/java/com/khartec/waltz/web/ModelArchitectureCompliance.java
=> Quality: ensure command classes implement 'Command' marker interface

docs/design/taxonomy_management/README.md
- design docs (security)
#3535
=> Taxonomy management:

waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.html
=> Roadmap: bulk picker

docs/design/taxonomy_management/README.md, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeLifecycleStatus.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeType.java
=> Waltz 3545 taxonomy change command

waltz-common/src/main/java/com/khartec/waltz/common/Checks.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeImpact.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangePreview.java, waltz-service/src/main/java/com/khartec/waltz/service/DIConfiguration.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyManagementProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/UpdateMeasurableConcreteFlagProcessor.java
=> Taxonomy Management: implement `update concreteness` command

waltz-common/src/main/java/com/khartec/waltz/common/FunctionUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/user/RoleUtilities.java
=> Taxonomy Management: create new role

waltz-model/src/main/java/com/khartec/waltz/model/user/Role.java, waltz-service/src/main/java/com/khartec/waltz/service/user/RoleUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityNamedNoteEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementEndpoint.java
=> Taxonomy management: add role

docs/design/taxonomy_management/README.md, waltz-data/src/main/ddl/liquibase/db.changelog-1.14.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable_category/MeasurableCategoryDao.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable/Measurable.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_category/MeasurableCategory.java
- add editable column to measurable category
#3561
=> Taxonomy management: add editable flag to measurable category

waltz-ng/client/measurable/components/change-control/measurable-change-control.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-ng/client/measurable/components/tree/measurable-tree.html, waltz-ng/client/measurable/components/tree/measurable-tree.scss
- tidying up
- re-adding bars on measurable tree
#3562
=> Taxonomy Management: operation menus

waltz-data/src/main/ddl/liquibase/db.changelog-1.14.xml, waltz-data/src/main/java/com/khartec/waltz/data/roadmap/RoadmapDao.java, waltz-data/src/main/java/com/khartec/waltz/data/roadmap/RoadmapSearchDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/importers/ScenarioRatingImporter.java, waltz-model/src/main/java/com/khartec/waltz/model/roadmap/Roadmap.java, waltz-ng/client/roadmap/components/header/roadmap-header.html, waltz-ng/client/roadmap/components/header/roadmap-header.js, waltz-ng/client/roadmap/services/roadmap-store.js, waltz-ng/client/scenario/components/header/scenario-header.html, waltz-ng/client/scenario/components/header/scenario-header.js, waltz-ng/client/scenario/components/list-section/scenario-list-section.js, waltz-service/src/main/java/com/khartec/waltz/service/roadmap/RoadmapService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/RoadmapEndpoint.java
=> Db contrib/waltz 3482 roadmap delete

waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js
=> Db contrib/waltz 3577 app rating display on filter bug

waltz-ng/package.json
=> Upgrading mocha to fix growl vulnerability

waltz-ng/package.json
=> Upgrade lodash to latest.

waltz-common/src/main/java/com/khartec/waltz/common/hierarchy/HierarchyUtilities.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/utils/IdUtilities.java, waltz-ng/client/measurable-category/pages/edit/measurable-category-edit.js, waltz-ng/client/scenario/components/header/scenario-header.html, waltz-ng/client/scenario/components/list-section/scenario-list-section.html, waltz-ng/client/scenario/components/list-section/scenario-list-section.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-static-node-utils.js, waltz-ng/client/svg-diagram/component/svg-diagram.js, waltz-ng/client/taxonomy-management/components/pending-taxonomy-changes-list/pending-taxonomy-changes-list.js, waltz-ng/client/taxonomy-management/components/taxonomy-change-command-preview/taxonomy-change-command-preview.js
=> Taxonomy management:  cleanup before starting on this task

waltz-ng/client/measurable/components/change-control/measurable-change-control.html
=> Taxonomy Edit: external id

waltz-data/src/main/ddl/liquibase/db.changelog-1.14.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-ng/client/measurable-category/pages/edit/measurable-category-edit.js, waltz-ng/client/measurable/components/change-control/measurable-change-control.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyManagementUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/AddChildMeasurableCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableConcreteFlagCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableDescriptionCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableNameCommandProcessor.java
=> Waltz 3603 taxonomy management ddl

waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-ng/client/measurable-category/pages/edit/measurable-category-edit.js, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-ng/client/taxonomy-management/components/pending-taxonomy-changes-list/pending-taxonomy-changes-list.html, waltz-ng/client/taxonomy-management/components/taxonomy-change-command-info/taxonomy-change-command-info.html, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyManagementUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/AddChildMeasurableCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableConcreteFlagCommandProcessor.java
=> Taxonomy Edit: add child

waltz-ng/client/measurable/components/change-control/measurable-change-control.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyChangeService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/AddMeasurableCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableConcreteFlagCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableDescriptionCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableExternalIdCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableNameCommandProcessor.java
=> Taxonomy Management: add peer

waltz-data/src/main/java/com/khartec/waltz/data/GenericSelector.java, waltz-data/src/main/java/com/khartec/waltz/data/GenericSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkIdSelectorFactory.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityReferenceUtilities.java, waltz-model/src/main/java/com/khartec/waltz/model/bookmark/Bookmark.java, waltz-ng/client/measurable/components/change-control/measurable-change-control.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-service/src/main/java/com/khartec/waltz/service/bookmark/BookmarkService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/AddMeasurableCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/RemoveMeasurableCommandProcessor.java
=> Taxonomy Management: remove node

waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.html, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js, waltz-ng/client/measurable/components/change-control/measurable-change-control.html, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/AddMeasurableCommandProcessor.java
=> Db contrib/waltz 3616 spindle add ui

waltz-data/src/main/java/com/khartec/waltz/data/client_cache_key/ClientCacheKeyDao.java, waltz-model/src/main/java/com/khartec/waltz/model/client_cache_key/ClientCacheKey.java, waltz-ng/client/client_cache_key/index.js, waltz-ng/client/client_cache_key/services/client-cache-key-store.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/common/services/index.js, waltz-ng/client/common/services/service-broker.js, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js, waltz-ng/client/modules.js, waltz-service/src/main/java/com/khartec/waltz/service/client_cache_key/ClientCacheKeyService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ClientCacheKeyEndpoint.java
=> Caching: allow server to invalidate client cache

waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/taxonomy_management/TaxonomyChangeDao.java, waltz-service/src/main/java/com/khartec/waltz/service/bookmark/BookmarkService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyChangeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/TaxonomyManagementEndpoint.java
=> Taxonomy Edit: persist

waltz-model/src/main/java/com/khartec/waltz/model/exceptions/NotAuthorizedException.java, waltz-ng/client/measurable-category/pages/edit/measurable-category-edit.js, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-ng/client/user/roles.js, waltz-ng/client/user/user-management.js, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyChangeService.java
=> Taxonomy Management: secure endpoint

waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-static-node-utils.js
=> Roadmap: Scenario cell text color white/black

waltz-ng/client/measurable-category/pages/list/measurable-category-list.html, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js
=> Taxonomy Management: edit link

waltz-service/src/main/java/com/khartec/waltz/service/user/UserRoleService.java
=> User Role should happen even if user not associated with Person record

waltz-ng/client/app-groups/pages/edit/app-group-edit.html
=> App group editor tabs incorrectly labelled

waltz-ng/client/data-type-usage/directives/app-data-type-usage-list.html, waltz-ng/client/data-type-usage/directives/app-data-type-usage-list.js
=> Data type usage not showing on app page

waltz-ng/client/data-types/components/usage-count-tree/data-type-usage-count-tree.html, waltz-ng/client/playpen/5/dynamic-nav-aid.html, waltz-ng/client/playpen/5/dynamic-nav-aid.js, waltz-ng/client/playpen/5/index.js, waltz-ng/client/playpen/5/playpen5.html, waltz-ng/client/playpen/5/playpen5.js
-WIP for dynamic nav aid in playpen
#3632
=> DataType: tree on overview page needs to use italics for non-concrete

waltz-model/src/main/java/com/khartec/waltz/model/DescriptionProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityReference.java, waltz-model/src/main/java/com/khartec/waltz/model/orgunit/OrganisationalUnit.java, waltz-model/src/main/java/com/khartec/waltz/model/roadmap/Roadmap.java, waltz-model/src/test/com/khartec/waltz/model/EntityReferenceTests.java
=> WaltzEntity:entityReference.description() should be null safe

waltz-ng/client/common/services/index.js, waltz-ng/client/common/services/prevent-navigation-service.js, waltz-ng/client/modules.js, waltz-ng/client/roadmap/index.js, waltz-ng/client/roadmap/pages/view/roadmap-view.js, waltz-ng/client/roadmap/routes.js, waltz-ng/client/routes.js, waltz-ng/client/scenario/pages/view/scenario-view.js, waltz-ng/client/scenario/routes.js, waltz-ng/package-lock.json, waltz-ng/package.json
=> Upgrade UI-Router to 1.x

waltz-common/src/main/java/com/khartec/waltz/common/IOUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/LoggingUtilities.java
=> Logback fails to initialise when config file provided embedded in jar

waltz-data/src/main/ddl/liquibase/db.changelog-1.15.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/actor/ActorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_alias/EntityAliasDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_tag/EntityTagDao.java, waltz-model/src/main/java/com/khartec/waltz/model/actor/Actor.java
=> Alias/Tags/Actors - add provenance

waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/applications/components/overview/app-overview.js, waltz-ng/client/widgets/keyword-edit.html, waltz-ng/client/widgets/keyword-edit.js
- Also tweaked usability.  They now save/delete automatically
#3671
=> Tags: fixed label

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/clients/c1/sc1/XlsImporter.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/clients/c1/sc1/model/ProjectRow.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/SaveMeasurableRatingCommand.java, waltz-ng/client/common/colors.js, waltz-ng/client/entity-diagrams/components/section/entity-diagrams-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/browser-tree-panel/measurable-ratings-browser-tree-panel.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/services/measurable-rating-store.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.scss, waltz-ng/client/roadmap/components/roadmap-references/roadmap-references.html, waltz-ng/client/widgets/icon.js, waltz-ng/client/widgets/inline-edit-area.html, waltz-ng/client/widgets/no-data.scss, waltz-ng/client/widgets/sub-section.scss, waltz-ng/style/_waltz-tabs.scss, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
#3593 
This also
- changes the styling of sub-sections
- removes planned date from ratings (ui and model - not ddl)
- puts ratings in a sub-section
- also a bit of a change initiative demo code (shouldn't have been part of this PR)
=> Ratings: Remove all ratings from a given category

waltz-ng/client/entity-statistics/components/history-chart/entity-statistic-history-chart.js
- was not redrawing due to a short-circuit in the $onChanges method
- if the highlighted points was changed it only updated that, ignoring the associated points change
#3689
=> EntityStats: fixing history chart

waltz-ng/client/routes.js, waltz-ng/index.ejs, waltz-ng/webpack.dev.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticResourcesEndpoint.java
=> Angular: support for urls in Waltz without using the # anchor

waltz-data/src/main/ddl/liquibase/db.changelog-1.15.xml, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerInformation.java, waltz-ng/client/server-info/index.js, waltz-ng/client/server-info/services/server-info-store.js
=> ServerInformation: add external_id

waltz-ng/client/applications/components/overview/app-overview.html
=> Add entity enum to app overview section

waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-physical-flow-popup.html, waltz-ng/client/physical-flows/components/register/overview/physical-flow-edit-overview.html, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
- also fixed some incorrect `toDisplayName:TransportKind` references
#3681
=> Phys flow removal erroneously dual logging.

waltz-data/src/main/ddl/liquibase/db.changelog-1.15.xml
=> Removing logical_flow:is_removed column

waltz-ng/client/user/roles.js
=> User Management: Survey Admin role repeated twice

waltz-ng/client/data-types/components/usage-count-tree/data-type-usage-count-tree.js
=> Data type tree fails to render

waltz-data/src/main/ddl/liquibase/db.changelog-1.15.xml, waltz-data/src/main/java/com/khartec/waltz/data/taxonomy_management/TaxonomyChangeDao.java, waltz-ng/client/measurable/components/change-control/measurable-change-control.html
=> Taxonomy Management: DDL mistake. Params is Long, not String

waltz-data/src/main/ddl/liquibase/db.changelog-1.15.xml
=> Measurables: add unique composite index on category + external id

waltz-common/src/main/java/com/khartec/waltz/common/EnumUtilities.java, waltz-model/src/main/java/com/khartec/waltz/model/user/Role.java, waltz-ng/client/app-groups/components/related-app-groups-section/related-app-groups-section.js, waltz-ng/client/common/role-utils.js, waltz-ng/client/entity-named-note/components/panel/entity-named-notes-panel.html, waltz-ng/client/entity-named-note/components/section/entity-named-notes-section.js, waltz-ng/client/involvement/components/involved-people-section.html, waltz-ng/client/involvement/components/involved-people-section.js, waltz-ng/client/measurable-category/pages/list/measurable-category-list.html, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js, waltz-ng/client/org-units/components/related-org-unit-section/related-org-unit-section.js, waltz-ng/client/user/directives/has-role-for-entity-kind.js, waltz-service/src/main/java/com/khartec/waltz/service/user/RoleUtilities.java
=> Add involvement to Measurable Category page/s

waltz-common/src/main/java/com/khartec/waltz/common/FunctionUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/taxonomy_management/TaxonomyChangeType.java, waltz-ng/client/measurable-category/pages/list/measurable-category-list.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyManagementUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/AddMeasurableCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/MoveMeasurableCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/RemoveMeasurableCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableConcreteFlagCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableDescriptionCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableNameCommandProcessor.java
=> Allow taxonomy items to be moved

waltz-ng/client/scenario/components/list/scenario-list.html
=> Fixing typo

waltz-ng/client/routes.js
=> Routing: hash removal not working correctly

waltz-ng/package-lock.json, waltz-ng/package.json
=> Upgrade Node Sass to v4.11.0

waltz-ng/client/ratings/rating-utils.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/package-lock.json
=> Roadmap - add app fails to calculate default rating correctly

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/MeasurableRatingHarness.java, waltz-ng/client/common/tally-utils.js, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js, waltz-ng/client/measurable-rating/services/measurable-rating-store.js, waltz-ng/test/common/tally-utils/summing.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Measurable category tallies

waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_rating/SaveAssessmentRatingCommand.java, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.html, waltz-ng/client/assessments/services/assessment-rating-store.js, waltz-service/src/main/java/com/khartec/waltz/service/assessment_rating/AssessmentRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssessmentRatingEndpoint.java
=> Db contrib/waltz 3697 assessment rating audit history generic

waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html
=> Db contrib/waltz 3760 df physical flow link to add

docs/development/jooq.md, waltz-ng/package-lock.json, waltz-schema/pom.xml
=> Upgrading jOOQ

waltz-data/src/main/ddl/liquibase/db.changelog-1.16.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/complexity/ServerComplexityDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/ServerGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerInformation.java, waltz-model/src/main/java/com/khartec/waltz/model/server_usage/ServerUsage.java
=> Server Information: migrate asset_code to Server Usage table

.lgtm.settings.xml, .lgtm.yml, _config.yml, docs/integration/h2/h2.md, waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.10.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.15.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-schema/pom.xml
=> H2 Support

waltz-data/src/main/ddl/liquibase/db.changelog-1.16.xml, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/search/MariaServerInformationSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/search/PostgresServerInformationSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/search/ServerInformationSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/search/SqlServerServerInformationSearch.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/ServerGenerator.java, waltz-ng/client/navbar/components/nav-search-overlay.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_search/EntitySearchService.java, waltz-service/src/main/java/com/khartec/waltz/service/server_information/ServerInformationService.java
=> Server Information: add to overall search

waltz-data/src/main/ddl/liquibase/db.changelog-1.16.xml
=> Remove 'tour' tables

waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/MeasurableRatingExporterHarness.java, waltz-ng/client/measurable-rating/components/browser-tree-panel/measurable-ratings-browser-tree-panel.html, waltz-ng/client/measurable-rating/components/browser-tree-panel/measurable-ratings-browser-tree-panel.js, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.html, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/index.js, waltz-ng/client/widgets/data-extract-link.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/BaseDataExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/MeasurableRatingExtractor.java
=> Export measurable ratings

waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramEntityDao.java, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramEntityService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/RemoveMeasurableCommandProcessor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FlowDiagramEntityEndpoint.java
=> Taxonomy Mgmt - rm:

docs/integration/external-linking/external-linking.md, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-ng/client/applications/routes.js, waltz-ng/client/change-initiative/pages/external-id-view/change-initiative-external-id-view.html, waltz-ng/client/change-initiative/pages/external-id-view/change-initiative-external-id-view.js, waltz-ng/client/change-initiative/routes.js, waltz-ng/client/change-initiative/services/change-initiative-store.js, waltz-ng/client/data-types/routes.js, waltz-service/src/main/java/com/khartec/waltz/service/change_initiative/ChangeInitiativeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeInitiativeEndpoint.java
- cleaned up other usages
- unified naming
- documented
#3815
=> ChangeInitiative: route by ext id

waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/physical-flows/components/participants-section/physical-flow-participants-section.html, waltz-ng/client/physical-flows/components/participants-section/physical-flow-participants-section.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js
- removed dead code
- boosted font size
#3823
=> Minor flow participant improvements

waltz-data/src/main/java/com/khartec/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramEntityDao.java, waltz-ng/package-lock.json, waltz-service/src/main/java/com/khartec/waltz/service/entity_relationship/EntityRelationshipService.java, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramEntityService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/RemoveMeasurableCommandProcessor.java
- checks/removes entity relationships
- removes flow diagrams refs
#3622
=> Remove measurable improvements:

waltz-data/src/main/ddl/liquibase/db.changelog-1.16.xml, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/roadmap/components/add-roadmap/add-roadmap.html, waltz-ng/client/roadmap/components/roadmap-scenario-axis-config/roadmap-scenario-axis-config.js, waltz-ng/client/scenario/components/list/scenario-list.html
- selections not showing immediately
- fixing font sizes
- fixing incorrect enum type in ref data
#3826
=> Roadmap: checkbox selection issue

waltz-service/src/main/java/com/khartec/waltz/service/measurable_relationship/MeasurableRelationshipService.java
=> Improved logging for measurable relationship modifications

waltz-ng/client/assessments/components/editor/assessment-editor.html
=> Db contrib/waltz 3843 assessment rating format readonly text

waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/technology/components/group-technology-summary.js, waltz-ng/client/technology/components/technology-summary-section.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLDatabaseExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLServerExtractor.java
=> Db contrib/waltz 3758 provide export of servers dbs eol ubr v

waltz-common/src/main/java/com/khartec/waltz/common/CollectionUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/FunctionUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_any.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_filter.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_map.java, waltz-data/src/main/java/com/khartec/waltz/data/EntityReferenceNameResolver.java
=> Improving CollectionUtilities testing and docs

waltz-common/src/main/java/com/khartec/waltz/common/ListUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/ListUtilities_compact.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/MoveMeasurableCommandProcessor.java
=> Taxonomy changes will create audit log entries

waltz-service/src/main/java/com/khartec/waltz/service/data_type/DataTypeService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
=> Adding new logical flows will now add the `unknown` decorator (if poss)

waltz-ng/client/common/link-utils.js, waltz-ng/client/entity-statistics/services/entity-statistics-utilities.js
=> Indicators: detail view doesn't work for scenarios

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js, waltz-ng/client/measurable/pages/measurable-view/measurable-view.html, waltz-ng/client/measurable/pages/measurable-view/measurable-view.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyManagementUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/RemoveMeasurableCommandProcessor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Facet: Complete support for Measurable view

waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js
=> Facet: Entity Stats view

waltz-data/src/main/ddl/liquibase/db.changelog-1.16.xml, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_usage/ServerUsageDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ServerHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerInformation.java, waltz-model/src/main/java/com/khartec/waltz/model/server_usage/ServerUsage.java, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/server-info/components/overview/server-overview.html, waltz-ng/client/server-info/components/overview/server-overview.js, waltz-ng/client/server-info/components/server-pies/server-pies.html, waltz-ng/client/server-info/components/server-pies/server-pies.js, waltz-ng/client/server-info/index.js, waltz-ng/client/server-info/pages/view/server-view.js, waltz-ng/client/server-info/services/server-usage-store.js, waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/technology/components/group-technology-summary.js, waltz-ng/client/technology/components/technology-section/technology-section.html, waltz-ng/client/technology/components/technology-section/technology-section.js, waltz-ng/client/technology/components/technology-summary-pies.html, waltz-ng/client/technology/components/technology-summary-pies.js, waltz-ng/client/widgets/basic-info-tile.html, waltz-ng/client/widgets/basic-info-tile.scss, waltz-ng/client/widgets/keyword-list.scss, waltz-ng/client/widgets/pie/pie-table.html, waltz-ng/client/widgets/pie/pie-table.js, waltz-service/src/main/java/com/khartec/waltz/service/server_usage/ServerUsageService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ServerUsageEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLServerExtractor.java
=> Db contrib/waltz 3850 server usage

waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/ServerGenerator.java
=> Fixing server generator

waltz-data/src/main/ddl/liquibase/db.changelog-1.16.xml, waltz-ng/client/scenario/components/list/scenario-list.html
=> Add position to scenarios

waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-ng/client/common/link-utils.js, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.html, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.js, waltz-ng/client/navbar/components/navbar-filters/navbar-filters.html, waltz-ng/client/navbar/components/navbar-filters/navbar-filters.js, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java
-also fixed auth sources
#3875
=> Facet: UI improvements

waltz-ng/client/common/components/grid/grid-with-search.html, waltz-ng/client/common/components/grid/grid-with-search.js, waltz-ng/client/common/components/search-control/search-control.html, waltz-ng/client/common/components/search-control/search-control.js, waltz-ng/client/common/index.js, waltz-ng/client/networking.js, waltz-ng/client/survey/survey-instance-list-user-view.html
=> Db contrib/waltz 3882 survey ux

waltz-ng/client/applications/components/apps-section/apps-section.js, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.js, waltz-ng/client/ratings/components/rag-line/rag-line.js
=> WIP: Facet: Bug fixes

waltz-ng/client/common/link-utils.js, waltz-ng/client/navbar/components/navbar-filters/navbar-filters.js
=> Facet: Bug fixes

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLDatabaseExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLServerExtractor.java
=> Db contrib/waltz 3758 provide export of servers databases

waltz-data/src/main/java/com/khartec/waltz/data/scenario/ScenarioDao.java, waltz-model/src/main/java/com/khartec/waltz/model/scenario/Scenario.java, waltz-ng/client/scenario/components/list/scenario-list.html
=> Scenarios: allow items to be positioned in list

waltz-ng/client/physical-flows/components/overview/physical-flow-overview.html
=> Physical Flows: support entity enums

waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ApplicationIdSelectorHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/IdSelectionOptions.java, waltz-model/src/main/java/com/khartec/waltz/model/application/ApplicationIdSelectionOptions.java, waltz-model/src/test/com/khartec/waltz/model/ApplicationIdSelectionOptionsTests.java
=> AppIdSelectionOptions.mkOpts: infinite loop

waltz-data/src/main/java/com/khartec/waltz/data/roadmap/RoadmapDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/RoadmapHarness.java, waltz-ng/client/org-units/components/related-org-unit-section/related-org-unit-section.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-data-utils.js
=> Db contrib/waltz 3905 roadmap bugs

waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/EntityHierarchyDao.java, waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramEntityDao.java
=> Delete fails when using table alias

waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-data/src/main/java/com/khartec/waltz/data/user/UserRoleDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/BulkRoleAssign.java, waltz-jobs/src/main/resources/bulk-role-assign-example.txt, waltz-service/src/main/java/com/khartec/waltz/service/person/PersonService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-service/src/main/java/com/khartec/waltz/service/user/UserRoleService.java, waltz-service/src/main/java/com/khartec/waltz/service/user/UserService.java, waltz-service/src/main/java/com/khartec/waltz/service/user_contribution/UserContributionService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/UserEndpoint.java
=> Db contrib/waltz 3914 perm example

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/ServerGenerator.java, waltz-ng/client/common/entity-utils.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/facet/facet-utils.js, waltz-ng/client/facet/index.js, waltz-ng/client/facet/services/facet-store.js, waltz-ng/client/modules.js, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.html, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.js, waltz-ng/client/navbar/components/navbar-filters/navbar-filters.js, waltz-ng/client/person/components/summary/person-summary.js, waltz-ng/client/person/pages/view/person-view.js, waltz-ng/client/person/routes.js, waltz-service/src/main/java/com/khartec/waltz/service/facet/FacetService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FacetEndpoint.java
=> Facets: Should facet counts and hide those than have no count

waltz-ng/client/measurable/components/summary/measurable-summary.js, waltz-ng/client/measurable/pages/measurable-view/measurable-view.html, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.js, waltz-ng/client/navbar/components/navbar-filters/navbar-filters.js
=> Facets: Measurable summary does not respond to facet changes

waltz-ng/client/roadmap/components/roadmap-references/roadmap-references.html
=> Fixing Typo on Roadmaps section

waltz-data/src/main/ddl/liquibase/db.changelog-1.17.xml, waltz-data/src/main/java/com/khartec/waltz/data/allocation_scheme/AllocationSchemeDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/AllocationSchemeHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/allocation_scheme/AllocationScheme.java, waltz-service/src/main/java/com/khartec/waltz/service/allocation_schemes/AllocationSchemesService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AllocationSchemeEndpoint.java
=> Allocation Scheme: DDL, DAO, Service

waltz-ng/client/allocation-scheme/index.js, waltz-ng/client/allocation-scheme/services/allocation-scheme-store.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/modules.js
=> Allocation Scheme: ng-module and store

waltz-data/src/main/ddl/liquibase/db.changelog-1.17.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/com/khartec/waltz/data/allocation/AllocationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/allocation/Allocation.java, waltz-model/src/main/java/com/khartec/waltz/model/allocation_scheme/AllocationScheme.java, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AllocationEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticResourcesEndpoint.java
=> Allocation: DAO, service, model and endpoint

waltz-ng/client/allocation/index.js, waltz-ng/client/allocation/services/allocation-store.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/modules.js, waltz-ng/client/playpen/3/playpen3.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticResourcesEndpoint.java
=> Allocation: js module and store

waltz-data/src/main/java/com/khartec/waltz/data/allocation/AllocationDao.java, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.html, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.js, waltz-ng/client/allocation/index.js, waltz-ng/client/allocation/services/allocation-store.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AllocationEndpoint.java
=> Allocation: move to fixed implemented

docs/design/future_flows/README.md
=> WIP: Future flows docs

.gitignore, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.html, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.js, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.scss, waltz-ng/style/_waltz.scss
=> Allocation: UI enhancements

waltz-ng/client/allocation/allocation-utilities.js, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.js, waltz-ng/client/playpen/3/playpen3.js, waltz-ng/package-lock.json, waltz-ng/test/allocation/allocation-utilities-test.js
=> Allocation: to-fixed / to-float method and tests

waltz-data/src/main/java/com/khartec/waltz/data/allocation/AllocationDao.java, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.js, waltz-ng/client/allocation/services/allocation-store.js, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationService.java, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationUtilities.java, waltz-service/src/test/java/com/khartec/waltz/service/allocation/AllocationUtilitiesTest.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AllocationEndpoint.java
=> Allocation: save allocs to server

waltz-ng/client/allocation/allocation-utilities.js, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.html, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.js, waltz-ng/client/allocation/components/entity-panel/allocation-entity-panel.scss
=> Allocation: ui bug fixes

waltz-common/src/main/java/com/khartec/waltz/common/CollectionUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationUtilities.java, waltz-service/src/test/java/com/khartec/waltz/service/allocation/AllocationUtilitiesTest.java
=> Allocation: allocation rounding and tests

waltz-ng/client/applications/application-utils.js, waltz-ng/client/applications/components/app-summary.js, waltz-ng/client/applications/components/app-table.js, waltz-ng/client/applications/components/related-apps-section/related-apps-section.js, waltz-ng/client/common/services/BaseLookupService.js
=> ApplicationKind: Soft code override support

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticResourcesEndpoint.java
-reverted to version prior to 1st Apr 2019
#3985
=> Static Resource: Index.html is not found on deployed build

waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type/search/DataTypeSearchDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/EndUserAppGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/EntityStatisticGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/FlowSummaryWithTypesAndPhysicalsExport.java, waltz-model/src/main/java/com/khartec/waltz/model/utils/IdUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/application/ApplicationService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorRatingsCalculator.java, waltz-service/src/main/java/com/khartec/waltz/service/data_type/DataTypeService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowUploadService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataTypesEndpoint.java
=> Db contrib/waltz 3989 feed export

waltz-data/src/main/java/com/khartec/waltz/data/complexity/ServerComplexityDao.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticResourcesEndpoint.java
=> Db contrib/waltz 3984 server complexity blank

docs/features/assessments/README.md, waltz-common/src/main/java/com/khartec/waltz/common/ColorUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/ListUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/RandomUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/AppGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/AssessmentGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/AssetCostGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/LoadAll.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/SampleDataGenerator.java, waltz-ng/client/assessments/components/editor/assessment-editor.html, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssessmentRatingEndpoint.java
=> Waltz 3981 ro assessments

waltz-common/src/main/java/com/khartec/waltz/common/Checks.java, waltz-common/src/test/java/com/khartec/waltz/common/Checks_checkAll.java, waltz-data/src/main/java/com/khartec/waltz/data/allocation/AllocationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/AllocationSchemeHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationUtilities.java, waltz-service/src/test/java/com/khartec/waltz/service/TestingUtilities.java, waltz-service/src/test/java/com/khartec/waltz/service/allocation/AllocationUtilitiesTest.java
- Rebalance methods + rounding
- Find allocations to remove/measurable ratings to add (DAO)
- Tests
#3966
=> Allocation: bulk verify allocations and measurable ratings in sync

waltz-data/src/main/ddl/liquibase/db.changelog-1.17.xml
=> Future Flows: Database tables

waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.scss, waltz-ng/style/_variables.scss
=> Allocation: percentages coloured

waltz-data/src/main/java/com/khartec/waltz/data/allocation/AllocationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/AllocationSchemeHarness.java, waltz-ng/client/allocation/services/allocation-store.js, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AllocationEndpoint.java
=> Allocation show schemes in measurable-ratings-panel

waltz-data/src/main/java/com/khartec/waltz/data/attribute_change/AttributeChangeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_set/ChangeSetDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitDao.java, waltz-model/src/main/java/com/khartec/waltz/model/attribute_change/AttributeChange.java, waltz-model/src/main/java/com/khartec/waltz/model/change_set/ChangeSet.java, waltz-model/src/main/java/com/khartec/waltz/model/change_unit/ChangeAction.java, waltz-model/src/main/java/com/khartec/waltz/model/change_unit/ChangeUnit.java, waltz-model/src/main/java/com/khartec/waltz/model/change_unit/ExecutionStatus.java, waltz-ng/client/attribute-change/index.js, waltz-ng/client/attribute-change/services/attribute-change-store.js, waltz-ng/client/attribute-change/services/index.js, waltz-ng/client/change-set/index.js, waltz-ng/client/change-set/services/change-set-store.js, waltz-ng/client/change-set/services/index.js, waltz-ng/client/change-unit/index.js, waltz-ng/client/change-unit/services/change-unit-store.js, waltz-ng/client/change-unit/services/index.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/modules.js, waltz-service/src/main/java/com/khartec/waltz/service/attribute_change/AttributeChangeService.java, waltz-service/src/main/java/com/khartec/waltz/service/change_set/ChangeSetService.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttributeChangeEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeSetEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeUnitEndpoint.java
=> Future Flows: Model, DAO, Service and Endpoint implementations

waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.js, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.scss, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js
=> Allocation refresh ratings

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.js, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/measurable-rating/index.js, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.html, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.scss, waltz-ng/style/_waltz-visibility.scss
=> Waltz 4014 alloc warn

waltz-common/src/main/java/com/khartec/waltz/common/Aliases.java, waltz-common/src/main/java/com/khartec/waltz/common/ArrayUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/CollectionUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_any.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_filter.java, waltz-common/src/test/java/com/khartec/waltz/common/CollectionUtilities_map.java, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.js, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AllocationEndpoint.java
=> Allocations: secure endpoint

waltz-common/src/main/java/com/khartec/waltz/common/ListUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/InlineSelectFieldFactory.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java, waltz-ng/client/change-log/components/change-log-table.js, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationService.java, waltz-service/src/main/java/com/khartec/waltz/service/allocation/AllocationUtilities.java
=> Allocations: write to changelog

waltz-common/src/main/java/com/khartec/waltz/common/OptionalUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/XmlUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/OptionalUtilities_ofNullableOptional.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/EndUserAppGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/InvolvementGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/LoadAll.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/InvolvementHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/DiagramToDotExport.java, waltz-model/src/main/java/com/khartec/waltz/model/OrganisationalUnitIdProvider.java, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-service/src/main/java/com/khartec/waltz/service/assessment_rating/AssessmentRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/email/EmailService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/processors/UpdateMeasurableConcreteFlagCommandProcessor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppViewEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/BaseDataExtractor.java
=> Allocation: decorate rating tree with allocation indicators

waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.js
Takes the allocated percentage of an item and splits it
across other (allocated) items
#3967
=> Allocations: zero and allocate operation

waltz-ng/client/change-unit/components/attribute-change/attribute-change-panel.html, waltz-ng/client/change-unit/components/attribute-change/attribute-change-panel.js, waltz-ng/client/change-unit/components/data-type-change-panel/data-type-change-panel.html, waltz-ng/client/change-unit/components/data-type-change-panel/data-type-change-panel.js, waltz-ng/client/change-unit/components/data-type-change-panel/data-type-change-panel.scss, waltz-ng/client/change-unit/components/section/change-unit-section.html, waltz-ng/client/change-unit/components/section/change-unit-section.js, waltz-ng/style/_waltz.scss
=> future flows: show modification

waltz-data/src/main/ddl/liquibase/db.changelog-1.17.xml, waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlow.java, waltz-ng/client/change-unit/components/section/change-unit-section.html, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.html, waltz-ng/style/_waltz-draft.scss, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/AttributeChangeCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitService.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/processors/ActivateCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/processors/DataTypeChangeCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/processors/ModifyCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/processors/RetireCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
=> WIP: future flow completion

waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/RoadmapGenerator.java, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-data-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram-node-grid-utils.js, waltz-ng/client/scenario/components/scenario-diagram/scenario-diagram.js
- fix: roadmap generator transposing rows and columns
#4039
=> Roadmaps: persist col widths to localstorage

waltz-ng/client/entity/services/entity-search-store.js
- fix is to `urlEncode` the query component
#4047
=> Search: cannot search for names containing slashes

waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html
=> Waltz 3978 alloc help

waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AllocationEndpoint.java
=> Allocations: change required role to `RATING_EDITOR`

waltz-ng/client/applications/application-utils.js, waltz-ng/client/common/services/enums/application-kind.js, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.html, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.js
- bonus: reworked the ui a bit to be more space efficient
- bonus: added tooltips
#3920
=> Facets: allow selection of a single kind

waltz-common/src/main/java/com/khartec/waltz/common/SetUtilities.java, waltz-ng/client/change-set/components/overview/change-set-overview.html, waltz-ng/client/change-unit/components/section/change-unit-section.js, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/AttributeChangeCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/processors/DataTypeChangeCommandProcessor.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/processors/ModifyCommandProcessor.java
- include data type modification
#4030
=> Future Flows: Apply changes on completion

waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/BookmarkGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/LoadAll.java, waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.scss, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.html, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.scss, waltz-ng/style/_waltz.scss
=> UI Enhancements: rating indicator and bookmark search

waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/common/components/entity-link/entity-icon-label.js
=> EntityIconLabel: Lazy load enhanced popover data

waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/common/components/entity-link/entity-icon-label.html
=> Assessment ratings: format markdown in popovers

waltz-ng/client/change-set/components/section/change-set-section.html
=> ChangeSets: showing table when there is no data

waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/widgets/inline-edit-area.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AllocationsExtractor.java
-consistency in naming for 'commments'
-added rating description to allocations export
-small formatting changes
#4074
#4072
=> App Ratings Section: popovers to support markdown

docs/development/database/dump_and_restore.md
=> Documentation: backup and restore commands

waltz-ng/client/complexity/components/section/complexity-section.html, waltz-ng/client/complexity/components/section/complexity-section.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ComplexityExtractor.java
- bonus: fixed interaction with filter changes
#4088
=> Complexity: include asset code in view and export

waltz-data/src/main/java/com/khartec/waltz/data/orgunit/search/PostgresOrganisationalUnitSearch.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ChangeInitiativeHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/DIConfiguration.java, waltz-web/src/main/resources/waltz.sample.properties
- jmx namespaces were clashing preventing spring bootup
- fix allows an (optional) qualifier when generating the namespace
- OU search under postgres was failing if description col had null
- fix by coalescing description to prevent nulls
#4101
#4100
=> Webapps - allow multi wars on single app server, fix OU search on pg

waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitDao.java, waltz-model/src/main/java/com/khartec/waltz/model/change_unit/ChangeUnit.java, waltz-ng/client/change-unit/components/section/change-unit-section.html
=> Future Flows: Support assessments on Change Units

waltz-ng/client/physical-specifications/physical-specification-view.html
=> Physical Spec: Ability to add assessments

waltz-data/src/main/java/com/khartec/waltz/data/GenericSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitIdSelectorFactory.java, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/change-unit/services/change-unit-store.js, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.scss, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-utilities.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js, waltz-ng/client/logical-flow/pages/view/logical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeUnitEndpoint.java
=> Future Flows: view pending / retired flows in source / target panel

pom.xml, waltz-ng/client/common/file-utils.js, waltz-ng/client/logical-flow/components/logical-flows-tabgroup-section/logical-flows-tabgroup-section.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.html, waltz-ng/client/org-units/pages/list-view/list-view.html, waltz-ng/client/widgets/data-extract-link.html, waltz-ng/client/widgets/data-extract-link.js, waltz-service/src/main/java/com/khartec/waltz/service/DIBaseConfiguration.java, waltz-service/src/main/java/com/khartec/waltz/service/DIConfiguration.java, waltz-service/src/main/java/com/khartec/waltz/service/SlowQueryListener.java, waltz-web/pom.xml, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AllocationsExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AttestationExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/BaseDataExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ComplexityExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ExtractFormat.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/LogicalFlowExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/MeasurableCategoryExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/MeasurableRatingExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/OrgUnitExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ScenarioExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyInstancesDatabaseExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLDatabaseExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLServerExtractor.java
=> Db contrib/waltz 4109 extract

docs/design/future_flows/data_feed_requirements.md
=> Future Flow: Document data feed requirements for Future Flows

waltz-ng/client/actor/pages/actor-view/actor-view.html, waltz-ng/client/actor/pages/actor-view/actor-view.js, waltz-ng/client/app-groups/pages/view/app-group-view.html, waltz-ng/client/app-groups/pages/view/app-group-view.js, waltz-ng/client/applications/pages/view/app-view.html, waltz-ng/client/applications/pages/view/app-view.js, waltz-ng/client/applications/routes.js, waltz-ng/client/change-initiative/pages/view/change-initiative-view.html, waltz-ng/client/change-initiative/pages/view/change-initiative-view.js, waltz-ng/client/data-types/pages/view/data-type-view.html, waltz-ng/client/data-types/pages/view/data-type-view.js, waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.html, waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.js, waltz-ng/client/dynamic-section/components/dynamic-sections-view/dynamic-sections-view.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/dynamic-section/services/dynamic-section-manager.js, waltz-ng/client/measurable/pages/measurable-view/measurable-view.html, waltz-ng/client/measurable/pages/measurable-view/measurable-view.js, waltz-ng/client/org-units/pages/unit-view/unit-view.html, waltz-ng/client/org-units/pages/unit-view/unit-view.js, waltz-ng/client/org-units/routes.js, waltz-ng/client/person/pages/view/person-view.html, waltz-ng/client/person/pages/view/person-view.js, waltz-ng/client/scenario/pages/view/scenario-view.html, waltz-ng/client/scenario/pages/view/scenario-view.js
=> DynamicSectionManager: simplified service

waltz-ng/package-lock.json, waltz-ng/package.json
=> Waltz 4143 dependencies

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java, waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.html, waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.js
=> EntityStats: support decimal point values in roll-ups
