waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AllocationsExtractor.java
=> Allocations: filename of export + postgres bug

waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js
=> Roadmap diagram, incorrect rendering when col count exceeds 8

waltz-data/src/main/java/com/khartec/waltz/data/change_set/ChangeSetDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_set/ChangeSetIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitIdSelectorFactory.java, waltz-ng/client/change-set/components/panel/change-set-panel.html, waltz-ng/client/change-set/components/panel/change-set-panel.js, waltz-ng/client/change-set/components/section/change-set-section.html, waltz-ng/client/change-set/index.js, waltz-ng/client/change-set/services/change-set-store.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/person/components/person-apps-section/person-apps-section.js, waltz-ng/client/person/components/person-change-set-section/person-change-set-section.html, waltz-ng/client/person/components/person-change-set-section/person-change-set-section.js, waltz-ng/client/person/index.js, waltz-service/src/main/java/com/khartec/waltz/service/change_set/ChangeSetService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeSetEndpoint.java
=> Future Flows: show change set section on other pages

waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/ChangeSetGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/ChangeUnitGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/LoadAll.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/PhysicalFlowGenerator.java
=> ChangeSets: write sample data generator

waltz-data/src/main/ddl/liquibase/db.changelog-1.18.xml, waltz-data/src/main/java/com/khartec/waltz/data/actor/ActorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_named_note/EntityNamedNoteDao.java, waltz-data/src/main/java/com/khartec/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/AllocationHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/CreatedUserTimestampProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/UserTimestamp.java, waltz-model/src/main/java/com/khartec/waltz/model/command/EntityChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_flow/LogicalFlow.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/MeasurableRatingCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlow.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification/PhysicalSpecification.java, waltz-service/src/main/java/com/khartec/waltz/service/actor/ActorService.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_named_note/EntityNamedNoteService.java, waltz-service/src/main/java/com/khartec/waltz/service/involvement_kind/InvolvementKindService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowUploadService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssessmentRatingEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Physical Flow/Spec/Logical Flow: add `createdBy/At`

waltz-ng/client/common/services/service-broker.js, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.js, waltz-ng/client/entity-statistics/utilities.js, waltz-ng/client/navbar/components/nav-filters-overlay/nav-filters-overlay.js, waltz-ng/client/routes.js
-removed the updateURLWithoutReload method
#4152
=> Facets: error on entity stats view

waltz-data/src/main/ddl/liquibase/db.changelog-1.18.xml, waltz-jobs/src/main/java/com/khartec/waltz/jobs/clients/c1/sc1/XlsImporter.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/OrgUnitGenerator.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/OrgUnitExtractor.java
=> OrgUnit table, add provenance, created_by, updated_by

waltz-ng/client/attestation/attestation-run-view.js, waltz-ng/client/common/colors.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-utilities.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js
=> Source and Target graph, selecting source or target node filters flows

waltz-ng/client/assessments/components/summary-pies/assessment-rating-summary-pies.js, waltz-ng/client/common/checks.js, waltz-ng/client/common/d3-utils.js, waltz-ng/client/entity/components/entity-link-list/entity-link-list.html, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/logical-flow/components/logical-flows-data-type-summary-pane/logical-flows-data-type-summary-pane.js, waltz-ng/client/org-units/components/tree/org-unit-tree.html, waltz-ng/client/widgets/pie/pie-segment-table.html, waltz-ng/client/widgets/pie/pie-segment-table.js, waltz-ng/client/widgets/pie/pie-table.html, waltz-ng/client/widgets/pie/pie-table.js, waltz-ng/client/widgets/pie/pie-utils.js
=> Db contrib/pie bugs 4187

waltz-ng/client/change-initiative/pages/view/change-initiative-view.html, waltz-ng/client/change-initiative/pages/view/change-initiative-view.js
=> Add owning org unit to CI

waltz-ng/client/widgets/pie/pie-table.js
=> Pie cancel button fix

waltz-ng/client/applications/components/app-summary.html, waltz-ng/client/applications/components/apps-by-investment-pie.html, waltz-ng/client/applications/components/apps-by-lifecycle-phase-pie.html, waltz-ng/client/assessments/components/summary-pies/assessment-rating-summary-pies.html, waltz-ng/client/databases/components/database-pies.html, waltz-ng/client/logical-flow/components/logical-flows-data-type-summary-pane/logical-flows-data-type-summary-pane.html, waltz-ng/client/server-info/components/server-pies/server-pies.html, waltz-ng/client/software-catalog/components/simple-software-usage-pies.html, waltz-ng/client/software-catalog/directives/software-catalog-section.html, waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/widgets/pie/pie-table.html, waltz-ng/client/widgets/pie/pie-table.js
- show nothing if no assessment ratings
- rename title to name to fix hover-overs
#4189
#4190
#4193
=> Pie cancel button fix 2

waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/importers/licence/finos/FinosLicenceComplianceImporter.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/importers/licence/spdx/SpdxLicenceImporter.java
-importer fixes for Windows
#4174
=> Support for licence as an entity in Waltz

waltz-ng/client/measurable-category/pages/edit/measurable-category-edit.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-ng/client/measurable/measurable-change-utils.js
=> Db contrib/waltz 3613 taxonomy management prevent duplicates

waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/EntityHierarchyDao.java, waltz-service/src/main/java/com/khartec/waltz/service/person_hierarchy/PersonHierarchyService.java
=> Hierarchy rebuilds operate within tx

waltz-data/src/main/ddl/liquibase/db.changelog-1.18.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml
#4210
Spoiler: I went with `VARCHAR(500)`
=> UserAgentLog: bug - agent string too short

waltz-web/README.md
=> Db contrib/export for attestation runs broken 4207

waltz-common/src/main/java/com/khartec/waltz/common/MapUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/AssessmentGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/LoadAll.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/importers/ScenarioRatingImporter.java, waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.js, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js
=> Collapse down 'Not Provided' into a shortened list

waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js
=> Source and Target graph, filtering by entity enhancements

waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java
=> Auth Source fails on Person page

waltz-data/src/main/ddl/liquibase/db.changelog-1.18.xml
=> Create table: app group org unit entry

waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java
=> Db contrib/waltz 4225 search bar disappears on text selection

waltz-data/src/main/ddl/liquibase/db.changelog-1.18.xml
=> Deutschebank db contrib/waltz 4211 survey response text increase length

waltz-data/src/main/ddl/liquibase/db.changelog-1.18.xml, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java
=> Db contrib/waltz 4211 survey response text increase length

docs/features/configuration/settings.md, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ApplicationIdSelectorHarness.java, waltz-ng/client/org-units/components/tree/org-unit-tree.html
=> AppGroup: app id selector factory expands app-group-ou-entries

waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java
=> Db contrib/waltz 4236 surveys lifecycle bugs

waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/PhysicalFlowExtractor.java
=> Db contrib/waltz 4226 physical flows export to db extractor

waltz-ng/client/user/components/user-pick-list/user-pick-list.html, waltz-ng/client/user/components/user-pick-list/user-pick-list.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java
=> Survey audit: log participant changes

waltz-ng/client/measurable/measurable-change-utils.js
=> Taxonomy Mgmt: allow duplicate add_peer/add_child cmds

waltz-common/src/main/java/com/khartec/waltz/common/DigestUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SharedPreferenceEndpoint.java
=> Db contrib/waltz 4247 base64 utils

pom.xml
=> Db contrib/waltz 4243 dep vers

waltz-ng/client/applications/directives/app-selector.html, waltz-ng/client/applications/formly/fields.js, waltz-ng/client/applications/pages/registration/app-registration.html, waltz-ng/client/bookmarks/components/bookmarks-edit-panel/bookmarks-edit-panel.html, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html, waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.html, waltz-ng/client/bookmarks/directives/bookmark-form.html, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.html, waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.html, waltz-ng/client/logical-flow/components/logical-flow-edit-panel/logical-flow-edit-panel.html, waltz-ng/client/widgets/no-data.html, waltz-ng/package-lock.json
- supporting the exploratory work with cypress.io
- poc work, no where near completed
#4265
=> Testing: adding `data-ux` attr to elems for ease of selection

waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/importers/AppGroupFromOrgUnitImporter.java
=> Db contrib/waltz 4263 populate app group from ou entry table

waltz-ng/client/common/index.js
=> Grid: fixing broken search

waltz-ng/client/common/filters/display-name-filter.js
=> Db contrib/waltz 4278 cost kind display value

docs/features/configuration/settings.md, docs/integration/external-authentication/external-authentication.md, waltz-common/src/main/java/com/khartec/waltz/common/IOUtilities.java, waltz-model/src/main/java/com/khartec/waltz/model/settings/NamedSettings.java, waltz-model/src/main/java/com/khartec/waltz/model/user/AuthenticationResponse.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/auth/AuthenticationEndpoint.java
=> Authentication: support external authentication

waltz-ng/client/common/filters/display-name-filter.js, waltz-ng/client/involvement/components/sub-section/key-people-sub-section.html, waltz-ng/client/survey/survey-run-create.js
=> Db contrib/waltz 4255 key people hover over

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/AbstractIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/licence/LicenceIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java
=> Reverting Maria Union fix

waltz-ng/client/common/list-utils.js, waltz-ng/client/entity-statistics/components/related-entity-statistics-summaries.html, waltz-ng/client/entity-statistics/components/related-entity-statistics-summaries.js, waltz-ng/test/common/list-utils-test.js
=> NWM-Contrib: Entity Stats: related indicators layout issue

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/LogicalFlowExtractor.java
=> Db contrib/waltz 4288 logical flow exporter

waltz-ng/client/licence/components/overview/licence-overview.html, waltz-ng/client/licence/components/overview/licence-overview.js, waltz-ng/client/licence/pages/list/licence-list.html, waltz-ng/client/licence/pages/list/licence-list.js, waltz-ng/client/licence/pages/view/licence-view.js
=> Licence improvements

waltz-ng/client/technology/components/group-technology-summary.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/MeasurableRatingExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLDatabaseExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLServerExtractor.java
=> Db contrib/waltz 4288 extractors failing

waltz-common/src/main/java/com/khartec/waltz/common/ListUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/WaltzUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/DemoSettingsGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/LoadAll.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/stress/LogicalFlowStressGenerator.java, waltz-ng/client/applications/directives/basic-app-selector.html, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.html, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/logical-flow/components/edit/logical-flow-type-editor.html
=> integration testing - ux improvements

waltz-data/src/main/ddl/liquibase/db.changelog-1.19.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/assessment_definition/AssessmentDefinitionDao.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_definition/AssessmentDefinition.java, waltz-model/src/main/java/com/khartec/waltz/model/assessment_definition/AssessmentVisibility.java, waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.js
=> Assessment Visibility

waltz-data/src/main/ddl/liquibase/db.changelog-1.19.xml
- used to store relationship between waltz entities with more
than one external systems
#4321
=> Create additional external ids table

waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/measurable-rating/components/browser-tree-panel/measurable-ratings-browser-tree-panel.js, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.html, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.js, waltz-ng/client/ratings/components/rating-scheme-legend/rating-scheme-legend.html, waltz-ng/client/system/rating-schemes-view.html
=> Measurable Ratings: display rating_scheme_item descriptions

waltz-data/src/main/ddl/liquibase/db.changelog-1.19.xml, waltz-data/src/main/java/com/khartec/waltz/data/assessment_definition/AssessmentDefinitionDao.java
=> Assessment Visibility rename

waltz-ng/client/attestation/components/section/attestation-section.html, waltz-ng/client/attestation/components/section/attestation-section.js
=> Db contrib/waltz 4295 attestations if none

waltz-common/src/main/java/com/khartec/waltz/common/SetUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/licence/LicenceIdSelectorFactory.java, waltz-ng/client/applications/pages/view/app-view.js, waltz-ng/client/data-flow/components/application-flow-summary-pane/application-flow-summary-pane.html, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/flow-diagram/flow-diagram-view.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/org-units/pages/list-view/list-view.html
Moved flow diagram page to dynamic sections,
- fixed flow diagram licence selector bug
- partial fix for app selector bug (#4330)
- fixed descriptive text on org unit list page
- removed redundant (non-vararg) `SetUtilities:minus`
- fixed layout for flow summary info view when client has
low horizontal resolution
#4328
#4330 (partial)
#4249
#4063
=> Numerous small change fixes

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-ng/client/common/components/grid/grid.scss
=> Db contrib/waltz 4345 cost tab alignment

waltz-data/src/main/ddl/liquibase/db.changelog-1.20.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> Software Usage: remove default value constraint on external_id

waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js
=> Db contrib/waltz 4362 search bar navigate to single result

waltz-ng/client/common/components/entity-link/entity-link.html, waltz-ng/client/person/components/summary/person-summary.js
=> Person view: server error when org_unit_id is null

waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Flow Diagram: application selector should 'union all' the flow endpoints

waltz-ng/client/dynamic-section/services/dynamic-section-manager.js
=> Log dynamic section clicks in access log

waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/style/_waltz.scss
=> Show rating scheme item description on assessment rating tooltip

waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java
=> Data Type usage does not update after updating logical flow decorator

docs/development/database/schema.md
=> Db contrib/waltz 4260 software catalogue service dsl ref to dao

waltz-data/src/main/java/com/khartec/waltz/data/change_unit/ChangeUnitIdSelectorFactory.java
=> Change Unit Selector error on Actor page

waltz-ng/client/external-identifier/components/editor/external-identifier-editor-table.js, waltz-ng/client/external-identifier/services/external-identifier-store.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ExternalIdentifierEndpoint.java
=> Db contrib/waltz 4394 ext id fix

waltz-ng/client/profile/view.html
=> Db contrib/waltz 4409 person profile page email link

docs/design/physical_flow_ratings/README.md, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java
=> Db contrib/waltz 4415 related app groups include user apps

docs/design/physical_flow_ratings/README.md, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
=> Db contrib/waltz 4399 flow deduplication copy ext id from flown spec

docs/design/physical_flow_ratings/README.md
=> Db contrib/waltz 4384 waltz search phy spec on ext

docs/design/physical_flow_ratings/README.md
=> Db contrib/waltz 4414 freshness indicator on logical flow diagram

docs/design/physical_flow_ratings/README.md, waltz-common/src/main/java/com/khartec/waltz/common/SetUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/DataTypeUsageStatsHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/FlowDirection.java, waltz-model/src/main/java/com/khartec/waltz/model/data_flow_decorator/DataTypeDirectionKey.java, waltz-model/src/main/java/com/khartec/waltz/model/data_flow_decorator/LogicalFlowDecoratorStat.java, waltz-ng/client/logical-flow-decorator/services/logical-flow-decorator-store.js, waltz-ng/client/logical-flow/components/logical-flows-data-type-summary-pane/logical-flows-data-type-summary-pane.html, waltz-ng/client/logical-flow/components/logical-flows-data-type-summary-pane/logical-flows-data-type-summary-pane.js, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.js, waltz-ng/client/logical-flow/services/logical-flow-utility.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowDecoratorEndpoint.java
=> Db contrib/waltz 4356 logical flow summary tab hierarchy table

waltz-ng/client/common/list-utils.js, waltz-ng/client/entity-enum/components/entity-enum/entity-enum.js
=> Waltz 4418 enum ordering

waltz-data/src/main/ddl/liquibase/db.changelog-1.19.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> Waltz 3685 rating fks

waltz-data/src/main/java/com/khartec/waltz/data/external_identifier/ExternalIdentifierDao.java, waltz-service/src/main/java/com/khartec/waltz/service/external_identifier/ExternalIdentifierService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
=> Db contrib/waltz 4433 remove ext identifiers on phys flow delete

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestion.java, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-template-create.js, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-edit.js, waltz-ng/client/survey/survey-template-view.html
=> Waltz 4442 question ext ids

waltz-ng/client/common/link-utils.js
=> Db contrib/waltz 4450 waltz search server results takes to software

waltz-ng/client/data-types/components/overview/data-type-overview.html, waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> Db contrib/waltz 4452 add application detail to data viewpoint

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-ng/client/common/components/entity-link/entity-icon-label.js, waltz-ng/client/common/components/grid/grid-with-search.html, waltz-ng/client/common/components/grid/grid-with-search.js, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js
=> Db contrib/waltz 4470 physical flow detail reorg

waltz-ng/client/common/components/entity-link/entity-icon-label.js, waltz-ng/client/data-types/services/data-type-store.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.scss, waltz-service/src/main/java/com/khartec/waltz/service/data_type/DataTypeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataTypesEndpoint.java
=> Db contrib/waltz 4407 data type popover source and target graph

waltz-ng/client/person/routes.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/profile/view.html, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-run-view.html, waltz-ng/client/survey/survey-run-view.js, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/widgets/markdown.js
=> Db contrib/waltz 3859 survey ux

waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.scss
=> Db contrib/waltz 4488 boingy graph improvements

waltz-ng/client/common/grid-utils.js, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.js, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.js, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-run-view.js, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/widgets/markdown.js
=> Db contrib/waltz 4489 survey ux2

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml, waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-model/src/main/java/com/khartec/waltz/model/bookmark/Bookmark.java, waltz-ng/client/bookmarks/components/bookmarks-edit-panel/bookmarks-edit-panel.html, waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.html, waltz-ng/client/bookmarks/directives/bookmark-form.html, waltz-ng/client/bookmarks/directives/bookmark-form.js
=> Db contrib/waltz 4492 support for restricted bookmarks

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml
=> Db contrib/waltz 4486 added last modified date column to attestation

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml
=> Waltz 4084 4448 alloc ddl

waltz-data/src/main/java/com/khartec/waltz/data/software_catalog/SoftwarePackageDao.java
=> Fixing bug with bulk store

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml
=> Fixing role name  inconsistency

waltz-ng/client/auth-sources/components/section/auth-sources-section.html, waltz-ng/client/auth-sources/components/section/auth-sources-section.js, waltz-ng/client/auth-sources/components/table/auth-sources-table.html, waltz-ng/client/auth-sources/components/table/auth-sources-table.js
- bonus: fixed bug where table sometimes failed to render
(think this was casued by the `onInitialisation` callback no
longer existing)
#2600
=> Fixing authsources popover consistency

waltz-ng/client/widgets/page-header/page-header.scss, waltz-ng/style/_waltz.scss
Rounded corners on header now have the same radius as those on sections.
#4396
=> UI Consistency: Rounded corners

waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.js
=> Db contrib/waltz 4400 assessments ux

waltz-ng/client/entity-diagrams/components/section/entity-diagrams-section.html, waltz-ng/client/flow-diagram/components/diagrams-panel/view/flow-diagrams-panel-view.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/widgets/editable-field.html
=> Adding markdown support to flow diagram descriptions

waltz-ng/client/physical-flows/physical-flow-view.js
- did not revert back to overview when toggling dupe button
#4398
=> Cleanup dupes toggle bug

waltz-ng/client/technology/components/technology-section/technology-section.js, waltz-ng/client/widgets/icon.js
=> HW/OS/DB Obsolescence - ux improvements

waltz-ng/client/history/services/history-store.js, waltz-ng/client/welcome/components/recently-viewed-section/recently-viewed-section.html, waltz-ng/client/welcome/components/recently-viewed-section/recently-viewed-section.js, waltz-ng/client/welcome/index.js
=> Bonus: boosted size of recently viewed list

waltz-ng/client/measurable/pages/measurable-view/measurable-view.html
=> Fixing offset for measurable view 

waltz-ng/client/entity-diagrams/components/section/entity-diagrams-section.js, waltz-ng/client/entity-svg-diagram/components/viewer/entity-svg-diagram-viewer.html, waltz-ng/client/entity-svg-diagram/components/viewer/entity-svg-diagram-viewer.js, waltz-ng/client/entity-svg-diagram/components/viewer/entity-svg-diagram-viewer.scss, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.html, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.html
=> Db contrib/waltz 4522 diagram ux

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml, waltz-data/src/main/java/com/khartec/waltz/data/GenericSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationInstanceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationRunDao.java, waltz-ng/client/attestation/attestation-pie-utils.js, waltz-ng/client/attestation/components/section/attestation-summary-section.html, waltz-ng/client/attestation/components/section/attestation-summary-section.js, waltz-ng/client/attestation/index.js, waltz-ng/client/attestation/services/attestation-instance-store.js, waltz-ng/client/attestation/services/attestation-run-store.js, waltz-ng/client/common/colors.js, waltz-ng/client/common/components/grid/grid-with-search.js, waltz-ng/client/common/grid-utils.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationRunService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttestationInstanceEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttestationRunEndpoint.java
=> Db contrib/waltz 4486 attestation group view

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml
=> Software Package External Id Larger

waltz-data/src/main/ddl/liquibase/db.changelog-1.21.xml, waltz-ng/client/common/components/grid/grid.scss, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntitySearchEndpoint.java
=> Db contrib/waltz 4529 minor fixes for 1.21

waltz-model/src/main/java/com/khartec/waltz/model/IdSelectionOptions.java, waltz-ng/client/change-unit/components/section/change-unit-section.js, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitViewService.java
=> Db contrib/waltz 4536 change sets pf removal

pom.xml, waltz-ng/client/widgets/sub-section.js, waltz-ng/package-lock.json, waltz-schema/pom.xml
=> Waltz 4542 java lib upgrades

waltz-common/src/test/java/com/khartec/waltz/common/SetUtilities_minus.java, waltz-common/src/test/java/com/khartec/waltz/common/SetUtilities_orderedUnion.java, waltz-schema/pom.xml
=> Db contrib/waltz 4548 set utilities unit tests

waltz-data/src/main/ddl/liquibase/db.changelog-1.22.xml
=> Software Version: Rename releaseDate and also remove default value

CONTRIBUTING.md, CONTRIBUTORS.md, NOTICE.md, waltz-web/src/main/webapp/WEB-INF/web.xml
=> Moving code base to Apache Public License version 2

waltz-data/src/main/java/com/khartec/waltz/data/EntityReferenceNameResolver.java, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ChangeInitiativeHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/NotificationHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/UnionHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/FlowSummaryWithTypesAndPhysicalsExport.java, waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/widgets/data-extract-link.js
#4267
Tested on MSSQL, Maria and Postgres
=> Fixing issues with Maria/jOOQ support for union operators

pom.xml, waltz-ng/package-lock.json, waltz-schema/pom.xml
- build now complains early (and with informative message) if missing properties are detected
- build aborts if on a pre 3.5 version of maven
- build creates sources jars
#3988
=> Tightened up maven settings

waltz-ng/package-lock.json, waltz-ng/package.json, waltz-ng/webpack.config.js, waltz-web/pom.xml
- prevents accumulation of build artifacts
#4527
=> Clean out the npm dist directory when doing a full build

waltz-data/src/main/ddl/liquibase/db.changelog-1.22.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml
=> Maria does not support columns with default calculated dates

waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.js, waltz-ng/client/logical-flow/components/edit/logical-flow-type-editor.html
=> Data type selection will auto-deselect unknown upon any selection.

pom.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.22.xml
=> Db contrib/waltz 4592 asset costs table decimal size

pom.xml
=> Db contrib/waltz 4594 attestation feedback fail to attest

waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.html, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Fixing search and survey extraction

waltz-ng/client/auth-sources/components/tree-filter/tree-filter.html, waltz-ng/client/entity-statistics/components/entity-statistic-tree.html, waltz-ng/client/entity-statistics/components/entity-statistic-tree.js
=> Adding search to entity statistic tree

docs/design/entity_lifecycle/README.md
=> Db contrib/waltz 4617 doc lifecycle

waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-ng/client/involvement/components/involved-people-section.js, waltz-ng/client/involvement/involvement-utils.js
=> Db contrib/waltz 4622 dedupe involvements

waltz-ng/client/attestation/attestation-instance-list-user-view.html, waltz-ng/client/attestation/attestation-instance-list-user-view.js, waltz-ng/client/attestation/attestation-utils.js, waltz-ng/client/attestation/components/confirmation/attestation-confirmation.html, waltz-ng/client/attestation/components/confirmation/attestation-confirmation.js, waltz-ng/client/attestation/components/confirmation/attestation-confirmation.scss, waltz-ng/client/attestation/components/section/attestation-section.html, waltz-ng/client/attestation/components/section/attestation-section.js, waltz-ng/client/data-flow/components/application-flow-summary-graph/application-flow-summary-graph.js
=> Attestation improvements

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java
=> Db contrib/wwaltz 4629 logical flow bulk loader bug

waltz-data/src/main/ddl/liquibase/db.changelog-1.22.xml, waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/InvolvementGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/PersonResolver.java, waltz-model/src/main/java/com/khartec/waltz/model/involvement/Involvement.java, waltz-ng/client/entity/components/entity-involvement-editor/entity-involvement-editor.html
=> Db contrib/waltz 4626 involvement add read only flag

docs/development/database/attestation-snippets.sql, waltz-common/src/main/java/com/khartec/waltz/common/FunctionUtilities.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.22.xml, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationViewDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/AttestationViewHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/Operation.java, waltz-ng/client/applications/components/apps-section/apps-section.html, waltz-ng/client/applications/components/apps-section/apps-section.js, waltz-ng/client/assessments/assessment-utils.js, waltz-ng/client/asset-cost/components/section/asset-costs-section.html, waltz-ng/client/asset-cost/components/table/asset-cost-table.js, waltz-ng/client/attestation/attestation-pie-utils.js, waltz-ng/client/attestation/attestation-utils.js, waltz-ng/client/attestation/components/section/attestation-section.js, waltz-ng/client/attestation/components/section/attestation-summary-section.js, waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.js, waltz-ng/client/change-log/components/change-log-section.js, waltz-ng/client/common/components/entity-link/entity-icon-label.js, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationInstanceService.java
=> Db contrib/waltz 4619 attestations 2

waltz-data/src/main/ddl/liquibase/db.changelog-1.22.xml, waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-model/src/main/java/com/khartec/waltz/model/involvement/Involvement.java, waltz-ng/client/involvement/components/involved-people-section.js, waltz-ng/client/involvement/involvement-utils.js, waltz-service/src/main/java/com/khartec/waltz/service/involvement/InvolvementService.java
=> Db contrib/waltz 4635 continued involvement add read only flag

waltz-ng/client/widgets/from-now.js
=> survey timezone error

waltz-ng/client/applications/components/apps-section/apps-section.html, waltz-ng/client/applications/components/apps-section/apps-section.js
=> Db contrib/waltz 4665 app section export to extractor

waltz-data/src/main/ddl/liquibase/db.changelog-1.23.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionResponseDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/SurveyBuilder.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionFieldType.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionResponse.java, waltz-ng/client/common/services/enums/survey-question-field-type.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-edit.js, waltz-ng/client/survey/survey.scss, waltz-ng/style/style.scss, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyQuestionDropdownEntryService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyQuestionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyRunExtractor.java
=> Surveys: Add multi-select as an input type

waltz-ng/client/measurable/components/summary/measurable-summary.html
=> Db contrib/waltz 4690 add popover to measurable summary

waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/common/components/entity-link/entity-icon-label.js, waltz-ng/client/common/components/entity-link/entity-link.html, waltz-ng/client/common/components/entity-link/entity-link.js, waltz-ng/client/measurable/components/tree/measurable-tree.html
=> Db contrib/waltz 4683 other viewpoints add height restricted popover to links

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating_replacement/MeasurableRatingReplacementDao.java, waltz-ng/client/entity/components/entity-selector/entity-selector.js, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.html, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/measurable-rating-utils.js, waltz-ng/client/measurable-rating/services/measurable-rating-replacement-store.js, waltz-ng/client/widgets/editable-field.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating_replacement/MeasurableRatingReplacementService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingPlannedDecommissionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingReplacementEndpoint.java
=> Waltz 4693 replacement apps

waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/measurable-rating-utils.js, waltz-ng/client/ratings/components/rating-indicator-cell/wric-rating-popup.html, waltz-ng/client/widgets/icon.js
=> Code cleanup

waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/EntityHierarchyDao.java, waltz-ng/client/measurable-category/pages/edit/measurable-category-edit.js, waltz-ng/client/taxonomy-management/components/pending-taxonomy-changes-sub-section/pending-taxonomy-changes-sub-section.html, waltz-ng/client/taxonomy-management/components/pending-taxonomy-changes-sub-section/pending-taxonomy-changes-sub-section.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java, waltz-service/src/main/java/com/khartec/waltz/service/taxonomy_management/TaxonomyChangeService.java
+ Other taxonomy edit fixes
#4147
#4706
=> NWM Contrib - Rebuild measurable hierarchy after manual taxonomy edits

waltz-ng/client/auth-sources/components/section/auth-sources-section.html, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.html, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.html, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.js, waltz-ng/client/entity-svg-diagram/components/panel/entity-svg-diagrams-panel.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.html, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js, waltz-ng/client/measurable-relationship/components/editor/update-related-measurable-editor.js, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js, waltz-ng/client/roadmap/components/roadmap-scenario-axis-config/roadmap-scenario-axis-config.html, waltz-ng/client/roadmap/components/roadmap-scenario-axis-config/roadmap-scenario-axis-config.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html, waltz-ng/style/_waltz-tabs.scss
=> Db contrib/waltz 4721 related measurables multi select tree

waltz-ng/client/applications/components/apps-section/apps-section.js, waltz-ng/client/flow-diagram/components/change-initiative-associations/flow-diagram-change-initiative-associations.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-node-popup.html, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.html, waltz-ng/client/person/pages/home/person-home.html, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/survey-instance-response-edit.html
=> Db contrib/waltz 4722 selector lifecycles

waltz-data/src/main/ddl/liquibase/db.changelog-1.23.xml
=> Db contrib/waltz 4719 foreign key constraint for assessment rating

waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/survey/components/instance-list/survey-instance-list.html, waltz-ng/client/survey/components/instance-list/survey-instance-list.js, waltz-ng/client/survey/components/survey-section.html, waltz-ng/client/survey/components/survey-section.js, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/services/survey-run-store.js, waltz-ng/client/survey/survey-utils.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyInstanceEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java
=> Person Page: add survey section

waltz-ng/client/navbar/directives/navbar-profile.html
=> NWM-Contrib: Login: enter key to submit log in form

waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.html
=> Rating picker bug fix

waltz-ng/client/survey/survey-instance-response-edit.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Db contrib/waltz 4667 survey run small bug fixes

waltz-ng/client/assessments/assessment-utils.js, waltz-ng/client/licence/components/section/licence-section.js, waltz-ng/client/licence/pages/list/licence-list.js, waltz-ng/client/technology/components/technology-section/technology-section.js, waltz-ng/package-lock.json
=> Db contrib/waltz 4764 licence list assessments

waltz-common/src/main/java/com/khartec/waltz/common/ArrayUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/ArrayUtilities_initial.java, waltz-common/src/test/java/com/khartec/waltz/common/ArrayUtilities_last.java, waltz-common/src/test/java/com/khartec/waltz/common/ArrayUtilities_map.java, waltz-ng/client/survey/components/dropdown/survey-dropdown-editor.html, waltz-ng/client/survey/components/dropdown/survey-dropdown-editor.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html
=> Improving look n feel of surveys

waltz-data/src/main/ddl/liquibase/db.changelog-1.23.xml
=> Add rating_editor_role to measurable category

waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> App Groups: adding person section

waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/entity-statistics/components/section/entity-statistic-section.js
=> Db contrib/4777 indicator sort by outcome

waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-ng/client/physical-flows/components/register/edit-specification/physical-flow-edit-specification.html, waltz-ng/client/physical-flows/physical-flow-registration.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification/PhysicalSpecificationService.java
=> Db contrib/waltz 4779 physical flow edit reactivate removed specs

waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.html, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.html, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java
=> Db contrib/waltz 4782 data type bug

waltz-ng/client/licence/pages/list/licence-list.html
=> Licence Management: reword description text

waltz-ng/client/involvement/components/involved-people-section.html, waltz-ng/client/involvement/components/involved-people-section.js
=> Db contrib/waltz 4776 involved people involvement kind description popover

waltz-data/src/main/ddl/liquibase/db.changelog-1.23.xml
=> MySql / MariaDB: cannot complete 1.23 scripts

docs/dev-log/4813-measurable-ubr.md, waltz-data/src/main/ddl/liquibase/db.changelog-1.24.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/OrganisationalUnitDao.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable/Measurable.java, waltz-model/src/main/java/com/khartec/waltz/model/orgunit/OrganisationalUnit.java, waltz-ng/client/common/components/entity-link/entity-icon-label.js, waltz-ng/client/measurable/components/info/measurable-info.html, waltz-ng/client/measurable/components/info/measurable-info.js, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/measurable/components/summary/measurable-summary.js
=> Adding org unit to measurable

pom.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.24.xml, waltz-data/src/main/java/com/khartec/waltz/data/actor/ActorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable_category/MeasurableCategoryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-data/src/main/java/com/khartec/waltz/data/rel/ChangeInitiativeToMeasurableRelDao.java, waltz-data/src/main/java/com/khartec/waltz/data/rel/RelationshipKindDao.java, waltz-integration-test/README.md, waltz-integration-test/pom.xml, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/BaseIntegrationTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/DITestingConfiguration.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/actor/ActorDaoTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/rel/ChangeInitiativeToMeasurableDaoTest.java, waltz-model/src/main/java/com/khartec/waltz/model/rel/BaseRelationship.java, waltz-model/src/main/java/com/khartec/waltz/model/rel/ChangeInitiativeToMeasurableRel.java, waltz-model/src/main/java/com/khartec/waltz/model/rel/CreateRelationshipCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/rel/RelationshipKind.java
Adding integration tests and another ddl change
#4812
=> Waltz 4812 cm2m rel

waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/measurable/components/org-unit-direct-measurable-section/org-unit-direct-measurable-section.html, waltz-ng/client/measurable/components/org-unit-direct-measurable-section/org-unit-direct-measurable-section.js, waltz-ng/client/measurable/index.js
=> Org Unit to Measurable section

waltz-data/src/main/java/com/khartec/waltz/data/measurable_category/MeasurableCategoryDao.java, waltz-ng/client/measurable-category/services/measurable-category-store.js, waltz-ng/client/measurable/components/org-unit-direct-measurable-section/org-unit-direct-measurable-section.html, waltz-ng/client/measurable/components/org-unit-direct-measurable-section/org-unit-direct-measurable-section.js, waltz-ng/client/measurable/components/org-unit-relationship-tree/measurable-org-unit-relationship-tree.html, waltz-ng/client/measurable/components/org-unit-relationship-tree/measurable-org-unit-relationship-tree.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_category/MeasurableCategoryService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableCategoryEndpoint.java
=> Db contrib/waltz 4834 org unit measurable view

waltz-ng/client/applications/formly/fields.js, waltz-ng/client/formly/org-unit-input-template.html, waltz-ng/client/measurable/components/org-unit-direct-measurable-section/org-unit-direct-measurable-section.html, waltz-ng/client/measurable/components/org-unit-relationship-tree/measurable-org-unit-relationship-tree.html, waltz-ng/client/measurable/components/org-unit-relationship-tree/measurable-org-unit-relationship-tree.js
=> Waltz 4837 ui tweaks

waltz-schema/pom.xml
=> jOOQ Code Gen: set javaTimeTypes to false

waltz-data/src/main/java/com/khartec/waltz/data/tag/TagDao.java, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.js, waltz-ng/client/data-types/components/flow-section/data-type-flow-section.html, waltz-ng/client/data-types/components/flow-section/data-type-flow-section.js, waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.html, waltz-ng/client/logical-flow/components/flow-filter-options/flow-filter-options.js, waltz-ng/client/logical-flow/components/logical-flows-boingy-graph/logical-flows-boingy-graph.html, waltz-ng/client/logical-flow/components/logical-flows-boingy-graph/logical-flows-boingy-graph.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js, waltz-ng/client/logical-flow/logical-flow-utils.js, waltz-ng/client/tag/services/tag-store.js, waltz-ng/client/user/services/user-preference-service.js, waltz-ng/style/style.scss, waltz-service/src/main/java/com/khartec/waltz/service/tag/TagService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/TagEndpoint.java
=> Data Flows: Add support to filter flows based on tags

waltz-ng/client/physical-flows/physical-flow-view.html
- now links to logical flows, not to participants
#4858
=> Improving breadcrumbs in physical flows

waltz-data/src/main/ddl/liquibase/db.changelog-1.25.xml, waltz-data/src/main/java/com/khartec/waltz/data/rel/RelationshipKindDao.java, waltz-model/src/main/java/com/khartec/waltz/model/rel/RelationshipKind.java, waltz-ng/client/measurable-relationship/components/item-view/related-measurable-item-view.html, waltz-ng/client/measurable-relationship/components/item-view/related-measurable-item-view.js, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.js
=> Db contrib/waltz 4852 multi relationships naming directions

waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/roadmaps/ScenarioPopulator.java
=> Db contrib/waltz 4833 scenario pop

waltz-ng/client/physical-flow/physical-flow-table-utilities.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/PhysicalFlowExtractor.java
=> Physical Flow table should use flow ext id

waltz-ng/client/measurable-category/pages/list/measurable-category-list.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/EntityRelationshipsExtractor.java
=> Db contrib/waltz 4899 ci measurable relationships export

waltz-ng/client/measurable-relationship/components/item-view/related-measurable-item-view.html, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.js
=> Db contrib/waltz 4903 related measurables small changes

waltz-ng/client/person/components/person-apps-section/person-apps-section.html, waltz-ng/client/person/components/person-apps-section/person-apps-section.js, waltz-ng/client/person/components/person-apps-table/person-apps-table.html, waltz-ng/client/person/components/person-apps-table/person-apps-table.js, waltz-ng/client/person/index.js
=> Db contrib/waltz 4902 person apps involvements

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/EntityRelationshipsExtractor.java
=> Db contrib/waltz 4899 ci measurable export additional columns

waltz-ng/client/applications/components/app-costs-section/app-costs-section.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/TechnologyEOLServerExtractor.java
=> Db contrib/waltz 4821 location servers export app costs order

waltz-ng/client/measurable-relationship/components/table/related-measurables-table.html, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.js
=> Db contrib/waltz 4923 relationships hover over

waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.js, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.js
=> Db contrib/waltz 4930 relationships to private app groups

waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.html, waltz-ng/client/measurable-relationship/components/editor/create-related-measurable-editor.js
=> Db contrib/waltz 4937 outer search on multi select tree

waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.html, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.js, waltz-ng/client/measurable-rating/measurable-rating-utils.js
=> Db contrib/waltz 4938 error set decommission date in us tz

docs/development/release-lifecycle.md
=> Documenting versioning strategy

waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> Adding entity named note section to flow diagram page

pom.xml, waltz-common/pom.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/search/PostgresAppSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/search/PostgresChangeInitiativeSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/search/PostgresMeasurableSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/search/PostgresOrganisationalUnitSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/search/PostgresServerInformationSearch.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/bookmark/BookmarkDaoTest.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/resolvers/InvolvementNameToIdResolver.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/resolvers/OrgNameToIdResolver.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/resolvers/PersonNameToEmpIdResolver.java, waltz-web/pom.xml
Note - this change contains a jooq update
#4950
=> Updating Waltz dependencies

waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/InvolvementGenerator.java
Could not recreate, but have improved test data generation.
#4554
=> Category page gives error

waltz-data/src/main/ddl/liquibase/db.changelog-1.26.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
- added new liquibase file for 1.26
#4936
=> Add kind to `entity_alias` table

docs/blog/_posts/2019-01-20-arch-unit.md
=> Updated blog

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/PersonDataGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/SampleDataGenerator.java, waltz-web/pom.xml
- sample docker image was getting too large (>500MB)
#4802
=> Reduce sample data generation size

.travis.yml, waltz-integration-test/pom.xml, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/BaseIntegrationTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/DITestingConfiguration.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/measurable_rating/MeasurableRatingDaoTest.java, waltz-service/src/main/java/com/khartec/waltz/service/DIBaseConfiguration.java, waltz-service/src/main/java/com/khartec/waltz/service/email/EmailService.java, waltz-service/src/main/java/com/khartec/waltz/service/email/WaltzEmailer.java, waltz-web/pom.xml, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/NavAidExtractor.java
=> Integration tests for measurable ratings

docs/blog/_posts/2020-06-30-dev-schema-modifications.md, docs/development/database/schema.md, waltz-data/src/main/ddl/liquibase/db.changelog-1.26.xml, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupEntryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupOrganisationalUnitDao.java, waltz-model/src/main/java/com/khartec/waltz/model/IsReadOnlyProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroup.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroupDetail.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroupEntry.java, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java
=> Added DDL and updated DAO/Model/Services

waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogSummariesDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ChangeLogSummariesHarness.java, waltz-ng/client/change-log/services/change-log-store.js, waltz-ng/client/playpen/3/calendar-heatmap.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-ng/client/playpen/index.js, waltz-service/src/main/java/com/khartec/waltz/service/changelog/ChangeLogService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeLogEndpoint.java
=> Waltz 4876 cal heatmap

README.md
Per #4872 all activation criteria have been met, so just accept this PR to formalize the transition of Waltz as the latest FINOS active project!
Congratulations to @davidwatkins73 and all the maintainer team for having achieved this milestone so quickly. Kudos to @mcleo-d as well for the support here!
=> Closes #4872 - Adding Waltz active badge

waltz-ng/client/survey/survey-run-view.html, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/widgets/data-extract-link.js, waltz-ng/package-lock.json
Allow export  of in-progress surveys
=> Waltz 4993 export in progress

README.md, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/EntityRelationshipsExtractor.java
=> Db contrib/waltz 4991 ci measurable extractor all cis

waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/ChangeLogGenerator.java, waltz-ng/client/app-groups/components/favourites-panel/favourites-panel.html, waltz-ng/client/app-groups/components/favourites-panel/favourites-panel.js, waltz-ng/client/change-log/components/change-breakdown-table.html, waltz-ng/client/change-log/components/change-breakdown-table.js, waltz-ng/client/change-log/components/summaries-panel/change-summaries-panel.html, waltz-ng/client/change-log/components/summaries-panel/change-summaries-panel.js, waltz-ng/client/common/components/calendar-heatmap/calendar-heatmap.js
=> Waltz 4876 tweaks

waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js
=> Db contrib/waltz 5014 allow set decom post app retirement date

docs/development/database/snippets.sql, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeIdSelectorFactory.java, waltz-ng/package-lock.json, waltz-service/src/main/java/com/khartec/waltz/service/data_type/DataTypeDecoratorService.java
=> Db contrib/waltz 5016 phys flow datatype error

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Db contrib/waltz 5019 survey extractor comments bug

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ChangeLogExtractor.java
=> Db contrib/waltz 5021 change log person export

waltz-service/src/main/java/com/khartec/waltz/service/data_type/DataTypeDecoratorService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ChangeLogExtractor.java
=> Logical flow: audit log error prevents data type update

waltz-model/src/main/java/com/khartec/waltz/model/assessment_rating/AssessmentRatingDetail.java, waltz-ng/client/survey/survey-template-edit.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionAppPredicateNamespace.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionBasePredicateNamespace.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionEntityPredicateNamespace.java
=> Waltz 5025 cond surveys app predicates

.gitignore, docs/design/default_ratings/default_ratings.adoc, docs/design/homepage/homepage.adoc
=> Adding design doc for default ratings

waltz-ng/client/common/d3-utils.js, waltz-ng/client/common/function-utils.js, waltz-ng/client/common/index.js, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/logical-flow/logical-flow-utils.js, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js, waltz-ng/client/technology/components/technology-section/technology-section.js, waltz-ng/client/widgets/simple-stack-chart.js, waltz-ng/test/common/random-pick-test.js
The gui allows users to select an empty set of flows.
However the ui then only shows a message saying there are no flows and doesn't allow the user to select back to 'all' or a different non-empty list.
#5041
=> Physical Flows Section: if selecting an empty set of consumers/producers then user becomes trapped

waltz-data/src/main/ddl/liquibase/db.changelog-1.27.xml, waltz-schema/pom.xml
- attestation_1_11
- measurable_1_21
#4441
=> Removing backup tables

waltz-model/src/main/java/com/khartec/waltz/model/scenario/ChangeScenarioCommand.java, waltz-model/src/test/java/com/khartec/waltz/model/scenario/ChangeScenarioCommandTest.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowUploadService.java, waltz-service/src/main/java/com/khartec/waltz/service/scenario/ScenarioRatingItemService.java
=> Fixing some LGTM warnings

waltz-ng/client/common/components/date-picker/date-picker-form-input.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.html, waltz-ng/client/widgets/editable-field.html, waltz-ng/client/widgets/editable-field.js, waltz-ng/client/widgets/inline-edit-area.html
=> App retirement date alignment

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionResponseDao.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java
=> Panterose 5025/cleanquestions

waltz-data/src/main/ddl/liquibase/db.changelog-1.27.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable_category/MeasurableCategoryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_category/MeasurableCategory.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RagName.java, waltz-ng/client/attestation/attestation-instance-list-user-view.html, waltz-ng/client/attestation/components/confirmation/attestation-confirmation.html, waltz-ng/client/attestation/components/confirmation/attestation-confirmation.js, waltz-ng/client/attestation/components/inline-measurable-rating-panel/inline-measurable-rating-panel.html, waltz-ng/client/attestation/components/inline-measurable-rating-panel/inline-measurable-rating-panel.js, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.scss, waltz-ng/client/measurable-rating/measurable-rating-utils.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.js, waltz-ng/client/ratings/services/rating-scheme-store.js, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.html, waltz-ng/client/roadmap/components/roadmap-scenario-diagram/roadmap-scenario-diagram.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable_category/MeasurableCategoryService.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/rating_scheme/RatingSchemeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/RatingSchemeEndpoint.java
=> Deutschebank db contrib/waltz 5036 limiting assessment on measurable category

waltz-data/src/main/ddl/liquibase/db.changelog-1.27.xml
=> Db contrib/waltz 5061 vulnerability tables

waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-ng/client/survey/survey-actions.js, waltz-ng/client/survey/survey-instance-response-edit.html
The template change is not ideal, maybe due to my poor knowledge of AngularJS (see the nbClick ...)
=> 5025: fix submission disabling, and also filter buttons based on panel

waltz-ng/client/logical-flow/pages/view/logical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.html
=> Enabling assessments on phys/logical flows

waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/RoleEndpoint.java
=> fixing survey permission issues

waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceStateMachineFactory.java, waltz-model/src/test/java/com/khartec/waltz/model/survey/SurveyInstanceStateMachineTest.java
=> Db contrib/waltz 5079 survey fixes 2

docs/blog/_posts/2020-09-17-cond-surveys.md
=> Survey blog post

waltz-data/src/main/ddl/liquibase/db.changelog-1.28.xml, waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ReportGridHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/report_grid/ColumnUsageKind.java, waltz-model/src/main/java/com/khartec/waltz/model/report_grid/ReportGridColumnDefinition.java, waltz-model/src/main/java/com/khartec/waltz/model/report_grid/ReportGridDefinition.java, waltz-ng/client/common/list-utils.js, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.html, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.js, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.scss, waltz-ng/style/_waltz.scss
- added ability to add/remove summaries
- speeded up filtering
- added help text
#5107
=> Adding report grid summaries and filtering

waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/LogicalFlowDecorationGenerator.java, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.html, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.js, waltz-ng/client/report-grid/components/report-grid-picker/report-grid-picker.html, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.html, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js, waltz-ng/client/svg-diagram/component/svg-diagram.js
- also fixing some d3 v6-v4 revert issues.
#5107
=> adding ordering to report grid columns.

waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.html, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.js, waltz-ng/client/report-grid/components/report-grid-picker/report-grid-picker.html, waltz-ng/client/report-grid/components/report-grid-picker/report-grid-picker.js, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.html, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js
=> Db contrib/waltz 5107 aggregate measurable qry

docs/design/draft/attestation_permissions/attestation_permissions.adoc
=> Db contrib/waltz 5103 involvement permissions desgin doc

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupEntryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/BaseIntegrationTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/actor/ActorDaoTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/app_group/AppGroupDaoTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/application/ApplicationDaoTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/measurable_rating/MeasurableRatingDaoTest.java
- basic app dao
- app selector via ou
- app groups
=> Improved integration testing

waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ReportGridHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/report_grid/ReportGridService.java
=> Db contrib/waltz 5107 grid perf 20201013

waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.html, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ReportGridExtractor.java
=> Db contrib/waltz 5107 report grid extractor

waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-ng/client/attestation/attestation-utils.js, waltz-ng/client/attestation/components/section/attestation-summary-section.html, waltz-ng/client/attestation/components/section/attestation-summary-section.js, waltz-ng/client/common/components/grid/grid-with-search.html, waltz-ng/client/common/components/grid/grid.js, waltz-ng/client/common/grid-utils.js, waltz-ng/client/networking.js, waltz-ng/client/widgets/data-extract-link.js, waltz-ng/client/widgets/from-now.js, waltz-web/pom.xml, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AttestationExtractor.java
=> Db contrib/waltz 5127 attestation yr filter

waltz-data/src/main/ddl/liquibase/db.changelog-1.28.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/permission_group/Permission.java, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/attestation/components/section/attestation-section.html, waltz-ng/client/attestation/components/section/attestation-section.js, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/modules.js, waltz-ng/client/permission-group/index.js, waltz-ng/client/permission-group/services/permission-group-store.js, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/permission/PermissionGroupDao.java, waltz-service/src/main/java/com/khartec/waltz/service/permission/PermissionGroupService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PermissionGroupEndpoint.java
=> Db contrib/waltz 5103 involvement based auth for attestation

docs/design/draft/flow_data_types/flow_data_types.adoc, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.html
=> Db contrib/waltz 5085 datatype tweaks read only

waltz-common/src/main/java/com/khartec/waltz/common/exception/ModifyingReadOnlyRecordException.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating_planned_decommission/MeasurableRatingPlannedDecommissionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating_replacement/MeasurableRatingReplacementDao.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/bookmark/BookmarkDaoTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/measurable_rating/MeasurableRatingDaoTest.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/AllocationHarness.java, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.js, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.html, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating_planned_decommission/MeasurableRatingPlannedDecommissionService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Waltz 5134 perm cleanup

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js
=> Db contrib/waltz 5130 unknown rating colour text

waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/ratings/rating-utils.js
=> Fix: selecting rating using keyboard

waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java
=> Backporting performance fix for the reportgrid

waltz-ng/client/app-groups/components/summary/app-group-summary.js, waltz-ng/client/complexity/components/basic-info-tile/complexity-basic-info-tile.js, waltz-ng/client/complexity/services/complexity-store.js, waltz-ng/client/measurable/components/summary/measurable-summary.js, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.html, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js, waltz-ng/client/person/components/summary/person-summary.js
=> Db contrib/waltz 5147 further performance tweaks inc search

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-ng/client/applications/resolvers.js, waltz-ng/client/applications/routes.js, waltz-ng/client/applications/services/application-store.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java
- dupes could be caused by having ids repeated in the external id table
- bonus: cleaned up warning whilst looking at flow of code from ui to dao
#5140
=> Fixing duplicates

waltz-ng/client/survey/survey-template-edit.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionAppPredicateNamespace.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionChangeInitiativePredicateNamespace.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionEntityPredicateNamespace.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionPredicateEvaluator.java
#5170 
- adding CI support for `belongsToOrgUnit`
- adding `hasInvolvement(roleNAme)` support for CI's and Apps
=> Waltz 5170 cond surveys

waltz-ng/client/server-info/components/overview/server-overview.html
=> Server view: add support for entity-enums

waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/navbar/directives/navbar-profile.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/MeasurableCategoryExtractor.java
=> Waltz 5176 measurable extract inc level

waltz-data/src/main/java/com/khartec/waltz/data/licence/LicenceDao.java, waltz-ng/client/licence/routes.js, waltz-ng/client/licence/services/licence-store.js, waltz-service/src/main/java/com/khartec/waltz/service/licence/LicenceService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LicenceEndpoint.java
=> Db contrib/waltz 5181 licence by external

waltz-data/src/main/java/com/khartec/waltz/data/settings/SettingsDao.java
=> Fixing null case when hydrating settings

waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.html, waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.js, waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.scss
=> Adding dynamic section help

waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java
=> Default roles fix

waltz-ng/client/common/d3-utils.js, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.html, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js
=> Partial Edge Drawing

waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js
=> Waltz 5190 ped 2

waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js
- also some fixes for IE11
#5190
=> Tweaking look n' feel

docs/blog/_posts/2020-11-29-ped.md
=> Adding a blog

docs/blog/_posts/2020-11-29-ped.md, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.html, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.scss
=> Db contrib/waltz 5190 ped 4

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating_replacement/MeasurableRatingReplacementDao.java
=> Adding missing constraint to update

waltz-ng/client/physical-flows/components/flow-spec-definition-section/flow-spec-definition-section.js
=> Ensuring id is sent for field updates

waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.html, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.html, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.js
=> Can directly edit dates for replacement apps

waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/style/_waltz.scss
=> Re-ordering data flow section

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js
=> Fixes bug when toggling allocation section

waltz-ng/client/common/date-utils.js, waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/client/measurable-rating/components/planned-decommission-editor/planned-decommission-editor.js, waltz-ng/client/measurable-rating/measurable-rating-utils.js, waltz-web/src/main/java/com/khartec/waltz/web/Main.java
=> Fixes timezone bug with bst / utc

waltz-service/src/main/java/com/khartec/waltz/service/permission/PermissionGroupService.java
=> Db contrib/waltz 5216 permission service null user

waltz-ng/client/common/colors.js, waltz-ng/client/data-types/components/usage-tree/data-type-usage-tree.html, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js, waltz-ng/style/_variables.scss
=> Db contrib/waltz 5220 grid colour in ie

waltz-common/src/test/java/com/khartec/waltz/common/IOUtilities_getFileResource.java
=> Fixing unit tests

waltz-ng/client/assessments/components/editor/assessment-editor.html, waltz-ng/client/assessments/components/list/assessment-rating-list.html
=> Added markdown support consistently to assessment ratings

waltz-data/src/main/ddl/liquibase/db.changelog-1.30.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> Adding ext id to entity-named-note-type

waltz-data/src/main/ddl/liquibase/db.changelog-1.30.xml, waltz-data/src/main/java/com/khartec/waltz/data/SelectorUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/cost/CostDao.java, waltz-data/src/main/java/com/khartec/waltz/data/cost/CostKindDao.java, waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/ReportGridHarness.java, waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.html, waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.js, waltz-ng/client/cost/components/entity-costs-section/entity-costs-section.html, waltz-ng/client/cost/components/entity-costs-section/entity-costs-section.js, waltz-ng/client/cost/services/cost-kind-store.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-service/src/main/java/com/khartec/waltz/service/cost/CostService.java, waltz-service/src/main/java/com/khartec/waltz/service/cost_kind/CostKindService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/CostKindEndpoint.java
=> Db contrib/waltz 5241 latest year for each cost kind

waltz-data/src/main/java/com/khartec/waltz/data/asset_cost/AssetCostDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/example/GenericTaxonomyLoader.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionEntityPredicateNamespace.java
- instead of `.fetchOne` and then `.ofNullable`
#5252
=> Using .fetchOptional

waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.html, waltz-ng/client/cost/components/graph/entity-costs-graph.js, waltz-ng/client/cost/components/graph/entity-costs-graph.scss, waltz-ng/client/dynamic-section/services/dynamic-section-manager.js, waltz-ng/client/routes.js, waltz-ng/style/_waltz.scss
- also did some small tidying up of the entity cost graph section.
#5249
=> Sections in menus not re-opening correctly

waltz-ng/client/assessments/components/assessment-definition-overview/assessment-definition-overview.html, waltz-ng/client/assessments/pages/edit/assessment-rating-bulk-upload.html, waltz-ng/client/assessments/pages/edit/assessment-rating-bulk-upload.js, waltz-ng/client/assessments/pages/view/assessment-definition-view.html, waltz-ng/client/assessments/pages/view/assessment-definition-view.js, waltz-ng/client/cost/components/graph/entity-costs-graph.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/CostEndpoint.java
- adding rating indicator cells to grid
- minor ui simplification
- bonus: animated entity cost axis labels
- bonus: top costs defaults to 15 entries
#5275
=> Bulk assessments: ui tweaks

waltz-ng/client/assessments/components/editor/assessment-editor.js, waltz-ng/client/assessments/components/favourites-list/assessment-rating-favourites-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.js, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.html
=> Db contrib/waltz 5240 assessment section no data and expand

waltz-ng/client/assessments/components/favourites-list/assessment-rating-favourites-list.html, waltz-ng/client/assessments/components/favourites-list/assessment-rating-favourites-list.js, waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.js, waltz-ng/client/assessments/components/section/assessment-rating-section.html, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.html, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.js, waltz-ng/client/change-set/pages/view/change-set-view.html, waltz-ng/client/change-set/pages/view/change-set-view.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/licence/pages/view/licence-view.html, waltz-ng/client/licence/pages/view/licence-view.js, waltz-ng/client/logical-flow/pages/view/logical-flow-view.html, waltz-ng/client/logical-flow/pages/view/logical-flow-view.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/software-catalog/pages/view/software-package-view.html, waltz-ng/client/software-catalog/pages/view/software-package-view.js, waltz-ng/client/user/index.js
=> Db contrib/waltz 5240 assessment sub section fixes

waltz-ng/client/change-set/pages/view/change-set-view.html, waltz-ng/client/change-set/pages/view/change-set-view.js, waltz-ng/client/change-unit/components/section/change-unit-section.html, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/licence/pages/view/licence-view.html, waltz-ng/client/licence/pages/view/licence-view.js, waltz-ng/client/logical-flow/pages/view/logical-flow-view.html, waltz-ng/client/logical-flow/pages/view/logical-flow-view.js, waltz-ng/client/physical-flows/components/flow-table/physical-flow-table.js, waltz-ng/client/physical-flows/components/physical-flow-section/physical-flow-section.html, waltz-ng/client/physical-flows/components/physical-flow-section/physical-flow-section.js, waltz-ng/client/physical-specifications/components/spec-definition-section/physical-spec-definition-section.html, waltz-ng/client/physical-specifications/components/spec-definition-section/physical-spec-definition-section.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/software-catalog/pages/view/software-package-view.html, waltz-ng/client/software-catalog/pages/view/software-package-view.js, waltz-ng/client/tag/pages/tag-physical-flow-view.html, waltz-ng/client/tag/pages/tag-physical-flow-view.js
=> Db contrib/waltz 5281 convert to dynamic sections

waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationRunDao.java, waltz-ng/client/user/user-management.js
=> Db contrib/waltz 5244 set issued by attestation run pending create

waltz-common/src/main/java/com/khartec/waltz/common/RandomUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/SetUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/cost/CostDao.java, waltz-data/src/main/java/com/khartec/waltz/data/cost/CostKindDao.java, waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/WaltzUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/AssetCostGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/harness/AssetCostHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/cost/EntityCostsSummary.java, waltz-ng/client/app-groups/pages/edit/app-group-edit.html, waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/client/asset-cost/components/basic-info-tile/asset-costs-basic-info-tile.html, waltz-ng/client/asset-cost/components/basic-info-tile/asset-costs-basic-info-tile.js, waltz-ng/client/change-initiative/components/bulk-change-initiative-selector/bulk-change-initiative-selector.js, waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.html, waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.js, waltz-ng/client/cost/components/graph/entity-costs-graph.js, waltz-ng/client/cost/components/graph/entity-costs-graph.scss, waltz-ng/client/cost/services/cost-store.js, waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.js, waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js, waltz-service/src/main/java/com/khartec/waltz/service/cost/CostService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/CostEndpoint.java
=> Show missing entity costs

waltz-ng/client/assessments/components/editor/assessment-editor.html, waltz-ng/client/assessments/components/editor/assessment-editor.js, waltz-ng/client/assessments/components/favourites-list/assessment-rating-favourites-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.html, waltz-ng/client/assessments/components/list/assessment-rating-list.js, waltz-ng/client/assessments/components/section/assessment-rating-section.html, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.html, waltz-ng/client/widgets/sub-section.scss, waltz-ng/style/_animations.scss
=> Tweaking assessment ui

waltz-ng/client/assessments/index.js, waltz-ng/client/assessments/pages/edit/assessment-rating-bulk-upload.html, waltz-ng/client/assessments/pages/edit/assessment-rating-bulk-upload.js, waltz-ng/client/assessments/pages/list/assessment-definition-list.html, waltz-ng/client/assessments/pages/list/assessment-definition-list.js, waltz-ng/client/assessments/pages/view/assessment-definition-view.html, waltz-ng/client/assessments/pages/view/assessment-definition-view.js, waltz-ng/client/assessments/routes.js
=> Adding navigation for assessment definitions

waltz-ng/client/assessments/pages/list/assessment-definition-list.html, waltz-ng/client/assessments/pages/list/assessment-definition-list.js
=> Increasing size of assessment list

waltz-ng/client/common/services/enums/entity.js, waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.html
=> Better handling of missing costs

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml
=> Db contrib/waltz 5302 phys flow ext id provenance idx

waltz-ng/style/_waltz-tree.scss
=> Ensuring tree twisties point to top of multi-line nodes

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml, waltz-data/src/main/java/com/khartec/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_relationship/EntityRelationship.java, waltz-ng/client/common/link-utils.js, waltz-ng/client/common/services/enums/entity.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/entity-relationship/components/overview/entity-relationship-overview.html, waltz-ng/client/entity-relationship/components/overview/entity-relationship-overview.js, waltz-ng/client/entity-relationship/index.js, waltz-ng/client/entity-relationship/pages/view/entity-relationship-view.html, waltz-ng/client/entity-relationship/pages/view/entity-relationship-view.js, waltz-ng/client/entity-relationship/routes.js, waltz-ng/client/entity-relationship/services/entity-relationship-store.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_relationship/EntityRelationshipService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityRelationshipEndpoint.java
=> Db contrib/waltz 5306 entity rel id column and page

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml, waltz-data/src/main/java/com/khartec/waltz/data/settings/SettingsDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/DemoSettingsGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/settings/Setting.java, waltz-ng/client/system/settings-view.html
=> Db contrib/waltz 5248 add description to help dev team remember what they mean

waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js
=> Db contrib/waltz 5301 measurable ratings not sorted in pie chart

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml, waltz-schema/pom.xml
=> Seeing if we can fix for maria

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/notification/NotificationDao.java
=> Db contrib/waltz 5334 slow query performance

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml, waltz-data/src/main/java/com/khartec/waltz/data/actor/ActorDao.java, waltz-model/src/main/java/com/khartec/waltz/model/actor/Actor.java, waltz-model/src/main/java/com/khartec/waltz/model/actor/ActorChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/actor/ActorCreateCommand.java, waltz-ng/client/system/actors-view.html, waltz-ng/client/system/actors-view.js, waltz-ng/client/widgets/editable-field.js, waltz-schema/pom.xml
- bonus: editable-field now autofocuses.
#5330
=> Adding external id to actor

waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/notification/NotificationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/notification/NotificationSummary.java
- bonus: fix exception in notification dao.
#5344
=> Ensure measurable selector respects the lifecycle status of measurables

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml, waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RagName.java
=> Add externalId to rating scheme item

waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionsAdminView.svelte
=> Adding and removing rating scheme items now supported

waltz-ng/client/common/selector-utils.js
=> Removing dead code

waltz-data/src/main/ddl/liquibase/db.changelog-1.31.xml
=> Db contrib/waltz 5336 survey templates add external id column

waltz-ng/client/common/WaltzHttp.js
=> Fixing dodgy usage of localstorage

waltz-ng/client/server-info/components/server-pies/server-pies.html, waltz-ng/client/server-info/components/server-pies/server-pies.js
=> Db contrib/waltz 20210412 test synch

waltz-ng/client/bookmarks/svelte/BookmarkPanel.svelte, waltz-ng/client/common/services/index.js, waltz-ng/client/common/svelte/LoadingPlaceholder.svelte
- took opportunity to create loading placeholder widget
- ensured remote cache is cleared on page transitions
#5372
=> Embedding issue was caused by timing problems (we think)

docs/design/draft/custom_environments/custom_environment.adoc
=> Db contrib/waltz 5143 custom environments doc

docs/design/draft/custom_environments/custom_environment.adoc, waltz-ng/client/actor/components/actor-overview.html, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/complexity/components/app-complexity-summary-section/app-complexity-summary-section.js, waltz-ng/client/cost/components/entity-costs-section/entity-costs-section.js, waltz-ng/client/logical-flow/pages/view/logical-flow-view.html, waltz-ng/client/measurable/components/info/measurable-info.html, waltz-ng/client/physical-flows/components/physical-flow-and-specification-detail/physical-flow-and-specification-detail.html, waltz-ng/client/physical-specifications/components/overview/physical-specification-overview.html, waltz-service/src/main/java/com/khartec/waltz/service/survey/inclusion_evaluator/QuestionPredicateEvaluator.java
=> Db contrib/waltz 5325 add provenance to entities

waltz-ng/package-lock.json, waltz-ng/package.json, waltz-web/pom.xml
=> Ensure mocha tests are run as part of mvn package.

waltz-data/src/main/ddl/liquibase/db.changelog-1.32.xml, waltz-ng/client/common/index.js, waltz-ng/client/common/svelte/MiniActions.svelte, waltz-ng/client/svelte-stores/application-store.js, waltz-ng/client/svelte-stores/permission-group-store.js, waltz-ng/client/technology/components/technology-section/technology-section.html, waltz-ng/client/technology/svelte/custom-environment-panel/CustomEnvironmentPanel.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/EnvironmentRegistration.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageEdit.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsagePanel.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageTable.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageTree.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/custom-environment-utils.js, waltz-ng/client/technology/svelte/custom-environment-panel/editingCustomEnvironmentState.js, waltz-ng/style/_bootstrap-styles.scss, waltz-service/src/main/java/com/khartec/waltz/service/custom_environment/CustomEnvironmentService.java, waltz-service/src/main/java/com/khartec/waltz/service/custom_environment/CustomEnvironmentUsageService.java, waltz-service/src/main/java/com/khartec/waltz/service/permission/PermissionGroupService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/CustomEnvironmentEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/CustomEnvironmentUsageEndpoint.java
=> Waltz 5143 custom env lnf

waltz-model/src/main/java/com/khartec/waltz/model/database_information/DatabaseInformation.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerInformation.java, waltz-ng/client/common/svelte/EntityLabel.svelte, waltz-ng/client/common/svelte/EntityLink.svelte, waltz-ng/client/common/svelte/ViewLink.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageAssetInfo.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageEdit.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsagePanel.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageTable.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageTree.svelte, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/CustomDataExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/CustomEnvironmentUsageExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/DataExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/DirectQueryBasedDataExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ExtractorUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ReportGridExtractor.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Db contrib/waltz 5143 custom env extractor detail panel

docs/blog/_posts/2021-04-29-custom-environments.md, docs/features/custom-environments/README.md
=> Db contrib/waltz 5143 custom env docs

waltz-ng/test/README.md, waltz-ng/test/allocation/allocation-utilities-test.js, waltz-ng/test/common/entity-utils-test.js, waltz-ng/test/common/hierarchy-utils/build-hierarchies-test.js, waltz-ng/test/common/hierarchy-utils/tree-searching-test.js, waltz-ng/test/common/link-utils-test.js, waltz-ng/test/common/list-utils-test.js, waltz-ng/test/common/random-pick-test.js, waltz-ng/test/common/selector-utils-test.js, waltz-ng/test/common/services/base-lookup-service-test.js, waltz-ng/test/common/services/core-api-utils-test.js, waltz-ng/test/common/string-utils-test.js, waltz-ng/test/common/tally-utils/summing-test.js, waltz-ng/test/common/term-search-test.js, waltz-ng/test/custom-environment/group-by-application-test.js, waltz-ng/test/survey/group-questions-test.js
=> Made mocha tests follow simple naming pattern

waltz-ng/client/survey/components/survey-template-overview.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Db contrib/waltz 5359 survey template expose new external identifier column

waltz-ng/client/common/svelte/DataTypeTreeNode.svelte, waltz-ng/client/data-types/components/usage-count-tree/data-type-usage-count-tree.html, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.html, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js
=> Show deprecated data types more clearly

waltz-ng/client/measurable/components/tree/measurable-tree.html
=> Db contrib/waltz 5411 fixed viewpoints search performance

waltz-ng/client/logical-flow/logical-flow-utils.js, waltz-ng/client/measurable-category/pages/list/measurable-category-list.html, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js, waltz-ng/client/measurable-category/routes.js
=> last selected category fix

waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js
=> Fix data type search

waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.html, waltz-ng/client/data-types/components/usage-selector/data-type-usage-selector.js, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.scss, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.scss, waltz-ng/client/survey/survey.scss, waltz-ng/style/_variables.scss
- instance view looks better
- nicer alignment
- answers are in a box
- fixed tree search (again)
- colors for instance status
#5424
=> Survey tweaks

waltz-ng/client/app-groups/pages/edit/app-group-edit.html, waltz-ng/client/app-groups/pages/edit/app-group-edit.js, waltz-service/src/main/java/com/khartec/waltz/service/app_group/FavouritesService.java
- also prevent subscribes being promote to owners for favourite groups
- added user to external id of newly created fav groups
- tweaked layout of subscriber tables
#5437
=> Prevent favourite groups from being made public

waltz-common/src/main/java/com/khartec/waltz/common/EnumUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/SearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/actor/ActorSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/search/ApplicationSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/search/ChangeInitiativeSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/search/SqlServerChangeInitiativeSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type/search/DataTypeSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_data_element/search/LogicalDataElementSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/search/MeasurableSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/search/OrganisationalUnitSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/person/search/PersonSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/search/PhysicalSpecificationSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/roadmap/RoadmapSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/search/ServerInformationSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/software_catalog/SoftwarePackageDao.java, waltz-ng/client/common/error-utils.js, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.html, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js, waltz-service/src/main/java/com/khartec/waltz/service/software_catalog/SoftwareCatalogService.java
=> Db contrib/waltz 5434 search optimization

bin/run.sh, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-ng/package-lock.json, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/LicencesExtractor.java
=> Db contrib/waltz 5442 licences export fix

waltz-ng/client/survey/survey-instance-response-view.html
=> Db contrib/waltz 5458 missing survey response comments markdown

waltz-ng/client/applications/pages/view/app-view.js
=> Preventing duplicate data loads caused by enrichment of primary ref

waltz-data/src/main/ddl/liquibase/db.changelog-1.34.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestion.java, waltz-ng/client/survey/components/answer/survey-response-answer.html, waltz-ng/client/survey/components/answer/survey-response-answer.js, waltz-ng/client/survey/components/input/survey-response-input.html, waltz-ng/client/survey/components/input/survey-response-input.js, waltz-ng/client/survey/components/question-overview-table/survey-template-question-overview-table.html, waltz-ng/client/survey/index.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-edit.js, waltz-ng/client/survey/survey-utils.js, waltz-ng/client/survey/survey.scss
support for survey sub-questions
#5466
=> Survey sub questions

waltz-ng/client/flow-diagram/components/diagram-svelte/Annotation.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/AnnotationLayer.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/Flow.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/FlowDiagram.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/FlowLayer.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/Node.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/NodeLayer.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/diagram-model-store.js, waltz-ng/client/flow-diagram/components/diagram-svelte/drag-handler.js, waltz-ng/client/flow-diagram/components/diagram-svelte/flow-diagram-svelte.js, waltz-ng/client/flow-diagram/flow-diagram-view.html, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/svelte-stores/person-store.js
=> Waltz 5455 flow diagram svelte

waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java, waltz-service/src/main/java/com/khartec/waltz/service/database_information/DatabaseInformationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DatabaseInformationEndpoint.java
=> Fixing broken archunit tests

waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/FlowPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/NodePanel.svelte
=> Db contrib/waltz 5455 flow diagram node edit

waltz-ng/client/flow-diagram/components/diagram-svelte/Node.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddOverlayGroupEntrySubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGlyph.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGroupsPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGroupsTable.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/flow-diagram-utils.js
=> Overlay panels now use a glyph instead of textual description

waltz-ng/client/flow-diagram/components/diagram-svelte/Annotation.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/Flow.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/Node.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddAnnotationSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddLogicalFlowSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddNodeSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddOverlayGroupEntrySubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddPhysicalFlowSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddRelatedChangeInitiativeSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddRelatedMeasurableSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AnnotationPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/CloneOverlayGroupSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/ContextPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/DefaultPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/NodePanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGroupsPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGroupsTable.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/store/layout.js, waltz-ng/client/flow-diagram/components/diagram-svelte/store/overlay.js
=> Quick fixes

waltz-ng/client/technology/components/technology-section/technology-section.js
=> Server link in the technology section is not working

waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/flow-resolver.js
=> Fixing bug with logical flow selection

waltz-ng/client/flow-diagram/components/diagram-svelte/Annotation.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddOverlayGroupEntrySubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/EditFlowDiagramOverviewPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/EditOverlayIconSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGroupsTable.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/group-utils.js, waltz-ng/client/flow-diagram/components/diagram-svelte/store/overlay.js, waltz-ng/client/system/svelte/ratings-schemes/SymbolPicker.svelte
=> Db contrib/waltz 5455 symbol picker and edit overlay group

waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddOverlayGroupEntrySubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/FlowPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/MeasurableAlignmentTreeNode.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/MeasurableAlignmentTreeSelector.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGroupsPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/OverlayGroupsTable.svelte, waltz-ng/client/svelte-stores/flow-diagram-overlay-group-store.js
=> Db contrib/waltz 5455 small flow diagram tweaks

waltz-ng/client/flow-diagram/components/diagram-svelte/Node.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/drag-handler.js
=> First click selects node

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AssessmentRatingExtractor.java
- also cleaned up inclusion logic
- now simply looks at entity lifecycle
#5498
=> Assessment exporter now includes user comments

docs/features/attestations/README.md, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationInstanceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationPreCheckDao.java
=> Db contrib/waltz 5500 attestation docs and check fix

waltz-data/src/main/ddl/liquibase/db.changelog-1.35.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> Waltz 5471 1 35

docs/blog/_posts/2021-06-30-flow-diagrams.md, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddOverlayGroupEntrySubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddPhysicalFlowSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/ContextPanel.svelte, waltz-ng/client/system/svelte/ratings-schemes/SymbolPicker.svelte, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FlowDiagramEndpoint.java
=> Db contrib/waltz 5455 flow diagrams anon visibility edit buttons small tweaks

waltz-model/src/main/java/com/khartec/waltz/model/authoritativesource/AuthoritativeSource.java, waltz-ng/client/auth-sources/components/auth-source-summary-list/AuthSourceDetail.svelte, waltz-ng/client/auth-sources/components/svelte/AuthSourceOverview.svelte, waltz-ng/client/auth-sources/components/table/auth-sources-table.js
=> Auth source linking

waltz-data/src/main/java/com/khartec/waltz/data/InlineSelectFieldFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramEntityDao.java, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddRelatedDataTypeSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntitiesPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntitiesViewTable.svelte, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Db contrib/waltz 5517 flow diagram datatype relationships

waltz-model/src/main/java/com/khartec/waltz/model/logical_flow/LogicalFlow.java, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddRelatedMeasurableSubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntitiesViewTable.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntityAddFlowsPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntityAddNodesPanel.svelte, waltz-ng/client/svelte-stores/change-initiative-store.js, waltz-ng/client/svelte-stores/data-type-store.js, waltz-ng/client/svelte-stores/logical-flow-store.js, waltz-ng/client/svelte-stores/measurables.js
=> Db contrib/waltz 5517 datatype rel entities rework

waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AddOverlayGroupEntrySubPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntitiesViewTable.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntityAddFlowsPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/RelatedEntityAddNodesPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/group-utils.js
=> Db contrib/waltz 5517 related measurbles add to overlay

waltz-jobs/src/main/java/com/khartec/waltz/jobs/tools/diagrams/FlowDiagramFromMeasurableGenerator.java, waltz-ng/client/flow-diagram/components/diagram-svelte/store/layout.js, waltz-ng/client/flow-diagram/components/diagram-svelte/store/model.js, waltz-ng/test/flow-diagram/layout-store-test.js, waltz-ng/test/flow-diagram/model-store-test.js, waltz-ng/test/flow-diagram/overlay-store-test.js
=> Db contrib/ctctowaltz 2273 flow diag tests 5521

waltz-data/src/main/ddl/liquibase/db.changelog-1.35.xml
=> Waltz 5453 custom auth rating data change

waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-ng/client/auth-sources/components/auth-source-summary-list/auth-source-summary-list.js, waltz-ng/client/auth-sources/components/svelte/AuthSourceOverview.svelte, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java
=> Waltz 5453 custom auth ratings

waltz-ng/client/common/components/boolean-renderer.html, waltz-ng/client/common/components/boolean-renderer.js
- can be overridden if needed (see `trueLabel` etc)
#5533
=> Surveys use labels as well as tick/cross icons

waltz-ng/client/auth-sources/components/auth-source-summary-list/auth-source-summary-list.html, waltz-ng/client/auth-sources/components/section/auth-sources-section.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/AuthoritativeSourceExtractor.java
=> Waltz 5529 auth src export

docs/blog/_posts/2021-07-22-rel-1-35.md, docs/blog/_posts/2021-07-23-survey-sql.md
=> Waltz 5547 survey blog

waltz-ng/client/auth-sources/components/svelte/AuthRatingLegend.svelte
=> Db contrib/ctctowaltz 2283 base 1.36 change log 5545

waltz-model/src/main/java/com/khartec/waltz/model/EntityReference.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroup.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/change_initiative/ChangeInitiative.java, waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_data_element/LogicalDataElement.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable/Measurable.java, waltz-model/src/main/java/com/khartec/waltz/model/orgunit/OrganisationalUnit.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification/PhysicalSpecification.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerInformation.java, waltz-model/src/main/java/com/khartec/waltz/model/software_catalog/SoftwarePackage.java, waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/common/components/entity-link/entity-icon-label.js, waltz-ng/client/common/components/entity-link/entity-link.html, waltz-ng/client/common/components/entity-link/entity-link.js, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.html
=> Show external id in nav search results

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/PersonApplicationExtractor.java
=> Db contrib/ctctowaltz 2291 person app exporter fix 5561

waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationInstanceDao.java, waltz-model/src/main/java/com/khartec/waltz/model/attestation/AttestationInstance.java, waltz-ng/client/attestation/attestation-instance-list-user-view.html, waltz-ng/client/attestation/attestation-instance-list-user-view.js, waltz-ng/client/attestation/attestation-run-list.js, waltz-ng/client/widgets/page-header/page-header.scss
- showing incorrect last attested by dates
- wasn't indexing the attested kind/id properly
#5569
=> Attestation Dates fix

waltz-data/src/main/java/com/khartec/waltz/data/datatype_decorator/LogicalFlowDecoratorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-ng/client/attestation/attestation-run-create.html, waltz-service/src/main/java/com/khartec/waltz/service/data_type/DataTypeDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification/PhysicalSpecificationService.java
=> Fixing: Propagating phys spec datatypes to logical flows

waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js
- coloring arcs on flow diagram were applied on the enter cycle
- however, colors not arriving till later so need re-applying on the update cycle.
#5572
=> Fixing: timing/rendering issue with source and target

waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js
=> Source and Target graph not checking entity kind in changesets

docs/blog/_posts/2021-08-19-nav-user.md, waltz-ng/client/dynamic-section/section-store.js, waltz-ng/client/navbar/svelte-page.js
=> Blog: Sidebar

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java
=> Fixing flow selector for actor page

waltz-ng/client/databases/routes.js, waltz-ng/client/svelte-stores/toast-store.js
=> Db contrib/ctctowaltz 2303 database redirect ext id error toast 5565

waltz-ng/client/involvement/components/sub-section/key-people-sub-section.html, waltz-ng/client/involvement/components/sub-section/key-people-sub-section.js
=> Db contrib/ctctowaltz 2303 key people inv section open 5566

waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationInstanceDao.java, waltz-model/src/main/java/com/khartec/waltz/model/attestation/LatestMeasurableAttestationInfo.java, waltz-ng/client/attestation/components/section/attestation-section.html, waltz-ng/client/attestation/components/section/attestation-section.js, waltz-ng/client/attestation/components/svelte/MeasurableAttestationPanel.svelte, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/svelte-stores/attestation-instance-store.js, waltz-ng/client/svelte-stores/attestation-run-store.js, waltz-ng/client/svelte-stores/measurable-category-store.js, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationInstanceService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttestationInstanceEndpoint.java
=> Db contrib/ctctowaltz 2304 attestation section viewpoint tab 5601

waltz-ng/client/actor/components/basic-actor-selector.js
=> Db contrib/ctctowaltz 2300 actor cancel button missing 5607

waltz-ng/client/navbar/Sidebar.svelte, waltz-ng/client/navbar/navigation.scss, waltz-ng/client/navbar/svelte-page.html, waltz-ng/client/widgets/icon.js
=> Resizing sidebar expansion toggle

waltz-ng/client/flow-classification-rule/components/table/flow-classification-rules-table.js
=> Link from flow classification table to view page

waltz-ng/client/common/svelte/EntityLabel.svelte, waltz-ng/client/common/svelte/LastEdited.svelte, waltz-ng/client/flow-classification-rule/components/svelte/FlowClassificationRuleOverview.svelte, waltz-ng/client/flow-classification-rule/pages/view/flow-classification-rule-view.html, waltz-ng/client/flow-classification-rule/pages/view/flow-classification-rule-view.js, waltz-ng/client/svelte-stores/flow-classification-store.js
=> Fixing navigation error if entity not found

waltz-ng/client/complexity/components/graph/complexity-graph.js, waltz-ng/client/cost/components/graph/entity-costs-graph.js, waltz-ng/client/flow-diagram/components/diagram-svelte/FlowDiagram.svelte, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.html, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/widgets/section.scss
=> Main section not reflowing when sidebar state changes.

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.html
=> Performance improvements

waltz-ng/client/common/svelte/EntityLink.svelte, waltz-ng/client/flow-classification-rule/components/svelte/FlowClassificationRuleOverview.svelte
=> Fixing error on non-existent flow classification rule pages

waltz-ng/client/attestation/components/section/attestation-section.js
=> Rewording attestation confirmation message

waltz-common/src/main/java/com/khartec/waltz/common/SetUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/SetUtilities_complement.java
=> Adding Complement Method

waltz-common/src/main/java/com/khartec/waltz/common/ExcludeFromIntegrationTesting.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.7.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/BaseInMemoryIntegrationTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/DIInMemoryTestConfiguration.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/service/LogicalFlowServiceTest.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_flow/LogicalFlow.java, waltz-service/src/main/java/com/khartec/waltz/service/change_unit/ChangeUnitViewService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/scheduled_job/ScheduledJobService.java
=> Db contrib/ctctowaltz 2311 log flow service int tests 5641

waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/StringUtilities_capitalise.java, waltz-common/src/test/java/com/khartec/waltz/common/StringUtilities_length.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.37.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/allocation_scheme/AllocationSchemeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/allocation_scheme/AllocationScheme.java, waltz-ng/package-lock.json
=> Waltz 5570 capitalise test

waltz-data/src/main/ddl/liquibase/db.changelog-1.37.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/com/khartec/waltz/data/allocation_scheme/AllocationSchemeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/allocation_scheme/AllocationScheme.java
This reverts commit d1097a534738e3d77dfe6cf2d7e9ad8c6b05f6d5.
=> Revert "Revert "Adding external id to allocation scheme""

waltz-data/src/main/ddl/liquibase/db.changelog-1.37.xml
=> Waltz 5650 process diag ddl

waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.js, waltz-ng/client/data-flow/components/svelte/FlowContextPanel.svelte, waltz-ng/client/data-flow/components/svelte/FlowDecoratorExplorerPanel.svelte, waltz-ng/client/navbar/svelte-page.js, waltz-ng/client/svelte-stores/toast-store.js
- resized
- notification that it's beta
- removed beta _restriction_
- reordered tabs
bonus:
- toast for IE stays on screen a bit longer
#5657
=> Flow Decorator Explorer Panel

waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.html, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js
=> Measurable rating export includes allocations

waltz-common/src/main/java/com/khartec/waltz/common/OptionalUtilities.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/BaseInMemoryIntegrationTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/helpers/InvolvementHelper.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/helpers/NameHelper.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/helpers/PersonHelper.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/service/AppGroupServiceTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/service/AttestationServiceTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/service/BookmarkServiceTest.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/service/LogicalFlowServiceTest.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/generators/DatabaseGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/attestation/AttestEntityCommand.java
Attestation integration test
#5667
=> Attestation integration test

waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/DIInMemoryTestConfiguration.java, waltz-integration-test/src/test/resources/integration-test.properties
=> Fixing github actions

waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/helpers/ChangeLogHelper.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/service/SurveyTemplateServiceTest.java
=>  Testing: survey template service tests

waltz-data/src/main/java/com/khartec/waltz/data/assessment_definition/AssessmentDefinitionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-data/src/main/java/com/khartec/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/helpers/RatingSchemeHelper.java, waltz-integration-test/src/test/java/com/khartec/waltz/integration_test/inmem/story/AssessmentsTest.java, waltz-model/src/main/java/com/khartec/waltz/model/MandatoryDescriptionProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/rating/RatingSchemeItem.java, waltz-service/src/main/java/com/khartec/waltz/service/assessment_definition/AssessmentDefinitionService.java, waltz-service/src/main/java/com/khartec/waltz/service/assessment_rating/AssessmentRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/rating_scheme/RatingSchemeService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssessmentDefinitionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/RatingSchemeEndpoint.java
=> Waltz 5745 survey template

docs/blog/_posts/2021-11-05-deployment.md, docs/blog/_posts/2021-11-05-package-rename.md
- package rename
- deployment talk
#blog
=> Blog posts

waltz-data/src/main/java/org/finos/waltz/data/involvement/InvolvementDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyRunDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/helpers/NameHelper.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/helpers/PersonHelper.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/helpers/SurveyTemplateHelper.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/SurveyRunServiceTest.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/SurveyTemplateServiceTest.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/SurveyRunGenerator.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/SurveyHarness.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyRunCreateCommand.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyRunService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyTemplateService.java
Fix to InvolvementDao hidden amongst integration test change.
#5760
=> Prevent run creation from issuing to inactive people

docs/blog/_posts/2021-11-05-deployment.md, docs/blog/_posts/2021-11-05-package-rename.md, docs/design/draft/workflows/workflows.md, waltz-data/src/main/ddl/liquibase/db.changelog-1.39.xml, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceOwnerDao.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstance.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceOwner.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceOwnerCreateCommand.java, waltz-ng/client/data-flow/components/svelte/ClientContextPanel.svelte, waltz-ng/client/data-flow/components/svelte/FlowDetailContextPanel.svelte, waltz-ng/client/data-flow/components/svelte/PhysicalFlowDetailTable.svelte, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/survey-utils.js, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SurveyInstanceEndpoint.java
=> Db contrib/ctctowaltz 2363 survey instance owner table 5678

waltz-data/src/main/java/org/finos/waltz/data/access_log/AccessLogDao.java, waltz-data/src/main/java/org/finos/waltz/data/actor/ActorSearchDao.java, waltz-data/src/main/java/org/finos/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/org/finos/waltz/data/assessment_definition/AssessmentDefinitionDao.java, waltz-data/src/main/java/org/finos/waltz/data/asset_cost/AssetCostDao.java, waltz-data/src/main/java/org/finos/waltz/data/bookmark/BookmarkDao.java, waltz-data/src/main/java/org/finos/waltz/data/change_set/ChangeSetDao.java, waltz-data/src/main/java/org/finos/waltz/data/change_unit/ChangeUnitDao.java, waltz-data/src/main/java/org/finos/waltz/data/client_cache_key/ClientCacheKeyDao.java, waltz-data/src/main/java/org/finos/waltz/data/end_user_app/EndUserAppIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/entity_hierarchy/EntityHierarchyDao.java, waltz-data/src/main/java/org/finos/waltz/data/entity_named_note/EntityNamedNoteTypeDao.java, waltz-data/src/main/java/org/finos/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-data/src/main/java/org/finos/waltz/data/entity_statistic/EntityStatisticDao.java, waltz-data/src/main/java/org/finos/waltz/data/external_identifier/ExternalIdentifierDao.java, waltz-data/src/main/java/org/finos/waltz/data/flow_classification_rule/FlowClassificationRuleDao.java, waltz-data/src/main/java/org/finos/waltz/data/flow_diagram/FlowDiagramOverlayGroupDao.java, waltz-data/src/main/java/org/finos/waltz/data/involvement/InvolvementDao.java, waltz-data/src/main/java/org/finos/waltz/data/licence/LicenceDao.java, waltz-data/src/main/java/org/finos/waltz/data/logical_data_element/LogicalDataElementDao.java, waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/SurveyHarness.java, waltz-web/pom.xml
=> Build fix and basic cleanups

waltz-ng/client/common/svelte/Icon.svelte, waltz-ng/client/survey/components/svelte/SurveyApproverInfoPanel.svelte, waltz-ng/client/survey/components/svelte/SurveyRecipientInfoPanel.svelte, waltz-ng/client/survey/components/svelte/UserSurveyListPanel.svelte
=> Db contrib/ctctowaltz 2363 survey user list tweaks 5768

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.39.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.6.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceOwnerDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceRecipientDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyViewDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/SurveyRunServiceTest.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/SurveyRunGenerator.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/SurveyHarness.java, waltz-model/src/main/java/org/finos/waltz/model/survey/InstancesAndRecipientsCreateCommand.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstance.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceCreateCommand.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyRunCreateCommand.java, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.js, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/components/survey-run-create-general.js, waltz-ng/client/survey/components/survey-run-create-recipient.js, waltz-ng/client/survey/components/survey-run-create-store.js, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/services/survey-run-store.js, waltz-ng/client/survey/survey-run-create.html, waltz-ng/client/survey/survey-run-create.js, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SurveyInstanceEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SurveyRunEndpoint.java
=> Db contrib/ctctowaltz 2363 approval due date 5776

waltz-data/src/main/ddl/liquibase/db.changelog-1.39.xml, waltz-ng/client/survey/survey-utils.js
=> Adding is_default and approval due date to survey runs

waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyViewDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/SurveyRunServiceTest.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstance.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstancePermissions.java, waltz-model/src/test/java/org/finos/waltz/model/survey/SurveyInstanceStateMachineTest.java, waltz-ng/client/common/svelte/ViewLink.svelte, waltz-ng/client/common/svelte/info-panels/EntityInfoPanel.svelte, waltz-ng/client/common/svelte/info-panels/SurveyInstanceInfoPanel.svelte, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/playpen/1/survey-detail-store.js, waltz-ng/client/survey/components/instance-summary/survey-instance-summary.html, waltz-ng/client/survey/components/svelte/SurveyApproverInfoPanel.svelte, waltz-ng/client/survey/components/svelte/SurveyRecipientInfoPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewer.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewerPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/survey-detail-store.js, waltz-ng/client/survey/components/svelte/inline-panel/survey-viewer-utils.js, waltz-ng/client/survey/components/svelte/user-survey-store.js, waltz-ng/client/survey/survey-actions.js, waltz-ng/client/survey/survey-instance-list-user-view.js, waltz-ng/client/svelte-stores/survey-instance-store.js, waltz-ng/client/svelte-stores/survey-question-store.js, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceViewService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SurveyInstanceViewEndpoint.java
=> Db contrib/waltz 5778 survey context panel inline view

.github/ISSUE_TEMPLATE/Meeting.md
This PR adds the Waltz meeting template `Meeting.md` to `.github/ISSUE_TEMPLATE` to provide a meeting structure and the meeting details for Waltz project calls happening every second Thursday of each month.
```
---
name: 🤝 Waltz Meeting Agenda
about: To track Waltz meeting agenda and attendance
---
Thursday DD MMM yyyy - 10am ET / 3pm UK
Occurs the second Thursday of every month 
| Name | Firm | Comment |
|:---------|:------------|:-----|
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).
- …
```
=> Add Waltz FINOS Meeting Template

docs/plans/2021-year-end.adoc
=> Waltz 5792 end of year

waltz-ng/client/common/svelte/info-panels/PersonInfoPanel.svelte, waltz-ng/client/report-grid/components/svelte/ReportGridEditor.svelte, waltz-ng/client/report-grid/components/svelte/ReportGridOverview.svelte, waltz-ng/client/report-grid/components/svelte/ReportGridPicker.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDefinitionEditPanel.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDetailsEditor.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ReportGridColumnSummary.svelte, waltz-ng/client/report-grid/components/svelte/person-edit-panel/AddNewSubscriberPanel.svelte, waltz-ng/client/report-grid/components/svelte/person-edit-panel/ReportGridPersonEditPanel.svelte
=> Db contrib/waltz 5682 report grid editor tweaks

waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/SurveyInstanceHarness.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceAction.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceActionCompletionRequirement.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceFormDetails.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstancePermissions.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceStateTransition.java, waltz-model/src/main/java/org/finos/waltz/model/utils/IdUtilities.java, waltz-ng/client/common/svelte/ViewLink.svelte, waltz-ng/client/common/svelte/info-panels/SurveyInstanceInfoPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyActions.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewer.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewerContextPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/survey-detail-store.js, waltz-ng/client/svelte-stores/survey-instance-view-store.js, waltz-ng/client/system/svelte/settings/SettingsPanel.svelte, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceEvaluator.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceUtilities.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceViewService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyQuestionService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/inclusion_evaluator/QuestionBasePredicateNamespace.java, waltz-service/src/main/java/org/finos/waltz/service/survey/inclusion_evaluator/QuestionPredicateEvaluator.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SurveyInstanceViewEndpoint.java
=> Waltz 5805 survey action completion reqd

waltz-model/src/main/java/org/finos/waltz/model/changelog/ChangeLogComment.java, waltz-ng/client/common/svelte/SubSection.svelte, waltz-ng/client/common/svelte/info-panels/EndUserApplicationInfoPanel.svelte, waltz-ng/client/svelte-stores/end-user-application-store.js, waltz-ng/client/system/euda-list-view.html, waltz-ng/client/system/euda-list-view.js, waltz-ng/client/system/svelte/euda-list/EudaListPanel.svelte, waltz-service/src/main/java/org/finos/waltz/service/end_user_app/EndUserAppService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/EndUserAppEndpoint.java
=> Db contrib/waltz 5802 comment on change log promotion

waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyViewDao.java, waltz-ng/client/common/svelte/Markdown.svelte, waltz-ng/client/common/svelte/StaticPanel.svelte, waltz-ng/client/common/svelte/StaticPanels.svelte, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/components/svelte/SurveyApproverInfoPanel.svelte, waltz-ng/client/survey/components/svelte/SurveyRecipientInfoPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyActions.svelte, waltz-ng/client/svelte-stores/static-panel-store.js
=> Db contrib/waltz 5808 survey small enhancements

waltz-data/src/main/ddl/liquibase/db.changelog-1.39.xml
=> Adding created_at to app_group_entry

waltz-model/src/main/java/org/finos/waltz/model/survey/CopySurveyResponsesCommand.java
- adding Command marker interface to keep archunit happy
#5818
=> Survey copy

waltz-data/src/main/ddl/liquibase/db.changelog-1.39.xml, waltz-data/src/main/java/org/finos/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/ReportGridServiceTest.java, waltz-model/src/main/java/org/finos/waltz/model/app_group/AppGroupEntry.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKind.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKindCreateCommand.java, waltz-ng/client/report-grid/components/svelte/ReportGridControlPanel.svelte, waltz-ng/client/report-grid/components/svelte/ReportGridOverview.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/EntitySelector.svelte, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/ReportGridEndpoint.java
=> Db contrib/waltz 5803 involvement kind ext

docs/features/configuration/settings.md, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.js, waltz-ng/client/navbar/directives/navbar-profile.html, waltz-ng/client/navbar/directives/navbar-profile.js, waltz-ng/client/system/named-settings.js, waltz-ng/package-lock.json, waltz-ng/package.json
=> Db contrib/waltz 5832 disable roadmaps

waltz-data/src/main/ddl/liquibase/db.changelog-1.39.xml
=> Involvement Kind ext id

waltz-ng/client/entity-diagrams/components/section/entity-diagrams-section.html, waltz-ng/client/entity-diagrams/components/section/entity-diagrams-section.js
- render as proper links (allowing them to be opened in new tabs)
#5748
=> Diagram list

waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyViewDao.java, waltz-ng/client/survey/components/svelte/inline-panel/SurveyInstanceVersionPicker.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewerContextPanel.svelte
=> Db contrib/waltz 5679 user list view obsolete templates

waltz-data/src/main/java/org/finos/waltz/data/application/ApplicationDao.java, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.html, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.js, waltz-ng/client/assessments/components/bulk-assessment-rating-selector/bulk-assessment-rating-selector.html, waltz-ng/client/assessments/components/bulk-assessment-rating-selector/bulk-assessment-rating-selector.js, waltz-ng/client/common/entity-utils.js
=> Db contrib/waltz 5839 allow removed apps in bulk ops

waltz-ng/client/common/string-utils.js, waltz-ng/client/common/svelte/Grid.svelte, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.js, waltz-ng/client/report-grid/components/svelte/ReportGridOverview.svelte, waltz-ng/client/report-grid/components/svelte/ReportGridPicker.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDefinitionEditPanel.svelte, waltz-ng/client/report-grid/components/svelte/pickers/AssessmentDefinitionPicker.svelte, waltz-ng/client/report-grid/components/svelte/pickers/CostKindPicker.svelte, waltz-ng/client/report-grid/components/svelte/pickers/InvolvementPicker.svelte, waltz-ng/client/report-grid/components/svelte/pickers/SurveyQuestionPicker.svelte, waltz-ng/client/svelte-stores/report-grid-store.js
=> Db contrib/waltz 5829 grid removal

waltz-ng/client/common/components/date-picker/date-picker-form-input.js, waltz-ng/client/survey/components/survey-section.html, waltz-ng/client/survey/components/survey-section.js, waltz-ng/client/survey/components/svelte/inline-panel/SurveyActions.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewer.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewerContextPanel.svelte, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.js, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyRunService.java
=> Waltz 5850 survey bug

waltz-data/src/main/java/org/finos/waltz/data/attestation/AttestationInstanceDao.java, waltz-ng/client/system/system-admin-list.html
=> Fix archunit

.github/workflows/meetings.yml, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/data-flow/components/svelte/FlowContextPanel.svelte, waltz-ng/client/data-flow/components/svelte/FlowDetailContextPanel.svelte, waltz-ng/client/data-flow/components/svelte/PhysicalFlowDetailTable.svelte
=> Db contrib/waltz 5737 flow viz error navigation

.github/workflows/meetings.yml, waltz-data/src/main/java/org/finos/waltz/data/attestation/AttestationInstanceDao.java
=> Db contrib/waltz 5854 reassign recipients for all db

waltz-service/src/test/java/org/finos/waltz/service/workflow/side_effect/SideEffectTest.java
=> Migrating junit 4.x test to 5.x

waltz-ng/client/common/svelte/info-panels/SurveyInstanceInfoPanel.svelte, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Db contrib/waltz 5863 survey fix export performance

waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java
=> Db contrib/waltz 5876 redacted costs report grid

waltz-ng/client/survey/components/svelte/UserSurveyListPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/BooleanResponseRenderer.svelte, waltz-ng/client/survey/components/svelte/inline-panel/CopySurveyResponsesPanel.svelte
=> Db contrib/waltz 5880 search surveys copy response

waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.html, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ReportGridColumnSummary.svelte, waltz-ng/client/report-grid/components/svelte/report-grid-utils.js, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java
=> Db contrib/waltz 5883 report grid small fixes

waltz-data/src/main/java/org/finos/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionEditor.svelte, waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionsAdminView.svelte, waltz-ng/client/system/svelte/ratings-schemes/RatingSchemesAdminView.svelte
=> Db contrib/waltz 5898 rating schem item changes not saved

waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Db contrib/waltz 5894 survey not started export fix

waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceOwnerDao.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceService.java
=> Arguments have been accidently transposed

waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyTemplateDao.java, waltz-ng/client/common/services/core-api-utils.js, waltz-ng/client/common/svelte/info-panels/MeasurableInfoPanel.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDefinitionHeader.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDetailsEditor.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ReportGridColumnSummary.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewer.svelte, waltz-ng/client/survey/index.js, waltz-ng/client/survey/services/survey-instance-view-store.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.js, waltz-ng/client/svelte-stores/assessment-definition.js, waltz-ng/client/svelte-stores/measurable-category-store.js, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SurveyTemplateEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/TechnologyEOLServerExtractor.java
=> Db contrib/waltz 5913 add country to server export

waltz-data/src/main/java/org/finos/waltz/data/involvement/InvolvementDao.java, waltz-ng/client/involvement/services/involvement-store.js, waltz-ng/client/system/orphans-view.js, waltz-service/src/main/java/org/finos/waltz/service/involvement/InvolvementService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/InvolvementEndpoint.java
=> Fixing arch unit failures caused by `find*` methods returning `int`

waltz-ng/client/data-types/pages/home/data-type-home.html, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/DataTypeExtractor.java
=> Data type extractor

waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyViewDao.java
=> Db contrib/waltz 5930 survey approval list ignores owning roles

waltz-data/src/main/ddl/liquibase/db.changelog-1.40.xml, waltz-ng/package-lock.json
- application_group
- application_group_entry
- application_group_ou_entry
- application_group_member
- assessment_definition
- assessment_rating
#5935
=> Added schema docs for:

waltz-service/src/main/java/org/finos/waltz/service/entity_hierarchy/EntityHierarchyService.java
=> Fixing hier

waltz-data/src/main/java/org/finos/waltz/data/assessment_rating/AssessmentRatingDao.java, waltz-ng/client/assessments/pages/view/assessment-definition-view.js, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/AssessmentRatingExtractor.java
=> Db contrib/waltz 5944 assessment bulk export

waltz-data/src/main/ddl/liquibase/db.changelog-1.40.xml, waltz-data/src/test/java/org/finos/waltz/data/SearchUtilities_RelevancyComparatorTest.java, waltz-web/pom.xml
=> Db contrib/waltz 5492 bundle war resources

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/dao/MeasurableRatingDaoTest.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/helpers/PersonHelper.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/PermissionGroupServiceTest.java, waltz-model/src/main/java/org/finos/waltz/model/permission_group/CheckPermissionCommand.java, waltz-service/src/main/java/org/finos/waltz/service/permission/PermissionGroupDao.java, waltz-service/src/main/java/org/finos/waltz/service/permission/PermissionGroupService.java
=> Enhanced permissions

waltz-data/src/main/ddl/liquibase/db.changelog-1.40.xml, waltz-data/src/main/java/org/finos/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKind.java, waltz-ng/client/entity/components/entity-involvement-editor/entity-involvement-editor.js, waltz-ng/client/involvement/components/involved-people-section.js, waltz-service/src/main/java/org/finos/waltz/service/involvement/InvolvementService.java
=> Allow some involvement kinds to be non-user-selectable

waltz-service/src/main/java/org/finos/waltz/service/permission/PermissionGroupDao.java, waltz-service/src/main/java/org/finos/waltz/service/permission/PermissionGroupService.java
=> Fix failing archunit test

waltz-data/src/main/java/org/finos/waltz/data/notification/NotificationDao.java, waltz-ng/client/survey/components/svelte/SurveyApproverInfoPanel.svelte, waltz-ng/client/survey/components/svelte/SurveyRecipientInfoPanel.svelte
=> Db contrib/waltz 5960 notification survey counts

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/AttestationServiceTest.java, waltz-service/src/main/java/org/finos/waltz/service/attestation/AttestationInstanceService.java
- covered by PermissionGroupTests
#5659
=> Removing redundant failing test

waltz-data/src/main/java/org/finos/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-ng/client/physical-specifications/components/overview/physical-specification-overview.html, waltz-ng/client/physical-specifications/components/overview/physical-specification-overview.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/physical-specifications/services/physical-specification-store.js, waltz-service/src/main/java/org/finos/waltz/service/changelog/ChangeLogService.java, waltz-service/src/main/java/org/finos/waltz/service/physical_specification/PhysicalSpecificationService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/PhysicalSpecificationEndpoint.java
-- removing the physical flow change log merge of logical and specs. Should be written to each entity individually.
#4406
=> Update description and format on specs

waltz-data/src/main/ddl/liquibase/db.changelog-1.41.xml
=> Db contrib/waltz 5935 table remarks

waltz-data/src/main/ddl/liquibase/db.changelog-1.41.xml, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/AttestationInstanceEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/HeaderBasedAuthenticationFilter.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/SurveyInstanceExtractor.java
=> Db contrib/waltz 5979 auth override

waltz-ng/client/app-groups/pages/edit/app-group-edit.html, waltz-ng/client/app-groups/pages/edit/app-group-edit.js, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.html, waltz-ng/client/applications/components/bulk-application-selector/bulk-application-selector.js
=> Db contrib/waltz 5995 bulk add apps to group not found error

waltz-data/src/main/ddl/liquibase/db.changelog-1.41.xml, waltz-model/src/main/java/org/finos/waltz/model/enum_value/EnumValueKind.java, waltz-ng/client/data-flow/components/application-flow-summary-pane/application-flow-summary-pane.html, waltz-ng/client/data-flow/components/application-flow-summary-pane/application-flow-summary-pane.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/physical-flow/physical-flow-table-utilities.js, waltz-ng/client/physical-flows/components/flow-table/physical-flow-table.js, waltz-ng/client/physical-flows/components/physical-flow-and-specification-detail/physical-flow-and-specification-detail.html, waltz-ng/client/physical-flows/components/physical-flow-section/physical-flow-section.js, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js, waltz-ng/client/source-data-rating/components/overlay/source-data-overlay.html, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/PhysicalFlowExtractor.java
=> Db contrib/waltz 5998 remove freshness indicator

waltz-ng/client/change-log/components/breakdown-table/change-breakdown-table.html, waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/change-log/components/summaries-panel/change-summaries-panel.html, waltz-ng/client/common/svelte/calendar-heatmap/CalendarHeatmap.svelte, waltz-ng/client/common/svelte/calendar-heatmap/CalendarHeatmapControlPanel.svelte, waltz-ng/client/common/svelte/calendar-heatmap/Month.svelte
- fading month titles
- month highlight
- clearer text labels
#6002
=> UI Tweaks to calendar change log

waltz-ng/client/widgets/page-header/page-header.html
Responding to issue #5988 increasing truncation to 100 for page header.
=> Updated truncateMiddle from 50 to 100

waltz-data/src/main/java/org/finos/waltz/data/measurable_rating_planned_decommission/MeasurableRatingPlannedDecommissionDao.java, waltz-service/src/main/java/org/finos/waltz/service/survey/inclusion_evaluator/QuestionAppPredicateNamespace.java, waltz-service/src/main/java/org/finos/waltz/service/survey/inclusion_evaluator/QuestionChangeInitiativePredicateNamespace.java, waltz-service/src/main/java/org/finos/waltz/service/survey/inclusion_evaluator/QuestionEntityPredicateNamespace.java
=> Db contrib/waltz 5984 survey predicates app kind lifecycle phase

waltz-data/src/main/ddl/liquibase/db.changelog-1.41.xml
=> waltz-5998-remove-drop-column-freshness-indicator

waltz-data/src/main/ddl/liquibase/db.changelog-1.41.xml
=> Revert "waltz-5998-remove-drop-column-freshness-indicator"

README.md, waltz-ng/client/actor/components/svelte/ActorListView.svelte, waltz-ng/client/actor/index.js, waltz-ng/client/actor/pages/actor-view/actor-view.html, waltz-ng/client/actor/pages/list-view/actor-list-view.html, waltz-ng/client/actor/pages/list-view/actor-list-view.js, waltz-ng/client/common/svelte/DataExtractLink.svelte, waltz-ng/client/navbar/directives/navbar-profile.html, waltz-ng/client/svelte-stores/actor-store.js, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ActorExtractor.java
=> Db contrib/waltz 6021 actors view exportable

waltz-data/src/main/java/org/finos/waltz/data/flow_classification_rule/FlowClassificationRuleDao.java, waltz-service/src/main/java/org/finos/waltz/service/entity_hierarchy/EntityHierarchyService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/PhysicalFlowExtractor.java
- bonus: small fixes on hierarchy rebuilder
- bonus: fixing flow classification rule query
#6065
=> Fixing flow export

waltz-common/src/main/java/org/finos/waltz/common/exception/ModifyingReadOnlyRecordException.java, waltz-common/src/main/java/org/finos/waltz/common/exception/NotFoundException.java, waltz-ng/client/physical-flows/components/flow-editor/physical-flow-editor.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/widgets/editable-enum/editable-enum.html, waltz-ng/client/widgets/editable-enum/editable-enum.js, waltz-ng/client/widgets/editable-field.html, waltz-ng/client/widgets/editable-field.js, waltz-service/src/main/java/org/finos/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Db contrib/waltz 6070 readonly phys flows

waltz-ng/client/common/svelte/EntitySearchSelector.svelte, waltz-ng/package-lock.json, waltz-ng/package.json
=> Db contrib/waltz 6072 email search

pom.xml, waltz-data/src/main/java/org/finos/waltz/data/flow_classification_rule/FlowClassificationRuleDao.java, waltz-service/src/main/java/org/finos/waltz/service/entity_hierarchy/EntityHierarchyService.java
- ArchUnit
- Hikari
- Immutables
- Jackson
- Logback
- POI
- Spring
- bonus: small fixes on hierarchy rebuilder
- bonus: fixing flow classification rule query
#6063
=> Java lib upgrades

waltz-common/src/main/java/org/finos/waltz/common/MapUtilities.java, waltz-common/src/main/java/org/finos/waltz/common/OptionalUtilities.java, waltz-common/src/main/java/org/finos/waltz/common/StringUtilities.java, waltz-common/src/test/java/org/finos/waltz/common/MapUtilities_groupAndThenTest.java, waltz-common/src/test/java/org/finos/waltz/common/StringUtilities_mkPathTest.java, waltz-data/src/main/java/org/finos/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-data/src/main/java/org/finos/waltz/data/measurable_category/MeasurableCategoryAlignmentViewDao.java, waltz-model/src/main/java/org/finos/waltz/model/CommentProvider.java, waltz-model/src/main/java/org/finos/waltz/model/DescriptionProvider.java, waltz-model/src/main/java/org/finos/waltz/model/EntityLinkUtilities.java, waltz-model/src/main/java/org/finos/waltz/model/MandatoryDescriptionProvider.java, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleResolver.java
- groupAndThen
- @Value on fields
- StringUtilities.mkPath
#6032
=> Cleaning code warnings and deprecations

waltz-data/src/main/ddl/liquibase/db.changelog-1.42.xml, waltz-model/src/main/java/org/finos/waltz/model/Operation.java
=> Locked ratings

waltz-data/src/main/java/org/finos/waltz/data/permission/PermissionGroupDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/PermissionGroupServiceTest.java, waltz-model/src/main/java/org/finos/waltz/model/attestation/UserAttestationPermission.java, waltz-ng/client/attestation/components/section/attestation-section.js, waltz-ng/client/attestation/components/svelte/MeasurableAttestationSubPanel.svelte, waltz-ng/client/permission-group/services/permission-group-store.js, waltz-service/src/main/java/org/finos/waltz/service/custom_environment/CustomEnvironmentService.java, waltz-service/src/main/java/org/finos/waltz/service/custom_environment/CustomEnvironmentUsageService.java, waltz-service/src/main/java/org/finos/waltz/service/permission/PermissionGroupService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/PermissionGroupEndpoint.java
- small bug fix for never attested categories
#6074
=> Permissions code cleanup

waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Db contrib/waltz 6061 measurable ratings permissions fix

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/helpers/UserHelper.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/story/AssessmentsTest.java, waltz-service/src/main/java/org/finos/waltz/service/assessment_rating/AssessmentRatingService.java
- creating person, user and role records to allow user to have sufficient priveleges to create assessments.
#6114
=> Fixing broken integration test

README.md
=> Db contrib/waltz 6113 report grid intial load error

waltz-service/src/main/java/org/finos/waltz/service/aggregate_overlay_diagram/AggregateOverlayDiagramService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/AggregateOverlayDiagramEndpoint.java
=> Fixing archunit test

pom.xml, waltz-web/pom.xml, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/DirectQueryBasedDataExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ExtractFormat.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/OrgUnitExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/SupportsJsonExtraction.java, waltz-web/src/main/java/org/finos/waltz/web/json/ColumnDescriptor.java, waltz-web/src/main/java/org/finos/waltz/web/json/Grid.java, waltz-web/src/test/java/org/finos/waltz/web/endpoints/extracts/OrgUnitExtractorTest.java, waltz-web/src/test/java/org/finos/waltz/web/endpoints/extracts/reportgrid/ReportGridJSONTest.java
=> Db contrib/ctowaltz 2518 add organisation extractor api

waltz-ng/client/common/svelte/Markdown.svelte, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js
=> Fixing svelte markdown table handling

.github/workflows/maven.yml, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-web/pom.xml
=> Update maven versioning and github actions to set maven release

waltz-data/src/main/java/org/finos/waltz/data/assessment_rating/AssessmentRatingDao.java, waltz-ng/client/assessments/components/editor/AssessmentEditorView.svelte, waltz-ng/client/assessments/components/list/AssessmentRatingList.svelte, waltz-ng/client/assessments/components/list/AssessmentRatingListGroup.svelte, waltz-ng/client/assessments/components/section/assessment-rating-section.html, waltz-ng/client/assessments/components/section/assessment-rating-section.js, waltz-ng/client/common/svelte/Tooltip.svelte, waltz-ng/client/svelte-stores/assessment-definition.js, waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionEditor.svelte, waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionsAdminView.svelte, waltz-ng/client/system/svelte/assessment-definitions/assessment-definition-utils.js
=> Waltz 6164 def bug

waltz-data/src/main/ddl/liquibase/db.changelog-1.43.xml, waltz-ng/client/physical-flows/svelte/StepHeader.svelte
- registering missing enums
- bonus: making flow step headers clickable
#6167
=> Missing enums

waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/LogicalFlowDecoratorStatsEndpoint.java
=> Fixing incorrect role

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.44.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-web/pom.xml
=> Prepping 1.44

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.html, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-web/pom.xml
- endpoint had moved to use external-id's
#6175
=> Fixing report grid extraction

waltz-data/src/main/ddl/liquibase/db.changelog-1.44.xml
- without this it is impossible to register multiple attestation types
#6103
=> Adding more fields to the unique index on report_grid_col_def

waltz-data/src/main/java/org/finos/waltz/data/JooqUtilities.java, waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java, waltz-model/src/main/java/org/finos/waltz/model/report_grid/ReportGridCell.java, waltz-model/src/main/java/org/finos/waltz/model/report_grid/ReportGridColumnDefinition.java, waltz-ng/client/common/date-utils.js, waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.html, waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.js, waltz-ng/client/report-grid/components/svelte/ReportGridFilters.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDefinitionEditPanel.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/EntitySelector.svelte, waltz-ng/client/report-grid/components/svelte/pickers/AttestationPicker.svelte, waltz-ng/client/report-grid/components/svelte/pickers/EntityPicker.svelte, waltz-ng/client/report-grid/components/svelte/report-grid-store.js, waltz-ng/client/report-grid/components/svelte/report-grid-utils.js, waltz-service/src/main/java/org/finos/waltz/service/attestation/AttestationInstanceService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/ReportGridEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/reportgrid/DynamicJSONFormatter.java
=> Report grid, attestation support

waltz-data/src/main/ddl/liquibase/db.changelog-1.44.xml, waltz-data/src/main/java/org/finos/waltz/data/datatype_decorator/PhysicalSpecDecoratorDao.java, waltz-data/src/main/java/org/finos/waltz/data/scheduled_job/ScheduledJobDao.java, waltz-service/src/main/java/org/finos/waltz/service/scheduled_job/ScheduledJobService.java
=> Db contrib/waltz 6185 fix ripple data types scheduled job

waltz-common/src/main/java/org/finos/waltz/common/SetUtilities.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyQuestionDropdownEntryDao.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/tools/survey/SurveyDupe.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/tools/survey/config/SectionDupeConfig.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/tools/survey/config/SurveyDupeConfig.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/tools/survey/config/TargetSectionConfig.java, waltz-ng/client/measurable/components/tree/measurable-tree.html, waltz-ng/client/survey/components/survey-section.html, waltz-ng/client/survey/components/survey-section.js, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewer.svelte, waltz-ng/client/survey/survey-instance-response-edit.html
=> Db contrib/waltz 6203 template section dupe

waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java, waltz-ng/client/common/services/enums/entity.js, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/EntitySelector.svelte, waltz-ng/client/report-grid/components/svelte/pickers/EntityPicker.svelte, waltz-ng/client/report-grid/components/svelte/report-grid-utils.js, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java
=> Db contrib/waltz 6192 complexity scores report grid

waltz-ng/client/common/svelte/info-panels/SurveyInstanceInfoPanel.svelte, waltz-ng/client/survey/components/instance-list/survey-instance-list.html, waltz-ng/client/survey/components/instance-list/survey-instance-list.js, waltz-ng/client/survey/components/svelte/SurveyApproverInfoPanel.svelte, waltz-ng/client/survey/components/svelte/SurveyRecipientInfoPanel.svelte, waltz-ng/client/survey/services/survey-template-store.js
- was confusing if run's were given ambiguous names...
#6210
=> Survey lists show template name

waltz-ng/client/system/svelte/settings/SettingsPanel.svelte
=> Force word wrap on settings table

waltz-common/src/main/java/org/finos/waltz/common/StringUtilities.java, waltz-common/src/test/java/org/finos/waltz/common/StringUtilities_sanitizeCharactersTest.java, waltz-data/src/main/java/org/finos/waltz/data/assessment_rating/AssessmentRatingDao.java
=> Db contrib/waltz 6239 sanitize comments in assessment rating string

waltz-data/src/main/java/org/finos/waltz/data/datatype_decorator/PhysicalSpecDecoratorDao.java
=> Db contrib/waltz 6236 fix ripple data types job

waltz-model/src/main/java/org/finos/waltz/model/report_grid/FilterOperator.java, waltz-model/src/main/java/org/finos/waltz/model/report_grid/GridFilter.java, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridFilterViewService.java, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridUtilities.java, waltz-service/src/test/java/org/finos/waltz/service/report_grid/ReportGridUtilitiesTest.java
=> Db contrib/waltz 6221 add string filters to filter group population

waltz-model/src/main/java/org/finos/waltz/model/user/SystemRole.java, waltz-ng/client/system/actors-view.html, waltz-ng/client/system/actors-view.js, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/ActorEndpoint.java
=> Db contrib/waltz 6261 actor admin

waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDefinitionEditPanel.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/DerivedColumnDetailsEditor.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ReportGridColumnSummary.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/column-definition-utils.js, waltz-ng/client/survey/survey-template-edit.js, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridEvaluatorNamespace.java
=> Db contrib/waltz 6232 jexl links

waltz-ng/client/assessments/components/list/AssessmentRatingList.svelte, waltz-ng/client/common/colors.js, waltz-ng/client/playpen/4/ColorScale.svelte, waltz-ng/client/playpen/4/playpen4.html, waltz-ng/client/playpen/4/playpen4.js, waltz-ng/client/system/svelte/ratings-schemes/ColorPicker.svelte
=> Db contrib/waltz 6263 assessment search

waltz-common/pom.xml, waltz-common/src/main/java/org/finos/waltz/common/JacksonUtilities.java, waltz-data/src/main/java/org/finos/waltz/data/taxonomy_management/TaxonomyChangeDao.java, waltz-jobs/pom.xml, waltz-jobs/src/main/java/org/finos/waltz/jobs/tools/importers/licence/finos/FinosLicenceComplianceImporter.java, waltz-model/pom.xml, waltz-service/src/main/java/org/finos/waltz/service/change_unit/processors/DataTypeChangeCommandProcessor.java, waltz-web/pom.xml, waltz-web/src/main/java/org/finos/waltz/web/WebUtilities.java, waltz-web/src/test/java/org/finos/waltz/web/endpoints/extracts/OrgUnitExtractorTest.java
=> Db contrib/waltz 6117 object mapper

waltz-web/src/main/resources/spark/template/freemarker/recalculate-app-group-page.ftl
=> Fixning report grid filter group back link

waltz-common/src/main/java/org/finos/waltz/common/MapUtilities.java, waltz-ng/package.json, waltz-ng/package.json.md, waltz-ng/webpack.config.js, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridColumnCalculator.java, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridEvaluatorNamespace.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/StaticResourcesEndpoint.java
=> Db contrib/waltz 6296 report grid functions

waltz-data/src/main/ddl/liquibase/db.changelog-1.45.xml, waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/reportgrid/DynamicJSONFormatter.java
=> Db contrib/waltz 6306 grid comments export

.github/workflows/cve-scanning-node.yml
Proposing a better name for Node CVE scanning
=> Updating Node CVE scanning action name

waltz-ng/client/assessments/components/list/AssessmentRatingList.svelte, waltz-ng/client/assessments/components/list/AssessmentRatingListGroup.svelte, waltz-ng/client/bookmarks/svelte/BookmarkCategoryMenu.svelte, waltz-ng/client/common/svelte/PageHeader.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/Annotation.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/Node.svelte, waltz-ng/client/report-grid/components/svelte/ReportGridOverview.svelte, waltz-ng/client/report-grid/components/svelte/ReportGridPicker.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/DropdownPicker.svelte, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/EntitySelector.svelte, waltz-ng/package-lock.json
=> Keydown bug

waltz-ng/client/common/svelte/DropdownPicker.svelte, waltz-ng/client/common/svelte/MiniActions.svelte, waltz-ng/client/common/svelte/SearchInput.svelte, waltz-ng/client/common/svelte/calendar-heatmap/CalendarHeatmap.svelte, waltz-ng/client/common/svelte/calendar-heatmap/Day.svelte, waltz-ng/client/common/svelte/calendar-heatmap/Weeks.svelte, waltz-ng/client/common/svelte/popover/Popover.svelte, waltz-ng/client/data-flow/components/svelte/Categories.svelte, waltz-ng/client/data-flow/components/svelte/Clients.svelte, waltz-ng/client/data-flow/components/svelte/FlowDecoratorExplorerPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/Flow.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementBreakdown.svelte, waltz-ng/client/physical-flows/svelte/StepHeader.svelte, waltz-ng/client/process-diagram/components/process-diagram/ProcessDiagram.svelte, waltz-ng/client/process-diagram/components/process-diagram/svg-elems/Objects.svelte, waltz-ng/client/survey/components/svelte/SurveyRecipientInfoPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewerContextPanel.svelte, waltz-ng/client/system/svelte/ratings-schemes/SymbolPicker.svelte, waltz-ng/client/technology/svelte/custom-environment-panel/UsageTree.svelte, waltz-ng/style/_bootstrap-styles.scss
=> Waltz 6314 keydown bug

.github/workflows/maven.yml, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-data/src/main/ddl/liquibase/db.changelog-1.45.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
- also prepping 1.45.2
- also (temporarily) disable ci testing (liquibase incompatibility with h2)
#6323
=> Fixing postgres build

waltz-data/src/main/ddl/liquibase/db.changelog-1.46.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/SurveyRunGenerator.java
=> DDL for 1.46

waltz-data/src/main/ddl/liquibase/db.changelog-1.46.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml, waltz-data/src/main/java/org/finos/waltz/data/datatype_decorator/LogicalFlowDecoratorDao.java, waltz-data/src/main/java/org/finos/waltz/data/flow_classification_rule/FlowClassificationRuleDao.java, waltz-data/src/main/java/org/finos/waltz/data/orphan/OrphanDao.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/FlowClassificationRuleGenerator.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/LogicalFlowGenerator.java, waltz-model/src/main/java/org/finos/waltz/model/flow_classification_rule/FlowClassificationRule.java, waltz-model/src/main/java/org/finos/waltz/model/flow_classification_rule/FlowClassificationRuleCreateCommand.java, waltz-model/src/main/java/org/finos/waltz/model/flow_classification_rule/FlowClassificationRuleVantagePoint.java, waltz-ng/client/common/checks.js, waltz-ng/client/flow-classification-rule/components/summary-list/FlowClassificationRuleDetail.svelte, waltz-ng/client/flow-classification-rule/components/summary-list/FlowClassificationRuleEditor.svelte, waltz-ng/client/flow-classification-rule/components/summary-list/flow-classification-rule-summary-list.js, waltz-ng/client/flow-classification-rule/components/svelte/CompanionAppRulesPanel.svelte, waltz-ng/client/flow-classification-rule/components/svelte/CompanionDataTypeRulesPanel.svelte, waltz-ng/client/flow-classification-rule/components/svelte/FlowClassificationRuleOverview.svelte, waltz-ng/client/flow-classification-rule/components/table/flow-classification-rules-table.js, waltz-ng/client/flow-classification-rule/pages/view/flow-classification-rule-view.js, waltz-ng/client/svelte-stores/flow-classification-rule-store.js, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleResolver.java, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleService.java, waltz-service/src/test/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleResolverTest.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/FlowClassificationRuleEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/FlowClassificationRuleExtractor.java
=> Db contrib/waltz 6334 actor flow classification rules

waltz-data/src/main/java/org/finos/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyViewDao.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstance.java, waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceCreateCommand.java, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.html, waltz-ng/client/allocation/components/entity-sub-section/allocation-entity-sub-section.js, waltz-ng/client/allocation/services/allocation-store.js, waltz-ng/client/common/svelte/info-panels/SurveyInstanceInfoPanel.svelte, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/physical-flows/components/participants-section/physical-flow-participants-section.html, waltz-ng/client/physical-flows/components/participants-section/physical-flow-participants-section.js, waltz-ng/client/physical-flows/components/participants-sub-section/physical-flow-participants-sub-section.html, waltz-ng/client/physical-flows/components/participants-sub-section/physical-flow-participants-sub-section.js, waltz-ng/client/survey/components/instance-list/survey-instance-list.html, waltz-service/src/main/java/org/finos/waltz/service/allocation/AllocationService.java, waltz-service/src/main/java/org/finos/waltz/service/permission/permission_checker/AllocationPermissionChecker.java, waltz-service/src/main/java/org/finos/waltz/service/physical_flow/PhysicalFlowService.java, waltz-service/src/main/java/org/finos/waltz/service/physical_flow_participant/PhysicalFlowParticipantService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/AllocationEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/PhysicalFlowEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/PhysicalFlowParticipantEndpoint.java
=> Db contrib/waltz 6329 issued on from instance allocation perms

waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstance.java, waltz-model/src/test/java/org/finos/waltz/model/survey/SurveyInstanceStateMachineTest.java
- defaulting `issued_on` dates
=> Surveys issued_on dates

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prep 1.46 (again)

waltz-data/src/main/java/org/finos/waltz/data/complexity/ComplexityDao.java
=> Complexity summaries for both pg and mssql

waltz-ng/client/involvement-kind/components/svelte/BulkInvolvementLoader.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindPanel.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementListPanel.svelte
=> Db contrib/waltz 6349 bulk inv loader accept errors

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.2.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.47.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prepping v1.47

waltz-schema/src/main/resources/liquibase/db.changelog-1.47.xml, waltz-schema/src/main/resources/liquibase/db.properties.xml
Added unique constraints to:
- rating_scheme
- rating_scheme_item
- assessment_definition
Added rating group to rating_scheme_item
Added external_id to rating_scheme
Increased size of code column on rating_scheme_item
#6360
=> Support grouped ratings (and some other tweaks)

waltz-schema/src/main/resources/liquibase/db.changelog-1.47.xml
- added cardinality to assessment_definition
- updated assessment_rating key
- updated pk to allow for multi ratings
- updated ddl docs
#6359
=> Mulitvalued assessments

waltz-data/src/main/java/org/finos/waltz/data/rating_scheme/RatingSchemeDAO.java, waltz-model/src/main/java/org/finos/waltz/model/rating/RatingScheme.java, waltz-model/src/main/java/org/finos/waltz/model/rating/RatingSchemeItem.java, waltz-model/src/main/java/org/finos/waltz/model/scenario/ChangeScenarioCommand.java, waltz-ng/client/assessments/components/editor/AssessmentEditor.svelte, waltz-ng/client/assessments/components/editor/AssessmentEditorView.svelte, waltz-ng/client/ratings/components/rating-picker/rating-picker.scss, waltz-ng/client/system/svelte/ratings-schemes/ItemEditor.svelte, waltz-ng/client/system/svelte/ratings-schemes/ItemsView.svelte, waltz-ng/client/system/svelte/ratings-schemes/rating-scheme-utils.js, waltz-schema/src/main/resources/liquibase/db.properties.xml, waltz-service/src/main/java/org/finos/waltz/service/scenario/ScenarioRatingItemService.java
=> Grouped ratings UI

waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.html, waltz-ng/client/common/components/multi-select-tree-control/multi-select-tree-control.js, waltz-ng/client/common/hierarchy-utils.js, waltz-ng/client/measurable/components/tree/measurable-tree.js
=> Db contrib/waltz 6202 big trees

.github/workflows/maven.yml
to avoid noisy
```
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/...
```
=> mvn -ntp for less noisy output

.github/workflows/cve-scanning.yml
=> Adding -ntp to reduce mvn download noise in logs

Dockerfile
=> Fixing build

waltz-model/src/main/java/org/finos/waltz/model/report_grid/ReportGridCreateCommand.java, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridService.java
=> ReportGrid cloning sets visibility to PRIVATE

README.md, waltz-data/src/main/java/org/finos/waltz/data/EntityAliasPopulator.java, waltz-model/src/main/java/org/finos/waltz/model/bulk_upload/BulkUploadCommand.java, waltz-model/src/main/java/org/finos/waltz/model/bulk_upload/ResolveBulkUploadRequestParameters.java
=> Db contrib/waltz 6412 bulk involvement loader performance

docs/README.md
Fixes #6414
Updated the link to point to the file as requested
=> update broken link in docs readme md file

waltz-common/src/main/java/org/finos/waltz/common/ArrayUtilities.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceDao.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/LegalEntityGenerator.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/LoadAll.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/model/Country.java
=> Legal Entity Sample Data Generator

waltz-ng/client/measurable/components/tree/measurable-tree.js
=> Adding missing import

waltz-ng/client/assessments/components/list/AssessmentRatingListGroup.svelte, waltz-ng/client/assessments/components/rating-editor/AssessmentRatingEditor.svelte, waltz-ng/client/assessments/components/rating-editor/EditableRatingValue.svelte, waltz-ng/client/assessments/components/rating-editor/RatingDetailView.svelte, waltz-ng/client/assessments/components/rating-editor/RatingListView.svelte, waltz-ng/client/assessments/components/rating-editor/RemoveRatingConfirmationPanel.svelte
=> Waltz 6417 assessment UI

waltz-ng/client/role/custom-role.html, waltz-ng/client/role/custom-role.js
=> custom roles list search and scroll

waltz-ng/client/assessments/components/favourites-list/AssessmentFavouritesList.svelte, waltz-ng/client/assessments/components/info-tile/AssessmentWidget.svelte, waltz-ng/client/assessments/components/rating-editor/rating-store.js, waltz-ng/client/svelte-stores/assessment-definition.js
=> assessment loading

pom.xml, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/LogicalFlowServiceTest.java, waltz-test-common/pom.xml, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/README.md
=> Disable playwright tests in maven runner.

README.md, SECURITY.md
I based this on an example provided by [atomist](https://github.com/atomist/samples/blob/master/SECURITY.md)
=> Create a SECURITY.md

waltz-ng/client/assessments/components/list/AssessmentRatingList.svelte
=> AssessmentList: toggling last open group reopens all default sections

waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> Rename "Statistics (Indicators)" to simply "Statistics"

docs/development/build.md
Small but important fix for the packaging command alias for postgres
=> correct sample packaging command for postgres

waltz-ng/client/flow-classification-rule/components/summary-list/FlowClassificationRuleDetail.svelte, waltz-ng/client/flow-classification-rule/components/summary-list/FlowClassificationRuleEditor.svelte, waltz-ng/client/flow-classification-rule/components/summary-list/flow-classification-rule-summary-list.html, waltz-ng/client/flow-classification-rule/components/svelte/FlowClassificationRuleOverview.svelte, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/NameHelper.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/PlaywrightUtilities.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/ScreenshotHelper.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/flow_classification_rule/RuleCreationTest.java
- adding playwright test for creation
#6483
=> Flow classification rule

waltz-ng/client/actor/components/actor-selector.js, waltz-ng/client/flow-classification-rule/components/summary-list/FlowClassificationRuleDetail.svelte, waltz-ng/client/flow-classification-rule/components/summary-list/FlowClassificationRuleEditor.svelte, waltz-ng/client/flow-classification-rule/components/summary-list/flow-classification-rule-summary-list.html, waltz-ng/client/flow-classification-rule/components/svelte/FlowClassificationRuleOverview.svelte, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/NameHelper.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/PlaywrightUtilities.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/ScreenshotHelper.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/flow_classification_rule/RuleCreationTest.java
=> Fuzzy search when registering actor flows

waltz-data/src/main/java/org/finos/waltz/data/database_information/DatabaseInformationDao.java, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js, waltz-service/src/main/java/org/finos/waltz/service/database_information/DatabaseInformationService.java, waltz-service/src/main/java/org/finos/waltz/service/entity_search/EntitySearchService.java
=> Search for databases

waltz-schema/src/main/resources/liquibase/db.changelog-1.48.xml
=> Drop obsolete `entity_tag` table

waltz-data/src/main/java/org/finos/waltz/data/database_information/DatabaseInformationDao.java, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/navbar/components/navbar-search/navbar-search.html, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/org/finos/waltz/service/database_information/DatabaseInformationService.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/DatabaseHelper.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/PlaywrightUtilities.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/ScreenshotHelper.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/applications/ApplicationSearchTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/databases/DatabaseSearchTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/flow_classification_rule/RuleCreationTest.java
=> Waltz 6318 search test

waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionEditor.svelte, waltz-ng/client/system/svelte/assessment-definitions/assessment-definition-utils.js
=> Assessment Definitions: allow admin to specify qualifier ids

waltz-data/src/main/java/org/finos/waltz/data/person/PersonDao.java
=> Added missing where predicate to user search by role

pom.xml, waltz-web/pom.xml
=> Undoing spark upgrade

waltz-ng/client/embed/pages/embed-view.js, waltz-ng/client/welcome/welcome.js, waltz-ng/client/widgets/page-header/page-header.js
=> Added missing title to hoisted sections

waltz-data/src/main/java/org/finos/waltz/data/cost/CostDao.java, waltz-data/src/main/java/org/finos/waltz/data/cost/CostKindDao.java, waltz-model/src/main/java/org/finos/waltz/model/cost/CostKindWithYears.java, waltz-ng/client/common/svelte/entity-pickers/CostKindPicker.svelte, waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.html, waltz-ng/client/cost/components/app-costs-summary-section/app-costs-summary-section.js, waltz-ng/client/cost/components/graph/entity-costs-graph.js, waltz-ng/client/cost/services/cost-store.js, waltz-service/src/main/java/org/finos/waltz/service/aggregate_overlay_diagram/AggregateOverlayDiagramService.java, waltz-service/src/main/java/org/finos/waltz/service/cost/CostService.java, waltz-service/src/main/java/org/finos/waltz/service/cost_kind/CostKindService.java, waltz-web/src/main/java/org/finos/waltz/web/WebUtilities.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/CostEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/CostKindEndpoint.java
=> Waltz 6508 cost years

waltz-data/src/main/java/org/finos/waltz/data/actor/ActorSearchDao.java
=> Adding external id to actor search

waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/FlowClassificationRuleHarness.java, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/FlowClassificationRuleEndpoint.java
=> Quieten logs for FlowClassificationRuleService

docs/development/release-lifecycle.md
=> Document release procedures

waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/AssetCostHarness.java
=> Fixing build failure

waltz-data/src/main/java/org/finos/waltz/data/changelog/ChangeLogDao.java, waltz-service/src/main/java/org/finos/waltz/service/changelog/ChangeLogService.java
=> Removing tx param from ChangeLogDao method/s

pom.xml, waltz-model/src/main/java/org/finos/waltz/model/system_version/SystemVersionInfo.java, waltz-ng/client/system/routes.js, waltz-ng/client/system/svelte/version-info/VersionInfoPage.svelte, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/system/version-info-view.js, waltz-service/src/main/java/org/finos/waltz/service/changelog/ChangeLogService.java, waltz-service/src/main/java/org/finos/waltz/service/system_version/SystemVersionService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SystemVersionEndpoint.java
=> Version Information Page

waltz-ng/client/common/components/grid/grid-with-search.html
=> grid-counts

waltz-data/src/main/java/org/finos/waltz/data/legal_entity/LegalEntityRelationshipKindDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/AttestationPreCheckServiceTest.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/PermissionGroupServiceTest.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/LegalEntityHarness.java, waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/widgets/page-header/page-header.html, waltz-service/src/main/java/org/finos/waltz/service/legal_entity/LegalEntityRelationshipKindService.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/applications/ApplicationSearchTest.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/LegalEntityRelationshipKindEndpoint.java
=> Fixing Test failures

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.49.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prepping 1.49

waltz-ng/client/app-groups/components/overview/app-group-overview.html
=> Prevent users from subscribing to other peoples favourite groups

waltz-ng/client/app-groups/components/overview/app-group-overview.html, waltz-ng/client/applications/components/app-summary.html, waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/bookmarks/svelte/BookmarkPanel.svelte, waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/common/svelte/calendar-heatmap/CalendarHeatmap.svelte, waltz-ng/client/data-types/components/overview/data-type-overview.html, waltz-ng/client/databases/components/database-pies/database-pies.html, waltz-ng/client/logical-flow/components/logical-flows-data-type-summary-pane/logical-flows-data-type-summary-pane.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.html, waltz-ng/client/logical-flow/directives/flow-cloud-diagram.html, waltz-ng/client/logical-flow/directives/flow-cloud-diagram.js, waltz-ng/client/logical-flow/directives/index.js, waltz-ng/client/org-units/components/overview/org-unit-overview.html, waltz-ng/client/person/components/overview/person-overview.html, waltz-ng/client/server-info/components/server-pies/server-pies.html, waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/widgets/markdown.js, waltz-ng/client/widgets/pie/pie-table.html, waltz-ng/style/_bootstrap-styles.scss, waltz-ng/style/_waltz.scss
=> Minor layout tweaks

waltz-ng/client/system/svelte/ratings-schemes/SchemeEditor.svelte
=> Added external id to rating scheme edit page

waltz-ng/client/playpen/3/builder/TaxonomyDiagramBuilder.svelte
=> BoaP diagram supports measurable ordering

pom.xml
=> Rolling jexl back from 3.3 to 3.2.1

waltz-ng/client/aggregate-overlay-diagram/components/aggregate-overlay-diagram/widgets/aggregated-entities/AggregatedEntitiesWidgetParameters.svelte, waltz-ng/client/aggregate-overlay-diagram/components/aggregate-overlay-diagram/widgets/backing-entities/BackingEntitiesWidgetParameters.svelte
=> Db contrib/waltz 6628 agg overlay fix

waltz-data/src/main/java/org/finos/waltz/data/assessment_rating/AssessmentRatingDao.java, waltz-data/src/main/java/org/finos/waltz/data/entity_named_note/EntityNamedNoteDao.java, waltz-data/src/main/java/org/finos/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-data/src/main/java/org/finos/waltz/data/measurable/MeasurableDao.java, waltz-data/src/main/java/org/finos/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-model/src/main/java/org/finos/waltz/model/EntityKind.java, waltz-model/src/main/java/org/finos/waltz/model/taxonomy_management/TaxonomyChangeImpact.java, waltz-model/src/main/java/org/finos/waltz/model/taxonomy_management/TaxonomyChangePreview.java, waltz-ng/client/measurable/components/change-control/measurable-change-control.html, waltz-ng/client/measurable/components/change-control/measurable-change-control.js, waltz-ng/client/taxonomy-management/components/taxonomy-change-command-preview/taxonomy-change-command-preview.html, waltz-service/src/main/java/org/finos/waltz/service/assessment_rating/AssessmentRatingService.java, waltz-service/src/main/java/org/finos/waltz/service/entity_named_note/EntityNamedNoteService.java, waltz-service/src/main/java/org/finos/waltz/service/entity_relationship/EntityRelationshipService.java, waltz-service/src/main/java/org/finos/waltz/service/measurable/MeasurableService.java, waltz-service/src/main/java/org/finos/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/TaxonomyManagementUtilities.java, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/processors/MergeMeasurableCommandProcessor.java, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/processors/RemoveMeasurableCommandProcessor.java, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/processors/TaxonomyManagementHelper.java, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/processors/UpdateMeasurableConcreteFlagCommandProcessor.java, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/processors/UpdateMeasurableDescriptionCommandProcessor.java, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/processors/UpdateMeasurableNameCommandProcessor.java
=> Db contrib/waltz 6608 measujrable merge

waltz-common/src/main/java/org/finos/waltz/common/ListUtilities.java, waltz-common/src/main/java/org/finos/waltz/common/OptionalUtilities.java, waltz-data/src/main/java/org/finos/waltz/data/user/UserRoleDao.java, waltz-model/src/main/java/org/finos/waltz/model/bulk_upload/BulkUploadMode.java, waltz-model/src/main/java/org/finos/waltz/model/user/BulkUserOperationRowPreview.java, waltz-ng/client/svelte-stores/user-store.js, waltz-ng/client/user/svelte/UserBulkEditor.svelte, waltz-ng/client/user/svelte/UserManagementPanel.svelte, waltz-ng/client/user/svelte/UserRolesList.svelte, waltz-service/src/main/java/org/finos/waltz/service/user/UserRoleService.java, waltz-service/src/main/java/org/finos/waltz/service/user/UserService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/UserEndpoint.java
=> Bulk user administration

README.md, waltz-data/src/main/java/org/finos/waltz/data/involvement_group/InvolvementGroupDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyRunDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyViewDao.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/SurveyRunGenerator.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_group/InvolvementGroup.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_group/InvolvementGroupCreateCommand.java, waltz-schema/src/main/resources/liquibase/db.changelog-1.51.xml, waltz-service/src/main/java/org/finos/waltz/service/involvement_group/InvolvementGroupService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyRunService.java
=> Db contrib/waltz 6637 survey run invovlements to groups

waltz-data/src/main/java/org/finos/waltz/data/attestation/AttestationInstanceDao.java, waltz-data/src/main/java/org/finos/waltz/data/attestation/AttestationRunDao.java, waltz-data/src/main/java/org/finos/waltz/data/involvement_group/InvolvementGroupDao.java, waltz-data/src/main/java/org/finos/waltz/data/survey/SurveyRunDao.java, waltz-schema/src/main/resources/liquibase/db.changelog-1.51.xml, waltz-service/src/main/java/org/finos/waltz/service/attestation/AttestationRunService.java
=> Db contrib/waltz 6637 migrate attestation runs to inv groups

waltz-data/src/main/java/org/finos/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKind.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKindChangeCommand.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKindCreateCommand.java, waltz-ng/client/attestation/attestation-run-create.js, waltz-ng/client/common/svelte/entity-pickers/InvolvementPicker.svelte, waltz-ng/client/entity/components/entity-selector/entity-selector.html, waltz-ng/client/involvement-kind/components/svelte/BulkInvolvementLoader.svelte, waltz-ng/client/involvement-kind/components/svelte/EditInvolvementKindPanel.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindOverview.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindPanel.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindTable.svelte, waltz-ng/client/involvement-kind/components/svelte/bulk-involvement-loader-store.js, waltz-ng/client/involvement/components/involved-people-section.js, waltz-ng/client/involvement/services/involved-section-service.js, waltz-ng/client/person/components/person-apps-section/person-apps-section.js, waltz-ng/client/person/components/person-apps-table/person-apps-table.html, waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/DropdownPicker.svelte, waltz-ng/client/survey/components/survey-run-create-general.js, waltz-ng/client/survey/components/survey-section.js, waltz-schema/src/main/resources/liquibase/db.changelog-1.51.xml, waltz-service/src/main/java/org/finos/waltz/service/involvement/InvolvementService.java, waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/InvolvementEndpoint.java
=> Db contrib/waltz 6612 migrate inv kinds to be entity specific

waltz-ng/client/involvement/components/involved-people-section.js, waltz-schema/src/main/resources/liquibase/db.changelog-1.51.xml, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/InvolvementEndpoint.java
=> Db contrib/waltz 6644 software component fk on cascade delete

waltz-jobs/src/main/java/org/finos/waltz/jobs/harness/EntityHierarchyHarness.java, waltz-ng/client/measurable-category/pages/list/measurable-category-list.html, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/MeasurableCategoryExtractor.java
=> Db contrib/waltz 6662 flat hier export

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/dao/MeasurableRatingDaoTest.java, waltz-ng/client/common/hierarchy-utils.js, waltz-ng/client/common/services/service-broker.js, waltz-ng/client/data-flow/components/svelte/Categories.svelte, waltz-ng/client/data-flow/components/svelte/Clients.svelte, waltz-ng/client/data-flow/components/svelte/flow-decorator-utils.js, waltz-web/src/main/java/org/finos/waltz/web/Main.java
=> Db contrib/waltz 6665 fixes

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.52.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prep 1.52 release

waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/MeasurableCategoryExtractor.java
=> Waltz 6668 hier export sorting

waltz-data/src/main/java/org/finos/waltz/data/taxonomy_management/TaxonomyChangeDao.java, waltz-model/src/main/java/org/finos/waltz/model/taxonomy_management/TaxonomyChangeCommand.java, waltz-ng/client/common/services/enums/index.js, waltz-ng/client/common/services/enums/taxonomy-change-type.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/measurable-category/components/taxonomy-change-summary-cell/taxonomy-change-summary-cell.html, waltz-ng/client/measurable-category/components/taxonomy-change-summary-cell/taxonomy-change-summary-cell.js, waltz-ng/client/measurable-category/components/taxonomy-changes/taxonomy-changes-section.html, waltz-ng/client/measurable-category/components/taxonomy-changes/taxonomy-changes-section.js, waltz-ng/client/measurable-category/index.js, waltz-ng/client/measurable-category/pages/list/measurable-category-list.html, waltz-ng/client/measurable-category/pages/list/measurable-category-list.js, waltz-ng/client/taxonomy-management/services/taxonomy-management-store.js, waltz-service/src/main/java/org/finos/waltz/service/taxonomy_management/TaxonomyChangeService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/TaxonomyManagementEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/MeasurableCategoryExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/TaxonomyChangeExtractor.java
=> Db contrib/waltz 6675 taxonomy changes

waltz-data/src/main/java/org/finos/waltz/data/end_user_app/EndUserAppDao.java, waltz-data/src/main/java/org/finos/waltz/data/end_user_app/EndUserAppIdSelectorFactory.java, waltz-model/src/main/java/org/finos/waltz/model/enduserapp/EndUserApplication.java, waltz-service/src/main/java/org/finos/waltz/service/end_user_app/EndUserAppService.java
=> End User Applications: ensure retired entries are omitted by default

waltz-data/src/main/java/org/finos/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/change_set/ChangeSetIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/change_unit/ChangeUnitIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/legal_entity/LegalEntityRelationshipIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/licence/LicenceIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/process_diagram/ProcessDiagramIdSelectorFactory.java, waltz-model/src/main/java/org/finos/waltz/model/EntityKind.java, waltz-ng/client/applications/components/app-list-page-header/AppListPageHeader.svelte, waltz-ng/client/applications/pages/list/app-list.html, waltz-ng/client/applications/pages/list/app-list.js, waltz-ng/client/applications/pages/view/app-view.html, waltz-ng/client/applications/routes.js, waltz-ng/client/common/entity-utils.js, waltz-ng/client/common/link-utils.js, waltz-ng/client/common/svelte/ViewLink.svelte, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/entity-statistics/services/entity-statistics-utilities.js, waltz-ng/client/report-grid/components/svelte/ReportGridOverview.svelte, waltz-ng/client/system/named-settings.js, waltz-service/src/main/java/org/finos/waltz/service/data_type/DataTypeDecoratorService.java, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleService.java, waltz-service/src/main/java/org/finos/waltz/service/logical_flow/LogicalFlowService.java
=> All applications list view

waltz-model/src/main/java/org/finos/waltz/model/change_initiative/ChangeInitiativeView.java, waltz-ng/client/assessments/assessment-utils.js, waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.html, waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.js, waltz-ng/client/change-initiative/index.js, waltz-ng/client/change-initiative/services/change-initiative-view-store.js, waltz-ng/client/common/services/core-api-utils.js, waltz-service/src/main/java/org/finos/waltz/service/change_initiative/ChangeInitiativeViewService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/ChangeInitiativeViewEndpoint.java
=> Change Initiatives: incomplete assessments filters

waltz-ng/client/measurable-category/components/taxonomy-changes/taxonomy-changes-section.js, waltz-ng/client/survey/components/survey-run-create-general.js
=> Waltz 6698 survey issuance bug

waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/report_grid/ReportGridIntegrationTest.java
=> Report Grid UI tests

waltz-common/src/main/java/org/finos/waltz/common/IOUtilities.java, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/user/svelte/UserCreatePanel.svelte, waltz-ng/client/user/svelte/UserSelectList.svelte, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/ScreenshotHelper.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/applications/ApplicationSearchTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/databases/DatabaseSearchTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/flow_classification_rule/RuleCreationTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/report_grid/ReportGridIntegrationTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/surveys/SurveyIssuanceIntegrationTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/user_roles/UserRoleTests.java, waltz-test-common/src/test/resources/report-grid/create-grid/template.md, waltz-test-common/src/test/resources/user/registration/template.md
=> Playwright Testing: create user

waltz-ng/client/change-initiative/components/change-initiative-section/change-initiative-section.html, waltz-ng/client/involvement/components/involved-people-section.html, waltz-ng/style/_waltz.scss
=> Wrap filters in a 'details/section' tag

waltz-data/src/main/java/org/finos/waltz/data/app_group/AppGroupDao.java, waltz-ng/client/alias/services/alias-store.js, waltz-ng/client/app-groups/components/overview/app-group-overview.html, waltz-ng/client/app-groups/components/overview/app-group-overview.js, waltz-ng/client/applications/components/overview/app-overview.js, waltz-ng/client/formly/tags-input-template.html, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/AppGroupHelper.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/PlaywrightUtilities.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/SearchHelper.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/BasePlaywrightTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/app_group/AddAliasesTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/applications/ApplicationSearchTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/databases/DatabaseSearchTest.java, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/measurable_ratings/MeasurableRatingTests.java, waltz-test-common/src/test/resources/app-group/add-aliases/template.md, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/EntityAliasEndpoint.java
=> App group aliases

waltz-data/src/main/java/org/finos/waltz/data/EntityAliasPopulator.java, waltz-data/src/main/java/org/finos/waltz/data/app_group/AppGroupDao.java, waltz-data/src/main/java/org/finos/waltz/data/svg/SvgDiagramDao.java, waltz-ng/client/logical-flow/pages/view/logical-flow-view.html, waltz-ng/client/logical-flow/pages/view/logical-flow-view.js, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-service/src/main/java/org/finos/waltz/service/SpringExceptionTranslationExecuteListener.java, waltz-service/src/main/java/org/finos/waltz/service/changelog/ChangeLogService.java, waltz-service/src/main/java/org/finos/waltz/service/cost/CostService.java, waltz-service/src/main/java/org/finos/waltz/service/end_user_app/EndUserAppService.java, waltz-service/src/main/java/org/finos/waltz/service/involvement/InvolvementService.java, waltz-service/src/main/java/org/finos/waltz/service/involvement_kind/InvolvementKindService.java, waltz-service/src/main/java/org/finos/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/org/finos/waltz/service/orgunit/OrganisationalUnitService.java, waltz-service/src/main/java/org/finos/waltz/service/person/PersonService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/BulkUploadLegalEntityRelationshipEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/LogicalFlowEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/DirectQueryBasedDataExtractor.java
=> Db contrib/waltz 6737 flow resurrection

waltz-data/src/main/java/org/finos/waltz/data/entity_hierarchy/EntityRootsSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/person/PersonDao.java, waltz-service/src/main/java/org/finos/waltz/service/entity_hierarchy/EntityHierarchyService.java
=> FIX: person hierarchy roots view

waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/user/active-users.html, waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/bookmarks/BookmarkCreationAndRemovalIntegrationTest.java
=>  1.54 pre-release testing minor fixes 

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/AttestationServiceTest.java, waltz-ng/client/attestation/attestation-run-view.html
- fixing test compilation failure
- adding tooltip
#6790
=> Attestations: add a mailto link to generate a notification to recipients

waltz-ng/client/actor/components/actor-overview.html, waltz-ng/client/actor/components/actor-overview.js, waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.js, waltz-ng/client/assessments/pages/view/assessment-definition-view.html, waltz-ng/client/assessments/pages/view/assessment-definition-view.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/system/svelte/assessment-definitions/assessment-definition-utils.js
=> actor assessments

pom.xml, waltz-ng/client/access-log/service/access-log-store.js, waltz-web/pom.xml, waltz-web/src/main/java/org/finos/waltz/web/HttpHeader.java, waltz-web/src/main/java/org/finos/waltz/web/HttpStatus.java, waltz-web/src/main/java/org/finos/waltz/web/Main.java, waltz-web/src/main/java/org/finos/waltz/web/MimeTypes.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/StaticResourcesEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/DataExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/DirectQueryBasedDataExtractor.java
=> upgrading jetty

waltz-data/src/main/java/org/finos/waltz/data/JooqUtilities.java, waltz-ng/client/measurable-relationship/components/panel/related-measurables-panel.html, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.html, waltz-ng/client/measurable-relationship/components/table/related-measurables-table.js, waltz-service/src/main/java/org/finos/waltz/service/involvement/InvolvementViewService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/InvolvementViewEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/EntityRelationshipsExtractor.java
=> Entity Relationship extractor

waltz-data/src/main/java/org/finos/waltz/data/JooqUtilities.java, waltz-ng/package-lock.json, waltz-ng/test/common/entity-utils-test.js, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/MeasurableRatingExtractor.java
=> Adding application lifecycle phase to measurable rating exports

waltz-common/src/main/java/org/finos/waltz/common/StringUtilities.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/json/ReportGridDefinitionJSON.java
=> Report grid metadata

waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ReportGridExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/reportgrid/FormatterUtils.java
=> REport Grid entity field reference bug

pom.xml, waltz-jobs/src/main/java/org/finos/waltz/jobs/tools/lineage/LineageDiscoveryReport.java
=> Dependency upgrades

pom.xml, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/flow-classification-rule/components/svelte/FlowClassificationRuleOverview.svelte, waltz-ng/client/system/svelte/assessment-definitions/assessment-definition-utils.js, waltz-service/src/main/java/org/finos/waltz/service/report_grid/ReportGridEvaluatorNamespace.java
=> Adding assessments to flow classification rules

waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java, waltz-ng/client/data-flow/components/logical-flow-view-grid/logical-flow-view-grid.html, waltz-ng/client/data-flow/components/logical-flow-view-grid/logical-flow-view-grid.js, waltz-ng/client/data-types/components/data-type-decorator-section/DataTypeDetailPanel.svelte
=> Db contrib/waltz 6829 qol data flow improvements

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/DataTypeDecoratorServiceTest.java
=> Fix failing integration tests

waltz-data/src/main/java/org/finos/waltz/data/physical_specification/PhysicalSpecificationIdSelectorFactory.java
Flow details tab not working for actors
#6839
=> Adding actor support to phys spec selector

waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.html, waltz-ng/client/data-flow/components/logical-flow-view-grid/logical-flow-view-grid.html, waltz-ng/client/data-flow/components/logical-flow-view-grid/logical-flow-view-grid.js
=> Use flow name, drop back to spec name.

waltz-ng/client/involvement/components/sub-section/key-people-sub-section.html, waltz-ng/client/involvement/components/sub-section/key-people-sub-section.js, waltz-ng/client/involvement/involvement-utils.js, waltz-ng/client/involvement/services/involvement-view-service.js, waltz-service/src/main/java/org/finos/waltz/service/involvement/InvolvementViewService.java
- fixed view service endpoint logic
- simplified existing multi-call logic to the single view-service call
#6838
=> Key Involvement section showing removed people

waltz-service/src/main/java/org/finos/waltz/service/survey/SurveyInstanceUtilities.java
=> survey cle validation

waltz-data/src/main/java/org/finos/waltz/data/measurable_rating/MeasurableRatingViewDao.java, waltz-model/src/main/java/org/finos/waltz/model/flow_classification_rule/FlowClassificationRuleView.java, waltz-model/src/main/java/org/finos/waltz/model/measurable_rating/PrimaryRatingViewItem.java, waltz-ng/client/data-flow/components/data-flow-section/data-flow-section.js, waltz-ng/client/flow-classification-rule/components/section/flow-classification-rules-section.html, waltz-ng/client/flow-classification-rule/components/section/flow-classification-rules-section.js, waltz-ng/client/flow-classification-rule/components/summary-list/flow-classification-rule-summary-list.html, waltz-ng/client/flow-classification-rule/components/summary-list/flow-classification-rule-summary-list.js, waltz-ng/client/flow-classification-rule/components/table/flow-classification-rules-table.js, waltz-ng/client/flow-classification-rule/services/flow-classification-rule-store.js, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleService.java, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleViewService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/FlowClassificationRuleEndpoint.java
=> Flow Classification Rule table to show assessments

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.56.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prep Waltz 1.56 dev

waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.html, waltz-schema/src/main/resources/liquibase/db.changelog-1.56.xml, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/AllocationsExtractor.java
=> Bug alloc export

waltz-ng/client/actor/pages/actor-view/actor-view.html
=> Add external id to actor overview

waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html
=> Soften the rating breach warning

waltz-ng/client/data-flow/components/svelte/flow-detail-tab/PhysicalFlowTable.svelte, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/filters/FlowClassificationFilters.svelte, waltz-ng/client/flow-classification-rule/components/svelte/FlowClassificationRuleOverview.svelte
=> Fixing occasional failure of phys flow table

waltz-schema/src/main/resources/liquibase/db.changelog-1.57.xml
=> SoftwareVersion table: increase the version column size

waltz-service/src/main/java/org/finos/waltz/service/DIConfiguration.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/AuthenticationEndpoint.java
fixes for https://github.com/finos/waltz/issues/6938
=> small fixes for oauth2 implementation

waltz-web/src/main/java/org/finos/waltz/web/endpoints/auth/AuthenticationEndpoint.java
https://github.com/finos/waltz/issues/6941 fix variable name wrapped in quotes
=> oauth sso small fix

waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowDao.java, waltz-model/src/main/java/org/finos/waltz/model/logical_flow/LogicalFlow.java, waltz-schema/src/main/resources/liquibase/db.changelog-1.58.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml
=> Logical flow external ID

waltz-ng/client/applications/components/apps-view-grid/AppsViewGrid.svelte, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/SelectedPhysicalFlowDetail.svelte
=> Making spec linking more resilient

waltz-data/src/main/java/org/finos/waltz/data/attestation/AttestationRunDao.java
=> Attestation Run creation error message

waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js
=> Search panel will only dismiss on mousedown outside of the panel

waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowDao.java, waltz-model/src/main/java/org/finos/waltz/model/logical_flow/LogicalFlow.java, waltz-schema/src/main/resources/liquibase/db.changelog-1.58.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml
=> Revert "Revert "Logical flow external ID""

waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java
=> Db contrib/waltz 6975 report grids rs response bug

waltz-schema/src/main/resources/liquibase/db.changelog-1.58.xml
=> Db contrib/waltz 6976 lf ext id defaul val

README.md
closes https://github.com/finos/waltz/issues/6977
=> updated link to Docker README

waltz-ng/client/applications/components/overview/app-overview.html, waltz-ng/client/applications/components/overview/app-overview.js, waltz-ng/client/measurable-rating/svelte/PrimaryRatingOverviewSubSection.svelte, waltz-ng/client/measurable-rating/svelte/PrimaryRatingTooltipContent.svelte, waltz-ng/client/svelte-stores/measurable-rating-store.js, waltz-service/src/main/java/org/finos/waltz/service/measurable_rating/MeasurableRatingViewService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Db contrib/waltz 6820 primary ratings to app overview

waltz-ng/client/measurable-rating/components/edit-panel/measurable-rating-edit-panel.js, waltz-ng/package-lock.json, waltz-service/src/main/java/org/finos/waltz/service/measurable_rating/MeasurableRatingViewService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Db contrib/waltz 6820 primary ratings test fix

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prep 1.58.1

waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js
=> Clarifying text on the org unit column

waltz-ng/client/data-types/components/data-type-decorator-section/DataTypeDecoratorSection.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindPanel.svelte, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleService.java
=> Db contrib/waltz 7008 dt bug

waltz-data/src/main/java/org/finos/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/org/finos/waltz/model/physical_flow/PhysicalFlow.java, waltz-ng/client/common/components/entity-link/entity-icon-label.html, waltz-ng/client/common/grid-utils.js, waltz-ng/client/common/markdown-utils.js, waltz-ng/client/common/services/enums/entity.js, waltz-ng/client/common/svelte/EntityLabel.svelte, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/physical-flow/physical-flow-table-utilities.js, waltz-ng/client/physical-flows/components/flow-table/physical-flow-table.js, waltz-ng/client/physical-flows/components/physical-flow-and-specification-detail/physical-flow-and-specification-detail.html, waltz-ng/client/physical-flows/components/physical-flow-section/physical-flow-section.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/package-lock.json, waltz-ng/style/_waltz.scss
=> Db contrib/waltz 6159 physical flow name visibility

waltz-data/src/main/java/org/finos/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/org/finos/waltz/model/physical_flow/FlowAttributes.java, waltz-model/src/main/java/org/finos/waltz/model/physical_flow/PhysicalFlow.java, waltz-ng/client/physical-flows/svelte/PhysicalFlowCharacteristicsStep.svelte, waltz-ng/client/physical-flows/svelte/PhysicalFlowRegistrationView.svelte, waltz-service/src/main/java/org/finos/waltz/service/physical_flow/PhysicalFlowService.java
=> Physical flow registration name error

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package-lock.json, waltz-ng/package.json, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7027 update version to 1.58.2

waltz-ng/client/common/svelte/info-panels/SurveyInstanceInfoPanel.svelte, waltz-ng/client/survey/components/svelte/inline-panel/SurveyViewer.svelte
- bonus: improved css for survey sections
#7030
=> Survey instance shows the contact email

waltz-common/src/main/java/org/finos/waltz/common/ListUtilities.java, waltz-common/src/test/java/org/finos/waltz/common/ListUtilities_distinct.java, waltz-data/src/main/java/org/finos/waltz/data/licence/search/LicenceSearchDao.java, waltz-model/src/main/java/org/finos/waltz/model/licence/Licence.java, waltz-ng/client/navbar/components/nav-search-overlay/nav-search-overlay.js, waltz-service/src/main/java/org/finos/waltz/service/entity_search/EntitySearchService.java, waltz-service/src/main/java/org/finos/waltz/service/licence/LicenceService.java
=> Licences - search for licences from navbar

waltz-data/src/main/java/org/finos/waltz/data/change_unit/ChangeUnitIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/flow_diagram/FlowDiagramEntityDao.java, waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-data/src/main/java/org/finos/waltz/data/physical_flow/PhysicalFlowIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/physical_specification/PhysicalSpecificationIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/process_diagram/ProcessDiagramIdSelectorFactory.java, waltz-ng/client/common/entity-utils.js, waltz-ng/client/common/selector-utils.js, waltz-ng/client/common/svelte/ViewLink.svelte, waltz-ng/client/common/svelte/info-panels/EntityInfoPanel.svelte, waltz-ng/client/data-flow/components/svelte/FlowDecoratorExplorerPanel.svelte, waltz-ng/client/data-flow/components/svelte/flow-decorator-utils.js, waltz-ng/client/flow-diagram/components/diagram-svelte/Node.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/AnnotationPanel.svelte, waltz-ng/client/flow-diagram/components/diagram-svelte/context-panel/NodePanel.svelte, waltz-ng/client/flow-diagram/flow-diagram-utils.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-service/src/main/java/org/finos/waltz/service/data_type/DataTypeDecoratorService.java, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleService.java, waltz-service/src/main/java/org/finos/waltz/service/flow_diagram/FlowDiagramService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/LogicalFlowExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/PhysicalFlowExtractor.java
=> Db contrib/waltz 7047 euda flow viz

waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyInstanceStateMachineFactory.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ApplicationExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/ApplicationViewExtractor.java
=> Db contrib/waltz 7052 app extract

waltz-ng/client/attestation/components/attested-kind/attested-kind.html, waltz-ng/client/attestation/components/inline-measurable-rating-panel/inline-measurable-rating-panel.html, waltz-ng/client/attestation/components/inline-measurable-rating-panel/inline-measurable-rating-panel.js, waltz-service/src/main/java/org/finos/waltz/service/attestation/AttestationInstanceService.java, waltz-service/src/main/java/org/finos/waltz/service/attestation/AttestationRunService.java
=> Db contrib/waltz 7076 measurable category attestations

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package-lock.json, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.61.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prep 1.61 release

waltz-data/src/main/java/org/finos/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/org/finos/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/FlowDetailPanel.svelte, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/SelectedLogicalFlowDetail.svelte, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/SelectedPhysicalFlowDetail.svelte, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/flow-detail-utils.js, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.scss, waltz-ng/client/logical-flow/pages/view/logical-flow-view.html, waltz-ng/client/logical-flow/pages/view/logical-flow-view.js, waltz-ng/client/logical-flow/routes.js, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-ng/client/physical-flows/components/physical-flow-and-specification-detail/physical-flow-and-specification-detail.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-flows/routes.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/physical-specification-view.js, waltz-ng/client/physical-specifications/routes.js, waltz-ng/client/physical-specifications/services/physical-specification-store.js, waltz-schema/src/main/resources/liquibase/db.changelog-1.61.xml, waltz-service/src/main/java/org/finos/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/org/finos/waltz/service/physical_specification/PhysicalSpecificationService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/LogicalFlowEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/PhysicalSpecificationEndpoint.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/LogicalFlowExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/LogicalFlowViewExtractor.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/PhysicalFlowExtractor.java
=> Db contrib/waltz 7082 add ext id to phsy flow and spec

pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.60.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.61.xml
=> Fixing for postgres/h2

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Prep 1.61.1

waltz-data/src/main/java/org/finos/waltz/data/physical_specification/PhysicalSpecificationIdSelectorFactory.java, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/FlowDetailPanel.svelte, waltz-ng/client/data-flow/components/svelte/flow-detail-tab/LogicalFlowTable.svelte, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.js
=> Db contrib/waltz 7104 flow detail agg

waltz-ng/client/svelte-stores/entity-alias-store.js
=> Fixing missing alias store

pom.xml, waltz-data/src/main/java/org/finos/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/org/finos/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/InvolvementTest.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKind.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKindChangeCommand.java, waltz-model/src/main/java/org/finos/waltz/model/involvement_kind/InvolvementKindUsageStat.java, waltz-ng/client/involvement-kind/components/svelte/EditInvolvementKindPanel.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindOverview.svelte, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindTable.svelte, waltz-schema/src/main/resources/liquibase/db.changelog-1.61.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.62.xml, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/InvolvementHelper.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/PersonHelper.java
=> Involvement transitive flag

pom.xml, waltz-ng/package-lock.json
=> Db contrib/waltz 7113 upgrade core waltz java version

waltz-data/src/main/java/org/finos/waltz/data/CommonTableFieldsRegistry.java, waltz-data/src/main/java/org/finos/waltz/data/InlineSelectFieldFactory.java, waltz-data/src/main/java/org/finos/waltz/data/role/RoleDao.java, waltz-data/src/main/java/org/finos/waltz/data/user/UserRoleDao.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/BaseInMemoryIntegrationTest.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/UserRoleServiceTest.java, waltz-model/src/main/java/org/finos/waltz/model/role/Role.java, waltz-model/src/main/java/org/finos/waltz/model/role/RoleView/RoleView.java, waltz-ng/client/common/index.js, waltz-ng/client/common/link-utils.js, waltz-ng/client/common/svelte/ViewLink.svelte, waltz-ng/client/dynamic-section/dynamic-section-definitions.js, waltz-ng/client/involvement-kind/components/svelte/InvolvementKindTable.svelte, waltz-ng/client/role/index.js, waltz-ng/client/role/pages/role-list.html, waltz-ng/client/role/pages/role-list.js, waltz-ng/client/role/pages/role-view.js, waltz-ng/client/role/routes.js, waltz-ng/client/role/svelte/RoleList.svelte, waltz-ng/client/role/svelte/RoleListPanel.svelte, waltz-ng/client/role/svelte/RoleView.svelte, waltz-ng/client/role/svelte/SelectedRolePanel.svelte, waltz-ng/client/svelte-stores/role-store.js, waltz-ng/client/system/svelte/assessment-definitions/assessment-definition-utils.js, waltz-ng/client/user/svelte/UserRolesList.svelte, waltz-schema/src/main/resources/liquibase/db.changelog-1.62.xml, waltz-service/src/main/java/org/finos/waltz/service/role/RoleService.java, waltz-service/src/main/java/org/finos/waltz/service/user/UserRoleService.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/UserHelper.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/RoleEndpoint.java
=> Db contrib/waltz 7118 roles

waltz-ng/client/system/svelte/nav-aid-builder/TaxonomyNavAidBuilder.svelte
=> Db contrib/waltz 7152 navaid builder

waltz-data/src/main/java/org/finos/waltz/data/CommonTableFieldsRegistry.java, waltz-data/src/main/java/org/finos/waltz/data/JooqUtilities.java, waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/data/JooqUtilities_loadExternalIdToEntityRefMapTest.java, waltz-model/src/main/java/org/finos/waltz/model/CommonTableFields.java, waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/InvolvementHelper.java
=> Db contrib/waltz 7153 common table fields

waltz-data/src/main/java/org/finos/waltz/data/EntityAliasPopulator.java
=> Db contrib/waltz 7159 application service taxonomy 3 data loader upload owners

waltz-ng/client/common/svelte/ViewLink.svelte, waltz-ng/client/svelte-stores/svg-diagram-store.js, waltz-ng/client/system/routes.js, waltz-ng/client/system/static-diagram-view.html, waltz-ng/client/system/static-diagram-view.js, waltz-ng/client/system/static-diagrams-view.html, waltz-ng/client/system/static-diagrams-view.js, waltz-ng/client/system/svelte/static-diagrams/StaticDiagram.svelte, waltz-ng/client/system/svelte/static-diagrams/StaticDiagramsAdminView.svelte, waltz-ng/client/system/system-admin-list.js, waltz-service/src/main/java/org/finos/waltz/service/svg/SvgDiagramService.java, waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/SvgDiagramEndpoint.java
=> Db contrib/waltz 7155 diagrams

waltz-service/src/main/java/org/finos/waltz/service/entity_relationship/BulkUploadRelationshipService.java
=> entity relationship variable ref fix

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/BulkUploadRelationshipServiceTest.java, waltz-service/src/main/java/org/finos/waltz/service/entity_relationship/BulkUploadRelationshipService.java, waltz-service/src/test/java/org/finos/waltz/service/entity_relationship/BulkUploadRelationshipItemParserTest.java
=> Db contrib/entity relationship variable ref fix 7175

waltz-schema/src/main/resources/liquibase/db.changelog-1.65.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml
=> Db contrib/waltz 7162 add table comment change log

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.65.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.66.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7151 prep

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.67.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7190 prep

pom.xml
=> Db contrib/7199 logback version upgrade

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-schema/src/main/resources/liquibase/db.changelog.1.68.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/7203 prep 1.68

waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleUtilities.java
=> Db contrib/7215 expand auth statements to apply to actors

waltz-jobs/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7227 fix vulnerable dependencies

waltz-ng/client/navbar/directives/navbar-profile.js, waltz-ng/client/user/system-roles.js
=> Db contrib/waltz 7231 system admin tag should be visible for licence admin

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package-lock.json, waltz-ng/package.json, waltz-schema/pom.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7232 prep 1.68.1

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package-lock.json, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.69.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7236 1.69 prep

waltz-ng/client/attestation/components/section/attestation-summary-section.html
=> Db contrib/waltz 7249 logical flow and physical flow attestation extract giving error

waltz-ng/client/measurable-rating/components/bulk-rating-editor/BulkRatingEditor.svelte, waltz-service/src/main/java/org/finos/waltz/service/measurable_rating/BulkMeasurableRatingService.java
=> Db contrib/watz 7253 help text changes

waltz-service/src/main/java/org/finos/waltz/service/measurable_rating/BulkMeasurableRatingService.java
=> Db contrib/waltz 7256 allocations fix

.github/workflows/maven.yml
=> Db contrib/waltz 7258 build failure in finos waltz

docs/index.html, waltz-ng/client/actor/components/actor-overview.html, waltz-ng/client/actor/pages/actor-view/actor-view.html, waltz-ng/client/widgets/page-header/page-header.html
=> Db contrib/waltz 7267 actor name appearing in waltz incorrectly

docs/index.html, waltz-service/src/test/resources/org/finos/waltz/service/measurable_rating/test-measurable-rating-items-with-blanks.tsv, waltz-service/src/test/resources/org/finos/waltz/service/measurable_rating/test-measurable-rating-items-with-commented-lines.csv, waltz-service/src/test/resources/org/finos/waltz/service/measurable_rating/test-measurable-rating-items.csv, waltz-service/src/test/resources/org/finos/waltz/service/measurable_rating/test-measurable-rating-items.json, waltz-service/src/test/resources/org/finos/waltz/service/measurable_rating/test-measurable-rating-items.tsv
=> Db contrib/waltz 7263 bulk measurable rating test

waltz-integration-test/src/test/java/org/finos/waltz/integration_test/inmem/service/AssessmentRatingServiceTest.java
=> Db contrib/waltz 7276 assessment rating service tests failing on pipelines

waltz-ng/client/system/svelte/assessment-definitions/assessment-definition-utils.js
=> Db contrib/waltz 7282 add entity kind as datatype for assessment definition

waltz-ng/client/assessments/pages/view/assessment-definition-view.js, waltz-ng/client/dynamic-section/dynamic-section-definitions.js
=> Db contrib/watz 7287 add assessment rating tab for datatype entities

waltz-ng/client/flow-classification-rule/components/summary-list/FlowClassificationRulesPanel.svelte, waltz-schema/src/main/resources/liquibase/db.changelog-1.71.xml, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleService.java, waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationRuleUtilities.java
=> Db contrib/waltz 7292 new feature flags for flow classification rules

README.md, pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.72.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7296 prep 1.72

pom.xml, waltz-jobs/pom.xml, waltz-jobs/src/main/java/org/finos/waltz/jobs/generators/PhysicalFlowGenerator.java, waltz-jobs/src/main/java/org/finos/waltz/jobs/tools/importers/licence/finos/FinosLicenceComplianceImporter.java, waltz-ng/package-lock.json
- fix FinosLicenceComplianceImporter from failing to import yaml files
- update physical flow generator to name the flows (previously blank)
=> #7306-FinosLicenceComplianceImporter-Failing

docker-compose.yml
- fix error when launching with docker; getting error that gen_random_uuid() doesn't exist
- also expose database on a port to connect and populate data via LoadAll.java
also resolves #7021
=> #7131 Fix Docker Launch  Error 

.github/ISSUE_TEMPLATE/Meeting.md, pom.xml
=> Db contrib/waltz 7308 remediate oss vulnerabilities

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package-lock.json, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.73.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz 7301 prep 1.73 revision

pom.xml, waltz-common/pom.xml, waltz-data/pom.xml, waltz-integration-test/pom.xml, waltz-jobs/pom.xml, waltz-model/pom.xml, waltz-ng/package-lock.json, waltz-ng/package.json, waltz-schema/pom.xml, waltz-schema/src/main/resources/liquibase/db.changelog-1.73.1.xml, waltz-schema/src/main/resources/liquibase/db.changelog-master.xml, waltz-service/pom.xml, waltz-test-common/pom.xml, waltz-web/pom.xml
=> Db contrib/waltz prep 7332

pom.xml
- 1.33 to 2.5
- Test on JDK 1.8, Running on Tomcat 8, JRE 8
=> 7324 Update SnakeYaml
