waltz-ng/client/applications/app-edit.js, waltz-ng/client/applications/app-registration.js, waltz-ng/client/applications/formly/fields.js
=> Fixing ui-select with angular formly for angular 1.4

waltz-ng/client/widgets/pie.js
- showing a dashed outline of a circle
- half normal size
- light grey
#6
=> Pie charts give visual indication when no data

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/AppAliasDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/AppTagDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/application/AppRegistrationRequest.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-ng/client/applications/app-edit.js, waltz-ng/client/applications/app-registration.js, waltz-ng/client/applications/directives/app-overview.html, waltz-ng/client/applications/formly/fields.js, waltz-ng/client/common/colors.js, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/person/person-view.html, waltz-ng/client/widgets/display-field.js, waltz-ng/client/widgets/index.js, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/application/ApplicationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java
- updated liquibase
- updated immutables
- updated dao
- updated webapp
#1
=> Added overallRating field to application

waltz-ng/client/org-units/directives/org-unit-overview.html
=> Clicking the capabilities summary takes user to wrong sub-section

waltz-ng/client/org-units/directives/org-unit-overview.html
=> Add 'units' to ou summary blocks

waltz-ng/client/org-units/directives/org-unit-overview.html, waltz-ng/client/org-units/unit-view.html
=> Adding missing hyper link between complexity summary and detail

waltz-data/src/main/java/com/khartec/waltz/data/orgunit/OrganisationalUnitDao.java, waltz-model/src/main/java/com/khartec/waltz/model/orgunit/OrganisationalUnitHierarchy.java, waltz-ng/client/app-view/app-view.html, waltz-ng/client/auth-sources/index.js, waltz-ng/client/auth-sources/resolvers.js, waltz-ng/client/common/filters/display-name-filter.js, waltz-ng/client/common/services/BaseLookupService.js, waltz-ng/client/org-units/index.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/services/org-unit-view-options.js, waltz-ng/client/org-units/unit-nav-view.html, waltz-ng/client/org-units/unit-nav-view.js, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view.js, waltz-ng/client/widgets/page-header.html, waltz-service/src/main/java/com/khartec/waltz/service/orgunit/OrganisationalUnitService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/OrganisationUnitEndpoint.java
+ some perf fixes 
+ cleaning up org unit filtering code
=> Fixing broken auth source button

waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-model/src/main/java/com/khartec/waltz/model/bookmark/Bookmark.java, waltz-ng/client/bookmarks/bookmark-editor.html, waltz-ng/client/bookmarks/bookmark-editor.js, waltz-ng/client/bookmarks/directives/bookmark-form.html, waltz-ng/client/bookmarks/directives/bookmark-form.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/BookmarksEndpoint.java
=> Fixing broken bookmark edit

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/static_panel/StaticPanelDao.java, waltz-model/src/main/java/com/khartec/waltz/model/staticpanel/ContentKind.java, waltz-model/src/main/java/com/khartec/waltz/model/staticpanel/StaticPanel.java, waltz-ng/client/main.js, waltz-ng/client/static-panel/directives/static-panel.html, waltz-ng/client/static-panel/directives/static-panel.js, waltz-ng/client/static-panel/directives/static-panels.html, waltz-ng/client/static-panel/directives/static-panels.js, waltz-ng/client/static-panel/index.js, waltz-ng/client/static-panel/services/static-panel-store.js, waltz-ng/client/welcome/welcome.html, waltz-ng/client/welcome/welcome.js, waltz-web/src/main/java/com/khartec/waltz/service/static_panel/StaticPanelService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticPanelEndpoint.java
=> Adding Static Panels to homepage etc

waltz-model/src/main/java/com/khartec/waltz/model/application/ApplicationKind.java, waltz-ng/client/applications/app-edit.html, waltz-ng/client/common/services/BaseLookupService.js, waltz-ng/client/common/services/display_names.js, waltz-ng/client/examples/demo-endpoint-application.html
- THIRD_PARTY, CUSTOMISED
- Updated docs
- Ensured drop down sorted alphabetically
#51
=> Adding more datatypes to application kind

waltz-model/src/main/java/com/khartec/waltz/model/bookmark/BookmarkKind.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/icon_names.js
=> Add performance monitoring to bookmark kinds

waltz-ng/client/applications/directives/app-table.js
=> Show overall investment status in app-tables

waltz-ng/client/applications/directives/app-overview.html, waltz-ng/client/applications/directives/asset-code-explorer.html, waltz-ng/client/org-units/directives/org-unit-name-popup.html
=> Giving asset_code popup a bit more space

waltz-ng/client/data-flow/directives/boingy-graph/boingy-graph.html
=> Consistent close icon

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/directives/app-group-summary.html, waltz-ng/client/asset-cost/directives/asset-costs-section.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/capabilities/directives/capability-summary.html, waltz-ng/client/capabilities/directives/capability-summary.js, waltz-ng/client/capabilities/index.js, waltz-ng/client/complexity/directives/complexity-section.html, waltz-ng/client/org-units/directives/org-unit-overview.html, waltz-ng/client/org-units/unit-view.html
=> Added scorecard to top of capability view

waltz-ng/client/person/directives/person-summary.html, waltz-ng/client/person/directives/person-summary.js, waltz-ng/client/person/index.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-ng/client/person/person-view.js
=> Added scorecard to top of person view

waltz-ng/client/app-groups/directives/app-group-summary.js, waltz-ng/client/asset-cost/services/asset-cost-utilities.js, waltz-ng/client/capabilities/directives/capability-summary.js, waltz-ng/client/complexity/services/complexity-utilities.js, waltz-ng/client/org-units/directives/org-unit-overview.js, waltz-ng/client/person/directives/person-summary.js, waltz-ng/client/server-info/services/server-utilities.js
=> Scorecard calculations common across people/groups/orgs/capabilities

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/asset_cost/AssetCostDao.java, waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/bookmark/BookmarkDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/end_user_app/EndUserAppDao.java, waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_info/ServerInfoDao.java, waltz-model/src/main/java/com/khartec/waltz/model/ProvenanceProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/authoritativesource/AuthoritativeSource.java, waltz-model/src/main/java/com/khartec/waltz/model/bookmark/Bookmark.java, waltz-model/src/main/java/com/khartec/waltz/model/cost/AssetCost.java, waltz-model/src/main/java/com/khartec/waltz/model/dataflow/DataFlow.java, waltz-model/src/main/java/com/khartec/waltz/model/enduserapp/EndUserApplication.java, waltz-model/src/main/java/com/khartec/waltz/model/involvement/Involvement.java, waltz-model/src/main/java/com/khartec/waltz/model/serverinfo/ServerInfo.java
=> Adding provenance to data entities

waltz-ng/client/main.js, waltz-ng/client/svg-diagram/directives/svg-diagram.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SvgDiagramEndpoint.java
=> Fixing mailto and shape detectors

waltz-ng/client/app-capabilities/edit.js, waltz-ng/client/app-groups/app-group-edit.js, waltz-ng/client/app-groups/directives/app-group-list-section.js, waltz-ng/client/applications/app-edit.js, waltz-ng/client/bookmarks/bookmark-editor.js, waltz-ng/client/data-flow/registration-view.js, waltz-ng/client/main.js, waltz-ng/client/ratings/ratings-editor.js, waltz-ng/package.json, waltz-ng/style/style.scss
=> Added user notification/feedback

pom.xml, waltz-common/pom.xml, waltz-common/src/main/java/com/khartec/waltz/common/XmlUtilities.java, waltz-ng/client/capabilities/list-view.js, waltz-ng/client/org-units/list-view.js, waltz-ng/client/svg-diagram/directives/svg-diagram.js, waltz-ng/package.json, waltz-service/src/main/java/com/khartec/waltz/service/svg/SvgDiagramService.java
This time we're processing on the severside as
java has better support for xml namespaces.
#16
=> Another attempt at getting visio to work

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/applications/directives/apps-by-investment-pie.html, waltz-ng/client/applications/directives/apps-by-investment-pie.js, waltz-ng/client/applications/directives/apps-by-lifecycle-phase-pie.html, waltz-ng/client/applications/directives/apps-by-lifecycle-phase-pie.js, waltz-ng/client/applications/index.js, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/directives/capability-scorecard.html, waltz-ng/client/capabilities/directives/capability-scorecard.js, waltz-ng/client/capabilities/directives/capability-summary.html, waltz-ng/client/capabilities/directives/capability-summary.js, waltz-ng/client/capabilities/index.js, waltz-ng/client/data-flow/directives/data-flows-by-direction-pie.html, waltz-ng/client/data-flow/directives/data-flows-by-direction-pie.js, waltz-ng/client/data-flow/directives/index.js, waltz-ng/client/org-units/directives/org-unit-overview.html, waltz-ng/client/org-units/directives/org-unit-overview.js, waltz-ng/client/person/directives/person-summary.html, waltz-ng/client/person/directives/person-summary.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html
=> Adding pies to people/groups/capabilities pages

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
- working around limitation in mysql 5.5.x
#102
=> Removing default timestamp values

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-view/app-view.html, waltz-ng/client/org-units/directives/org-unit-flow-viz.html, waltz-ng/client/org-units/directives/org-unit-overview.html, waltz-ng/client/org-units/directives/org-unit.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/ratings/directives/viewer/capability-multi-selector.html, waltz-ng/index.template.html
- added strict-di mode 
- angular will complain if dependencies aren't explicitly declared
=> Tidying up rating viewer config panel

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/applications/directives/app-table.html, waltz-ng/client/applications/directives/app-table.js, waltz-ng/client/asset-cost/directives/asset-cost-table.html, waltz-ng/client/asset-cost/directives/asset-cost-table.js, waltz-ng/client/asset-cost/directives/asset-costs-section.html, waltz-ng/client/asset-cost/directives/asset-costs-section.js, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/main.js, waltz-ng/client/org-units/unit-view.html
=> Exporting app and cost data from tables

pom.xml, waltz-web/src/main/java/com/khartec/waltz/web/Main.java
=> Refreshing external java libraries

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/InvolvementHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/InvolvementGenerator.java, waltz-ng/client/asset-cost/directives/asset-costs-section.html
switched to inner joins.  Not sure why jooq performance penalty is so high with 'in' clauses
=> Improving performance of employee view

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-model/src/main/java/com/khartec/waltz/model/person/Person.java
=>   Adding organisational_unit_id to person record

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/app-view/app-view.html, waltz-ng/client/bookmarks/bookmark-editor.html, waltz-ng/client/bookmarks/bookmark-editor.js, waltz-ng/client/bookmarks/directives/bookmarks-section.html, waltz-ng/client/bookmarks/directives/bookmarks-section.js, waltz-ng/client/bookmarks/index.js, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/common/index.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html
=> Support for Bookmarks on App Group, Capability and Org Unit views

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowStatsDao.java, waltz-data/src/main/java/com/khartec/waltz/data/database_usage/DatabaseDao.java, waltz-data/src/main/java/com/khartec/waltz/data/end_user_app/EndUserAppDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_info/ServerInfoDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EndUserAppHarness.java, waltz-ng/client/app-groups/app-group-edit.html, waltz-ng/client/end-user-apps/services/end-user-app-store.js, waltz-ng/client/org-units/directives/org-unit-tree.html, waltz-ng/client/org-units/directives/org-unit-tree.js, waltz-ng/client/org-units/index.js, waltz-ng/client/org-units/list-view.html, waltz-ng/client/org-units/list-view.js, waltz-ng/client/org-units/resolvers.js, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/application/ApplicationService.java, waltz-service/src/main/java/com/khartec/waltz/service/end_user_app/EndUserAppService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EndUserAppEndpoint.java
=> End User App Tallies in Org Unit Tree

waltz-ng/client/auth-sources/resolvers.js, waltz-ng/client/org-units/unit-view.html
=> Fix bug preventing editing of authoritative sources

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/data-flow/directives/boingy-graph/boingy-graph.js, waltz-ng/client/data-flow/directives/data-flows-tabgroup.html, waltz-ng/client/data-flow/directives/data-flows-tabgroup.js, waltz-ng/client/data-flow/services/data-flow-utility.js, waltz-ng/client/org-units/directives/org-unit-flow-viz.html, waltz-ng/client/org-units/directives/org-unit-flow-viz.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-ng/client/person/person-view.js
=> Fix bug neigbour colouring on boingy graph.

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/system/job_log/JobLogDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/JobLogHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/ChangeInitiativeGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/change_initiative/ChangeInitiative.java, waltz-model/src/main/java/com/khartec/waltz/model/entiy_relationship/EntityRelationship.java, waltz-model/src/main/java/com/khartec/waltz/model/system/job_log/JobLog.java, waltz-model/src/main/java/com/khartec/waltz/model/system/job_log/JobStatus.java, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/common/services/display_names.js, waltz-ng/client/data-flow/directives/data-flows-tabgroup.html, waltz-ng/client/data-flow/directives/flow-cloud-diagram.js, waltz-ng/client/data-flow/directives/slope-graph/slope-graph-diagram.js, waltz-ng/client/main.js, waltz-ng/client/org-units/directives/org-unit-overview.html, waltz-ng/client/source-data-rating/directives/source-data-info.html
=> Merging change initiative enhancements, IE fixes and initial job log support

waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-ng/client/involvement/services/involvement-store.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-service/src/main/java/com/khartec/waltz/service/involvement/InvolvementService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementEndpoint.java
=> Add Change Initiatives to person-view

waltz-ng/client/data-flow/directives/data-flows-tabgroup.html
=> Shrink the logical dataflows cloud diagram

waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/data-flow/directives/data-flows-tabgroup.html
=> Shrink cloud diagram and add displaynames to feed summary

waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowDao.java
=> Slow to calculate rated dataflows for larger groups

waltz-common/src/main/java/com/khartec/waltz/common/FunctionUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_relationship/EntityRelationshipDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_info/ServerInfoDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/HarnessUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/ServerHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/AppGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/ServerGenerator.java, waltz-ng/client/app-groups/app-group-edit.html, waltz-ng/client/app-groups/app-group-edit.js, waltz-ng/client/app-groups/services/app-group-store.js, waltz-ng/client/applications/directives/app-selector.html, waltz-ng/client/applications/directives/app-selector.js, waltz-ng/client/change-initiative/services/change-initiative-store.js, waltz-ng/client/footer/footer.html, waltz-ng/client/navbar/navbar.html, waltz-ng/client/playpen/change-initiative-selector.html, waltz-ng/client/playpen/change-initiative-selector.js, waltz-ng/client/playpen/index.js, waltz-ng/client/playpen/playpen.html, waltz-ng/client/playpen/playpen.js, waltz-ng/client/user/services/user-service.js, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-web/README.md, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AppGroupEndpoint.java, waltz-web/src/main/resources/logback.xml
=> Performance and Change Initiatives in App Groups view

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-model/src/main/java/com/khartec/waltz/model/applicationcapability/ApplicationCapability.java, waltz-model/src/main/java/com/khartec/waltz/model/capability/Capability.java
=> Provenance / Nullable descriptions

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> add last_import to source_data_rating

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> make last_update in source_data_rating not nullable

waltz-common/src/main/java/com/khartec/waltz/common/DateTimeUtilities.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-data/src/main/java/com/khartec/waltz/data/user_agent_info/UserAgentInfoDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/UserAgentInfoHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/UserNameProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/user/User.java, waltz-model/src/main/java/com/khartec/waltz/model/user_agent_info/UserAgentInfo.java, waltz-ng/client/main.js, waltz-ng/client/modules.js, waltz-ng/client/routes.js, waltz-ng/client/thirdparty-setup.js, waltz-ng/client/user/index.js, waltz-ng/client/user/services/user-agent-info-store.js, waltz-service/src/main/java/com/khartec/waltz/service/user_agent_info/UserAgentInfoService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/UserAgentInfoEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/json/BrowserInfo.java
- bonus: cleaned up main.js
#222
=> Recording user agent (with last login date)

waltz-ng/client/app-groups/app-group-edit.html, waltz-ng/client/app-groups/app-group-edit.js, waltz-ng/client/app-groups/directives/app-group-app-selection-list.html, waltz-ng/client/app-groups/directives/app-group-list-section.html, waltz-ng/client/applications/app-registration.html, waltz-ng/client/applications/app-registration.js, waltz-ng/client/applications/routes.js, waltz-ng/client/auth-sources/edit.js, waltz-ng/client/bookmarks/directives/bookmark-form.html, waltz-ng/client/complexity/directives/complexity-section.html, waltz-ng/client/data-flow/directives/boingy-graph/boingy-graph.html, waltz-ng/client/data-flow/directives/rated-flow-chart/rated-flow-detail.html, waltz-ng/client/settings/settings-view.html, waltz-ng/client/traits/directives/trait-usage-editor.html, waltz-ng/client/user/user-management.html, waltz-ng/client/widgets/error-alert.html, waltz-ng/package.json, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java
=> Upgrading to Angular 1.5

curret_future.md
=> Documentation

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-ng/client/person/directives/person-summary.html, waltz-ng/client/profile/view.html, waltz-ng/client/profile/view.js
- added an index
- added directs/mgrs
- added link from person view
- bonus: fixed entity_stats_defn for mariadb
#251
=> Improve navigation of profile pages and add an index

waltz-ng/client/entity-statistics/directives/entity-statistic-section.html
=> Swap positon of Outcome and Name

waltz-ng/client/auth-sources/directives/auth-sources-table.html, waltz-ng/client/data-type-usage/directives/app-data-type-usage-editor.html, waltz-ng/client/data-type-usage/directives/app-data-type-usage-list.html, waltz-ng/client/data-type-usage/usage-kinds.js, waltz-ng/client/org-units/unit-view.html
=> Tidy up Auth sources

waltz-ng/client/navbar/navbar.html, waltz-ng/client/user/directives/has-role.js, waltz-ng/client/user/directives/if-anonymous.js, waltz-ng/style/_bootstrap-styles.scss, waltz-ng/style/_waltz.scss
=> Fix styling for dropdown menus

waltz-ng/client/applications/directives/app-table-name-celltemplate.html, waltz-ng/client/applications/directives/app-table.html, waltz-ng/client/applications/directives/app-table.js
- icon for info panel
- adjustments to info panel message for End User Apps
- disable 'more' link for end user apps
#277
#259
=> App portfolio adjustments

waltz-ng/client/applications/directives/app-table-name-celltemplate.html, waltz-ng/client/asset-cost/directives/asset-cost-table.js, waltz-ng/client/end-user-apps/directives/end-user-app-table.js, waltz-ng/client/involvement/directives/involved-people-section.js
=> Use ng-bind for cellTemplates and not {{ }}

waltz-common/src/main/java/com/khartec/waltz/common/CollectionUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataTypeUsageEndpoint.java
=> Logging data type changes

waltz-ng/client/widgets/page-header.js
=> Setting page titles

.travis.yml, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/applications/directives/app-summary.html, waltz-ng/client/applications/directives/app-table.html, waltz-ng/client/applications/directives/app-table.js, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/common/services/BaseLookupService.js, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/common/tally-utils.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view.js, waltz-ng/client/process/view.html, waltz-ng/client/process/view.js, waltz-ng/client/ratings/directives/common.js, waltz-ng/test/common/test_shallowDiff.js, waltz-ng/test/ratings/test_calculateGroupSummary.js
=> Fixed client side unit tests and integrated with travis

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/applications/directives/app-summary.html, waltz-ng/client/applications/directives/app-table.html, waltz-ng/client/applications/directives/app-table.js, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/common/tally-utils.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view.js, waltz-ng/client/process/view.html, waltz-ng/client/process/view.js
=> Application Summary and Portfolio across all aggregated views

waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/data-load.js, waltz-ng/client/change-log/directives/change-log-section.html, waltz-ng/client/change-log/directives/change-log-table.html, waltz-ng/client/change-log/directives/change-log-table.js, waltz-ng/client/change-log/index.js, waltz-ng/client/change-log/routes.js, waltz-ng/client/change-log/services/change-log-data.js, waltz-ng/client/change-log/view.html, waltz-ng/client/change-log/view.js, waltz-service/src/main/java/com/khartec/waltz/service/changelog/ChangeLogService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeLogEndpoint.java
=> Limiting Change log entries on app-view page

waltz-ng/client/applications/directives/app-table-name-celltemplate.html, waltz-ng/client/applications/directives/app-table.js
=> Fix for app table not working on package build

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDefinitionDao.java, waltz-ng/client/common/services/icon_names.js, waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.html, waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.scss, waltz-ng/client/entity-statistics/services/entity-statistic-store.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_statistic/EntityStatisticService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityStatisticEndpoint.java
=> entity-statistic-card improvements

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDefinitionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticValueDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EntityStatisticGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SampleData.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_statistic/EntityStatisticDefinition.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_statistic/StatisticCategory.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_statistic/StatisticType.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_statistic/StatisticValueState.java
=> visibility modifiers

waltz-ng/client/auth-sources/edit.js, waltz-ng/client/org-units/unit-view.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AuthoritativeSourceEndpoint.java
=> Auth Source edit btn perms

waltz-data/src/main/java/com/khartec/waltz/data/asset_cost/AssetCostDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/AssetCostHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/AssetCostGenerator.java, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/asset-cost/services/asset-cost-store.js, waltz-ng/client/asset-cost/services/asset-cost-view-service.js, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-service/src/main/java/com/khartec/waltz/service/asset_cost/AssetCostService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssetCostEndpoint.java
=> Asset cost views will always try to show latest year.

waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.html, waltz-ng/client/entity-statistics/directives/entity-statistic-summary-section.html
=> ent stat summary card col-md-4

waltz-ng/client/common/index.js, waltz-ng/client/entity-statistics/entity-statistic-view.js
=> Fix for old values in ent stat view spilling over to new criteria

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDao.java
=> Speed up ent-stat query

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EntityStatisticGenerator.java, waltz-ng/client/entity-statistics/entity-statistic-view.js
=> Eager load of summary data, then related later.

waltz-ng/client/entity-statistics/person-entity-statistic-view.js
-lazy loading of related summaries and values
#339
=> - fix for old values in person ent stat view spilling over to new criteria

waltz-ng/client/applications/components/apps-by-investment-pie.html, waltz-ng/client/applications/components/apps-by-investment-pie.js, waltz-ng/client/applications/components/apps-by-lifecycle-phase-pie.html, waltz-ng/client/applications/components/apps-by-lifecycle-phase-pie.js, waltz-ng/client/applications/index.js
=> Fixing broken pie labels

waltz-ng/client/technology/components/group-technology-summary.js
=> Fixing broken tech section

waltz-ng/client/applications/components/app-summary.js, waltz-ng/client/common/colors.js
=> Fixing awful pie color schemes

waltz-jobs/src/main/java/com/khartec/waltz/jobs/OrgUnitTreeHarness.java, waltz-ng/client/process/view.js
=> Fixing process page

waltz-ng/client/widgets/pie-segment-table.html, waltz-ng/client/widgets/pie-segment-table.js
=> Include percentages in pie chart tables

waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.html, waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.js, waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/main.js
=> Include asset code in entity statistic detail table

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Adding index to hierarchy table

waltz-ng/client/applications/directives/app-table.js
=> Application table showing incorrect filter type for asset code column

waltz-data/src/main/java/com/khartec/waltz/data/capability_rating/CapabilityRatingDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/AppCapabilityHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/JooqHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/capabilityrating/CapabilityRating.java, waltz-ng/client/applications/app-view.js, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/org-units/directives/org-unit-overview.js, waltz-ng/client/ratings/directives/common.js, waltz-ng/client/ratings/directives/rating-explorer/rating-explorer-section.js, waltz-ng/client/ratings/ratings-editor.js, waltz-ng/client/ratings/services/ratings-store.js, waltz-service/src/main/java/com/khartec/waltz/service/capability_rating/CapabilityRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/capability_usage/CapabilityUsageService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/CapabilityRatingEndpoint.java
=> Capability Rating now using simplified descriptor object

waltz-ng/client/ratings/directives/rating-explorer/rating-explorer-section.html, waltz-ng/client/ratings/directives/rating-explorer/rating-explorer-section.js
=> App Capability Rating Tree needs overhaul

waltz-ng/client/navbar/directives/navbar-profile.js, waltz-ng/client/navbar/directives/navbar.html, waltz-ng/client/navbar/directives/navbar.js
=> Missing overlay in header

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-ng/client/data-flow/data-flow-edit.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow/DataFlowService.java
=> Prevent logical feeds from referencing same app as target and source

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/AppHarness.java
=> Fix for search not working with searches like 'P&S Blotter'

waltz-ng/client/ratings/directives/rating-explorer/rating-explorer-section.html, waltz-ng/client/ratings/directives/rating-explorer/rating-explorer-section.js
=> Aborted the task, but keeping the refactorings

waltz-common/src/main/java/com/khartec/waltz/common/EnumUtilities.java, waltz-common/src/test/java/com/khartec/waltz/common/EnumUtilities_readEnum.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDefinitionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/OrganisationalUnitDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntityStatisticHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EntityStatisticGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_statistic/EntityStatisticDefinition.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_statistic/RollupKind.java, waltz-ng/client/applications/app-view.html, waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.js, waltz-ng/client/entity-statistics/directives/entity-statistic-section.html, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/services/entity-statistic-store.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_statistic/EntityStatisticService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityStatisticEndpoint.java
- SUM BY VALUE
- COUNT BY ENTITY
#394
=> Entity Statistic Summaries now support two rollup strategies:

waltz-ng/.eslintrc, waltz-ng/client/common/index.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-ng/client/playpen/3/playpen3.scss, waltz-ng/client/widgets/page-header.html, waltz-ng/client/widgets/page-header.js, waltz-ng/client/widgets/page-header.scss, waltz-ng/style/_util.scss
=> Make sure page title is visible when scrolling

waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.html
=> Make entity stats section on aggregate pages more appealing

waltz-ng/client/common/colors.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js
=> Entity Stats detail not working for people

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> User preference 767 byte primary key error on MariaDB UTF8

.travis.yml, waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> travis maria utf8 to spot liquibase errors

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java
=> DataType page model - add parent id and id to DataType

waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/icon_names.js
=> DataType page model - register entitykind, display and icon names

waltz-ng/client/system/hierarchies-view.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java
=> DataType page model - support for building entity hierarchy for DATA_TYPE

waltz-data/src/main/java/com/khartec/waltz/data/server_info/ServerInfoDao.java, waltz-model/src/main/java/com/khartec/waltz/model/serverinfo/ServerInfo.java
=> OS and HW eol

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_statistic/RollupKind.java, waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.html, waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.js, waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.html, waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.js, waltz-ng/client/entity-statistics/entity-statistic-utilities.js, waltz-ng/client/widgets/pie-segment-table.html, waltz-ng/client/widgets/pie-segment-table.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_statistic/EntityStatisticService.java
- Added optional pie chart table headings
#428
=> Entitity Stats: Support AVG_BY_VALUE rollup kind

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Removing FK's to make batch operations simpler

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/UnknownFlowGenerator.java, waltz-ng/client/playpen/3/playpen3.scss
-also a compile error due to data type record constructor parameter mismatch
#449
=> Fix Auth source colours faded out.

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/UnknownFlowGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/user/Role.java, waltz-ng/client/navbar/directives/navbar.html, waltz-ng/client/navbar/directives/navbar.js, waltz-ng/client/playpen/3/playpen3.scss, waltz-ng/client/user/user-management.html
Data Types visible to BETA_TESTER role
#448
=> Make the data type tab a sneak preview feature

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/capability/CapabilityDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/EntityHierarchyDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/EntityRootsSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/OrganisationalUnitDao.java, waltz-data/src/main/java/com/khartec/waltz/data/process/ProcessDao.java, waltz-ng/client/common/index.js, waltz-ng/client/system/hierarchies-view.html, waltz-ng/client/system/hierarchies-view.js, waltz-ng/client/system/services/hierarchies-store.js, waltz-service/src/main/java/com/khartec/waltz/service/capability/CapabilityService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityHierarchyEndpoint.java
=> Ability to view entity roots to help identify orphans

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/capability/CapabilityDao.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/EntityHierarchyDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/EntityRootsSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/OrganisationalUnitDao.java, waltz-data/src/main/java/com/khartec/waltz/data/process/ProcessDao.java, waltz-ng/client/common/index.js, waltz-ng/client/involvement/directives/involved-people-section.js, waltz-ng/client/involvement/involvement-utils.js, waltz-ng/client/system/hierarchies-view.html, waltz-ng/client/system/hierarchies-view.js, waltz-ng/client/system/services/hierarchies-store.js, waltz-service/src/main/java/com/khartec/waltz/service/capability/CapabilityService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityHierarchyEndpoint.java
=> Involvement records on App page shown incorrectly if the same person has more than one role

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_statistic/EntityStatisticService.java
=> Detail version of Pre calculated stats

waltz-ng/style/_waltz.scss
=> Dataflow decorators

waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java, waltz-ng/client/common/checks.js, waltz-ng/client/data-type-usage/components/data-type-usage-stat-table.html, waltz-ng/client/data-type-usage/components/data-type-usage-stat-table.js, waltz-ng/client/data-type-usage/index.js, waltz-ng/client/data-type-usage/services/data-type-usage-store.js, waltz-ng/client/data-types/components/data-type-overview.html, waltz-ng/client/data-types/components/data-type-overview.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/client/widgets/basic-info-tile.scss, waltz-service/src/main/java/com/khartec/waltz/service/usage_info/DataTypeUsageService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataTypeUsageEndpoint.java
=> Basic DataType Usage overiew

waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/AuthSourceHarness.java, waltz-ng/client/auth-sources/components/auth-sources-list.html, waltz-ng/client/auth-sources/components/auth-sources-list.js, waltz-ng/client/auth-sources/index.js, waltz-ng/client/auth-sources/services/auth-sources-store.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AuthoritativeSourceEndpoint.java
=> Authoritative Sources for data types view

waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/person/person-view.html, waltz-ng/index.template.html
=> Minor cosmetic changes

waltz-ng/client/entity-statistics/entity-statistic-utilities.js
=> Missing pie chart table heading for stat rollup kind: NONE

waltz-ng/client/applications/directives/app-table.html, waltz-ng/client/person/person-view-data.js
=> Person Page: App involvement showing duplicate app listings

waltz-ng/client/data-flow/directives/data-flow-table.html
=> Remove empty data type column from data flow table

waltz-ng/client/data-types/data-type-list.js
=> Data Type index page block processor incorrect

waltz-ng/client/data-types/components/data-type-overview.html, waltz-ng/client/data-types/components/data-type-overview.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/services/data-type-view-data.js
=> Remove Cost & Inidicators from data-type page

waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.scss, waltz-ng/client/data-types/components/rated-flow-boingy-graph.html, waltz-ng/client/data-types/components/rated-flow-boingy-graph.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/data-type-view.js, waltz-ng/client/data-types/index.js, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js
=> Data Type page now has it's own (rated) boingy graph

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowStatsDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/DataFlowDecoratorDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowDecoratorHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityIdSelectionOptions.java, waltz-model/src/main/java/com/khartec/waltz/model/IdSelectionOptions.java, waltz-ng/client/data-flow-decorator/services/data-flow-decorator-store.js, waltz-ng/client/data-flow/services/data-flow-store.js, waltz-ng/client/data-flow/services/data-flow-view-service.js, waltz-ng/client/data-type-usage/services/data-type-usage-store.js, waltz-ng/client/data-types/components/rated-flow-boingy-graph.html, waltz-ng/client/data-types/components/rated-flow-boingy-graph.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/data-type-view.js, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow/DataFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorRatingsService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataFlowDecoratorEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataFlowsEndpoint.java
=> data-type page - use app selector instead of client side filtering

waltz-jobs/src/main/java/com/khartec/waltz/jobs/ApplicationIdSelectorHarness.java, waltz-ng/client/data-types/data-type-view.js
=> data-type page - custom queries that don't use app selector

waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js, waltz-ng/client/entity-statistics/utilities.js
=> WIP - new data type selector query support

waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/ApplicationIdSelectorHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataTypeUsageHarness.java, waltz-ng/client/data-types/data-type-view.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow/DataFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/usage_info/DataTypeUsageService.java
=> DataType usage not updated when changed flows

waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataTypeUsageHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/usage_info/DataTypeUsageService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataTypeUsageEndpoint.java
=> bulk recalculate

waltz-ng/client/app-capabilities/directives/app-capability-section.html, waltz-ng/client/app-capabilities/directives/app-capability-usage-editor.html, waltz-ng/client/app-capabilities/edit.html, waltz-ng/client/app-capabilities/edit.js, waltz-ng/client/applications/app-view.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/directives/capability-picker.html, waltz-ng/client/capabilities/directives/capability-scorecard.html, waltz-ng/client/capabilities/directives/capability-selector-modal.html, waltz-ng/client/capabilities/directives/capability-selector.html, waltz-ng/client/capabilities/list-view.html, waltz-ng/client/common/services/display_names.js, waltz-ng/client/navbar/directives/navbar.js, waltz-ng/client/org-units/directives/org-unit-overview.html, waltz-ng/client/person/directives/person-summary.html, waltz-ng/client/process/view.html, waltz-ng/client/ratings/directives/rating-explorer/rating-explorer-section.html
=> Rename capabilities to functions (sniff)

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/DataTypeGenerator.java
=> DataType sample generator should include ids

waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/AuthSourceHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/Entry.java, waltz-ng/client/auth-sources/components/auth-sources-list.html, waltz-ng/client/auth-sources/components/auth-sources-list.js, waltz-ng/client/auth-sources/services/auth-sources-store.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AuthoritativeSourceEndpoint.java
=> Added consumers to DT auth source section

waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/data-types/components/rated-flow-boingy-graph.html, waltz-ng/client/data-types/components/rated-flow-boingy-graph.js
=> boingy filtering and safety

waltz-ng/client/technology/directives/technology-section.js, waltz-ng/style/_grid.scss
- Renamed * End of Life columns to EOL to save grid header space
#509
=> Highlight server/database EOL status in grids

waltz-ng/client/auth-sources/components/auth-sources-list.html, waltz-ng/client/data-flow/directives/flow-filter-options-overlay.scss, waltz-ng/client/data-types/components/rated-flow-boingy-graph.html, waltz-ng/client/data-types/components/rated-flow-boingy-graph.js, waltz-ng/client/data-types/data-type-view.html
=> Making data type graph filter into checkboxes 

waltz-ng/client/auth-sources/resolvers.js, waltz-ng/client/navbar/directives/navbar-profile.html, waltz-ng/client/navbar/directives/navbar.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/user/directives/has-role.js, waltz-ng/client/user/directives/if-anonymous.js, waltz-ng/client/user/directives/unless-role.js, waltz-ng/style/_bootstrap-styles.scss
=> Auth Sources cannot be edited

waltz-common/src/main/java/com/khartec/waltz/common/DateTimeUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PersonDataGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/EndOfLifeStatus.java, waltz-model/src/main/java/com/khartec/waltz/model/database_information/DatabaseInformation.java, waltz-model/src/main/java/com/khartec/waltz/model/database_information/DatabaseSummaryStatistics.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerInformation.java, waltz-ng/client/common/colors.js, waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/technology/components/group-technology-summary.js, waltz-ng/client/technology/directives/technology-section.js, waltz-ng/client/technology/services/technology-statistics-service.js
- Moved EOL calculation from client to server
- Updated PersonDataGenerator to rebuild person hierarchy
#497
=> Database Information Rollups

waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DatabaseHarness.java
=> Fix: db EOL rollups when running on SQL Server

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/end_user_app/EndUserAppDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EndUserAppMaker.java, waltz-model/src/main/java/com/khartec/waltz/model/Criticality.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/enduserapp/EndUserApplication.java, waltz-ng/client/applications/app-edit.js, waltz-ng/client/applications/components/app-summary.js, waltz-ng/client/applications/directives/app-overview.html, waltz-ng/client/applications/directives/app-table.html, waltz-ng/client/common/colors.js, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/end-user-apps/directives/end-user-app-table.js
=> Add Business_Criticality field

waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/process/view.js
=> put App Group view in history

waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/DataFlowDecoratorDao.java, waltz-ng/client/auth-sources/services/auth-sources-utils.js, waltz-ng/client/data-flow/directives/data-flows-tabgroup.js, waltz-ng/client/data-flow/services/data-flow-utility.js, waltz-ng/client/data-flow/services/data-flow-view-service.js
-- Fix: data flow tables show both incoming and outgoing flows for group
#522
=> Boingy graphs now coloured

waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/ServerGenerator.java
=> Server count rollups should handle duplicate host names

waltz-ng/client/data-flow/components/app-centric-flow-table/app-centric-flow-table.html, waltz-ng/client/data-flow/components/app-centric-flow-table/app-centric-flow-table.js, waltz-ng/client/data-flow/components/app-centric-flow-table/app-centric-flow-table.scss, waltz-ng/client/data-flow/components/index.js, waltz-ng/client/data-types/components/rated-flow-boingy-graph.html, waltz-ng/client/data-types/components/rated-flow-boingy-graph.js, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/style/_waltz.scss
=> App Centric Data flow details table

waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java
=> Fix bug when running under SQL Server

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html
=> Adding auth source section to pages.

waltz-ng/client/common/componets/index.js, waltz-ng/client/common/componets/multi-select-treecontrol.html, waltz-ng/client/common/componets/multi-select-treecontrol.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js
=> Multi select tree control

waltz-ng/client/data-flow/components/source-and-target-graph/source-and-target.js, waltz-ng/client/data-flow/services/data-flow-store.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js
=> Source and Target graph improvements

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/database_information/DatabaseSummaryStatistics.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerSummaryStatistics.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/databases/directives/database-pies.html, waltz-ng/client/databases/directives/database-pies.js, waltz-ng/client/server-info/directives/server-pies.html, waltz-ng/client/server-info/directives/server-pies.js, waltz-ng/client/technology/components/group-technology-summary.html, waltz-ng/client/technology/components/group-technology-summary.js, waltz-service/src/main/java/com/khartec/waltz/service/usage_info/DataTypeUsageService.java
- Fix data type usage calculation when running under MariaDB
#518
=> Add EOL Status pie charts

waltz-model/src/main/java/com/khartec/waltz/model/datatype/DataType.java, waltz-ng/client/common/componets/index.js, waltz-ng/client/common/componets/multi-select-tree-control/multi-select-tree-control.scss, waltz-ng/client/common/componets/multi-select-tree-control/multi-select-treecontrol.html, waltz-ng/client/common/componets/multi-select-tree-control/multi-select-treecontrol.js, waltz-ng/client/data-flow/components/edit/data-flow-type-editor.html, waltz-ng/client/data-flow/components/edit/data-flow-type-editor.js, waltz-ng/style/_waltz.scss
=> integrate multi select tree control into data flow data type editor

waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/components/app-costs-section/app-costs-section.html, waltz-ng/client/applications/components/app-costs-section/app-costs-section.js, waltz-ng/client/applications/index.js, waltz-ng/client/asset-cost/services/asset-cost-store.js, waltz-ng/client/asset-cost/services/asset-cost-view-service.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js
=> App Asset Cost improvements

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Update index on entity_statistic_value

waltz-ng/client/modules.js, waltz-ng/client/navbar/directives/navbar-recently-viewed.html, waltz-ng/client/welcome/components/recently-viewed-section/recently-viewed-section.html, waltz-ng/client/welcome/components/recently-viewed-section/recently-viewed-section.js, waltz-ng/client/welcome/index.js, waltz-ng/client/welcome/welcome.html, waltz-ng/client/welcome/welcome.js, waltz-ng/style/_waltz.scss
=> Homepage improvements

waltz-jobs/src/main/java/com/khartec/waltz/jobs/PersonHarness.java, waltz-ng/client/auth-sources/services/auth-sources-store.js, waltz-ng/client/data-type-usage/services/data-type-usage-store.js, waltz-ng/client/navbar/directives/navbar-profile.html, waltz-ng/client/system/hierarchies-view.html, waltz-ng/client/system/hierarchies-view.js, waltz-ng/client/system/recalculate-view.html, waltz-ng/client/system/recalculate-view.js, waltz-ng/client/system/routes.js, waltz-ng/client/system/settings-view.html, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/system/system-admin-list.js, waltz-ng/client/user/user-log.html, waltz-ng/client/user/user-management.html, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java, waltz-service/src/main/java/com/khartec/waltz/service/jmx/PersonMaintenance.java, waltz-service/src/main/java/com/khartec/waltz/service/person_hierarchy/PersonHierarchyService.java
=> Improving Admin screens

waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.html, waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.scss, waltz-ng/client/data-flow/components/data-flows-tabgroup/data-flows-tabgroup.html, waltz-ng/client/data-flow/components/data-flows-tabgroup/data-flows-tabgroup.js, waltz-ng/client/data-flow/components/data-flows-tabgroup/data-flows-tabgroup.scss, waltz-ng/client/data-flow/components/index.js, waltz-ng/client/data-flow/directives/index.js, waltz-ng/client/data-flow/services/data-flow-utility.js, waltz-ng/client/data-flow/services/data-flow-view-service.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/process/view.js, waltz-ng/style/_waltz.scss
- took opportunity to clean up code
- and convert into component
#546
=> Fixing boingy graph popup

pom.xml
=> Update to Spark 2.5

waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/OrphanHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/orphan/OrphanRelationship.java, waltz-model/src/main/java/com/khartec/waltz/model/orphan/OrphanSide.java, waltz-ng/client/modules.js, waltz-ng/client/orphan/index.js, waltz-ng/client/orphan/services/orphan-store.js, waltz-ng/client/system/hierarchies-view.html, waltz-ng/client/system/hierarchies-view.js, waltz-service/src/main/java/com/khartec/waltz/service/orphan/OrphanService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/OrphanEndpoint.java
- Apps with non existent Org Units
- App Caps with missing Apps or Caps
- Auth Sources with missing Org Units
#443
=> Orphan Entity View

waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/DatabaseGenerator.java
- Update database generator to include duplicates
#556
=> Database information rollups should handle duplicate instances

waltz-ng/client/routes.js, waltz-ng/client/system/index.js, waltz-ng/client/system/named-settings.js, waltz-ng/client/system/services/nag-message-service.js
=> Add nag notification if non-beta user using beta server

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntityStatisticHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EntityStatisticGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/Duration.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_statistic/EntityStatisticService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityStatisticEndpoint.java
- Update entity stat generator to include rollup kind: NONE
#560
=> Indicator History: API support

waltz-ng/client/entity-statistics/components/related-entity-statistics-summaries.html, waltz-ng/client/entity-statistics/entity-statistic-view.html
=> Indicator History: Page layout changes

waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/icon_names.js
=> Add 'System' EntityKind

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityStatisticEndpoint.java
=> Entity Statistic history added to ent-stat-view page

waltz-ng/client/entity-statistics/services/entity-statistic-store.js
=> Doesn't work with Duration.ALL

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntityStatisticHarness.java
=> Historic entity statistics do not work with duration 'ALL'

waltz-ng/client/entity-statistics/components/history-chart/entity-statistic-history-chart.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js
=> Adding statistic history to person stat pages

waltz-ng/client/main.js, waltz-ng/index.template.html, waltz-ng/package.json, waltz-ng/style/style.scss
=> Generic progress indicator

waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/application/search/SqlServerAppSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/capability/search/SqlServerCapabilitySearch.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/search/SqlServerChangeInitiativeSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/search/SqlServerOrganisationalUnitSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/person/search/SqlServerPersonSearch.java
=> FT Search handles 'bad' characters

waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/data-types/data-type-view.html, waltz-ng/client/navbar/directives/navbar.js
=> Rename Data Type to Data on main pages

waltz-local-config/src/main/resources/logback.xml
=> Rolling log file example config

waltz-ng/client/data-types/components/data-type-tree.html, waltz-ng/client/data-types/components/data-type-tree.js, waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.html, waltz-ng/client/entity/components/entity-hierarchy-navigator.html, waltz-ng/client/org-units/directives/org-unit-tree.html, waltz-ng/client/process/view.html, waltz-ng/client/ratings/directives/viewer/capability-multi-selector.html
=> Ordering trees

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Adding indexes to asset_cost

waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-ng/client/orphan/services/orphan-store.js, waltz-ng/client/system/orphans-view.js, waltz-service/src/main/java/com/khartec/waltz/service/orphan/OrphanService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/OrphanEndpoint.java
=> Identify orphan change initiatives

waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowStatsDao.java
=> DataFlowStatsDao - remove timing wrappers

waltz-ng/client/common/index.js, waltz-ng/client/entity-statistics/components/history-chart/entity-statistic-history-chart.js, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js
=> Stat graph clears on refocus

waltz-ng/client/org-units/directives/org-unit-overview.html
=> Show child nav if at top of OU tree

waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java
=> Parallelize DB summary stat calculations

waltz-ng/client/entity/components/immediate-hierarchy-navigator/immediate-hierarchy-navigator.html
=> Fix ou nav links on ou overview

waltz-ng/client/org-units/components/overview/org-unit-overview.html, waltz-ng/client/org-units/unit-view.html
=> Lazy load ou tree on ou-view page

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EndUserAppInvolvmentGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EndUserAppMaker.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowDecorationGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowGenerator.java, waltz-ng/client/complexity/services/complexity-store.js, waltz-ng/client/involvement/services/involvement-store.js, waltz-ng/client/person/directives/person-directs-list.html, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-ng/client/person/person-view.js, waltz-ng/client/system/recalculate-view.html, waltz-ng/client/system/recalculate-view.js
=> Optimising person view

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDefinitionDao.java, waltz-model/src/main/java/com/khartec/waltz/model/immediate_hierarchy/ImmediateHierarchy.java, waltz-model/src/main/java/com/khartec/waltz/model/immediate_hierarchy/ImmediateHierarchyUtilities.java, waltz-ng/client/entity-statistics/components/related-entity-statistics-summaries.html, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js, waltz-ng/client/entity-statistics/utilities.js, waltz-web/src/test/java/com/khartec/waltz/model/immediate_hierarchy/ImmediateHierarchyUtilitiesTest.java
=> Indicator detail view: Only show children as related indicators

waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.html, waltz-ng/client/entity-statistics/entity-statistic-view.js
=> Indicators: RollupKind NONE should not show grid on detail page

waltz-ng/client/org-units/services/org-unit-view-data.js
=> Fix - broken rating colors

waltz-ng/client/applications/components/apps-by-investment-pie.js, waltz-ng/client/common/index.js, waltz-ng/client/org-units/components/overview/org-unit-overview.js, waltz-ng/client/org-units/unit-view.js
=> Fixing some timing issues with ou-view

waltz-data/src/main/java/com/khartec/waltz/data/application/AppTagDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orgunit/OrganisationalUnitDao.java, waltz-model/src/main/java/com/khartec/waltz/model/appview/AppView.java, waltz-ng/client/alias/services/alias-store.js, waltz-ng/client/applications/app-edit.html, waltz-ng/client/applications/app-edit.js, waltz-ng/client/applications/app-view.js, waltz-ng/client/applications/resolvers.js, waltz-ng/client/applications/routes.js, waltz-ng/client/applications/services/application-store.js, waltz-ng/client/applications/services/application-view-store.js, waltz-ng/client/applications/services/index.js, waltz-ng/client/data-flow/components/source-and-target-graph/source-and-target.js, waltz-ng/client/ratings/directives/common.js, waltz-service/src/main/java/com/khartec/waltz/service/app_view/AppViewService.java, waltz-service/src/main/java/com/khartec/waltz/service/application/ApplicationService.java, waltz-service/src/main/java/com/khartec/waltz/service/orgunit/OrganisationalUnitService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java
=> Optimise app-view page loading

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_article/DataArticleDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/DataArticleGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/data_article/DataArticle.java, waltz-model/src/main/java/com/khartec/waltz/model/data_article/DataFormat.java, waltz-service/src/main/java/com/khartec/waltz/service/data_article/DataArticleService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataArticleEndpoint.java
=> Data Article

waltz-common/src/main/java/com/khartec/waltz/common/CollectionUtilities.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_article/DataArticleDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_data_flow/PhysicalDataFlowDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/DataArticleGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalDataFlowGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/data_article/DataArticle.java, waltz-model/src/main/java/com/khartec/waltz/model/data_article/DataFormatKind.java, waltz-model/src/main/java/com/khartec/waltz/model/dataflow/DataFlowDirection.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_data_flow/FrequencyKind.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_data_flow/PhysicalDataFlow.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_data_flow/TransportKind.java
=> Physical Data Flow

waltz-data/src/main/java/com/khartec/waltz/data/physical_data_flow/PhysicalDataFlowDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalDataFlowGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_data_article/DataFormatKind.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_data_flow/FrequencyKind.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_data_flow/TransportKind.java, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/physical-data-articles/components/physical-data-section.html, waltz-ng/client/physical-data-articles/components/physical-data-section.js, waltz-ng/client/physical-data-articles/index.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js
=> Gui panel added (requires BETA_TESTER role)

waltz-ng/client/data-flow/components/index.js, waltz-ng/client/physical-data-articles/components/physical-data-section.html, waltz-ng/client/physical-data-articles/components/physical-data-section.js, waltz-ng/client/playpen/1/playpen1.js
=> Gui panel enhancements

waltz-service/src/main/java/com/khartec/waltz/service/DIConfiguration.java
=> jOOQ: Disable SQL formatting and logging if prod build

waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java
#646
**Old timings:**
-- dur [stats]:2062
-- dur [stats]:2035
-- dur [stats]:1835
-- dur [stats]:1919
-- dur [stats]:1970
avg: 1964
**New timings:**
-- dur [stats]:855
-- dur [stats]:769
-- dur [stats]:429
-- dur [stats]:373
-- dur [stats]:337
avg: 552
=> Optimize server stats calculation

waltz-ng/client/app-groups/directives/app-group-summary.html, waltz-ng/client/app-groups/directives/app-group-summary.js, waltz-ng/client/capabilities/directives/capability-scorecard.html, waltz-ng/client/capabilities/directives/capability-scorecard.js, waltz-ng/client/person/directives/person-summary.html, waltz-ng/client/person/directives/person-summary.js
=> Server count missing on App group, Function and People pages

waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/application/ApplicationKind.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/icon_names.js, waltz-ng/client/data-flow/components/data-flows-tabgroup/data-flows-tabgroup.scss, waltz-ng/client/data-flow/components/source-and-target-panel/source-and-target-panel.scss, waltz-ng/client/navbar/components/nav-search-results.scss, waltz-ng/client/widgets/overlay-panel.scss, waltz-ng/client/widgets/page-header.scss, waltz-ng/client/widgets/section.scss, waltz-ng/style/_util.scss, waltz-service/src/main/java/com/khartec/waltz/service/orgunit/OrganisationalUnitService.java
=> Progress bar & External Apps

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DatabaseHarness.java
=> Optimize database stats calculation

waltz-ng/client/data-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/physical-data-articles/components/physical-data-section.html, waltz-ng/style/_waltz-scroll-region.scss, waltz-ng/style/_waltz.scss
=> Source and target popup to have conditional scroll region

waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowStatsDao.java
=> Fix issue when running on SQL server

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Adding indexes to phys-data-flow/article

waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowDao.java
=> Fixing broken boingy graph

waltz-data/src/main/java/com/khartec/waltz/data/complexity/CapabilityComplexityDao.java
=> Complexity rating re-calculation fails on MariaDB

waltz-model/src/main/java/com/khartec/waltz/model/appview/AppView.java, waltz-ng/client/app-capabilities/directives/app-capability-section.html, waltz-ng/client/app-capabilities/directives/app-capability-section.js, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/applications/routes.js, waltz-ng/client/asset-cost/services/asset-cost-store.js, waltz-ng/client/entity-statistics/services/entity-statistic-store.js, waltz-service/src/main/java/com/khartec/waltz/service/app_view/AppViewService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssetCostEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityStatisticEndpoint.java
=> App View: combine functions/ratings & reorder loading

waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.html, waltz-ng/client/widgets/pie-segment-table.html
=> Pie table values should be sorted

waltz-ng/client/common/index.js, waltz-ng/client/physical-data-articles/components/physical-data-section.html, waltz-ng/client/physical-data-articles/components/physical-data-section.js, waltz-ng/style/_bootstrap-styles.scss, waltz-ng/style/_waltz-visibility.scss
=> Physical Flows: repeated articles - make muted text more subtle

waltz-ng/client/common/common.scss, waltz-ng/client/common/componets/index.js, waltz-ng/client/common/componets/multi-select-tree-control/multi-select-treecontrol.js, waltz-ng/client/common/componets/search-control/search-control.html, waltz-ng/client/common/componets/search-control/search-control.js, waltz-ng/client/common/componets/search-control/search-control.scss, waltz-ng/client/common/index.js, waltz-ng/client/physical-data-articles/components/physical-data-section.html, waltz-ng/client/physical-data-articles/components/physical-data-section.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/style/_bootstrap-styles.scss, waltz-ng/style/_waltz.scss
=> Generic search control

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/InvolvementGenerator.java
=> Involvement Kind: DDL changes

waltz-data/src/main/java/com/khartec/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-model/src/main/java/com/khartec/waltz/model/LastUpdatedProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/invovement_kind/InvolvementKind.java, waltz-service/src/main/java/com/khartec/waltz/service/involvement_kind/InvolvementKindService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementKindEndpoint.java
=> Involvement Kind: Backend support

waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/involvement-kind/index.js, waltz-ng/client/involvement-kind/services/involvement-kind-service.js, waltz-ng/client/involvement-kind/services/involvement-kind-store.js, waltz-ng/client/modules.js
=> Involvement Kind: UI caching and display

waltz-data/src/main/java/com/khartec/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-service/src/main/java/com/khartec/waltz/service/involvement_kind/InvolvementKindService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/EndpointUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementKindEndpoint.java
- Dao, Service and Endpoint implementations
#717
=> Involvement Kind - admin backend

waltz-ng/client/lineage-report/components/lineage-flow-tabgroup/lineage-flow-tabgroup.html, waltz-ng/client/lineage-report/lineage-edit.html, waltz-ng/client/lineage-report/lineage-view.html
=> Fixing broken link

waltz-data/src/main/java/com/khartec/waltz/data/lineage_report/LineageReportDao.java, waltz-data/src/main/java/com/khartec/waltz/data/lineage_report_contribution/LineageReportContributorDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/LineageHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityReference.java, waltz-model/src/main/java/com/khartec/waltz/model/lineage_report/LineageReportDescriptor.java, waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/lineage-report/index.js, waltz-ng/client/lineage-report/lineage-view.js, waltz-ng/client/lineage-report/services/lineage-report-contributor-store.js, waltz-ng/client/lineage-report/services/lineage-report-store.js, waltz-ng/client/physical-data-articles/components/article-consumers/physical-data-article-consumers.html, waltz-ng/client/physical-data-articles/physical-data-article-view.html, waltz-ng/client/physical-data-articles/physical-data-article-view.js, waltz-service/src/main/java/com/khartec/waltz/service/lineage_report/LineageReportService.java, waltz-service/src/main/java/com/khartec/waltz/service/lineage_report_contributor/LineageReportContributorService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LineageReportContributorEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LineageReportEndpoint.java
=> Showing lineage links on article pages

waltz-data/src/main/java/com/khartec/waltz/data/lineage_report/LineageReportDao.java, waltz-model/src/main/java/com/khartec/waltz/model/lineage_report/CreateLineageReportCommand.java, waltz-ng/client/common/checks.js, waltz-ng/client/lineage-report/services/lineage-report-store.js, waltz-ng/client/physical-data-articles/physical-data-article-view.html, waltz-ng/client/physical-data-articles/physical-data-article-view.js, waltz-service/src/main/java/com/khartec/waltz/service/lineage_report/LineageReportService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LineageReportEndpoint.java
=> Create lineage report from article pages

waltz-data/src/main/java/com/khartec/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-model/src/main/java/com/khartec/waltz/model/invovement_kind/InvolvementKindChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/invovement_kind/InvolvementKindCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/utils/CommandUtilities.java, waltz-service/src/main/java/com/khartec/waltz/service/involvement_kind/InvolvementKindService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementKindEndpoint.java
=> Command pattern implementation for create, update

waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js
=> Indicator tree missing on Person indicator detail view

waltz-data/src/main/java/com/khartec/waltz/data/involvement_kind/InvolvementKindDao.java, waltz-ng/client/common/checks.js, waltz-ng/client/involvement-kind/services/involvement-kind-service.js, waltz-ng/client/involvement-kind/services/involvement-kind-store.js, waltz-ng/client/lineage-report/lineage-edit.js, waltz-ng/client/system/actors-view.html, waltz-ng/client/system/actors-view.js, waltz-ng/client/system/routes.js, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/widgets/editable-field.html, waltz-ng/client/widgets/editable-field.js, waltz-ng/style/_waltz.scss, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/InvolvementKindEndpoint.java
=> InvolvementKind Admin UI

waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow/LogicalDataFlowIdSelectorFactory.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/IdSelectionOptions.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow/DataFlowService.java
=> Cleanup data flow selector methods

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Added physical_flow_lineage

waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowDecoratorHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/IdSelectionOptions.java, waltz-ng/client/data-flow/services/data-flow-view-service.js, waltz-ng/client/data-types/data-type-view.js, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorService.java
=> Further cleanup of `desiredKind` usages

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> add asset owner into involvement_kinds

waltz-ng/client/common/componets/search-control/search-control.js, waltz-ng/client/data-flow/components/source-and-target-panel/source-and-target-panel.js
=> Fixing source and target popup

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_flow/LogicalDataFlowIdSelectorFactory.java
=> Removing old lineage tables

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalLineageGenerator.java
=> Lineage generator

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalLineageGenerator.java
=> Lineage generator - updated to take account of physical flows

waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/physical-flow-lineage/components/candidate-editor/lineage-candidate-editor.html, waltz-ng/client/physical-flow-lineage/components/candidate-editor/lineage-candidate-editor.js, waltz-ng/client/physical-flow-lineage/lineage-edit.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js, waltz-ng/client/physical-specifications/components/specification-consumers/physical-specification-consumers.js, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/physical-specifications/utilities.js
=> Lineage Editor, pt 2

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-ng/client/applications/app-asset-code-view.html, waltz-ng/client/applications/app-asset-code-view.js, waltz-ng/client/applications/resolvers.js, waltz-ng/client/applications/routes.js, waltz-ng/client/applications/services/application-store.js, waltz-service/src/main/java/com/khartec/waltz/service/application/ApplicationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java
=> Support application URLs with external ids (asset_code)

waltz-ng/style/_loading-bar.scss
=> loading spinner around Waltz logo

waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html
=> no physical flows message

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java
=> SQL Server: Improve performance of fetching historic entity stat values

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowLineageEndpoint.java
=> Lineage: add change log entries

waltz-data/src/main/java/com/khartec/waltz/data/EntityNameUtilities.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntityNameUtilitiesHarness.java
=> Entity name provider service

waltz-data/src/main/java/com/khartec/waltz/data/EntityNameUtilities.java
=> Add JavaDoc

waltz-ng/client/common/componets/entity-link/entity-icon-label.html, waltz-ng/client/common/componets/entity-link/entity-icon-label.js, waltz-ng/client/common/componets/entity-link/entity-link.html, waltz-ng/client/common/componets/entity-link/entity-link.js, waltz-ng/client/common/componets/index.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js
=> entity link component

waltz-ng/client/common/componets/entity-link/entity-link.js, waltz-ng/client/physical-flow-lineage/components/lineage-panel/physical-flow-lineage-panel.html, waltz-ng/client/physical-flow-lineage/lineage-edit.html, waltz-ng/client/physical-specifications/components/overview/physical-specification-overview.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html, waltz-ng/client/physical-specifications/components/specification-consumers/physical-specification-consumers.html, waltz-ng/style/_variables.scss, waltz-ng/style/_waltz.scss
=> Use EntityNameUtilities for resolving target and owning entity names

waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-ng/client/orphan/services/orphan-store.js, waltz-ng/client/system/orphans-view.js, waltz-service/src/main/java/com/khartec/waltz/service/orphan/OrphanService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/OrphanEndpoint.java
=> Orphan data flows should appear in orphan entity view

waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/DataFlowDecoratorDao.java
=> Auth Source Add -> Error when recalculating ratings

waltz-ng/client/common/services/icon_names.js, waltz-ng/client/physical-specifications/physical-specification-view.js
=> Lineage: push spec views into recent history

waltz-ng/client/data-flow/components/data-flows-tabgroup/data-flows-tabgroup.html, waltz-ng/style/_grid.scss
=> Improve grid styling

waltz-ng/client/common/common.scss, waltz-ng/client/common/componets/grid/grid.html, waltz-ng/client/common/componets/grid/grid.js, waltz-ng/client/common/componets/grid/grid.scss, waltz-ng/client/common/componets/index.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js
=> Waltz grid component

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow_lineage/PhysicalFlowLineageDao.java, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/data-types/data-type-list.js, waltz-ng/client/physical-flow-lineage/services/physical-flow-lineage-store.js, waltz-ng/client/playpen/2/playpen2.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow_lineage/PhysicalFlowLineageService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowLineageEndpoint.java
=> Lineage Reports in App Group

waltz-ng/client/physical-flows/physical-flow-view.html
=> Nicer flow overview section

waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js
=> Lineage Reports in Org unit view

waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-ng/client/person/person-view.js
=> Lineage report person view

waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/org-units/services/org-unit-view-data.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/client/person/person-view-data.js, waltz-ng/client/person/person-view.html, waltz-ng/client/person/person-view.js
=> lineage report function view

waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/data-flow/components/boingy-graph/boingy-graph.scss, waltz-ng/client/physical-flows/physical-flow-view.js
=> Lineage graph includes target

waltz-ng/client/physical-flows/physical-flow-view.js
=> Bookmarks not being returned.

waltz-ng/client/applications/app-view.html, waltz-ng/client/common/index.js, waltz-ng/client/data-flow/components/data-flow-table/data-flow-table.js, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js
=> Physical flow detail: Allow export from App screen

waltz-ng/client/common/colors.js, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.html, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.scss, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/style/_variables.scss
=> Lineage graph differentiates actors from applications

waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js
=> Derive search fields from grid column definitions

waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/common/componets/grid/grid.js, waltz-ng/client/common/componets/grid/grid.scss, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js
- Move export buttons to section header
- Hide scrollbars if not required
- Dynamic grid sizing based on number of rows
#834
=> Physical flow grid updates

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/AdditiveFlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalFlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalLineageGenerator.java
=> bonkers flow generator

waltz-ng/client/app-groups/directives/app-group-list-section.html, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/components/app-costs-section/app-costs-section.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/list-view.html, waltz-ng/client/change-log/directives/change-log-section.html, waltz-ng/client/data-types/components/data-type-originators.html, waltz-ng/client/data-types/components/rated-flow-boingy-graph.html, waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/entity-statistics/directives/entity-statistic-section.html, waltz-ng/client/involvement/directives/involved-people-section.html, waltz-ng/client/org-units/list-view.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-view.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-specifications/physical-specification-view.html, waltz-ng/client/process/directives/process-section.html, waltz-ng/client/process/list.html, waltz-ng/client/process/view.html, waltz-ng/client/static-panel/directives/static-panel.html
=> verify collapsible sections have id's

waltz-ng/client/common/componets/entity-link/entity-link.html, waltz-ng/client/common/componets/entity-link/entity-link.js
=> Grid cells using waltz-entity-link do not work correctly

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Safely extract entity name when logging changes

waltz-ng/client/change-log/view.html, waltz-ng/client/common/componets/grid/grid.scss
=> remove min-height style in waltz grid

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/AdditiveFlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowDecorationGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalSpecificationGenerator.java, waltz-ng/client/data-flow/components/source-and-target-panel/source-and-target-panel.js
=> Optimise source and target graph.

waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js
=> AppView: phys specs / consumes link goes to wrong page

waltz-ng/client/physical-flow-lineage/components/lineage-panel/physical-flow-lineage-panel.html, waltz-ng/client/physical-flow-lineage/components/lineage-panel/physical-flow-lineage-panel.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-specifications/components/mentions/physical-specification-mentions.html, waltz-ng/client/physical-specifications/components/mentions/physical-specification-mentions.js
=> Lineage reports: Allow export from physical flow screen

waltz-data/src/main/java/com/khartec/waltz/data/app_capability/AppCapabilityDao.java
=> Javascript error on capability page

waltz-ng/client/physical-flows/physical-flow-registration.html, waltz-ng/client/physical-flows/physical-flow-registration.js, waltz-ng/client/physical-flows/routes.js
=> Phys Flow Reg Skeleton

waltz-web/src/main/java/com/khartec/waltz/web/Main.java, waltz-web/src/main/java/com/khartec/waltz/web/WaltzApplication.java
=> Add web app shutdown hook to close conn pool

waltz-ng/client/actor/components/actor-selector.html, waltz-ng/client/actor/components/actor-selector.js, waltz-ng/client/actor/components/basic-actor-selector.html, waltz-ng/client/actor/components/basic-actor-selector.js, waltz-ng/client/actor/index.js, waltz-ng/client/applications/directives/app-selector.html, waltz-ng/client/applications/directives/basic-app-selector.html, waltz-ng/client/physical-flows/components/edit-target-entity/physical-flow-edit-target-entity.html, waltz-ng/client/physical-flows/components/edit-target-entity/physical-flow-edit-target-entity.js, waltz-ng/client/physical-flows/index.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js
=> PhysFlow Register: target picker

waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/physical-flows/components/attribute-editor/physical-flow-attribute-editor.html, waltz-ng/client/physical-flows/components/attribute-editor/physical-flow-attribute-editor.js, waltz-ng/client/physical-flows/formly/physical-flow-fields.js, waltz-ng/client/physical-flows/index.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js
=> PhysFlow Register: Attribute editor

waltz-ng/client/data-flow/components/data-flows-tabgroup/data-flows-tabgroup.html, waltz-ng/client/data-flow/components/data-flows-tabgroup/data-flows-tabgroup.js
=> Data flow table grid doesn't render sometimes

waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/physical-flows/components/attribute-editor/physical-flow-attribute-editor.html, waltz-ng/client/physical-flows/components/attribute-editor/physical-flow-attribute-editor.scss, waltz-ng/client/physical-flows/components/edit-target-entity/physical-flow-edit-target-entity.html, waltz-ng/client/physical-flows/components/edit-target-entity/physical-flow-edit-target-entity.scss, waltz-ng/client/physical-flows/components/overview/physical-flow-edit-overview.html, waltz-ng/client/physical-flows/components/overview/physical-flow-edit-overview.js, waltz-ng/client/physical-flows/components/overview/physical-flow-overview.scss, waltz-ng/client/physical-flows/index.js, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/style/_waltz.scss
=> WIP - phys flow register overview

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java
=> Allow actors to appear in phys flow list for apps.

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_flow/DataFlowDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/PhysicalFlowHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow/DataFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/settings.md
=> Default create logical flow when creating a physical

waltz-ng/style/_breadcrumbs.scss
=> Remove breadcrumb bottom border

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/actor/components/actor-overview.html, waltz-ng/client/actor/components/actor-overview.js, waltz-ng/client/actor/index.js, waltz-ng/client/actor/routes.js, waltz-ng/client/common/index.js
=> Basic Actor view page

waltz-ng/client/applications/directives/app-overview.html
=> Fixing complexity labels

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/change-log/services/change-log-data.js
=> Added change log to actor page

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/applications/app-view.html, waltz-ng/client/change-log/services/change-log-data.js, waltz-ng/client/physical-flows/components/export-buttons/physical-flow-export-buttons.html, waltz-ng/client/physical-flows/components/export-buttons/physical-flow-export-buttons.js, waltz-ng/client/physical-flows/index.js
@rovats  Could you review pls?
We've created a basic actor page with phys feeds.  Needed the same export functionality that you added to the app-view page so pulled out the buttons into a new component. Suspect this refactoring could be extended to cut down on duplicate JS in the page controller.
#901
=> Waltz 901 actor flows export

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js
=> Actor bookmarks

waltz-ng/client/physical-flow-lineage/lineage-edit.js
=> Prevent lineage flow being described by itself.

waltz-ng/client/physical-flow-lineage/components/candidate-editor/lineage-candidate-editor.html, waltz-ng/client/physical-flow-lineage/components/candidate-editor/lineage-candidate-editor.js, waltz-ng/client/physical-flow-lineage/lineage-edit.html
- nicer message if no inputs available
#914
=> Lineage editor improvements

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/complexity/ConnectionComplexityDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/DataFlowDecoratorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/JooqHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/AdditiveFlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowDecorationGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalFlowGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_flow/LogicalFlow.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_flow/LogicalFlowMeasures.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_flow/LogicalFlowStatistics.java, waltz-ng/client/app-groups/directives/app-group-summary.html, waltz-ng/client/capabilities/directives/capability-scorecard.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-ng/client/org-units/components/overview/org-unit-overview.html, waltz-ng/client/person/directives/person-summary.html, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorRatingsService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
=> Normalised names to logical-flow  (from data-flow)

waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.scss, waltz-ng/client/svg-diagram/component/common-svg-defs.html, waltz-ng/client/svg-diagram/component/common-svg-defs.js, waltz-ng/client/svg-diagram/index.js, waltz-ng/index.template.html
=> Prevent arrow heads from vanishing

waltz-ng/client/common/services/icon_names.js, waltz-ng/client/history/services/history-store.js, waltz-ng/client/physical-flows/physical-flow-view.js
=> Lineage: push physical flow views into recent history

waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/capability-view.js
=> Optimised load of capability-view

waltz-ng/client/common/services/display_names.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-ng/client/ratings/directives/rating-explorer/rating-explorer-section.html
=> Update rating terminology

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EntityStatisticGenerator.java, waltz-ng/client/app-capabilities/components/app-capability-table/app-capability-table.js, waltz-ng/client/entity-statistics/components/history-chart/entity-statistic-history-chart.js, waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.js, waltz-ng/client/networking.js
- also fixing coloring of table
#937
=>  Indicator history table not displayed for the last point in IE

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java
=> Parallelize calculation of related indicator tallies

waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.html, waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.js
=> Show totals in ent-stat history graph

waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/pie-segment-table.html, waltz-ng/client/widgets/pie-segment-table.scss, waltz-ng/client/widgets/pie-table.html, waltz-ng/client/widgets/pie-table.js
=> Pie tables orient themselves automatically

waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js
=> Tour support for phys flows

waltz-ng/client/app-capabilities/components/app-rating-tabgroup-section/app-rating-tabgroup-section.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/navbar/directives/navbar.js
=> Hide processes behind beta tester flag

waltz-ng/client/capabilities/capability-view.js, waltz-ng/client/widgets/pie-segment-table.html
=> Cap view reports numbers based on hierarchy.

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-data/src/main/java/com/khartec/waltz/data/application/AppTagDao.java, waltz-data/src/main/java/com/khartec/waltz/data/complexity/ComplexityScoreDao.java, waltz-data/src/main/java/com/khartec/waltz/data/performance_metric/PerformanceMetricPackDao.java, waltz-ng/client/app-capabilities/components/app-rating-tabgroup-section/app-rating-tabgroup-section.html, waltz-ng/client/capabilities/directives/capability-scorecard.html, waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.scss, waltz-ng/client/widgets/basic-info-tile.html, waltz-ng/client/widgets/basic-info-tile.js, waltz-ng/client/widgets/basic-info-tile.scss, waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/pie-segment-table.html
=> Using fetch then stream in jooq

pom.xml
=> Upgrading spark

waltz-ng/client/widgets/section.html
=> Section expand/collapse based on title click

waltz-ng/package.json, waltz-ng/webpack.config.js
=> Auto reload when js is out of date

.travis.yml, waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/pie-segment-table.html, waltz-ng/client/widgets/search.js, waltz-ng/client/widgets/twistie.html, waltz-ng/client/widgets/twistie.js
- bonus - twistie -> component
#965
=> Align pie table headers

waltz-ng/client/applications/app-view.html
=> App breadcrumbs normalised

waltz-ng/client/widgets/pie-segment-table.scss
=> Align pie-table indicator cells

waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.scss, waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.html, waltz-ng/client/entity-statistics/components/related-entity-statistics-summaries.html
=> Related statistics more visually distinct

waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.html, waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.html, waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js
=> Append timestamp to indicator export file name

waltz-ng/client/widgets/basic-info-tile.scss
=> Reduce min-height of info-tiles

waltz-ng/client/server-info/directives/server-pies.html, waltz-ng/client/technology/components/group-technology-summary.html
=> Align technology server pies

waltz-ng/client/capabilities/directives/capability-scorecard.html, waltz-ng/client/org-units/components/overview/org-unit-overview.html, waltz-ng/client/person/directives/person-summary.html
=> Logical flow cloud diagram: reduce white space

waltz-ng/client/app-groups/directives/app-group-summary.html
=> Fix app group view

waltz-ng/client/physical-flow-lineage/components/candidate-editor/lineage-candidate-editor.html, waltz-ng/client/physical-flow-lineage/lineage-edit.html
=> Lineage Editor: improve list of physical feeds

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/EntityStatisticGenerator.java, waltz-jobs/src/main/resources/version.properties, waltz-model/src/main/java/com/khartec/waltz/model/Duration.java, waltz-ng/client/entity-statistics/components/duration-selector.html, waltz-ng/client/entity-statistics/components/duration-selector.js, waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.html, waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.js, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/index.js, waltz-ng/client/entity-statistics/services/entity-statistic-store.js
=> Indicators: Add 1w/1m/3m/6m/1y selector to history chart

waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js
=> Person stat view duration selector not working

waltz-ng/client/org-units/components/overview/org-unit-overview.js, waltz-ng/client/org-units/unit-view.html
=> Capability summary stats not being displayed on Org unit view

waltz-ng/client/logical-flow/components/slope-graph/slope-graph-diagram.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/ratings/directives/rating-group/diagram.js, waltz-ng/client/ratings/directives/rating-group/rating-row-labels.js
=> incorrect arguments to  `_.truncate(xx, xxxx)`

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/database_information/DatabaseInformationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/DatabaseGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/ServerGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/LifecycleStatus.java, waltz-model/src/main/java/com/khartec/waltz/model/database_information/DatabaseInformation.java, waltz-model/src/main/java/com/khartec/waltz/model/server_information/ServerInformation.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/technology/directives/technology-section.js
=> Add new field: Lifecycle_Status to Server_information and db_info table

waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/actor/ActorSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowSearchDao.java, waltz-ng/client/actor/services/actor-store.js, waltz-ng/client/navbar/components/nav-search-results.html, waltz-ng/client/navbar/components/navbar-search-form.js, waltz-ng/client/physical-flows/service/physical-flow-store.js, waltz-service/src/main/java/com/khartec/waltz/service/actor/ActorService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ActorEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Actor / Flow search

waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/LogicalFlowStatsHarness.java
- Optimised tallyDataTypesByAppIdSelector and countDistinctFlowInvolvementByAppIdSelector
#998
=> Improve performance of logical flow stats calculation for Person view

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-ng/client/actor/actor-view.js
- fixing problem with migration script
#1014
=> Actor into history

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Logical flow id column should be auto increment on MariaDb

waltz-data/src/main/java/com/khartec/waltz/data/svg/SvgDiagramDao.java, waltz-service/src/main/java/com/khartec/waltz/service/svg/SvgDiagramService.java
=> Svg diagram, log time to identify slowness

waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/LogicalFlowStatsHarness.java
- Increased DB_EXECUTOR_POOL thread count to 20
#1028
=> Improve perf of person view - df stats - distinct app counts

waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/TransportKind.java, waltz-ng/client/common/services/display_names.js
=> Add UDP to TransportKiind

waltz-ng/client/physical-flows/components/edit-target-entity/physical-flow-edit-target-entity.html, waltz-ng/client/physical-flows/components/edit-target-entity/physical-flow-edit-target-entity.js, waltz-ng/client/physical-flows/components/edit-target-entity/physical-flow-edit-target-entity.scss, waltz-ng/client/physical-flows/components/register/physical-flow-edit-overview.html, waltz-ng/client/physical-flows/components/register/physical-flow-edit-specification.html, waltz-ng/client/physical-flows/physical-flow-registration.html, waltz-ng/client/physical-flows/physical-flow-registration.js, waltz-ng/index.template.html
- plus loading screen (sort of)
#1036
=> Specification enhancements

waltz-ng/client/common/colors.js, waltz-ng/client/technology/directives/technology-summary-pies.js
=> DEV and PRD both render as green on charts

waltz-ng/client/common/common.scss
=> Fixing typos

waltz-ng/client/applications/components/app-table.js, waltz-ng/client/change-log/components/change-log-table.js, waltz-ng/client/end-user-apps/directives/end-user-app-table.js
=> Use cellFilter rather than cellTemplate where possible

waltz-ng/client/capabilities/components/capability-ratings-section.js, waltz-ng/client/common/filters/description-filter.js, waltz-ng/client/common/filters/display-name-filter.js, waltz-ng/client/common/filters/icon-name-filter.js, waltz-ng/client/common/services/index.js, waltz-ng/client/entity-statistics/components/history-panel/entity-statistic-history-panel.js, waltz-ng/client/involvement/components/involved-people-section.js, waltz-ng/client/logical-flow/components/logical-flow-table/logical-flow-table.js, waltz-ng/client/logical-flow/components/logical-flows-tabgroup/logical-flows-tabgroup.js
=> remove Waltz prefix from display name svc etc.

waltz-ng/client/common/filters/icon-name-filter.js, waltz-ng/index.template.html
=> Background color set up front so no change during loading

waltz-ng/client/widgets/page-header.js
=> Header collapse now sychronous

waltz-ng/client/person/person-view-data.js
=> Start loading of flow stats outside of waves for speedier feedback

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/applications/components/app-table.html, waltz-ng/client/applications/components/app-table.js, waltz-ng/client/applications/components/apps-section/apps-section.html, waltz-ng/client/applications/components/apps-section/apps-section.js, waltz-ng/client/applications/index.js, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/org-units/unit-view.html
- app group
- capability view
- unit view
- person view
#1058
=> Normalising apps-section across:

waltz-ng/client/app-groups/app-group-view.html
=> app-group not remembering collapsed sections

waltz-ng/client/widgets/no-data.scss
=> Add border radius

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalFlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalSpecificationGenerator.java, waltz-ng/client/app-groups/app-group-view.html
In order to get a larger populator, increase random Flow count in Logical Flow Generator and also the spec count in Phys Spec Generator.
Changed back to regular values because it takes ages to run.
#1033
=> Verify app is happy with high phys flows

waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDao.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticDefinitionDao.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_statistic/EntityStatisticService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityStatisticEndpoint.java
=> Implement EntityVisibility and RollupVisibility on Entity Stats

waltz-ng/client/physical-flow-lineage/components/candidate-editor/lineage-candidate-editor.html, waltz-ng/client/physical-specifications/utilities.js
=> Ensure lineage editor flow selection is correct

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> indexes on phy spec and flow tables for owning and target entity refs

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java
=> Optimise query for PhysicalFlowDao.findByEntityReference

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-ng/client/physical-flow-lineage/components/candidate-editor/lineage-candidate-editor.js, waltz-ng/client/physical-flow-lineage/lineage-edit.js, waltz-ng/client/physical-flows/service/physical-flow-store.js, waltz-ng/client/physical-specifications/services/physical-specification-store.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Retrieve only consumed specs and flows for the lineage candidates editor

waltz-ng/client/technology/components/group-technology-summary.html
=> Improve s/w pie section

waltz-ng/client/common/colors.js
=> Improve pie color schemes

waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js
=> Boingy bug

waltz-ng/client/ratings/directives/common.js
- old references to d3 functions
#1100
=> Fixing broken build

waltz-ng/client/playpen/2/playpen2.html, waltz-ng/client/playpen/2/playpen2.js, waltz-ng/client/playpen/3/asset-cost-graph.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.scss
=> Rating picker improvements

waltz-ng/client/networking.js, waltz-ng/style/_bootstrap-styles.scss, waltz-ng/style/_waltz-text-muted.scss, waltz-ng/style/_waltz.scss
=> Mouse not turning to pointer over tabs (IE)

waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js
=> Boingy graph stays boingy after reset

waltz-web/settings.md, waltz-web/src/main/java/com/khartec/waltz/web/Main.java
=> enable gzip selectively

waltz-web/src/main/java/com/khartec/waltz/web/Main.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticResourcesEndpoint.java
=> remove cache control

waltz-ng/client/common/d3-utils.js, waltz-ng/client/common/index.js, waltz-ng/client/data-types/components/rated-flow-boingy-graph.js, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.html, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.js, waltz-ng/client/logical-flow/components/boingy-graph/boingy-graph.scss, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-ng/client/logical-flow/services/logical-flow-utility.js, waltz-ng/client/networking.js, waltz-ng/client/physical-flow-lineage/lineage-edit.js, waltz-ng/client/physical-flows/physical-flow-view.js
=> Waltz 1110 markers

waltz-ng/client/navbar/components/nav-search-results.html, waltz-ng/client/navbar/components/nav-search-results.js, waltz-ng/client/navbar/components/navbar-search-form.html, waltz-ng/client/navbar/components/navbar-search-form.js
=> fix ie search results closing incorrectly bug

waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.html, waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.scss
=> bookmark toggle and dimish unused filters

waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.html, waltz-ng/client/bookmarks/components/bookmark-kinds/bookmark-kinds.scss, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html
=> bookmark fixed width and selected background colour

waltz-ng/client/actor/actor-view.html, waltz-ng/client/actor/actor-view.js, waltz-ng/client/applications/app-view.html
=> bookmark source data ratings missing

waltz-data/src/main/java/com/khartec/waltz/data/access_log/AccessLogDao.java, waltz-model/src/main/java/com/khartec/waltz/model/accesslog/AccessTime.java, waltz-ng/client/access-log/service/access-log-store.js, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/user/active-users.html, waltz-ng/client/user/active-users.js, waltz-ng/client/user/routes.js, waltz-service/src/main/java/com/khartec/waltz/service/access_log/AccessLogService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AccessLogEndpoint.java
=> Admin page for recently active users

waltz-ng/client/logical-flow/directives/flow-cloud-diagram.html
=> clipping in cloud diagram

waltz-ng/client/applications/data-load.js
=> Auth source bug (nest.map -> nest.object)

waltz-ng/client/org-units/components/tree/org-unit-tree.html, waltz-ng/client/org-units/components/tree/org-unit-tree.js, waltz-ng/client/org-units/list-view.html, waltz-ng/client/org-units/list-view.js
=> Improving OU Tree

waltz-ng/client/app-capabilities/components/app-capability-editor/app-capability-editor.js
=> app-capability editor: debug messages in console

waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.html
=> indicator overview space

waltz-ng/client/routes.js, waltz-web/settings.md
=> last nav timer - reload page after period of inactivity

waltz-data/src/main/java/com/khartec/waltz/data/asset_cost/AssetCostDao.java, waltz-ng/client/asset-cost/components/asset-costs-graph.js, waltz-ng/client/asset-cost/components/asset-costs-graph.scss, waltz-ng/client/asset-cost/index.js, waltz-ng/client/asset-cost/services/asset-cost-store.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/org-units/unit-view.js, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/asset_cost/AssetCostService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AssetCostEndpoint.java
=> App Costs visualization

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/change-log/view.html, waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/involvement/components/involved-people-section.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-view.html, waltz-ng/client/physical-flows/components/export-buttons/physical-flow-export-buttons.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/widgets/data-extract-link.html
=> Add cloud-download icon to all export buttons

waltz-ng/client/applications/app-view.html
=> Move app auth source section into data tabset

waltz-ng/client/common/colors.js
=> Give colors to outcomes: HIGH, MEDIUM, LOW

waltz-ng/client/app-groups/directives/app-group-app-selection-list.html
=> AppGroup: add and refocus not working

waltz-ng/client/complexity/directives/complexity-bar-chart.js
=> Complexity graph - hover over number not working

waltz-ng/client/common/index.js, waltz-ng/client/logical-flow/components/rated-flow-summary/rated-summary-cell.html, waltz-ng/client/widgets/simple-stack-chart.js
=> Auth source chart

waltz-ng/client/applications/app-view.html
=> Disable authority tab when no data

waltz-ng/client/asset-cost/components/asset-costs-graph.js
=> Apply resize to svg asynchronously

waltz-ng/client/applications/components/app-costs-section/app-costs-section.html, waltz-ng/client/asset-cost/components/asset-costs-section.html, waltz-ng/client/bookmarks/bookmark-editor.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/capabilities/components/capability-ratings-section.html, waltz-ng/client/capabilities/list-view.html, waltz-ng/client/change-log/components/change-log-section.html, waltz-ng/client/complexity/directives/complexity-section.html, waltz-ng/client/data-types/components/data-type-originators.html, waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/org-units/list-view.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-home.html, waltz-ng/client/person/person-view.html, waltz-ng/client/physical-flows/physical-flow-registration.html, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/technology/directives/technology-section.html
=> Add more icons to collapsable sections

waltz-ng/client/user/active-users.html, waltz-ng/client/user/active-users.js
=> Active users - use a table and not the virtualised grid

waltz-ng/client/complexity/directives/complexity-bar-chart.js, waltz-ng/client/complexity/directives/complexity-bar-chart.scss, waltz-ng/client/widgets/page-header.js, waltz-ng/client/widgets/simple-stack-chart.js
=> Complexity bar chart fixes

waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.js
=> Bookmarks: order by kind

waltz-ng/client/asset-cost/components/asset-costs-section.html, waltz-ng/client/asset-cost/services/asset-cost-view-service.js
=> Cost graph number formatting

waltz-ng/client/widgets/pie-table.html, waltz-ng/client/widgets/pie-table.js
=> pie-table: synchronize selected elements between pie and tables by default

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/complexity/ComplexityScoreDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/ServerComplexityHarness.java
=> App Id selector for person - remove fetch for employee id

waltz-ng/client/widgets/pie-table.html, waltz-ng/client/widgets/pie-table.js
=> Revert "pie-table: synchronize selected elements between pie and tables by default"

waltz-ng/package.json
=> Upgrading to angular 1.5.9

waltz-ng/client/welcome/welcome.js
=> Waltz title not set on homepage

waltz-ng/client/change-initiative/change-initiative-view.html
=> change initiative - header attached

waltz-data/src/main/java/com/khartec/waltz/data/complexity/ComplexityScoreDao.java
=> ComplexityScoreDao.getForApp(): NullPointerException when the app has no associated scores

waltz-ng/client/user/user-log.html, waltz-ng/client/user/user-log.js
=> User Logs - view link should be proper link (not ng-click)

waltz-ng/package.json
=> Remove numeral.js dependency

waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable/Measurable.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable/MeasurableKind.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableEndpoint.java
=> Basic model/dao/svc/endpoint

waltz-data/src/main/java/com/khartec/waltz/data/FindEntityReferencesByIdSelector.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java, waltz-ng/client/common/services/display_names.js, waltz-ng/client/system/hierarchies-view.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java
=> Added measurable to ent hier

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/data-types/data-type-list.html, waltz-ng/client/lineage/components/lineage-reports-section.html, waltz-ng/client/lineage/components/lineage-reports-section.js, waltz-ng/client/lineage/index.js, waltz-ng/client/modules.js, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-view.html
=> Lineage reports section and not inlined

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/capabilities/capability-view.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-view.html, waltz-ng/client/technology/components/technology-summary-section.html, waltz-ng/client/technology/components/technology-summary-section.js
=> Technology summary section is inlined, create a component

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java
=> New table for measurable_rating

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/MeasurableRating.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Measurable Rating dao/svc/endpoint

docs/snippets.sql, waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Processed migrated to measurable table

waltz-ng/client/common/index.js, waltz-ng/client/common/services/BaseLookupService.js, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/playpen/4/playpen4.html, waltz-ng/client/playpen/4/playpen4.js
=> Measurables grouped into tabs by kind.

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/playpen/4/playpen4.html, waltz-ng/style/_waltz-tabs.scss, waltz-ng/style/_waltz.scss
=> .shows all measurables in rating section

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_hierarchy/AbstractIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/MeasurableHarness.java, waltz-ng/style/_waltz-tabs.scss, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java
=> AppId Selector & Friends

waltz-ng/client/common/index.js, waltz-ng/client/complexity/services/complexity-store.js, waltz-ng/client/databases/services/database-store.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/measurable/components/summary/measurable-summary.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/measurable/routes.js, waltz-ng/client/measurable/services/measurable-store.js, waltz-ng/client/server-info/services/server-info-store.js, waltz-ng/client/software-catalog/services/software-catalog-store.js, waltz-ng/client/technology/services/technology-statistics-service.js, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableEndpoint.java
=> Very basic measurable view page created.

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.html, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/measurable-rating/index.js, waltz-ng/client/measurable-rating/services/measurable-rating-store.js, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Measurable Ratings explorer section created

waltz-ng/client/common/services/icon-names.js, waltz-ng/client/measurable/measurable-view.js
=> Add measurable view to page history

waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/services/entity-statistics-utilities.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js
=> Added indicator to measurable view

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/MeasurablesGenerator.java, waltz-jobs/src/main/resources/products.csv, waltz-ng/client/person/directives/person-directs-list.html
=> Ordering directs by displayname

waltz-ng/client/measurable-rating/measurable-rating-edit.js
=> Measurable rating editor takes overall app rating as a default value.

waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java
=> Disable rating of non-concrete measurables

waltz-ng/client/measurable/measurable-list.html, waltz-ng/client/measurable/measurable-list.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/routes.js, waltz-ng/client/navbar/directives/navbar.js
=> Measurable list (index) page

waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/measurable/measurable-list.html
- select first tab with ratings
#1300
=> Measurable Rating editor

waltz-ng/client/asset-cost/components/asset-costs-graph.js, waltz-ng/client/common/d3-utils.js
=> Waltz 1223 ratio

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/com/khartec/waltz/data/svg/SvgDiagramDao.java, waltz-model/src/main/java/com/khartec/waltz/model/svg/SvgDiagram.java, waltz-ng/client/capabilities/list-view.js, waltz-ng/client/data-types/data-type-list.js, waltz-ng/client/measurable/measurable-list.js, waltz-ng/client/org-units/list-view.js, waltz-ng/client/person/person-home.js, waltz-ng/client/process/list.js, waltz-ng/client/svg-diagram/services/svg-diagram-store.js, waltz-service/src/main/java/com/khartec/waltz/service/svg/SvgDiagramService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SvgDiagramEndpoint.java
=> Renaming svg_diagram:kind to :group

waltz-ng/style/_waltz.scss
=> Renaming static_panel:kind to :encoding

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Measurable Rating: indexes

waltz-common/src/main/java/com/khartec/waltz/common/ArrayUtilities.java, waltz-common/src/main/java/com/khartec/waltz/common/Checks.java, waltz-common/src/test/java/com/khartec/waltz/common/ArrayUtilities_isEmpty.java, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeDao.java, waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-data/src/main/java/com/khartec/waltz/data/static_panel/StaticPanelDao.java, waltz-data/src/main/java/com/khartec/waltz/data/svg/SvgDiagramDao.java, waltz-ng/client/measurable/measurable-list.html, waltz-ng/client/measurable/measurable-list.js, waltz-ng/client/static-panel/services/static-panel-store.js, waltz-ng/client/svg-diagram/services/svg-diagram-store.js, waltz-service/src/main/java/com/khartec/waltz/service/access_log/AccessLogService.java, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-service/src/main/java/com/khartec/waltz/service/application/ApplicationService.java, waltz-service/src/main/java/com/khartec/waltz/service/changelog/ChangeLogService.java, waltz-service/src/main/java/com/khartec/waltz/service/involvement/InvolvementService.java, waltz-service/src/main/java/com/khartec/waltz/service/person/PersonService.java, waltz-service/src/main/java/com/khartec/waltz/service/static_panel/StaticPanelService.java, waltz-service/src/main/java/com/khartec/waltz/service/svg/SvgDiagramService.java, waltz-service/src/main/java/com/khartec/waltz/service/user/UserPreferenceService.java, waltz-service/src/main/java/com/khartec/waltz/service/user/UserService.java, waltz-service/src/main/java/com/khartec/waltz/service/user_agent_info/UserAgentInfoService.java, waltz-service/src/main/java/com/khartec/waltz/service/user_contribution/UserContributionService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticPanelEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SvgDiagramEndpoint.java
- normalised check method
#1309
=> Measurable List page: added svgs

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/search/MariaMeasurableSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/search/MeasurableSearchDao.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/search/PostgresMeasurableSearch.java, waltz-data/src/main/java/com/khartec/waltz/data/measurable/search/SqlServerMeasurableSearch.java, waltz-ng/client/measurable/services/measurable-store.js, waltz-ng/client/navbar/components/nav-search-results.html, waltz-ng/client/navbar/components/navbar-search-form.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableEndpoint.java
=> Measurables added to search

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Changelog: DDL: Add CHILD_KIND and OPERATION

waltz-data/src/main/java/com/khartec/waltz/data/changelog/ChangeLogDao.java, waltz-model/src/main/java/com/khartec/waltz/model/Operation.java, waltz-model/src/main/java/com/khartec/waltz/model/changelog/ChangeLog.java, waltz-service/src/main/java/com/khartec/waltz/service/app_capability/AppCapabilityService.java, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-service/src/main/java/com/khartec/waltz/service/bookmark/BookmarkService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification/PhysicalSpecificationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ApplicationEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AuthoritativeSourceEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataTypeUsageEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityAliasEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowLineageEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/TraitUsageEndpoint.java
=> Changelog: Modify code to populate CHILD_KIND and OPERATION columns

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Add backfill update statement for data type usages

waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.js
- saving indicator
- remembers last rating choice
- warns if rating != overallRating
#1306
#1297
=> Editor improvements:

waltz-ng/client/entity/components/immediate-hierarchy-navigator/immediate-hierarchy-navigator.js, waltz-ng/client/measurable/components/summary/measurable-summary.html, waltz-ng/client/measurable/components/summary/measurable-summary.js
=> Navigate though measurables via summary section

waltz-ng/client/app-groups/app-group-view.js, waltz-ng/client/applications/app-view.js, waltz-ng/client/applications/data-load.js, waltz-ng/client/data-types/services/data-type-view-data.js, waltz-ng/client/org-units/services/org-unit-view-data.js
=> Moving change log store callers over to entity-refs

waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/person/person-view.html
=> Provide csv export file names from Person/Measurable views

waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/ratings/directives/common.js
- bonus: removed unused function
#1288
=> Loading measurable view in waves

waltz-ng/client/asset-cost/components/asset-costs-graph.js, waltz-ng/client/asset-cost/components/asset-costs-graph.scss, waltz-ng/client/complexity/components/complexity-bar-chart.js
=> Update Asset-cost section colour scheme

waltz-ng/client/modules.js
=> Removing ngRedux

waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java, waltz-ng/client/measurable/routes.js, waltz-ng/client/measurable/services/measurable-store.js, waltz-service/src/main/java/com/khartec/waltz/service/measurable/MeasurableService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableEndpoint.java
=> Support old capability url's

waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html
- bonus: Improve lnf of measurable panel
#1259
=> Updating ui router

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_rating/SaveMeasurableRatingCommand.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> FIX - ensure provenenance provided for measurable-ratings

waltz-data/src/main/java/com/khartec/waltz/data/EntityNameUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/orphan/OrphanDao.java, waltz-ng/client/orphan/services/orphan-store.js, waltz-ng/client/system/orphans-view.js, waltz-service/src/main/java/com/khartec/waltz/service/orphan/OrphanService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/OrphanEndpoint.java
=> Orphan counts report measurable ratings breaks.

waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js
=> Disable column hiding on entity stat detail grid

waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/logical-flow/components/rated-flow-summary/rated-flow-summary-panel.html, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/org-units/unit-view.html, waltz-ng/client/person/person-view.html
=> Auth source section is inlined, create a component

waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js
=> Scroll to top of source target graph when collapsing.

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/complexity/ComplexityScoreDao.java, waltz-data/src/main/java/com/khartec/waltz/data/complexity/MeasurableComplexityDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/CapabilityComplexityHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/complexity/ComplexityKind.java, waltz-model/src/main/java/com/khartec/waltz/model/complexity/ComplexityRating.java, waltz-ng/client/applications/directives/app-overview.html, waltz-ng/client/complexity/components/complexity-section.html, waltz-ng/client/complexity/components/complexity-section.js, waltz-ng/client/complexity/services/complexity-store.js, waltz-service/src/main/java/com/khartec/waltz/service/complexity/ComplexityRatingService.java, waltz-service/src/main/java/com/khartec/waltz/service/complexity/ConnectionComplexityService.java, waltz-service/src/main/java/com/khartec/waltz/service/complexity/MeasurableComplexityService.java, waltz-service/src/main/java/com/khartec/waltz/service/complexity/ServerComplexityService.java
=> Complexity scores now use measurables.

waltz-ng/client/applications/app-view.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html
=> Sorting nodes in measurable rating tree

waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.js
=> rating change not working in IE

waltz-data/src/main/java/com/khartec/waltz/data/measurable/MeasurableDao.java
=> app-view tree showing incorrect hierarchy

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html
=> Measurable ratings : no-data

waltz-ng/client/entity-statistics/components/entity-statistic-summary-card.html, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js
=> entity stats - better handling of 'no data'

waltz-ng/client/entity-statistics/entity-statistic-view.html
=> entity stats: measurable browsing

waltz-ng/client/asset-cost/components/asset-costs-graph.js, waltz-ng/client/complexity/components/complexity-bar-chart.js
=> cost / complexity charts - use different color scales

waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.html, waltz-ng/client/entity-statistics/components/entity-statistic-detail-panel.js, waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js, waltz-ng/client/entity-statistics/entity-statistic-view.html, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity-statistics/person-entity-statistic-view.html, waltz-ng/client/entity-statistics/person-entity-statistic-view.js
=> Add Org Unit to entity stat value table when in explorer

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Fixing db schema

waltz-ng/client/widgets/page-header/page-header.html, waltz-ng/client/widgets/page-header/page-header.js
=> Fixed Header bar - click to return to top of page

waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js
=> Occasional error on entity stats page

waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html
=> lowercase the entitykind display name when bookmarks are empty

waltz-ng/client/widgets/page-header/page-header.html
=> remove tooltip from sticky header

waltz-data/src/main/java/com/khartec/waltz/data/DBExecutorPool.java, waltz-data/src/main/java/com/khartec/waltz/data/DBExecutorPoolInterface.java, waltz-data/src/main/java/com/khartec/waltz/data/JooqUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/entity_statistic/EntityStatisticSummaryDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-service/src/main/java/com/khartec/waltz/service/DIConfiguration.java, waltz-service/src/main/java/com/khartec/waltz/service/app_view/AppViewService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java
=> jOOQ worker pool is derived from max pool size

docs/properties.md, waltz-service/src/main/java/com/khartec/waltz/service/DIConfiguration.java
=> Support jndi property values

waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/inline-edit-area.html, waltz-ng/client/widgets/inline-edit-area.js
=> Immediate saving of rating changes

waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.js
- also keyboard enabled the picker component
#1414
=> Fixing editor bug.

waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/perspective/components/grid/perspective-grid.js
=> Actually got round to doing issue at hand

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml
=> Survey: DDL changes

waltz-common/src/main/java/com/khartec/waltz/common/StringUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/IdSelectorFactoryProvider.java, waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/involvement/InvolvementDao.java, waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceRecipientDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyRunDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyTemplateDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/EntityKind.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstance.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceRecipient.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceRecipientCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceStatus.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyIssuanceKind.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRun.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunStatus.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyTemplate.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyTemplateStatus.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java
=> Survey: Backend changes - Run configuration

waltz-ng/test/domain-objects/index.js
=> Fixing unit test

waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js
=> Fixing stat bug

waltz-ng/client/widgets/pie-segment-table.js
=> Ensuring totals in pie charts are rounded to a fixed precision (2dp)

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Waltz 1445 p measurables

waltz-ng/client/widgets/pie-segment-table.js
=> Pie table: decimal points (.00) being displayed for integers

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Perspective Defn table creation

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Created new perspective-rating table

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
and initial inserts for logical flow, physical flows and specs
#1366
=> attestation table

waltz-ng/client/playpen/4/playpen4.js, waltz-ng/client/playpen/index.js
=> Refining grid

waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyInstanceRecipient.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunCreateCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunCreateResponse.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyRunStatusChangeCommand.java, waltz-ng/client/modules.js, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/components/survey-run-create-general.js, waltz-ng/client/survey/components/survey-run-create-recipient.html, waltz-ng/client/survey/components/survey-run-create-recipient.js, waltz-ng/client/survey/index.js, waltz-ng/client/survey/resolvers.js, waltz-ng/client/survey/routes.js, waltz-ng/client/survey/services/survey-run-store.js, waltz-ng/client/survey/services/survey-template-store.js, waltz-ng/client/survey/survey-run-create.html, waltz-ng/client/survey/survey-run-create.js, waltz-ng/style/_waltz-visibility.scss, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey: Front end changes - run configuration

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Survey: Questions and responses DDL

waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow_lineage/PhysicalFlowLineageService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification/PhysicalSpecificationService.java
=> Flow attestation support

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestion.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionFieldType.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyQuestionService.java
=> Survey Questions: Backend

waltz-common/src/main/java/com/khartec/waltz/common/ArrayUtilities.java, waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/perspective_rating/PerspectiveRatingDao.java, waltz-model/src/main/java/com/khartec/waltz/model/perspective/PerspectiveRatingValue.java, waltz-ng/client/perspective/components/editor/perspective-editor.js, waltz-ng/client/perspective/components/grid/perspective-grid.js, waltz-ng/client/perspective/serivces/perspective-rating-store.js, waltz-ng/client/playpen/4/playpen4.html, waltz-ng/client/playpen/4/playpen4.js, waltz-service/src/main/java/com/khartec/waltz/service/perspective_rating/PerspectiveRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/WebUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PerspectiveRatingEndpoint.java
=> Perspective ratings

waltz-ng/client/common/colors.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/widgets/pie-segment-table.html, waltz-ng/client/widgets/pie-segment-table.js, waltz-ng/client/widgets/pie-table.js
=> Fixing pie table

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-ng/client/common/index.js, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/icon-names.js, waltz-ng/client/system/hierarchies-view.js
=> Fixing source data ratings

waltz-ng/client/asset-cost/directives/asset-cost-table.js, waltz-ng/client/asset-cost/services/asset-cost-utilities.js, waltz-ng/client/bookmarks/bookmark-editor.js, waltz-ng/client/common/components/entity-link/entity-link.js, waltz-ng/client/common/filters/to-domain-filter.js, waltz-ng/client/common/index.js, waltz-ng/client/common/link-utils.js, waltz-ng/client/common/string-utils.js, waltz-ng/client/complexity/components/complexity-section.js, waltz-ng/client/entity-statistics/components/entity-statistic-detail-table.js, waltz-ng/client/entity-statistics/entity-statistic-view.js, waltz-ng/client/entity/components/immediate-hierarchy-navigator/immediate-hierarchy-navigator.js, waltz-ng/client/logical-flow/components/logical-flow-table/logical-flow-table.js, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.js, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js, waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/physical-flow-lineage/components/lineage-panel/physical-flow-lineage-panel.js, waltz-ng/client/physical-flows/components/flow-table/physical-flow-table.js, waltz-ng/client/physical-flows/physical-flow-registration.js, waltz-ng/client/physical-specifications/components/mentions/physical-specification-mentions.js, waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.js, waltz-ng/client/system/hierarchies-view.js, waltz-ng/client/widgets/external-link.js, waltz-ng/client/widgets/pie-segment-table.js
=> Pulling common functions into more specific util files.

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Fixing capability references in changelog

waltz-ng/client/perspective/components/editor/perspective-editor.html, waltz-ng/client/perspective/components/grid/perspective-grid.html, waltz-ng/client/perspective/perspective-rating-edit.html, waltz-ng/client/perspective/perspective-rating-edit.js, waltz-ng/client/perspective/routes.js
=> Creating basic perspective-rating editor page

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-model/src/main/java/com/khartec/waltz/model/person/Person.java
=> Tighten Person table / dao / model

waltz-model/src/main/java/com/khartec/waltz/model/rating/RagRating.java, waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/perspective/components/editor/perspective-editor.html, waltz-ng/client/perspective/perspective-rating-edit.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.js
=> Allow reset/revert to be picker in perspective editor

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyRunGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyTemplateGenerator.java
- survey run &  instance & recipient generator
WALTZ-1473
=> Survey: sample data generator

waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/perspective/perspective-rating-edit.js
=> Allow cancel of selected measurable in editor

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PerspectiveRatingEndpoint.java
=> Secure Perspective Rating Endpoint

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/perspective_definition/PerspectiveDefinitionDao.java, waltz-model/src/main/java/com/khartec/waltz/model/RagNamesProvider.java, waltz-model/src/main/java/com/khartec/waltz/model/measurable_category/MeasurableCategory.java, waltz-model/src/main/java/com/khartec/waltz/model/perspective/PerspectiveDefinition.java, waltz-ng/client/perspective/components/editor/perspective-editor.html, waltz-ng/client/ratings/components/rating-picker/rating-picker.js
=> Add rag names to perspectives

waltz-ng/client/perspective/components/editor/perspective-editor.html, waltz-ng/client/perspective/components/editor/perspective-editor.js
=> Add keyboard shortcuts to perspective editor

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyRunDao.java, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/survey/index.js, waltz-ng/client/survey/routes.js, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/services/survey-run-store.js, waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-list-user-view.js, waltz-ng/client/survey/survey-run-create.html, waltz-ng/client/survey/survey-run-create.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyInstanceEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java
=> Survey: UI - display logged in user's surveys

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionResponseDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionResponse.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java
=> Survey: change `survey_question_reponse` pkey

waltz-data/src/main/java/com/khartec/waltz/data/perspective_rating/PerspectiveRatingDao.java, waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/common/map-utils.js, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.js, waltz-ng/client/perspective/perspective-rating-edit.js, waltz-ng/client/perspective/serivces/perspective-rating-store.js, waltz-ng/client/ratings/components/rating-indicator-cell/rating-indicator-cell.scss, waltz-service/src/main/java/com/khartec/waltz/service/perspective_rating/PerspectiveRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PerspectiveRatingEndpoint.java
=> Perspective overrides shown in measurable tree / panel

waltz-ng/client/measurable-rating/measurable-rating-edit.html
=> Rating warning was always showing regardless of status

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Fixing for MSSQL

waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PerspectiveRatingEndpoint.java
=> Correcting Security role

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyRunDao.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceIdSelectorFactory.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java
- dao
- service
- survey instance id selector factory
WALTZ-1533
=> Survey: backend for showing surveys associated with an entity

waltz-ng/client/applications/app-view.html, waltz-ng/client/common/list-utils.js, waltz-ng/client/common/map-utils.js, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/associated-perspectives/associated-perspectives.html, waltz-ng/client/measurable-rating/components/associated-perspectives/associated-perspectives.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.js, waltz-ng/client/measurable-rating/components/tree/measurable-rating-tree.html, waltz-ng/client/measurable-rating/index.js, waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/perspective/components/overrides/perspective-overrides.html, waltz-ng/client/perspective/components/overrides/perspective-overrides.js, waltz-ng/client/perspective/index.js, waltz-ng/client/perspective/perspective-rating-edit.js, waltz-ng/client/ratings/components/rating-picker/rating-picker.js, waltz-ng/client/ratings/rating-utils.js, waltz-ng/style/_waltz-visibility.scss
=> Lining perspectives to views / editor

waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java
=> Fix harness

docs/features/README.md
=> Basic schema documentation

waltz-data/src/main/java/com/khartec/waltz/data/measurable_rating/MeasurableRatingDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/MeasurableRatingHarness.java, waltz-ng/client/app-groups/app-group-view.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.js, waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.js, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.js, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.html, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.js, waltz-ng/client/measurable-rating/index.js, waltz-ng/client/measurable-rating/services/measurable-rating-store.js, waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js, waltz-ng/client/org-units/unit-view.html, waltz-service/src/main/java/com/khartec/waltz/service/measurable_rating/MeasurableRatingService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/MeasurableRatingEndpoint.java
=> Show related measurables

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceRecipientDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyRunGenerator.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyQuestionService.java
=> Survey: Random completed surveys with responses

waltz-ng/client/system/hierarchies-view.js
=> Remove process from hier rebuild page

waltz-ng/client/measurable-rating/measurable-rating-edit.js, waltz-ng/client/system/hierarchies-view.html, waltz-service/src/main/java/com/khartec/waltz/service/entity_hierarchy/EntityHierarchyService.java
=> Prevent submission of ratings against non-concrete measurables

waltz-ng/client/survey/routes.js, waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-list-user-view.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js, waltz-ng/client/survey/survey-run-create.js, waltz-ng/client/survey/survey-utils.js
=> Survey Instance Response view

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyInstanceDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyRunGenerator.java, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/survey/components/survey-instance-list.html, waltz-ng/client/survey/components/survey-instance-list.js, waltz-ng/client/survey/index.js, waltz-ng/client/survey/services/survey-instance-store.js, waltz-ng/client/survey/services/survey-run-store.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyInstanceIdSelectorFactory.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyInstanceEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java
=> Survey: frontend for showing surveys associated with an entity

docs/README.md, waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/logical_flow/AddLogicalFlowCommand.java, waltz-ng/client/logical-flow/logical-flow-edit.js, waltz-ng/client/logical-flow/services/logical-flow-store.js, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
=> Logical Flow - last update by / last updated at

waltz-ng/client/survey/survey-instance-response-edit.js
=> Surveys: once a survey is submitted - redirect away from edit pages

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Fix liquibase for when there are existing logical flows in table

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification/PhysicalSpecification.java, waltz-ng/client/common/checks.js, waltz-ng/client/physical-flows/components/register/physical-flow-edit-specification.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
=> Physical Spec need last updated by/at

waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-list-user-view.js
=> SurveyInstance: list for user edit or view as appropriate

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlow.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
=> Physical Flows need last updated by/at

waltz-ng/client/applications/directives/app-overview.html
=> App - overall rating shown with rag indicator

waltz-ng/client/survey/routes.js, waltz-ng/client/survey/survey-template-list.html, waltz-ng/client/survey/survey-template-list.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Waltz 1584

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-ng/client/physical-flows/physical-flow-registration.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java
=> Prevent duplicate flows being created from same source and target

waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey.scss, waltz-ng/style/_waltz.scss
=> Waltz 1546 survey response validation

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyRunDao.java, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/survey/routes.js, waltz-ng/client/survey/services/survey-run-store.js, waltz-ng/client/survey/survey-run-create.html, waltz-ng/client/survey/survey-template-list.html, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java
=> Template list page

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Waltz 1599

waltz-data/src/main/ddl/liquibase/db.changelog-1.2.xml
=> Surveys: Indexes

waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/survey/components/survey-instance-list.js
=> Survey: Show completed instance on application view

waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.html, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.html
=> viewpoint ratings section not remembering collapsed status

waltz-ng/client/survey/survey-instance-list-user-view.html
=> Survey: User list improvements

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyRunGenerator.java, waltz-ng/client/survey/components/survey-run-create-recipient.html, waltz-ng/client/survey/components/survey-run-create-recipient.js
=> Survey: run generator allows creation of run with zero recipients

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyTemplateDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyQuestionService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyQuestionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey: back-end for creating surveys and questions

waltz-ng/client/survey/survey.scss
=> Surveys: Improve mandatory question highlighting

waltz-ng/client/playpen/3/playpen3.js, waltz-ng/client/playpen/index.js, waltz-ng/package.json
=> Upgrade UI-Router

waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/survey.scss
=> Survey: survey run validation

waltz-ng/client/survey/components/survey-run-create-general.html
=> Survey: Run create improvements

waltz-ng/client/complexity/components/complexity-section.js
=> Fixing wording on complexity table

waltz-ng/client/org-units/components/overview/org-unit-overview.html, waltz-ng/client/org-units/components/overview/org-unit-overview.js, waltz-ng/client/org-units/unit-view.html
#1591 
Decided to rip out the function count section from the header of the OU page.  It doesn't make too much sense in the new 'measurable' world.
=> Remove function count stats

waltz-ng/client/logical-flow/components/edit/logical-flow-type-editor.html, waltz-ng/client/logical-flow/components/edit/logical-flow-type-editor.js
=> Clicking anywhere on node toggles data type selection

waltz-ng/client/perspective/components/overrides/perspective-overrides.js
=> Perspectives: overrides not showing up on appview

waltz-data/src/main/java/com/khartec/waltz/data/perspective_definition/PerspectiveDefinitionDao.java, waltz-ng/client/perspective/serivces/perspective-definition-store.js, waltz-ng/client/system/perspective-view.scss, waltz-ng/client/system/perspectives-view.html, waltz-ng/client/system/perspectives-view.js, waltz-ng/client/system/routes.js, waltz-ng/client/system/system-admin-list.html, waltz-ng/style/_waltz.scss, waltz-service/src/main/java/com/khartec/waltz/service/perspective_definition/PerspectiveDefinitionService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PerspectiveDefinitionEndpoint.java
=> Allow admins to create perspective definitions

waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey Run: restrict creation to admin

waltz-ng/client/measurable-rating/measurable-rating-edit.html
=> Always reming user of overall app rating in measurable editor

waltz-ng/client/applications/app-view.html, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.html, waltz-ng/client/bookmarks/components/bookmarks-section/bookmarks-section.js
=> Hide bookmark type browser on non-app pages

waltz-ng/client/common/components/date-picker/date-picker-form-input.html, waltz-ng/client/common/components/date-picker/date-picker-form-input.js, waltz-ng/client/common/components/index.js, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/components/survey-run-create-general.js
=> Survey: Date picker doesn't work on IE

waltz-ng/client/applications/app-view.html, waltz-ng/client/technology/directives/technology-section.html, waltz-ng/client/technology/directives/technology-section.js
#1442 
separate issue created to convert this into a component #1634
=> technology section missing source data ratings

waltz-ng/client/measurable-rating/measurable-rating-edit.html
=> Measurable Editor - comment not saving (IE)

waltz-ng/client/survey/survey-run-create.js
=> Survey: Copy name and description from template when creating runs

waltz-model/src/main/java/com/khartec/waltz/model/user/Role.java, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/user/user-management.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey Run/Template: add SURVEY_ADMIN permission

waltz-ng/client/common/components/index.js, waltz-ng/client/common/components/last-updated/last-updated.html, waltz-ng/client/common/components/last-updated/last-updated.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html
=> last-updated widget

waltz-ng/client/asset-cost/components/asset-costs-section.html, waltz-ng/client/complexity/components/complexity-section.html, waltz-ng/client/entity-statistics/components/entity-statistic-summary-section.html, waltz-ng/client/logical-flow/components/rated-flow-summary/rated-flow-summary-panel.html, waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html, waltz-ng/client/measurable-rating/components/browser-section/measurable-ratings-browser-section.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.html, waltz-ng/client/measurable-rating/measurable-rating-edit.html, waltz-ng/client/perspective/components/editor/perspective-editor.js, waltz-ng/client/perspective/components/grid/perspective-grid.js, waltz-ng/client/perspective/perpective-utilities.js, waltz-ng/client/playpen/4/playpen4.html, waltz-ng/client/playpen/4/playpen4.js, waltz-ng/client/system/perspectives-view.html, waltz-ng/client/widgets/overlay-panel.html, waltz-ng/client/widgets/pie.scss, waltz-ng/style/_animations.scss, waltz-ng/style/_variables.scss
=> UI Improvements: animate ng-if's to fade in/out

waltz-ng/client/survey/survey-run-create.html, waltz-ng/client/survey/survey-run-create.js
=> Survey: mailto fails for surveys with long body text (IE only)

waltz-ng/client/survey/survey-run-create.js
=> Survey: Fix mailto link

waltz-ng/client/widgets/editable-field.html
=> Change editable field button title from Change to Save

waltz-ng/client/common/colors.js
=> Entity Statistic - review Colour values - PaaS non PaaS

waltz-ng/client/common/colors.js
=> More colors

waltz-ng/client/navbar/directives/navbar-profile.html, waltz-ng/client/survey/survey-instance-list-user-view.html, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html
=> Add survey links under Profile menu

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/OrgUnitGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalFlowGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/PhysicalSpecificationGenerator.java, waltz-ng/client/physical-flows/physical-flow-registration.html, waltz-ng/client/physical-flows/physical-flow-registration.js
=> Warn if a new flow is being created that is similar to an existing

waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.html, waltz-ng/client/measurable-rating/components/app-section/measurable-rating-app-section.js, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.html, waltz-ng/client/measurable-rating/components/panel/measurable-rating-panel.js, waltz-ng/client/perspective/components/overrides/perspective-overrides.html, waltz-ng/client/perspective/components/overrides/perspective-overrides.js, waltz-ng/client/perspective/perspective-rating-edit.html, waltz-ng/client/perspective/perspective-rating-view.html, waltz-ng/client/perspective/perspective-rating-view.js, waltz-ng/client/perspective/routes.js, waltz-ng/client/playpen/4/playpen4.html
=> Perspectives now visible on a read-only page.

waltz-ng/client/app-groups/directives/app-group-summary.html
=> Complexity total not showing on app-group page

waltz-ng/client/app-groups/app-group-view.html
=> Complexity section not showing on app-group page

waltz-ng/client/measurable/measurable-list.js
=> Measurable - Nav Aid for function misdirects user

waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.html
=> Nicer handling of no-related surveys

waltz-ng/client/asset-cost/components/asset-costs-section.html, waltz-ng/client/complexity/components/complexity-section.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup-section/logical-flows-tabgroup-section.html, waltz-ng/client/logical-flow/components/logical-flows-tabgroup-section/logical-flows-tabgroup-section.js, waltz-ng/client/measurable-rating/components/explorer-section/measurable-rating-explorer-section.html, waltz-ng/client/measurable-rating/components/related-measurables-section/related-measurables-section.html
=> Nicer handling of no-related data

waltz-ng/client/common/colors.js
=> Fix color keys

waltz-ng/client/survey/survey-instance-response-edit.html
=> Survey: show the run's contact email in the response edit form

waltz-data/src/main/java/com/khartec/waltz/data/static_panel/StaticPanelDao.java, waltz-ng/client/applications/app-edit.html, waltz-ng/client/static-panel/services/static-panel-store.js, waltz-ng/client/system/routes.js, waltz-ng/client/system/static-panels-view.html, waltz-ng/client/system/static-panels-view.js, waltz-ng/client/system/system-admin-list.html, waltz-ng/client/thirdparty-setup.js, waltz-service/src/main/java/com/khartec/waltz/service/static_panel/StaticPanelService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/EndpointUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/StaticPanelEndpoint.java
=> Basic support for editing/creating static panels

waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/widgets/pie-segment-table.scss, waltz-ng/client/widgets/pie.js, waltz-ng/client/widgets/pie.scss
=> Donuts not pie charts

waltz-ng/client/formly/index.js, waltz-ng/client/system/static-panels-view.html, waltz-ng/client/thirdparty-setup.js
=> unifying formly config

waltz-ng/client/perspective/components/grid/perspective-grid.html, waltz-ng/client/perspective/components/grid/perspective-grid.js, waltz-ng/client/perspective/components/grid/perspective-grid.scss, waltz-ng/client/perspective/perspective-rating-view.html, waltz-ng/client/perspective/perspective-rating-view.js, waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/toggle.html, waltz-ng/client/widgets/toggle.js, waltz-ng/style/_waltz.scss
=> toggle visibility of inherited perspective ratings

waltz-ng/client/change-initiative/change-initiative-view.js
=> add change initiatives to view history

waltz-ng/client/perspective/perspective-rating-edit.html, waltz-ng/client/perspective/perspective-rating-edit.js, waltz-ng/client/perspective/perspective-rating-view.html, waltz-ng/client/perspective/perspective-rating-view.js
=> Add static panels to measurable sections and perspective related views

waltz-ng/client/survey/survey-instance-response-edit.html
=> Fix survey response form

waltz-ng/client/measurable-rating/measurable-rating-edit.html
=> Fixing IE bug with rating editor

waltz-ng/client/asset-cost/components/asset-costs-graph.scss, waltz-ng/client/complexity/components/complexity-bar-chart.scss
=> Improve LnF of bar charts

waltz-ng/client/change-initiative/directives/change-initiative-selector.html
=> Change initiative selector display 'Search for app...'

waltz-ng/client/asset-cost/services/asset-cost-utilities.js, waltz-ng/client/common/string-utils.js, waltz-ng/client/widgets/pie-segment-table.js
=> Pie table: Remove number formatting suffixes (k, m etc)

waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js
=> Survey: template view shouldn't show draft runs

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
=> created changelog-1.3.xml

waltz-ng/client/attestation/components/attestation-table.html, waltz-ng/client/attestation/components/attestation-table.js, waltz-ng/client/attestation/index.js, waltz-ng/client/attestation/routes.js, waltz-ng/client/attestation/services/attestation-store.js, waltz-ng/client/attestation/view.html, waltz-ng/client/attestation/view.js, waltz-ng/client/common/components/grid/grid-with-search.js, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/modules.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttestationEndpoint.java
=> Attestation screen and link from physical flow

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionDao.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyTemplateDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/SurveyHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyTemplateGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyTemplateChangeCommand.java, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/routes.js, waltz-ng/client/survey/services/survey-question-store.js, waltz-ng/client/survey/services/survey-template-store.js, waltz-ng/client/survey/survey-template-create.html, waltz-ng/client/survey/survey-template-create.js, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-edit.js, waltz-ng/client/survey/survey-template-list.html, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey.scss, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyQuestionService.java, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyQuestionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey: Create/Edit template UI

waltz-ng/client/person/services/person-store.js
=> Survey: should display 'unknown' for owners no longer exist

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyTemplateDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyRunGenerator.java, waltz-ng/client/survey/services/survey-template-store.js, waltz-ng/client/survey/survey-template-list.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey: Show draft templates in list

waltz-ng/client/common/components/boolean-renderer.js, waltz-ng/client/common/components/index.js, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js
=> Survey: Show questions on template view

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> data_type_association table creation and initial population

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyTemplateGenerator.java, waltz-ng/client/common/bool-utils.js, waltz-ng/client/common/components/boolean-renderer.js, waltz-ng/client/survey/survey-instance-response-view.html
=> Survey: Use boolean renderer on response view

waltz-ng/client/measurable-rating/components/browser/measurable-ratings-browser.js
=> Rating tree should be collapsed by default

waltz-data/src/main/ddl/liquibase/db.changelog-1.0.xml
=> Fixing ddl issue

waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/DataFlowDecoratorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-ng/client/logical-flow/logical-flow-edit.js, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/DataFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowEndpoint.java
#1762
Testing comments
- Deleted flow which has no physical flows, deletes as expected.
- Attempted delete of flow which has physical flows.  Doesn't delete, and error notification shows with message.
=> prevent log flow delete if physical exists

waltz-data/src/main/java/com/khartec/waltz/data/person/PersonDao.java, waltz-ng/client/person/directives/person-directs-list.html
=> Person page: managers list should not be sorted (only reportees)

waltz-ng/client/common/string-utils.js
=> asset costs showing `undefined` whilst waiting for value

docs/snippets.sql
deleted logical flows which still have remaining physical flows
=> summarise deleted logical flows

docs/features/surveys/survey.md, docs/features/surveys/survey_template_state_diagram.puml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyTemplateDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyTemplateGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyTemplateStatusChangeCommand.java, waltz-ng/client/survey/services/survey-template-store.js, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyTemplateService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyTemplateEndpoint.java
=> Survey: Allow template status to be updated

waltz-ng/client/navbar/components/nav-search-results.html, waltz-ng/client/navbar/components/nav-search-results.js, waltz-ng/client/navbar/components/navbar-search-form.js
=> Add 'Change Initiative' to nav search

waltz-ng/client/physical-flows/physical-flow-view.html
=> Physical Flow Delete button still active when disabled

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> Remove capability tables from full text index

waltz-ng/client/measurable/measurable-view.html, waltz-ng/client/measurable/measurable-view.js
=> Add involvement views to measurables

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/MeasurableRelationshipsGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/MeasurablesGenerator.java, waltz-jobs/src/main/resources/regions.csv, waltz-model/src/main/java/com/khartec/waltz/model/entiy_relationship/RelationshipKind.java
=> Measurable relationships: generate demo data

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowDecoratorHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataFlowDecoratorRatingsServiceHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/FlowDecorationGenerator.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/MeasurablesGenerator.java, waltz-model/src/main/java/com/khartec/waltz/model/data_flow_decorator/LogicalFlowDecorator.java, waltz-service/src/main/java/com/khartec/waltz/service/authoritative_source/AuthoritativeSourceService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorRatingsService.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/DataFlowDecoratorEndpoint.java
=> Renaming data_flow_decorator to logical_flow_decorator

waltz-ng/client/applications/app-view.html, waltz-ng/client/applications/app-view.js, waltz-ng/client/applications/directives/app-overview-section.html, waltz-ng/client/applications/directives/app-overview-section.js, waltz-ng/client/applications/directives/app-overview.html, waltz-ng/client/applications/directives/app-overview.js, waltz-ng/client/entity-tags/services/entity-tag-store.js, waltz-service/src/main/java/com/khartec/waltz/service/entity_tag/EntityTagService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntityTagEndpoint.java
=> Associate tags with apps

waltz-data/src/main/java/com/khartec/waltz/data/application/search/MariaAppSearch.java
=> Fixing alias search on maria

waltz-ng/client/modules.js, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/components/survey-run-overview.html, waltz-ng/client/survey/components/survey-template-overview.html, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-list.html, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/thirdparty-setup.js, waltz-ng/client/widgets/index.js, waltz-ng/client/widgets/markdown.js, waltz-ng/package.json
=> Add markdown support on Surveys

waltz-ng/client/survey/survey-template-edit.js
=> Survey: Template edit/create form improvements

waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationDao.java, waltz-ng/client/attestation/services/attestation-store.js, waltz-ng/client/system/recalculate-view.html, waltz-ng/client/system/recalculate-view.js, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttestationEndpoint.java
=> Calculate lineage attestations via batch

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionDropdownEntryDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionDropdownEntry.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionFieldType.java, waltz-ng/client/common/services/display-names.js, waltz-ng/client/survey/components/dropdown/survey-dropdown-editor.html, waltz-ng/client/survey/components/dropdown/survey-dropdown-editor.js, waltz-ng/client/survey/index.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js, waltz-ng/client/survey/survey-template-edit.html, waltz-ng/client/survey/survey-template-edit.js, waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey-template-view.js, waltz-ng/client/survey/survey-utils.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyQuestionDropdownEntryService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyQuestionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/json/SurveyQuestionInfo.java
=> Survey: Support question type 'Dropdown'

waltz-ng/client/applications/directives/app-overview.html
=> Add markdown support on application description

waltz-ng/client/survey/survey-instance-response-view.html
=> Survey - boolean renderer shows tick and 'true' / 'false'

waltz-ng/client/main.js
=> Notifications should appear away from the top right

waltz-jobs/src/main/java/com/khartec/waltz/jobs/sample/SurveyRunGenerator.java, waltz-ng/client/survey/components/dropdown/survey-dropdown-editor.html, waltz-ng/client/survey/components/dropdown/survey-dropdown-editor.js, waltz-ng/client/survey/survey-template-edit.html
=> Bulk editor mode for dropdown entries

waltz-ng/client/main.js, waltz-ng/client/thirdparty-setup.js
Moved setup into thirdparty-setup.js
#1755
=> Notification review feedback

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-model/src/main/java/com/khartec/waltz/model/data_flow_decorator/LogicalFlowDecorator.java, waltz-service/src/main/java/com/khartec/waltz/service/data_flow_decorator/LogicalFlowDecoratorService.java
=> logical_flow_decorator last_updated

waltz-ng/client/survey/survey-template-edit.html
=> Survey: Template edit checkboxes are huge

waltz-data/src/main/java/com/khartec/waltz/data/app_group/AppGroupDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/EntitySearchHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/app_group/AppGroup.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_search/EntitySearchOptions.java, waltz-service/src/main/java/com/khartec/waltz/service/app_group/AppGroupService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_search/EntitySearchService.java
=> Add App group search to generic search service

waltz-data/src/main/java/com/khartec/waltz/data/actor/ActorSearchDao.java, waltz-model/src/main/java/com/khartec/waltz/model/entity_search/EntitySearchOptions.java, waltz-ng/client/entity/components/entity-selector/entity-selector.html, waltz-ng/client/entity/components/entity-selector/entity-selector.js, waltz-ng/client/entity/index.js, waltz-ng/client/entity/services/entity-search-store.js, waltz-ng/client/playpen/1/playpen1.html, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/EntitySearchEndpoint.java
=> Create searchable entity selection field

waltz-ng/client/common/list-utils.js, waltz-ng/client/entity/components/entity-selector/entity-selector.js, waltz-ng/client/survey/components/survey-run-create-general.html, waltz-ng/client/survey/components/survey-run-create-general.js, waltz-ng/client/survey/survey-run-create.html
=> Survey: support selectors other than app-group in run generation

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionResponseDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionFieldType.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionResponse.java, waltz-ng/client/common/services/display-names.js, waltz-ng/client/entity/components/entity-selector/entity-selector.html, waltz-ng/client/entity/components/entity-selector/entity-selector.js, waltz-ng/client/survey/components/survey-run-create-general.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-edit.js, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js, waltz-ng/client/survey/survey-template-edit.js, waltz-ng/client/survey/survey.scss
=> Survey: Support question type 'Application'

waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyQuestionResponseDao.java, waltz-model/src/main/java/com/khartec/waltz/model/survey/SurveyQuestionFieldType.java, waltz-ng/client/common/link-utils.js, waltz-ng/client/common/services/display-names.js, waltz-ng/client/person/person-id-view.js, waltz-ng/client/survey/survey-instance-response-edit.html, waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-template-edit.js, waltz-ng/package.json
=> Survey: Support question type 'Person'

waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-ng/client/survey/components/survey-run-create-general.js
=> Change initiative id selector factory should support identity selector

waltz-ng/client/common/browser-utils.js, waltz-ng/client/common/components/multi-select-tree-control/multi-select-treecontrol.js
=> Logical flow data type: Checkbox doesn't work on IE

waltz-ng/client/survey/survey-instance-response-view.html, waltz-ng/client/survey/survey-instance-response-view.js, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyInstanceEndpoint.java
=> Survey: Allow surveys to be set to In Progress after submission

waltz-ng/client/measurable/components/summary/measurable-summary.html
=> Add markdown support on measurables description

docs/features/entity_relationship/entity_relationship.md, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-model/src/main/java/com/khartec/waltz/model/entiy_relationship/EntityRelationshipChangeCommand.java, waltz-model/src/main/java/com/khartec/waltz/model/entiy_relationship/RelationshipKind.java, waltz-ng/client/applications/application-utils.js, waltz-ng/client/applications/components/app-table.js, waltz-ng/client/applications/components/related-apps-section/related-apps-section.html, waltz-ng/client/applications/components/related-apps-section/related-apps-section.js, waltz-ng/client/applications/index.js, waltz-ng/client/change-initiative/change-initiative-app-relationship-edit.html, waltz-ng/client/change-initiative/change-initiative-app-relationship-edit.js, waltz-ng/client/change-initiative/change-initiative-utils.js, waltz-ng/client/change-initiative/change-initiative-view.html, waltz-ng/client/change-initiative/change-initiative-view.js, waltz-ng/client/change-initiative/routes.js, waltz-ng/client/change-initiative/services/change-initiative-store.js, waltz-ng/client/common/checks.js, waltz-ng/client/common/link-utils.js, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/entity/components/related-entity-editor/related-entity-editor.html, waltz-ng/client/entity/components/related-entity-editor/related-entity-editor.js, waltz-ng/client/entity/index.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js, waltz-ng/client/user/user-management.html, waltz-service/src/main/java/com/khartec/waltz/service/change_initiative/ChangeInitiativeService.java, waltz-service/src/main/java/com/khartec/waltz/service/entity_relationship/EntityRelationshipUtilities.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/ChangeInitiativeEndpoint.java
=> Change Initiatives: associate to entities (applications)

waltz-ng/client/survey/survey-run-create.js
=> Survey: Fix typos in survey emails

waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java
=> Survey: Ensure duplicate instance recipients are not created

waltz-ng/client/survey/survey-instance-response-view.html
=> Survey: Format number responses

waltz-data/src/main/java/com/khartec/waltz/data/change_initiative/ChangeInitiativeIdSelectorFactory.java, waltz-ng/client/survey/components/survey-run-create-general.js
=> Add id selectors for change initiatives

waltz-ng/client/survey/survey-template-view.html, waltz-ng/client/survey/survey.scss
=> Survey: Runs responses progress bar jumps

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-ng/client/survey/survey-template-create.js
=> Survey: Prevent duplicate template names

waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/widgets/section.html, waltz-ng/client/widgets/section.js
=> Waltz Section - collapsible binding ignored

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js
=> Disable zoom on dbl-click

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/complexity/ConnectionComplexityDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_flow_decorator/LogicalFlowDecoratorDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowIdSelectorFactory.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/DataTypeUsageHarness.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/LogicalFlowDecoratorHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/IsRemovedProvider.java, waltz-ng/client/logical-flow/logical-flow-edit.js, waltz-service/src/main/java/com/khartec/waltz/service/logical_flow/LogicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/LogicalFlowDecoratorEndpoint.java
=> Soft Delete for Logical Flows

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml
=> Physical Spec Definition: create tables

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> Modify sample file table

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> Fixing mssql issues

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlow.java
=> Physical Flow: add (optional) definition id fkey

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/ddl/liquibase/db.properties.xml, waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramAnnotationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/flow_diagram/FlowDiagramAnnotation.java, waltz-model/src/main/java/com/khartec/waltz/model/flow_diagram/SaveDiagramCommand.java, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/flow-diagram-utils.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/flow-diagram/services/flow-diagram-annotation-store.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/playpen/3/playpen3.html, waltz-ng/client/playpen/3/playpen3.js, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FlowDiagramEndpoint.java
=> Preparation work for diagram save

waltz-data/src/main/java/com/khartec/waltz/data/physical_specification_definition/PhysicalSpecDefinitionSampleFileDao.java, waltz-jobs/src/main/java/com/khartec/waltz/jobs/PhysicalSpecDefinitionHarness.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinition.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinitionField.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification_definition/PhysicalSpecDefinitionSampleFile.java, waltz-ng/client/common/services/display-names.js, waltz-ng/client/common/services/index.js, waltz-ng/client/physical-flows/components/spec-definition/physical-spec-definition-panel.html, waltz-ng/client/physical-flows/components/spec-definition/physical-spec-definition-panel.js, waltz-ng/client/physical-flows/index.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-flows/service/physical-spec-definition-field-store.js, waltz-ng/client/physical-flows/service/physical-spec-definition-sample-file-store.js, waltz-ng/client/physical-flows/service/physical-spec-definition-store.js, waltz-ng/client/survey/components/survey-template-overview.html, waltz-ng/client/survey/survey-template-list.html, waltz-service/src/main/java/com/khartec/waltz/service/physical_specification_definition/PhysicalSpecDefinitionSampleFileService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecDefinitionEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecDefinitionFieldEndpoint.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalSpecDefinitionSampleFileEndpoint.java
=> Physical Flow view page: need a spec_defn / sample file section

waltz-ng/client/flow-diagram/components/diagrams-panel/diagrams-panel.html, waltz-ng/client/flow-diagram/components/diagrams-panel/diagrams-panel.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/flow-diagram/services/flow-diagram-entity-store.js, waltz-ng/client/playpen/1/playpen1.html, waltz-ng/client/playpen/1/playpen1.js
=> Flow Diagram: diagram list panel

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlowSpecDefinitionChangeCommand.java, waltz-ng/client/physical-flows/components/spec-definition/physical-spec-definition-panel.html, waltz-ng/client/physical-flows/components/spec-definition/physical-spec-definition-panel.js, waltz-ng/client/physical-flows/physical-flow-view.html, waltz-ng/client/physical-flows/physical-flow-view.js, waltz-ng/client/physical-flows/service/physical-flow-store.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Physical Flow: change linked version

waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramAnnotationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramDao.java, waltz-data/src/main/java/com/khartec/waltz/data/flow_diagram/FlowDiagramEntityDao.java, waltz-service/src/main/java/com/khartec/waltz/service/flow_diagram/FlowDiagramService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/FlowDiagramEndpoint.java
=> Flow Diagram: Persist diagram to database

waltz-ng/client/common/index.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/flow-diagram/services/flow-diagram-store.js
=> Basic persistence to diagram service endpoint

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/authoritative_source/AuthoritativeSourceDao.java, waltz-data/src/main/java/com/khartec/waltz/data/data_type_usage/DataTypeUsageDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/logical_flow/LogicalFlowStatsDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java
=> rename removed logical

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowDao.java, waltz-data/src/main/java/com/khartec/waltz/data/physical_specification/PhysicalSpecificationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/application/Application.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_flow/PhysicalFlow.java, waltz-model/src/main/java/com/khartec/waltz/model/physical_specification/PhysicalSpecification.java
=> Add soft delete (is_removed) to application, phys_flow/spec

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationDao.java, waltz-model/src/main/java/com/khartec/waltz/model/attestation/Attestation.java, waltz-ng/client/attestation/services/attestation-store.js, waltz-ng/client/system/recalculate-view.html, waltz-ng/client/system/recalculate-view.js, waltz-service/src/main/java/com/khartec/waltz/service/attestation/AttestationService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/AttestationEndpoint.java
=> Calculate logical flow data type decoration attestations via a batch

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-add-flow-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-add-flow-popup.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-annotation-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-annotation-popup.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/index.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
- extracted popup to own components
#1954
=> Flow buckets are now shown

waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-add-flow-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-add-flow-popup.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Disable option to add duplicate flows

waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js
=> Remove flows from diagram

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> flow_diagram_annotation fails to add pkey due to annotation_id nullable

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml, waltz-ng/client/physical-specifications/physical-specification-view.js
=> Spec definition: Add unique constraint on version

waltz-common/src/main/java/com/khartec/waltz/common/DateTimeUtilities.java, waltz-data/src/main/java/com/khartec/waltz/data/survey/SurveyRunDao.java, waltz-model/src/main/java/com/khartec/waltz/model/DateChangeCommand.java, waltz-ng/client/survey/components/survey-run-overview.html, waltz-ng/client/survey/components/survey-run-overview.js, waltz-ng/client/survey/services/survey-run-store.js, waltz-ng/client/survey/survey-run-view.html, waltz-ng/client/survey/survey-run-view.js, waltz-ng/client/widgets/editable-field.html, waltz-ng/client/widgets/editable-field.js, waltz-service/src/main/java/com/khartec/waltz/service/survey/SurveyRunService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/SurveyRunEndpoint.java
=> Survey: ability to alter due date

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> Add indexes on Physical Spec Definition tables

waltz-data/src/main/ddl/liquibase/db.changelog-1.3.xml
=> Add index to annotations

waltz-data/src/main/java/com/khartec/waltz/data/physical_flow/PhysicalFlowIdSelectorFactory.java, waltz-ng/client/flow-diagram/components/diagram/flow-diagram.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-editor.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-logical-flow-popup.js, waltz-ng/client/flow-diagram/components/editor/flow-diagram-physical-flow-popup.html, waltz-ng/client/flow-diagram/components/editor/flow-diagram-physical-flow-popup.js, waltz-ng/client/flow-diagram/services/flow-diagram-state-service.js, waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-graph.js, waltz-service/src/main/java/com/khartec/waltz/service/physical_flow/PhysicalFlowService.java, waltz-web/src/main/java/com/khartec/waltz/web/endpoints/api/PhysicalFlowEndpoint.java
=> Physical Flows can be added to logical flows in diagram

waltz-ng/client/survey/components/survey-section.html
=> Survey: Incorrect URL on entity views
