finos/waltz

pom.xml

The incremental compiler can cause javac to crash on 'non-clean' projects.  This option prevents it from running and therefore should avoid the bug.
#93

Disabling incremental compiler

---

waltz-ng/client/svg-diagram/directives/svg-diagrams.html
waltz-ng/client/svg-diagram/directives/svg-diagrams.js

Visio inlines a CSS block which corrupts other diagrams on the page.
Solution is to ensure the diagram is not rendered when not visible (as opposed
to being hidden)
#95

Preventing svg diagrams from corrupting each other

---

waltz-data/pom.xml

- added 'database.schema' to waltz.properties
#96

Softcoding schema in build file

---

waltz-data/src/main/java/com/khartec/waltz/data/application/ApplicationIdSelectorFactory.java
waltz-data/src/main/java/com/khartec/waltz/data/data_type/DataTypeIdSelectorFactory.java
waltz-jobs/src/main/java/com/khartec/waltz/jobs/ApplicationIdSelectorHarness.java

DataType page: App Id selector for data types

---

waltz-ng/client/measurable/measurable-list.html
waltz-ng/client/measurable/measurable-list.js

- bonus fix: select first non-empty tab on measurable index page
#1358

FIX - navaids should display correclty

---

waltz-ng/client/common/index.js
waltz-ng/client/common/string-utils.js
waltz-ng/client/perspective/components/grid/perspective-grid.js
waltz-ng/client/user/services/user-preference-service.js
waltz-ng/client/widgets/section.js

- started pulling functions out of `common/index.js` into more targetted `xyz-utils.js` files
#1485

Truncate long titles in grid editor

---

waltz-ng/client/widgets/pie-segment-table.html

Pie-table: rows jump around on select (IE only)

---

.travis.yml

- revert to node version 7 and not current because node_sass hasn't caught up yet
#2273

Travis build breaking

---

waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.scss

- allows entire 'button' to be clicked rather than just the image/text
#2711

Section nav links now block level elements

---

waltz-ng/client/common/components/entity-link/entity-link.html
waltz-ng/client/common/components/entity-link/entity-link.js

Waltz entity links can be passed a target='_blank' param to instruct
them to open new window/tab.
#3033

Allow waltz-entity-links to open new window/tab

---

.lgtm.yml

This build configuration enables Java analysis on LGTM.com. As discussed in #3097 with @davidwatkins73: a large part of the Java build process depends on generating code, which requires a running SQL server. For now I've disabled that module (`waltz-schema`) and all modules that depend on it by patching the `pom.xml`.
When analyzing a revision, LGTM will always use the `lgtm.yml` file that is present in that revision. So if the build process ever changes, all you have to do is update this file. The build is very configurable; see https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
(Full disclosure: I'm part of the team that build LGTM.com)

Add lgtm.yml build configuration for lgtm.com Java analysis

---

waltz-ng/client/measurable-category/pages/list/measurable-category-list.js
waltz-ng/client/measurable-category/routes.js
waltz-ng/client/measurable/pages/measurable-view/measurable-view.html
waltz-ng/client/navbar/directives/navbar.js
waltz-ng/client/user/services/user-preference-service.js

- fixed routing to use  `main.measurable-category.list`
- plus remembers last viewed category
#3389

Measurable Perf

---

waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.html
waltz-ng/client/bookmarks/components/bookmarks-view-panel/bookmarks-view-panel.js

- uses standard `waltz-search-control` widget
#4067

Bookmarks: filter on individual bookmarks, not categories

---

pom.xml

We can build with mvn 3.2 +, no need to require 3.5+

Relax maven version dependency slightly

---

waltz-ng/client/common/components/grid/grid-with-search.html
waltz-ng/client/report-grid/components/grid-view-section/report-grid-view-section.html
waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.html
waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js

- fixed minor bug with grid-with-search
- better support for no-data
- shows 'hidden' data counts
- correctly clears filters when closing summaries
#5107

Adding multi selection of filters within a single column

---

waltz-data/src/main/java/com/khartec/waltz/data/server_information/ServerInformationDao.java

- looks like DSL.count() in this usage returns a long not an integer as claimed by the type signature.....
#5153

Fixes class cast exception

---

waltz-data/src/main/java/com/khartec/waltz/data/report_grid/ReportGridDao.java
waltz-model/src/main/java/com/khartec/waltz/model/report_grid/ReportGridCell.java
waltz-ng/client/common/components/grid/grid.scss
waltz-ng/client/report-grid/components/report-grid-view-panel/report-grid-view-panel.js
waltz-web/src/main/java/com/khartec/waltz/web/endpoints/extracts/ReportGridExtractor.java

Adding involvement support on grid reports
- Configure via adding an `INVOLVEMENT_KIND` record as a `report_grid_column_definition`
- Bonus: search can now be used over ratings and person cells
- Bonus: renamed some methods in the `ReportGridDao` to improve clarity 
#5224

Report grid can now reference people (via involvements)

---

waltz-ng/client/dynamic-section/components/dynamic-section-navigation/dynamic-section-navigation.js
waltz-ng/client/dynamic-section/components/dynamic-section-wrapper/dynamic-section-wrapper.html
waltz-ng/client/dynamic-section/components/dynamic-section-wrapper/dynamic-section-wrapper.js
waltz-ng/client/dynamic-section/components/dynamic-sections-view/dynamic-sections-view.html
waltz-ng/client/dynamic-section/components/dynamic-sections-view/waltz-dynamic-sections-view.scss
waltz-ng/client/dynamic-section/dynamic-section-definitions.js
waltz-ng/client/physical-flows/components/physical-flow-section/physical-flow-section.html
waltz-ng/client/physical-specifications/components/physical-data-section/physical-data-section.html

Jumping between sections can be frustrating at times. This is due to the dynamic size of the header sections. A simple approach is to use a fixed a anchor and jump to that.
#5413

Fix section jumping inconsistencies

---

waltz-ng/client/logical-flow/components/logical-flow-edit-panel/logical-flow-edit-panel.html
waltz-ng/client/logical-flow/components/logical-flow-edit-panel/logical-flow-edit-panel.js
waltz-ng/client/logical-flow/components/source-and-target-graph/source-and-target-utilities.js

- forgotten to pass the authRatingsByKey dictionary to the source-and-target graph.
#5541

Flow editor not showing rating colors

---

waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationInstanceDao.java
waltz-ng/client/attestation/attestation-instance-list-user-view.js

- gives last attested instance priority when showing recent attestations (uses `ORDER BY ... NULLS LAST`)
- 'continue to next attestation' toggle remembers choice when cancelling
#5615
#5617

Attestation fixes

---

waltz-data/src/main/java/com/khartec/waltz/data/attestation/AttestationInstanceDao.java

Root cause: assumption that the run has an attested_entity_id - this is only for measurable attestations (i.e the category id).
This in turn caused the sql to not match on the run and therefore it creates a new run/instance on the fly rather than closing the existing one.
#5661

Attestations: closing instances fails for logical and physical flows

---

waltz-data/src/main/java/com/khartec/waltz/data/datatype_decorator/LogicalFlowDecoratorDao.java

- caused by refactoring: `selectFrom(...)` to a `select(...)` and then missing the `.from(...)`
#5668

Adding missing from statement to logical flow decorator

---

.github/workflows/maven.yml
Dockerfile
README.md
docker-compose.yml
docker/DOCKER.md
docker/docker-entrypoint.sh
docker/waltz.properties
waltz-web/README.md

**Building and dockerize Waltz** for running Waltz with PostgreSQL as a database so it can be run within any environment.
By default, the image will try to update DB and run Waltz with default parameters. 
In case you want to specify given actions and/or change DB parameters you can change docker's `CMD` with `run` or `update` and pass corresponding env variables as shown in the example below.
Image name: `ghcr.io/ljubon/waltz:latest`
Image size: `393MB`
Latest release: [link](https://github.com/ljubon/waltz/pkgs/container/waltz)
Default values and parameters with executing `update` and `run` 
```
docker run -it -d --name waltz ghcr.io/finos/waltz:latest
```
Working example for this PR with only `run` Waltz, without `update` DB
```
docker run -it -d --name waltz \
--env DB_HOST=postgres \ …
```

dockerize waltz

---

.github/workflows/meetings.yml

This pull request adds `.github/workflows/meetings.yml` to the Waltz project repository for recording and registering Waltz project meeting attendees with FINOS.
This script is managed and maintained by the FINOS team.

Add FINOS Meeting Action to Waltz Project Repo

---

waltz-model/src/main/java/org/finos/waltz/model/survey/SurveyTemplate.java
waltz-ng/client/common/services/enums/entity.js
waltz-ng/client/common/svelte/Grid.svelte
waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/ColumnDefinitionEditPanel.svelte
waltz-ng/client/report-grid/components/svelte/column-definition-edit-panel/EntitySelector.svelte
waltz-ng/client/report-grid/components/svelte/pickers/AssessmentDefinitionPicker.svelte
waltz-ng/client/report-grid/components/svelte/pickers/SurveyQuestionPicker.svelte
waltz-ng/client/report-grid/components/svelte/report-grid-utils.js
waltz-ng/test/report-grid/report-grid-utils.js

- new columns to end of list
- filter assessments and surveys which aren't for apps
- uses rollups (HIGHEST) for measurables (rather than NONE)
#5883

Grid enhancements

---

waltz-data/src/main/java/org/finos/waltz/data/measurable_rating_planned_decommission/MeasurableRatingPlannedDecommissionDao.java

Code was assuming an existing record would be found and throwing an NPE if it wasn't.
This was caused by attempting to convert a null result record into a DecommRecord.
#6014

Fixing app/fn decom bug

---

waltz-data/src/main/java/org/finos/waltz/data/assessment_definition/AssessmentDefinitionDao.java
waltz-model/src/main/java/org/finos/waltz/model/assessment_definition/AssessmentDefinition.java
waltz-ng/client/assessments/components/section/assessment-rating-section.js
waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.html
waltz-ng/client/assessments/components/sub-section/assessment-rating-sub-section.js
waltz-ng/client/assessments/services/assessment-definition-store.js
waltz-ng/client/dynamic-section/dynamic-section-definitions.js
waltz-ng/client/measurable/components/overview/measurable-overview.html
waltz-ng/client/svelte-stores/assessment-definition.js
waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionEditor.svelte
waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionRemovalConfirmation.svelte
waltz-ng/client/system/svelte/assessment-definitions/AssessmentDefinitionsAdminView.svelte
waltz-ng/client/system/svelte/assessment-definitions/MeasurableCategoryPicker.svelte
waltz-ng/client/system/svelte/assessment-definitions/assessment-definition-utils.js
waltz-service/src/main/java/org/finos/waltz/service/assessment_definition/AssessmentDefinitionService.java
waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/AssessmentDefinitionEndpoint.java
waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/MeasurableEndpoint.java

Added qualifier support to table.
Added findByEntityReference which does a lookup if passed a measurable in order to fill in the qualifier.
Resorted the list of entity kinds supported by assessments.
Added assessment section to measurable page sections.
Added assessment sub-section to measurable header.
Svelte Store will remove the qualifier if the def is not a measurable
#6127

Assessment support for measurables

---

pom.xml
waltz-common/pom.xml
waltz-data/pom.xml
waltz-data/src/main/ddl/liquibase/db.changelog-1.45.xml
waltz-data/src/main/ddl/liquibase/db.changelog-master.xml
waltz-integration-test/pom.xml
waltz-jobs/pom.xml
waltz-model/pom.xml
waltz-schema/pom.xml
waltz-service/pom.xml
waltz-test-common/pom.xml
waltz-web/pom.xml

Prep 1.45 dev

---

waltz-data/src/main/java/org/finos/waltz/data/physical_specification/PhysicalSpecificationDao.java
waltz-model/src/main/java/org/finos/waltz/model/physical_flow/FlowAttributes.java
waltz-ng/client/physical-flows/svelte/PhysicalFlowCharacteristicsStep.svelte
waltz-ng/client/physical-flows/svelte/PhysicalFlowRegistrationView.svelte
waltz-service/src/main/java/org/finos/waltz/service/data_type/DataTypeDecoratorService.java
waltz-service/src/main/java/org/finos/waltz/service/physical_flow/PhysicalFlowService.java

Db contrib/waltz 6269 physical flow ext id save

---

waltz-data/pom.xml
waltz-schema/assembly.xml
waltz-schema/pom.xml

Signed-off-by: Hervé Boutemy <hboutemy@apache.org>
maven GH workflow is currently failing:
```
...
[INFO] ------------------------< org.finos:waltz-data >------------------------
[INFO] Building waltz-data 1.47-SNAPSHOT                                  [5/9]
[INFO] --------------------------------[ jar ]---------------------------------
...
[INFO] --- maven-assembly-plugin:3.1.1:single (create-archive) @ waltz-data ---
...
[INFO] Reading assembly descriptor: /home/runner/work/waltz/waltz/waltz-data/assembly.xml
...
Error:  Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.1:single (create-archive) on project waltz-data: Failed to create assembly: Error creating assembly archive zip: archive cannot be empty -> [Help 1]
...
```
It is caused by incomplete move of ddl …

fix failing assembly after #6346

---

waltz-data/src/main/java/org/finos/waltz/data/EntityAliasPopulator.java

Bulk involvement fixes

---

docs/development/upgrade.md
waltz-schema/src/main/resources/liquibase/README.md

Version Information Page

---

waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.html
waltz-ng/client/dynamic-section/components/dynamic-section/dynamic-section.js
waltz-ng/client/dynamic-section/section-store.js
waltz-ng/client/widgets/page-header/page-header.js

We seem to have a problem with window.history.replaceState, it writes entries in the history which seem to block the back button from working correctly.
The code is in section-store and is only really needed to update the query param with a list of open sections. In turn this is only needed so the url can be sent to others and the appropriate sections will open.
After some experimentation it seems as if we can remove that feature and instead us a more straightforward sharing mechanism, where a shareable url is copied to the clip board.
#6657

Better back btn support

---

waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.html

#6406
This draft PR aims to address the data type list sorting on flow details popup. The added screenshots to the issue were helpful in finding the popup menu. Despite, this PR requires testing with a node mapping to multiple data types.

6406: Ensure data type list is sorted on flow details popup

---

waltz-ng/client/involvement/components/involved-people-section.html
waltz-ng/client/involvement/components/involved-people-section.js

#6048 
This Draft PR aims to filter out removed users by default. The added information where useful in recreating this issue.

6048:should filter out removed users by default

---

waltz-common/src/test/java/org/finos/waltz/common/BatchProcessingCollectorTest.java
waltz-common/src/test/java/org/finos/waltz/common/Columns_toOffsetTest.java
waltz-common/src/test/java/org/finos/waltz/common/ListUtilities_getOrDefaultTest.java
waltz-common/src/test/java/org/finos/waltz/common/StreamUtilities_siphonTest.java
waltz-ng/client/survey/survey-run-create.html
waltz-test-common/src/main/java/org/finos/waltz/test_common/helpers/PersonHelper.java
waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/ScreenshotHelper.java
waltz-test-common/src/main/java/org/finos/waltz/test_common/playwright/Section.java
waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/flow_classification_rule/RuleCreationTest.java
waltz-test-common/src/test/java/org/finos/waltz/test_common/playwright/surveys/SurveyIssuanceIntegrationTest.java

- survey template creation
- single direct issuance
- issuance via run
#6071

Added playwright test for survey creation and issuance

---

waltz-web/README.md

uber-waltz-web-1.0-SNAPSHOT.jar is no longer created. Updating to waltz-web-jar-with-dependencies.jar
also raised here: https://github.com/finos/waltz/issues/4808

clarification of jar file name and minor edits

---

waltz-ng/client/common/colors.js

Added some more colour names

---

waltz-ng/client/data-flow/components/svelte/flow-detail-tab/FlowDetailPanel.svelte
waltz-ng/client/data-flow/components/svelte/flow-detail-tab/filters/FlowClassificationFilters.svelte
waltz-ng/client/data-flow/components/svelte/flow-detail-tab/filters/FlowDetailFilters.svelte
waltz-ng/client/data-flow/components/svelte/flow-detail-tab/filters/filter-utils.js
waltz-service/src/main/java/org/finos/waltz/service/flow_classification_rule/FlowClassificationService.java
waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/FlowClassificationEndpoint.java

flow details auth rating filter

---

waltz-ng/client/report-grid/components/svelte/report-grid-utils.js
waltz-schema/src/main/resources/liquibase/db.changelog-1.57.xml

- was sending the full enum object back, not just the name
- missing default values for primary ratings
#6961

Report Grid: Adding field refs not workings

---

waltz-data/src/main/java/org/finos/waltz/data/report_grid/ReportGridDao.java
waltz-model/src/main/java/org/finos/waltz/model/report_grid/AdditionalColumnOptions.java
waltz-ng/client/report-grid/components/svelte/ReportGridFilters.svelte
waltz-ng/client/report-grid/components/svelte/report-grid-utils.js

can now show:
- outcomes only (default)
- values only
- outcomes and values
#7037

Report Grids: entity stats have view options

---

waltz-data/src/main/java/org/finos/waltz/data/datatype_decorator/LogicalFlowDecoratorDao.java
waltz-ng/client/common/svelte/DataTypeNodeTooltipContent.svelte
waltz-ng/client/common/svelte/DataTypeTreeNode.svelte
waltz-ng/client/common/svelte/UsageCharacteristicsDecorator.svelte

Respect the DT decorator r/o flag

---

waltz-ng/client/survey/survey-template-edit.html
waltz-ng/client/survey/survey-template-edit.js

Db contrib/waltz 7123 survey fix

---

waltz-data/src/main/java/org/finos/waltz/data/data_type/DataTypeDao.java
waltz-data/src/main/java/org/finos/waltz/data/data_type/DataTypeUtilities.java
waltz-model/src/main/java/org/finos/waltz/model/datatype/DataTypeMigrationResult.java
waltz-ng/client/data-types/components/maintain/DataTypeMaintain.svelte
waltz-ng/client/data-types/index.js
waltz-ng/client/data-types/pages/home/data-type-home.html
waltz-ng/client/data-types/pages/maintain/data-type-maintain.html
waltz-ng/client/data-types/pages/maintain/data-type-maintain.js
waltz-ng/client/data-types/routes.js
waltz-ng/client/svelte-stores/data-type-store.js
waltz-service/src/main/java/org/finos/waltz/service/data_type/DataTypeService.java
waltz-web/src/main/java/org/finos/waltz/web/endpoints/api/DataTypesEndpoint.java

Db contrib/waltz 7138 data type merge

---

waltz-common/src/main/java/org/finos/waltz/common/DateTimeUtilities.java
waltz-ng/client/logical-flow/components/source-and-target-panel/source-and-target-panel.js
waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/LogicalFlowExtractor.java
waltz-web/src/main/java/org/finos/waltz/web/endpoints/extracts/LogicalFlowViewExtractor.java

Db contrib/7196 additional attributes to lf extracts

---

waltz-data/src/main/java/org/finos/waltz/data/measurable_category/MeasurableCategoryDao.java
waltz-model/src/main/java/org/finos/waltz/model/measurable_category/MeasurableCategory.java
waltz-schema/src/main/resources/liquibase/db.changelog-1.67.xml
waltz-service/src/main/java/org/finos/waltz/service/measurable_category/MeasurableCategoryService.java

Db contrib/7200 support to removing deprecated measurable categories

---

waltz-data/src/main/java/org/finos/waltz/data/access_log/AccessLogDao.java
waltz-data/src/main/java/org/finos/waltz/data/changelog/ChangeLogSummariesDao.java

#7331 updated code to use JOOQ datepart instead of native DATEPART SQL code on JOOQ queries
previously the page would not load and looked like this 
after the fix the pages are now displaying

7331 Analytics-Dashboard: fix Postgres support
